### ISSUE TITLE
[BUG] Module cannot be activated

### ISSUE THREAD

**Issue by j0912H97** [LSPosed/LSPosed#10]
**什么情况/What happened?**

模块无法激活

**Xposed模块列表/Xposed Module List**

com.fkzhang.qqxposed
org.meowcat.edxposed.manager
ru.ldxywdqq.ltemiawyf
com.coderstory.toolkit
com.gojek.galau.ggtools
com.raincat.dolby_beta
com.fkzhang.wechatxposed
com.shatyuka.zhiliao
com.nnnen.nnnenv2
github.tornaco.android.thanos.pro
com.bug.zqq
com.ejiaogl.tiktokhook
com.raincat.unblockneteasemusic
name.caiyao.sporteditor
cat.dcat.roothide
me.kyuubiran.qqcleaner
com.cofface.ivader
com.fuckcoolapk
zorro.xdouyin
com.plus.dy
com.qianbajin.sportaccelerator
pansong291.xposed.quickenergy.qiufeng
nil.nadph.qnotified
com.android.z
cn.kwaiching.hook
**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android:11

Magisk:21.4 (6fb20b3e) (21406)

Riru: v23.4(54) 

LSPposed:LSPosed-v0.5.2.0-5055-debug

**相关日志/Related Logs**

<!--
为了帮助我们定位问题，请使用 debug 版 LSPosed 模块抓取日志
Please capture log with debug version, otherwise it won't help us locating the issue
 
[LSPosed-v0.5.2.0-5055-debug_LSPosedManager-v0.5.2.0-5058 Riru-v23.4(54) magisk v21.4(21406) . 模块无法激log. zip](https://github.com/LSPosed/LSPosed/files/5897624/LSPosed-v0.5.2.0-5055-debug_LSPosedManager-v0.5.2.0-5058.Riru-v23.4.54.magisk.v21.4.21406.log.zip)

**Comment by j0912H97** [comment]
[LSPosed-v0.5.2.0-5055-debug_LSPosedManager-v0.5.2.0-5058 Riru-v23.4(54) magisk v21.4(21406) . 模块无法激log. zip](https://github.com/LSPosed/LSPosed/files/5897625/LSPosed-v0.5.2.0-5055-debug_LSPosedManager-v0.5.2.0-5058.Riru-v23.4.54.magisk.v21.4.21406.log.zip)

**Comment by yujincheng08** [comment]
I don't know which module cannot be activated. Clarify your problem clearly.
