### ISSUE TITLE
Lsposed Manager in f-droid

### ISSUE THREAD

**Issue by ansarimohammed422** [LSPosed/LSPosed#106]
**Detail**:
Publish lsposed manager in f-droid

**Comment by tehcneko** [comment]
f-droid is stupid

**Comment by diabl0w** [comment]
> f-droid is stupid

not as stupid as lsposed 😂

**Comment by yujincheng08** [comment]
@diabl0w @ansarimohammed422 As for why: https://twitter.com/topjohnwu/status/1360125269130891265

**Comment by reactormonk** [comment]
Depends on https://gitlab.com/fdroid/fdroidserver/-/issues/797

**Comment by linsui** [comment]
Since the signature issue in F-Droid has been solved, whould you mind re-open this issue? Thanks!

**Comment by rollingmoai** [comment]
Updates on this?
