### ISSUE TITLE
[Feature Request] Override system language in manager so we can choose language

### ISSUE THREAD

**Issue by mywalkb** [LSPosed/LSPosed#1086]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

I'd like choose the language used in the manager.
I transled with cowdin my language but someone restore back to english some words, I don't want lost my time to translate another one. A similar feature exist in ed xposed, but was only for english.

**Comment by yujincheng08** [comment]
wdym? We haven't sync translation.

**Comment by mywalkb** [comment]
> wdym? We haven't sync translation.

sure yet no, but a day you will merge and my changes are already lost. IMHO for this app locale are useless.
I translated because I don't like a mixed locale. 
Now we can choose the language is perfect!
Thank you for very very fast implementation.
