### ISSUE TITLE
[BUG] Memory leak in YAHFA build

### ISSUE THREAD

**Issue by kotori2** [LSPosed/LSPosed#11]
Lots of users reported this. Not yet confirmed, needs further investigation. 
If you came across this issue, please use debug build and post your logs here.

**Comment by raindroplouts** [comment]
[LSPosed_Verbose_20210130_172752.log](https://github.com/LSPosed/LSPosed/files/5897689/LSPosed_Verbose_20210130_172752.log)

**Comment by yujincheng08** [comment]
@raindroplouts debug log plz.

**Comment by raindroplouts** [comment]
oh fuck
