### ISSUE TITLE
Change app locale with help of some plugins

### ISSUE THREAD

**Issue by Vendict** [LSPosed/LSPosed#1107]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Please make possible to change locale of apps with helps plugins, i.e. :
AppLocale (https://repo.xposed.info/module/com.flo354.xposed.applocale)
AppSettingsReborn(https://repo.xposed.info/module/ru.bluecat.android.xposed.mods.appsettings)

### Describe the solution you'd like/描述你想要的解决方案

Please make possible to change locale of apps with helps plugins, i.e. :
AppLocale (https://repo.xposed.info/module/com.flo354.xposed.applocale)
AppSettingsReborn(https://repo.xposed.info/module/ru.bluecat.android.xposed.mods.appsettings)

**Comment by LeeBinder** [comment]
@yujincheng08 @Vendict can you give us a hint what in AppLocale's [source code](https://github.com/Flo354/XposedAppLocale) would need to be changed for compatibility with LSPosed and Android 11?
