### ISSUE TITLE
[Bug] Fatal Exception directly after boot

### ISSUE THREAD

**Issue by yennor** [LSPosed/LSPosed#1117]
### Steps to reproduce/复现步骤

1. Freshly install ArrowOs 11.0 on my Poco X3 NFC with microg (no google apps). 
2. Install magisk
3. Reboot
3. install riru
4. reboot
4. install riru-lsposed
5. reboot

### Expected behaviour/预期行为

LSPosed should be executed, management app appear

### Actual behaviour/实际行为

Exception in logcat. Management App nowhere

### Xposed Module List/Xposed 模块列表

```shell
nothing
```

### Magisk Module List/Magisk 模块列表

```shell
- Systemless Hosts
- AuroraServices
- F-Droid Privileged Extension
- Riru
```

### LSPosed version/LSPosed 版本

1.5.3 (5984)

### Android version/安卓版本

11, Security update 5.september 2021

### Magisk version/Magisk 版本

23.0

### Riru version/Riru 版本

26.1.2.r505.c20529bced

### CI Version/CI 版本

- [X] I am using latest CI version of LSPosed/我正在使用最新 CI 版本

### Logs/日志

FATAL EXCEPTION: main
PID: 667
java.lang.UnsatisfiedLinkError: dlopen failed: "/data/adb/modules/riru_lsposed/libdaemon.so" has bad ELF magic: 00000000
	at java.lang.Runtime.load0(Runtime.java:939)
	at java.lang.System.load(System.java:1628)
	at org.lsposed.lspd.service.LogcatService.<init>(Unknown Source:42)
	at org.lsposed.lspd.core.Main.main(Unknown Source:131)
	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:401)

**Comment by yujincheng08** [comment]
libdaemon.so is corrupted. Please check ur installation.
