### ISSUE TITLE
大佬 

### ISSUE THREAD

**Issue by xiaoTT** [LSPosed/LSPosed#1184]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

摩托罗拉edge s官方的分身id 是900-905 lsp识别不到  没办法模块应用到分身里 求改进

### Describe the solution you'd like/描述你想要的解决方案

id900-905分身应用也能享受lsp的模块

**Comment by yujincheng08** [comment]
我们只能兼容安卓的多用户，其他厂商自己造的分身功能我们不能保证兼容。想用可以使用第三方分身工具比如炼妖壶。
