### ISSUE TITLE
[Feature Request] Alternate way to open parasitic Manager

### ISSUE THREAD

**Issue by dcoolArne** [LSPosed/LSPosed#1200]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Is it possible to add some kind of Methode to open the new Manager that doesn't involve a Shortcut Widget, because i really like to keep my home screen empty. (I know this is an Issue on my side.)

### Describe the solution you'd like/描述你想要的解决方案

Maybe a way to open the new manager through the settings or magisk or even phone dialing, just some other way even if it is impractical.

**Comment by yujincheng08** [comment]
install /data/adb/lspd/manager.apk and remove the shortcut.

**Comment by dcoolArne** [comment]
But i would like to use the parasitic manager, if i install it back wouldn't i just have the normal manager again?

**Comment by starbucknathan** [comment]
Is there a way to add a afw exception for the parasitic manager?
