### ISSUE TITLE
[Bug] Soft restart after switching background

### ISSUE THREAD

**Issue by xspgy** [LSPosed/LSPosed#1214]
### Steps to reproduce/复现步骤

随便打开一个软件，按Home键回到桌面，如果在桌面直接点击应用不会软重启，如果从后台页面点击应用切换会软重启，如果从其他软件切换到另一个软件也是一样，所有xposed模块关闭并重启也是一样

### Expected behaviour/预期行为

切换后台不会软重启

### Actual behaviour/实际行为

切换后台软重启

### Xposed Module List/Xposed 模块列表

```shell
对话框取消 Beta版
核心破解
贴吧TS
微X模块
隐藏应用列表
QNotified
Rootcloak
TSBattery
```

### Magisk Module List/Magisk 模块列表

```shell
AD Hosts
Busybox for Android NDK
Riru
Riru - Hode My Applist
Riru - LXposed
Scene的附加模块
Uperf
```

### LSPosed version/LSPosed 版本

6089

### Android version/安卓版本

8.1

### Magisk version/Magisk 版本

23

### Riru version/Riru 版本

26.1.2.r505

### CI Version/CI 版本

- [ ] I am using latest CI version of LSPosed/我正在使用最新 CI 版本

### Logs/日志

[LSPosed_2021-10-03T18_53_50.123.zip](https://github.com/LSPosed/LSPosed/files/7273205/LSPosed_2021-10-03T18_53_50.123.zip)

**Comment by yujincheng08** [comment]
360 魔改了 IActivityController...
发一下 /system/framework/framework.jar 吧

**Comment by xspgy** [comment]
空的

**Comment by xspgy** [comment]
[boot-framework.zip](https://github.com/LSPosed/LSPosed/files/7273228/boot-framework.zip)
boot-framework应该也行吧，里面的dex是里面的vdex转换过的

**Comment by xspgy** [comment]
再转换成jar
[boot-framework.zip](https://github.com/LSPosed/LSPosed/files/7273238/boot-framework.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.6.0-6091-debug.zip](https://github.com/LSPosed/LSPosed/files/7273270/LSPosed-v1.6.0-6091-debug.zip)
Try this

**Comment by xspgy** [comment]
正常了
