### ISSUE TITLE
[Feature Request]  Accessing LSPosed from the settings app

### ISSUE THREAD

**Issue by ph4n70m-404** [LSPosed/LSPosed#1241]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Currently the only access to LSPosed (that i am aware of) is via a widget on the home screen. Since some people like to have a clean home screen sometimes with no icons whatsoever this can be a little inconvenient.

### Describe the solution you'd like/描述你想要的解决方案

In my opinion a good solution to this would be to be able to access LSPosed via a settings subsection, preferably in the system panel of options in an opt-in-able situation where people that didn't like it could disable it. It would also be nice if you could add the widget whenever, currently from the home screen if you try to add widgets you can't add the LSPosed one. In this solution users could add it for a bit whenever they need to access the app then remove it later.

edit: removing confusion

**Comment by ph4n70m-404** [comment]
Not exactly a duplicate as they suggest just being able to remove via a switch pestering them to add it as a widget.

**Comment by yujincheng08** [comment]
no. its not. most user pefer a shortcut.

**Comment by lss4** [comment]
Actually I also hope if there's an alternative way to access LSPosed, as I'm using [T-UI](https://github.com/fAndreuzzi/TUI-ConsoleLauncher) and [TEL](https://github.com/t-e-l) for home screen.

These home screens are CLI-style (with no concept of shortcuts or widgets) and thus I pretty much can't access LSPosed at all with them... maybe for TEL, if I know the name of the activity that leads to LSPosed, I might be able to invoke it.
