### ISSUE TITLE
[Feature Request] Automatically select apps when new app gets installed / Option for select/deselect all apps at once

### ISSUE THREAD

**Issue by ghost** [LSPosed/LSPosed#1246]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

Automatically select apps when it gets installed.
And a option for select/deselect all apps.

For example:
I use xprivacylua module and I would like to have all apps selected at all time/at once. It can be annoying to mark all one by one. But most problem is by installing a new app you have to remember that you have to select the app in the xprivacylua-module as well.

**Comment by DanSman** [comment]
Nah, you have to select each app. Otherwise it doesn't work.

**Comment by ardugitter** [comment]
See here:

https://github.com/LSPosed/LSPosed/issues/9

It is being worked on I think.

**Comment by yilksd** [comment]
@vvb2060 But the XprivacyLua README ( https://github.com/M66B/XPrivacyLua ) said that:

> LSPosed: please make sure that any app you want to restrict is [in the 'scope'](https://github.com/LSPosed/LSPosed/wiki/How-to-use-it#install--activate-modules) of LSposed.

At the moment Lsposed's  recommended scopes for XprivacyLua is system framework and settings storage, is this based on your opinion?
