### ISSUE TITLE
[Bug] 应用寄生与 关闭强制在启动器中强制显示图标无法共存

### ISSUE THREAD

**Issue by henduojigea** [LSPosed/LSPosed#1247]
### Steps to reproduce/复现步骤

开启应用寄生后，在LSP设置里关闭 “强制在启动器里显示图标”功能

### Expected behaviour/预期行为

不清楚

### Actual behaviour/实际行为

LSP无法打开，安装LSP也提示未安装模块，需重启才能恢复

### Xposed Module List/Xposed 模块列表

```shell
thanox
```

### Magisk Module List/Magisk 模块列表

```shell
Fullscreen/lmmersive Gestures (Q-S)
riru
Riru - Clipboard Whitelist
Riru Enhanced mode for Storage Isolation
riru lsposed
scene的附加模块
```

### LSPosed version/LSPosed 版本

1.6.0(6089）

### Android version/安卓版本

12beta5

### Magisk version/Magisk 版本

 b6298f86-alpha (23001)

### Riru version/Riru 版本

V26.1.2.r505. c20529bced

### CI Version/CI 版本

- [ ] I am using latest CI version of LSPosed/我正在使用最新 CI 版本

### Logs/日志

2021-10-09T07:23:01.875        0:   942:  1559 I/LSPosedLogcat   ] !!start_verbose!!
[ 2021-10-09T07:23:18.603        0:   942:  1559 I/LSPosedLogcat   ] !!refresh_verbose!!
-----part 2 end----

**Comment by Howard20181** [comment]
安装最新CI版的Debug构建并上传日志
