### ISSUE TITLE
Add an Option To Use Old Xposed Repo and more Repos

### ISSUE THREAD

**Issue by NULL0B** [LSPosed/LSPosed#126]
Is it possible to add a switch or maybe anthoer menu or button to open Old Exposed Repo also? The repo is now back to life.
is it possible to add an option to change github repo url as Magisk manager has?

**Comment by tehcneko** [comment]
no

**Comment by yujincheng08** [comment]
that one is deprecated

**Comment by NULL0B** [comment]
> that one is deprecated

and what about a custom repo url like magisk?
