### ISSUE TITLE
[Bug] Lsposed 1.6.1 prevent modules from working

### ISSUE THREAD

**Issue by Massi-X** [LSPosed/LSPosed#1272]
### Steps to reproduce/复现步骤

1. Update to Lsposed 1.6.1 from an older version
2. Reboot and look at your previously working modules, they don't work anymore (everything is active)
3. To make it work again you have to disable and re-enable them, causing confusion and one star reviews from the users!
Confirmed by me and another user

### Expected behaviour/预期行为

The hooks should work if the module is enabled in the preferences

### Actual behaviour/实际行为

Modules don't work as shown in the UI

### Xposed Module List/Xposed 模块列表

```shell
Everyone affected, for reference
com.metris.xposed.pmods
com.metris.xposed.bluetoothToolkitFree
```

### Magisk Module List/Magisk 模块列表

```shell
Riru
Riru - lsposed
```

### LSPosed version/LSPosed 版本

1.6.1

### Android version/安卓版本

11

### Magisk version/Magisk 版本

23

### Riru version/Riru 版本

26.1.3

### CI Version/CI 版本

- [X] I am using latest CI version of LSPosed/我正在使用最新 CI 版本

### Logs/日志

After the update to 1.6.1 and a reboot it loads the module but it doesn't really work:
[ 2021-10-14T15:27:34.520    10540: 10086: 10086 I/LSPosed-Bridge  ] Loading module com.metris.xposed.pmods from /data/app/~~_UR5lb9gFlqZiCY1qwfTIw==/com.metris.xposed.pmods-aSvfZAIqddAnetIQjID_jg==/base.apk
[ 2021-10-14T15:27:34.792    10540: 10086: 10086 I/LSPosed-Bridge  ]   Loading class com.metris.xposed.pmods.xposed.InitAll

Then going into the UI, disabling and re enabling the module and  kill the target app (in this case the pixel launcher), the module loads and work fine (see the log coming from the module on the last lline:
[ 2021-10-14T15:32:34.766    10013: 14430: 14430 I/LSPosed-Bridge  ] Loading module com.metris.xposed.pmods from /data/app/~~_UR5lb9gFlqZiCY1qwfTIw==/com.metris.xposed.pmods-aSvfZAIqddAnetIQjID_jg==/base.apk
[ 2021-10-14T15:32:34.917    10013: 14430: 14430 I/LSPosed-Bridge  ]   Loading class com.metris.xposed.pmods.xposed.InitAll
[ 2021-10-14T15:32:35.000    10013: 14430: 14430 I/LSPosed-Bridge  ] Starting up for pkg: com.google.android.apps.nexuslauncher with version: 821...

**Comment by etmatrix** [comment]
@Massi-X you can use [this](https://github.com/LSPosed/LSPosed/actions/runs/1341762184) release which contains the fix for your issue.

**Comment by Massi-X** [comment]
Can confirm it does work, thank you

**Comment by yujincheng08** [comment]
> Thank you! Do you have an ETA for the update?

Released
