### ISSUE TITLE
[Bug] Parasite manager disappears sometimes

### ISSUE THREAD

**Issue by techIndia-hacker** [LSPosed/LSPosed#1278]
### Steps to reproduce/复现步骤

1. Stop the OnePlus launcher using su
2. Go back to home screen
3. Lsposed shortcut vanishes

Device 1+7t & Oos 11.0.3

### Expected behaviour/预期行为

Lsposed manager shortcut shouldn't vanish from homescreen if the launcher performs a restart operation automatically

### Actual behaviour/实际行为

Parasitic lsposed manager vanishes on launcher restart

### Xposed Module List/Xposed 模块列表

```shell
Gravity box R
Lucky patcher
```

### Magisk Module List/Magisk 模块列表

```shell
Busy box
Riru core
Lsposed
Safetynet fix
Mount overlay fix
Wifi(qcom)
```

### LSPosed version/LSPosed 版本

6146

### Android version/安卓版本

11

### Magisk version/Magisk 版本

23

### Riru version/Riru 版本

26.1.3

### CI Version/CI 版本

- [X] I am using latest CI version of LSPosed/我正在使用最新 CI 版本

### Logs/日志

[Lsposed log.txt](https://github.com/LSPosed/LSPosed/files/7351067/Lsposed.log.txt)

**Comment by yujincheng08** [comment]
Nothing we can do. It's most likely the launcher's issue. Unless some log from the launcher telling why it removes the shortcut, we have nothing to fix.
