### ISSUE TITLE
Is there a way for the framework with manager to detect needed scope?

### ISSUE THREAD

**Issue by NULL0B** [LSPosed/LSPosed#128]
Maybe if the framework saves in a db a module name with hooked classes made by api. so the manager can find the apps that contain that classes and suggest to the user or auto add to white list.
This removes the necessity of wiki or separate repo for scoped manifest info for old modules. and also deprecates the manifest option.
Thanks
PD: This could have a better aproach.

**Comment by yujincheng08** [comment]
I dont think it necessary.
