### ISSUE TITLE
[Bug] Strange behaviour on fragment repoitem when I scroll up

### ISSUE THREAD

**Issue by etmatrix** [LSPosed/LSPosed#1288]
### Steps to reproduce/复现步骤

Open Manager
Repository
Tap a random module
Scroll up

### Expected behaviour/预期行为

Toolbar should stay on top and not partially

### Actual behaviour/实际行为

Toolbar go up partially and I can't see it
Here a screenshot which explain better
![Screenshot_20211016-121355_Shell](https://user-images.githubusercontent.com/3065939/137586915-71f182a1-ea75-413b-99b0-e4c315bbbad4.png)

### Xposed Module List/Xposed 模块列表

```shell
My custom test module
```

### Magisk Module List/Magisk 模块列表

```shell
Riru
Lsposed
```

### LSPosed version/LSPosed 版本

1.6.2 (6152)

### Android version/安卓版本

11 LineageOS 18.1

### Magisk version/Magisk 版本

23.0 23000

### Riru version/Riru 版本

26.1.3

### CI Version/CI 版本

- [X] I am using latest CI version of LSPosed/我正在使用最新 CI 版本

### Logs/日志

No logs are generate by LSPosed while the action scroll up.

**Comment by yujincheng08** [comment]
This is how MD3 is designed.
