### ISSUE TITLE
[Bug] module disabled after abnormal softreboot

### ISSUE THREAD

**Issue by ale82to** [LSPosed/LSPosed#1307]
### Steps to reproduce/复现步骤

after abnormal softreboot (not normal user softreboot) lsposed shows as active and also modules but actually nothing works!.
my device is a poco F3 on dot os 5.2 (Android 11) but I remember the same exact issue happened to me on my old phone arrow os (Android 11, mi 10 Lite and EdXposed).
this happened to me twice in the last 3 days (while disabling some bloatware that caused the abnormal softreboot). 
the first time it was late at night and I did not have time to do some test so I restored my full twrp backup (hopefully!) 
today happened again and I had some time to spare, I read on xda that this may sometimes happen and removing both Riru and lsposed from Magisk and then rebooting and reinstalling them is supposed to fix this flaw. 
well for me it did not work at all. I even wiped dalvik and system cache from TWRP without success. 
so as I last resort I restored my trwrp backup but I first tried just restoring super (system) wich did not fixed the problem, then I just restored data which did fixed the issue hopefully. 
can please someone give some advice or some hints for next time is gonna happen to solve this without restoring twrp data (i mquite sure that some just some files /permission get currupted) backup.
sorry for such a long bug report and thanks for the help. 

### Expected behaviour/预期行为

after the abnormal softreboot modules should work normally 

### Actual behaviour/实际行为

both lsposed and modules show as active but they won't work at all 

### Xposed Module List/Xposed 模块列表

```shell
xposed edge pro
Pokémon go
```

### Magisk Module List/Magisk 模块列表

```shell
busybox
Riru
lsposed
```

### LSPosed version/LSPosed 版本

1.6. 2

### Android version/安卓版本

11

### Magisk version/Magisk 版本

23

### Riru version/Riru 版本

26.1. 2

### CI Version/CI 版本

- [X] I am using latest CI version of LSPosed/我正在使用最新 CI 版本

### Logs/日志

log:
----part 1 start----
[ 1970-06-13T12:49:33.022        0:   582:   582 F/libc            ] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 582 (init), pid 582 (init)
[ 1970-06-13T12:49:33.032        0:   582:   582 F/libc            ] crash_dump helper failed to exec
[ 2021-10-18T04:39:48.976        0:   734:   734 D/AndroidRuntime  ] >>>>>> START com.android.internal.os.RuntimeInit uid 0 <<<<<<
[ 2021-10-18T04:39:49.004        0:   734:   734 I/AndroidRuntime  ] Using default boot image
[ 2021-10-18T04:39:49.004        0:   734:   734 I/AndroidRuntime  ] Leaving lock profiling enabled
[ 2021-10-18T04:39:49.213        0:   748:   748 I/Riru64          ] Riru v26.1.3 (513) in zygote64
[ 2021-10-18T04:39:49.213        0:   748:   748 I/Riru64          ] Android 11 (api 30, preview_api 0)
[ 2021-10-18T04:39:49.213        0:   748:   748 W/Riru64          ] retrying to connect rirud in 1s
[ 2021-10-18T04:39:49.268        0:   734:   734 D/lspd            ] Time zone APEX ICU file found: /apex/com.android.tzdata/etc/icu/icu_tzdata.dat
[ 2021-10-18T04:39:49.272        0:   734:   734 D/lspd            ] I18n APEX ICU file found: /apex/com.android.i18n/etc/icu/icudt66l.dat
[ 2021-10-18T04:39:49.351        0:   749:   749 I/Riru            ] Riru v26.1.3 (513) in zygote
[ 2021-10-18T04:39:49.351        0:   749:   749 I/Riru            ] Android 11 (api 30, preview_api 0)
[ 2021-10-18T04:39:49.351        0:   749:   749 W/Riru            ] retrying to connect rirud in 1s
[ 2021-10-18T04:39:49.435        0:   734:   734 W/lspd            ] JNI RegisterNativeMethods: attempt to register 0 native methods for android.media.AudioAttributes
[ 2021-10-18T04:39:49.464        0:   734:   734 D/AndroidRuntime  ] Calling main entry org.lsposed.lspd.core.Main
[ 2021-10-18T04:39:49.478        0:   730:   963 I/RiruDaemon      ] Set socket context to u:r:zygote:s0
[ 2021-10-18T04:39:49.478        0:   730:   963 D/RiruDaemon      ] Start server
[ 2021-10-18T04:39:49.480        0:   730:   963 D/RiruDaemon      ] Accept
[ 2021-10-18T04:39:49.518        0:   734:   734 I/LSPosedService  ] starting server...
[ 2021-10-18T04:39:49.518        0:   734:   734 I/LSPosedService  ] version 1.6.2 (6152)
[ 2021-10-18T04:39:49.524        0:   734:   981 I/LSPosedLogcat   ] start running
[ 2021-10-18T04:39:49.526        0:   734:   981 I/LSPosedLogcat   ] New verbose log file: /data/adb/lspd/log/verbose_2021-10-18T04:39:49.524.txt
[ 2021-10-18T04:39:49.528        0:   734:   981 I/LSPosedLogcat   ] New modules log file: /data/adb/lspd/log/modules_2021-10-18T04:39:49.528.txt
[ 2021-10-18T04:39:49.588        0:   734:   734 W/SQLiteCompatibilityWalFlags ] Cannot read global setting sqlite_compatibility_wal_flags - Application state not available
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/lib64/libriru.so
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/lib64/libriruhide.so
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/lib64
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/system/lib64/libriruloader.so
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/system/lib64
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/system
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/lib/libriru.so
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/lib/libriruhide.so
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/lib
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/system/lib/libriruloader.so
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/system/lib
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core/system
[ 2021-10-18T04:39:49.908        0:   730:   730 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru-core
[ 2021-10-18T04:39:49.909        0:   730:   730 I/RiruDaemon      ] Magisk version is 23000
[ 2021-10-18T04:39:49.909        0:   730:   730 I/RiruDaemon      ] Magisk tmpfs path is /dev/RVYx
[ 2021-10-18T04:39:49.909        0:   730:   730 I/RiruDaemon      ] Original native bridge is 0
[ 2021-10-18T04:39:49.909        0:   730:  1176 D/RiruDaemon      ] /dev/RVYx/.magisk/modules/riru_lsposed is a Riru module
[ 2021-10-18T04:39:49.909        0:   730:  1176 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru_lsposed/riru/lib/liblspd.so
[ 2021-10-18T04:39:49.909        0:   730:  1176 D/RiruDaemon      ] Path for riru_lsposed@lspd is /dev/RVYx/.magisk/modules/riru_lsposed/riru/lib/liblspd.so
[ 2021-10-18T04:39:49.909        0:   730:  1176 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru_lsposed/riru/lib
[ 2021-10-18T04:39:49.909        0:   730:  1176 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru_lsposed/riru
[ 2021-10-18T04:39:49.910        0:   730:  1176 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru_lsposed
[ 2021-10-18T04:39:49.912        0:   730:  1175 D/RiruDaemon      ] /dev/RVYx/.magisk/modules/riru_lsposed is a Riru module
[ 2021-10-18T04:39:49.912        0:   730:  1175 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru_lsposed/riru/lib64/liblspd.so
[ 2021-10-18T04:39:49.912        0:   730:  1175 D/RiruDaemon      ] Path for riru_lsposed@lspd is /dev/RVYx/.magisk/modules/riru_lsposed/riru/lib64/liblspd.so
[ 2021-10-18T04:39:49.912        0:   730:  1175 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru_lsposed/riru/lib64
[ 2021-10-18T04:39:49.912        0:   730:  1175 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru_lsposed/riru
[ 2021-10-18T04:39:49.912        0:   730:  1175 D/RiruDaemon      ] u:object_r:system_file:s0 /dev/RVYx/.magisk/modules/riru_lsposed
[ 2021-10-18T04:39:49.918        0:   730:   730 I/RiruDaemon      ] Read dev random BPLuHCU
[ 2021-10-18T04:39:49.918        0:   730:   730 I/RiruDaemon      ] Dev random is BPLuHCU
[ 2021-10-18T04:39:49.919        0:   730:   730 I/RiruDaemon      ] clear ServiceManager
[ 2021-10-18T04:39:49.923        0:   730:   730 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2021-10-18T04:39:49.945        0:   734:   734 I/LSPosedService  ] service package is not started, wait 1s.
[ 2021-10-18T04:39:49.992        0:   714:  1277 I/Magisk          ] ** late_start service mode running
[ 2021-10-18T04:39:49.992        0:   714:  1277 I/Magisk          ] * Running service.d scripts
[ 2021-10-18T04:39:49.992        0:   714:  1277 I/Magisk          ] * Running module service scripts
[ 2021-10-18T04:39:49.992        0:   714:  1277 I/Magisk          ] riru-core: exec [service.sh]
[ 2021-10-18T04:39:49.993        0:   714:  1277 I/Magisk          ] riru_lsposed: exec [service.sh]
[ 2021-10-18T04:39:50.095     1000:  1369:  1369 F/libc            ] Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) in tid 1369 (vendor.lineage.), pid 1369 (vendor.lineage.)
[ 2021-10-18T04:39:50.117     1000:  1404:  1404 F/DEBUG           ] *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ] Build fingerprint: 'google/redfin/redfin:11/RQ3A.210805.001.A1/7474174:user/release-keys'
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ] Revision: '0'
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ] ABI: 'arm64'
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ] Timestamp: 2021-10-18 04:39:50+0200
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ] pid: 1369, tid: 1369, name: vendor.lineage.  >>> /vendor/bin/hw/vendor.lineage.livedisplay@2.0-service-sdm <<<
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ] uid: 1000
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ] signal 6 (SIGABRT), code -1 (SI_QUEUE), fault addr --------
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ] Abort message: 'PictureAdjustment backend not ready, exiting.'
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ]     x0  0000000000000000  x1  0000000000000559  x2  0000000000000006  x3  0000007ffb7fd1e0
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ]     x4  0000000000000000  x5  0000000000000000  x6  0000000000000000  x7  7f7f7f7f7f7f7f7f
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ]     x8  00000000000000f0  x9  d299cc5cef88e731  x10 0000000000000000  x11 ffffffc0ffffffdf
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ]     x12 0000000000000001  x13 000000000000002e  x14 00057bcf768b22cb  x15 00000000341555ad
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ]     x16 0000007892b3fc80  x17 0000007892b21950  x18 000000789395c000  x19 0000000000000559
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ]     x20 0000000000000559  x21 00000000ffffffff  x22 00000078931e0000  x23 b4000077227e3698
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ]     x24 0000000000000000  x25 0000000000000000  x26 0000000000000000  x27 0000000000000000
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ]     x28 0000000000000000  x29 0000007ffb7fd260
[ 2021-10-18T04:39:50.118     1000:  1404:  1404 F/DEBUG           ]     lr  0000007892ad40ec  sp  0000007ffb7fd1c0  pc  0000007892ad4118  pst 0000000000001000
[ 2021-10-18T04:39:50.120     1000:  1404:  1404 F/DEBUG           ] backtrace:
[ 2021-10-18T04:39:50.120     1000:  1404:  1404 F/DEBUG           ]       #00 pc 000000000004e118  /apex/com.android.runtime/lib64/bionic/libc.so (abort+164) (BuildId: a05048b33ef27dbba9dab33905cfeddd)
[ 2021-10-18T04:39:50.120     1000:  1404:  1404 F/DEBUG           ]       #01 pc 00000000000062a4  /system/lib64/liblog.so (__android_log_default_aborter+12) (BuildId: 2f6dd032979577b24e54978331f34763)
[ 2021-10-18T04:39:50.120     1000:  1404:  1404 F/DEBUG           ]       #02 pc 0000000000012fa4  /apex/com.android.vndk.v30/lib64/libbase.so (android::base::LogMessage::~LogMessage()+320) (BuildId: a5b94a27fb193ef64c84417086861e55)
[ 2021-10-18T04:39:50.120     1000:  1404:  1404 F/DEBUG           ]       #03 pc 0000000000005688  /vendor/bin/hw/vendor.lineage.livedisplay@2.0-service-sdm (vendor::lineage::livedisplay::V2_0::sdm::PictureAdjustment::PictureAdjustment(std::__1::shared_ptr<vendor::lineage::livedisplay::V2_0::sdm::SDMController>)+240) (BuildId: 605ead4d562b19463bbc5297c9261e53)
[ 2021-10-18T04:39:50.120     1000:  1404:  1404 F/DEBUG           ]       #04 pc 0000000000006e98  /vendor/bin/hw/vendor.lineage.livedisplay@2.0-service-sdm (RegisterAsServices()+116) (BuildId: 605ead4d562b19463bbc5297c9261e53)
[ 2021-10-18T04:39:50.120     1000:  1404:  1404 F/DEBUG           ]       #05 pc 000000000000732c  /vendor/bin/hw/vendor.lineage.livedisplay@2.0-service-sdm (main+108) (BuildId: 605ead4d562b19463bbc5297c9261e53)
[ 2021-10-18T04:39:50.120     1000:  1404:  1404 F/DEBUG           ]       #06 pc 0000000000049718  /apex/com.android.runtime/lib64/bionic/libc.so (__libc_init+108) (BuildId: a05048b33ef27dbba9dab33905cfeddd)
[ 2021-10-18T04:39:50.215        0:   730:   963 D/RiruDaemon      ] Accepted uid=0, pid=748, context=u:r:zygote:s0
[ 2021-10-18T04:39:50.215        0:   730:   963 D/RiruDaemon      ] Accept
[ 2021-10-18T04:39:50.217        0:   730:  1459 I/RiruDaemon      ] Action 6
[ 2021-10-18T04:39:50.217        0:   730:  1459 I/RiruDaemon      ] Action: read Magisk tmpfs path
[ 2021-10-18T04:39:50.218        0:   730:  1459 I/RiruDaemon      ] Handle action 6 finished
[ 2021-10-18T04:39:50.245        0:   748:   748 I/Riru64          ] hook installed
[ 2021-10-18T04:39:50.245        0:   730:  1459 I/RiruDaemon      ] Action 7
[ 2021-10-18T04:39:50.245        0:   730:  1459 I/RiruDaemon      ] Action: read modules
[ 2021-10-18T04:39:50.245        0:   730:  1459 I/RiruDaemon      ] Handle action 7 finished
[ 2021-10-18T04:39:50.249        0:   748:   748 I/Riru64          ] module loaded: riru_lsposed@lspd (api 25)
[ 2021-10-18T04:39:50.273        0:   748:   748 I/LSPosed         ] onModuleLoaded: welcome to LSPosed!
[ 2021-10-18T04:39:50.273        0:   748:   748 I/LSPosed         ] onModuleLoaded: version v1.6.2 (6152)
[ 2021-10-18T04:39:50.275        0:   748:   748 I/LSPosed         ] Loaded /dev/RVYx/.magisk/modules/riru_lsposed/framework/lspd.dex with size 305176
[ 2021-10-18T04:39:50.322        0:   730:  1459 I/RiruDaemon      ] Action 2
[ 2021-10-18T04:39:50.323        0:   730:  1459 I/RiruDaemon      ] Action: write status
[ 2021-10-18T04:39:50.325        0:   730:  1459 I/RiruDaemon      ] Handle action 2 finished
[ 2021-10-18T04:39:50.325        0:   730:  1459 I/RiruDaemon      ] No next action, exiting...
[ 2021-10-18T04:39:50.342        0:   748:   748 I/Riru64          ] replaced com.android.internal.os.Zygote#nativeForkAndSpecialize
[ 2021-10-18T04:39:50.342        0:   748:   748 I/Riru64          ] replaced com.android.internal.os.Zygote#nativeForkSystemServer
[ 2021-10-18T04:39:50.342        0:   748:   748 I/Riru64          ] replaced com.android.internal.os.Zygote#nativeSpecializeAppProcess
[ 2021-10-18T04:39:50.352        0:   730:   963 D/RiruDaemon      ] Accepted uid=0, pid=749, context=u:r:zygote:s0
[ 2021-10-18T04:39:50.352        0:   730:   963 D/RiruDaemon      ] Accept
[ 2021-10-18T04:39:50.352        0:   730:  1479 I/RiruDaemon      ] Action 6
[ 2021-10-18T04:39:50.352        0:   730:  1479 I/RiruDaemon      ] Action: read Magisk tmpfs path
[ 2021-10-18T04:39:50.352        0:   730:  1479 I/RiruDaemon      ] Handle action 6 finished
[ 2021-10-18T04:39:50.378        0:   749:   749 I/Riru            ] hook installed
[ 2021-10-18T04:39:50.379        0:   730:  1479 I/RiruDaemon      ] Action 7
[ 2021-10-18T04:39:50.379        0:   730:  1479 I/RiruDaemon      ] Action: read modules
[ 2021-10-18T04:39:50.380        0:   730:  1479 I/RiruDaemon      ] Handle action 7 finished
[ 2021-10-18T04:39:50.381        0:   749:   749 I/Riru            ] module loaded: riru_lsposed@lspd (api 25)
[ 2021-10-18T04:39:50.393        0:   749:   749 I/LSPosed         ] onModuleLoaded: welcome to LSPosed!
[ 2021-10-18T04:39:50.393        0:   749:   749 I/LSPosed         ] onModuleLoaded: version v1.6.2 (6152)
[ 2021-10-18T04:39:50.394        0:   749:   749 I/LSPosed         ] Loaded /dev/RVYx/.magisk/modules/riru_lsposed/framework/lspd.dex with size 305176
[ 2021-10-18T04:39:50.426        0:   730:  1479 I/RiruDaemon      ] Action 2
[ 2021-10-18T04:39:50.426        0:   730:  1479 I/RiruDaemon      ] Action: write status
[ 2021-10-18T04:39:50.427        0:   730:  1479 I/RiruDaemon      ] Handle action 2 finished
[ 2021-10-18T04:39:50.427        0:   730:  1479 I/RiruDaemon      ] No next action, exiting...
[ 2021-10-18T04:39:50.576        0:   749:   749 I/Riru            ] replaced com.android.internal.os.Zygote#nativeForkAndSpecialize
[ 2021-10-18T04:39:50.576        0:   749:   749 I/Riru            ] replaced com.android.internal.os.Zygote#nativeForkSystemServer
[ 2021-10-18T04:39:50.576        0:   749:   749 I/Riru            ] replaced com.android.internal.os.Zygote#nativeSpecializeAppProcess
[ 2021-10-18T04:39:50.924        0:   730:   730 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2021-10-18T04:39:50.945        0:   734:   734 I/LSPosedService  ] service package is not started, wait 1s.
[ 2021-10-18T04:39:51.483     1000:  1573:  1573 I/LSPosed         ] Loading modules for system_server/1000
[ 2021-10-18T04:39:51.495     1000:  1573:  1573 I/LSPosed-Bridge  ] Loading module com.jozein.xedgepro from /data/app/~~zV4vrfLog6ULt2lJUWGLFQ==/com.jozein.xedgepro-0ZwCOx-eNzFHRqATEeRy0w==/base.apk
[ 2021-10-18T04:39:51.499     1000:  1573:  1573 I/LSPosed-Bridge  ]   Loading class com.jozein.xedgepro.xposed.HookMain
[ 2021-10-18T04:39:51.513     1000:  1573:  1573 I/LSPosed-Bridge  ] [XEdgePro] Cannot load settings!
[ 2021-10-18T04:39:51.917     1000:  1573:  1573 I/LSPosed-Bridge  ] [XEdgePro] Xposed-edge-pro-v6.0.4. 
Xiaomi M2012K11AG, alioth, Android 11, SDK 30, ROM: RD2A.211001.002, SELinux enforced.
[ 2021-10-18T04:39:51.924        0:   730:   730 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2021-10-18T04:39:51.945        0:   734:   734 I/LSPosedService  ] service package is not started, wait 1s.
[ 2021-10-18T04:39:51.965     1000:  1573:  1573 I/LSPosed-Bridge  ] [XEdgePro] System hooked.
[ 2021-10-18T04:39:52.924        0:   730:   730 I/RiruDaemon      ] Service activity not found, wait 1s...
[ 2021-10-18T04:39:52.946        0:   734:   734 I/LSPosedService  ] service package is not started, wait 1s.
[ 2021-10-18T04:39:53.352        0:   734:  1145 I/LSPosedService  ] manager is not installed
[ 2021-10-18T04:39:53.940        0:   730:   730 I/RiruDaemon      ] Riru loaded, reset native bridge to 0...
[ 2021-10-18T04:39:53.950        0:   730:   730 I/RiruDaemon      ] Exec resetprop exited with 0
[ 2021-10-18T04:39:53.950        0:   730:   730 I/RiruDaemon      ] Riru loaded, stop rirud socket...
[ 2021-10-18T04:39:53.950        0:   730:   730 I/RiruDaemon      ] Stop server
[ 2021-10-18T04:39:53.950        0:   730:   730 I/RiruDaemon      ] Server stopped
[ 2021-10-18T04:39:53.969     1000:  1573:  1615 I/LSPosedService  ] binder received
[ 2021-10-18T04:39:53.969        0:   730:   963 W/RiruDaemon      ] Accept failed, server is closed ?
java.net.SocketException: Socket closed
	at libcore.io.Linux.accept(Native Method)
	at libcore.io.ForwardingOs.accept(ForwardingOs.java:69)
	at libcore.io.BlockGuardOs.accept(BlockGuardOs.java:63)
	at android.system.Os.accept(Os.java:53)
	at android.system.Os.accept(Os.java:47)
	at android.net.LocalSocketImpl.accept(LocalSocketImpl.java:306)
	at android.net.LocalServerSocket.accept(LocalServerSocket.java:91)
	at b.d.c(Unknown Source:23)
	at b.d.run(:2)
[ 2021-10-18T04:39:53.969        0:   730:   963 I/RiruDaemon      ] Waiting for restart server...
[ 2021-10-18T04:39:53.969        0:   734:   734 I/LSPosedService  ] sent service to bridge
[ 2021-10-18T04:39:53.969        0:   734:   734 I/LSPosedLogcat   ] !!stop_verbose!!

**Comment by yujincheng08** [comment]
> today happened again I installed debug build apk and took a verbose log where do I upload the zip containing log, on mobile version of github I cannot see any upload button. thanks

click the bottom bar in the edit box (PC Only)
