### ISSUE TITLE
[Bug] Error downloading

### ISSUE THREAD

**Issue by 89z** [LSPosed/LSPosed#1318]
### Steps to reproduce/复现步骤

If I try to install LSPosed from inside Magisk:

~~~
v1.6.2 (6152)
~~~

### Expected behaviour/预期行为

Success

### Actual behaviour/实际行为

I get this message:

~~~
Magisk Manager
Riru_-_LSPosed-v1.6.2_(6152)(6152).zip
Error downloading
~~~

### Xposed Module List/Xposed 模块列表

```shell
Riru
```

### Magisk Module List/Magisk 模块列表

```shell
Riru
```

### LSPosed version/LSPosed 版本

6152

### Android version/安卓版本

8

### Magisk version/Magisk 版本

v21.4

### Riru version/Riru 版本

26.1.3

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

None

**Comment by yujincheng08** [comment]
Its not broken. We also tested with MagiskOnEmulator.

**Comment by 89z** [comment]
https://github.com/shakalaca/MagiskOnEmulator/issues/47

**Comment by yujincheng08** [comment]
Nah. It works like a charm.

**Comment by 89z** [comment]
@yujincheng08 thank you for the picture, however it is useless without instruction how to install new version of Magisk.

**Comment by yujincheng08** [comment]
> @yujincheng08 thank you for the picture, however it is useless without instruction how to install new version of Magisk.

Instruction: https://github.com/shakalaca/MagiskOnEmulator#install-magisk-on-official-android-emulator

**Comment by 89z** [comment]
> Instruction: https://github.com/shakalaca/MagiskOnEmulator#install-magisk-on-official-android-emulator

@yujincheng08 thank you for the instruction, however many people have tried instruction, which is not valid:

https://github.com/shakalaca/MagiskOnEmulator/issues/47

**Comment by yujincheng08** [comment]
Many people find it works on the other hand ;)

**Comment by yujincheng08** [comment]
I at least tried 23, 27, 30, 31

**Comment by yujincheng08** [comment]
One of our devs try from 22-31 except 28 and all works great 😅

**Comment by 89z** [comment]
I know for a fact that your comments are not valid, as both scripts have a bug:

- https://github.com/shakalaca/MagiskOnEmulator/blob/2561f3f06d523b038bb7055522cb024b33995f17/patch.bat#L5
- https://github.com/shakalaca/MagiskOnEmulator/blob/2561f3f06d523b038bb7055522cb024b33995f17/patch.sh#L5-L6

**Comment by 89z** [comment]
The file name does not match... should be  `Magisk-v23.0.apk`

**Comment by 89z** [comment]
I think I am smart enough:

https://stackoverflow.com/users/1002260

**Comment by 89z** [comment]
@yujincheng08 its simple, you cannot point to valid instruction. You can point to broken instruction, so I will say new Magisk is broken. When you can show valid instruction, then I can say new Magisk is valid. Thank you!

**Comment by yujincheng08** [comment]
Locking this issue since it's definitely not relative to LSPosed. We cannot help you download LSPosed without Internet access.
