### ISSUE TITLE
swype row module doesn't work with lsposed[Bug] 

### ISSUE THREAD

**Issue by patrickdrd** [LSPosed/LSPosed#1345]
### Steps to reproduce/复现步骤

1. download swype from here:
https://www.apkmirror.com/apk/nuance-communications-inc/swype-dragon-trial/
2. download swype row module from here:
https://forum.xda-developers.com/t/app-xposed-swype-row-26-05-2016-v1-4-thread-update-27-07-2017.3297733/

### Expected behaviour/预期行为

it should insert a new row in swype keyboard

### Actual behaviour/实际行为

it isn't working for me with lsposed, it was working fine with edxposed I had before

### Xposed Module List/Xposed 模块列表

```shell
app locale
core patch
custoMIUIzer
hiddencore module
maps tweaks
swype row
```

### Magisk Module List/Magisk 模块列表

```shell
magiskhide props config
riru
auto insmod modules
busybox for android ndk
move certificates
systemless host
universal safetynet fix
```

### LSPosed version/LSPosed 版本

1.6.2.0

### Android version/安卓版本

10

### Magisk version/Magisk 版本

23.0

### Riru version/Riru 版本

25.4.4

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志
[LSPosed_2021-11-01T10_19_13.668.zip](https://github.com/LSPosed/LSPosed/files/7451699/LSPosed_2021-11-01T10_19_13.668.zip)

[LSPosed_2021-11-01T10_19_00.808.zip](https://github.com/LSPosed/LSPosed/files/7451697/LSPosed_2021-11-01T10_19_00.808.zip)

**Comment by yujincheng08** [comment]
You are not using debug CI version but you ticked.

And this module requires resources hook but you didn't mention if you enable it.
