### ISSUE TITLE
[Bug] Lsposed is not activated 1.6.2

### ISSUE THREAD

**Issue by SungJinWoou** [LSPosed/LSPosed#1346]
### Steps to reproduce/复现步骤

1.Download and install Riru
2.Download and install Riru Lsposed 1.6.2
3.Reboot and then launch manager Lsposed.

### Expected behaviour/预期行为

It should say that Lsposed is actives and working fine .

### Actual behaviour/实际行为

It says to install or activate Lsposed nor I already did that, even with a fresh clean.

### Xposed Module List/Xposed 模块列表

```shell
No module
```

### Magisk Module List/Magisk 模块列表

```shell
MagiskHide props config
Riru
Riru Lsposed
```

### LSPosed version/LSPosed 版本

1.6.2 (6152)

### Android version/安卓版本

Android 11

### Magisk version/Magisk 版本

Magisk v.23

### Riru version/Riru 版本

Riru 26.31.3

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Can't have access to the logs via Lsposed.

![Screenshot_20211101-132016](https://user-images.githubusercontent.com/93525884/139670577-50eb4c57-e5e3-4d1b-b118-d77c2de2ff48.jpg)
![Screenshot_20211101-132125](https://user-images.githubusercontent.com/93525884/139670616-fb09ae5b-944d-4921-9419-791efbc836c4.jpg)

**Comment by yujincheng08** [comment]
screenshot Magisk module list.

**Comment by yujincheng08** [comment]
No response. Close.

**Comment by SungJinWoou** [comment]
Hi,

Sorry didn't see your message at time, here is the screenshot.
![Screenshot_20211101-141508](https://user-images.githubusercontent.com/93525884/139677446-348e62b9-5932-4f0d-8f0d-db09935c7c90.jpg)

**Comment by yujincheng08** [comment]
riru is not showing its status. So its riru's problem.

**Comment by SungJinWoou** [comment]
Okay so I have to go on Riru GitHub for the problem.

**Comment by yujincheng08** [comment]
Yes.

**Comment by SungJinWoou** [comment]
Thank you
