### ISSUE TITLE
[Feature Request] Enable a module for all apps by default

### ISSUE THREAD

**Issue by twann4** [LSPosed/LSPosed#1349]
Currently, the user has to select each app to enable with a module manually. This is very inconvenient with modules such as XPrivacyLua.

XPrivacyLua has a feature to restrict all new apps from accessing the clipboard, getting the installed apps, etc. - which is really useful. However, the fact that the user has to enable each app in LSPosed makes it useless.

**Comment by Howard20181** [comment]
#9

**Comment by v-dawg** [comment]
Yes, please add this :)
