### ISSUE TITLE
[Bug] Dark Nav Bar becomes visible in apps

### ISSUE THREAD

**Issue by changetotower** [LSPosed/LSPosed#1358]
### Steps to reproduce/复现步骤

Install latest LSPosed Module with Magisk v23

### Expected behaviour/预期行为

Navigation bar remains transparent

### Actual behaviour/实际行为

Dark Nav Bar becomes visible in apps / Magisk Module "Fullscreen Gestures" not working anymore

### Xposed Module List/Xposed 模块列表

```shell
XPrivacyLua
```

### Magisk Module List/Magisk 模块列表

```shell
Riru
Riru - LSPosed
Universal SafetyNet Fix
Fullscreen Gestures
```

### LSPosed version/LSPosed 版本

1.6.2

### Android version/安卓版本

A12

### Magisk version/Magisk 版本

23

### Riru version/Riru 版本

26.1.3

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

n/a

**Comment by yujincheng08** [comment]
Cant understand what you said.

**Comment by vvb2060** [comment]
No response. Close.
