### ISSUE TITLE
[Bug] Can't add shortcuts to Lawnchair

### ISSUE THREAD

**Issue by k10876** [LSPosed/LSPosed#1359]
### Steps to reproduce/复现步骤

1. Install lawnchair 12 alpha 3 (in my case)
2. Open LSPosed manager
3. Add a shortcut according to its instructions
Notes: this bug may be only available on my device. If it truly is, sorry for the inconvenience

### Expected behaviour/预期行为

The shortcut is added in the homepage

### Actual behaviour/实际行为

The shortcut is NOT added In the homepage

### Xposed Module List/Xposed 模块列表

```shell
QQ瘦身
Scene 4
Thanox
```

### Magisk Module List/Magisk 模块列表

```shell
CuprumToolbox Module
Riru
Riru - Enhanced mode for Storage isolation
Riru-LSPosed
Scene附加模块
Sui
```

### LSPosed version/LSPosed 版本

1.6.2(6189)

### Android version/安卓版本

9.0

### Magisk version/Magisk 版本

23.0

### Riru version/Riru 版本

26.1.3

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2021-11-04T18_07_40.287.zip](https://github.com/LSPosed/LSPosed/files/7474011/LSPosed_2021-11-04T18_07_40.287.zip)

**Comment by yujincheng08** [comment]
> [ 2021-11-04T18:06:28.063        0:   814:  1053 D/LSPosedService  ] shortcut exists, updating

The shortcut is already existed in the system. If it's not showing up, it's your system's problem or your launcher's problem. Nothing else we can do.
