### ISSUE TITLE
[FR] Make selecting scopes page more user-friendly

### ISSUE THREAD

**Issue by soumyamahunt** [LSPosed/LSPosed#138]
The scope selection page needs some UI/UX improvements make scope selection for end-user more accessible.

1. Now the sorting and filtering options aren't available when doing a search, the options should be made available while searching too:

| ![Screenshot_20210214-120522](https://user-images.githubusercontent.com/51203900/107870676-6dcf2400-6ec0-11eb-9beb-e3f0879723ed.jpg) | ![Screenshot_20210214-120536](https://user-images.githubusercontent.com/51203900/107870678-758ec880-6ec0-11eb-8db8-cb830c33b783.jpg) |
| :--------------------------------- | :-------------------- |

2. There should be option for selecting all, select none and to reset to default scopes for a mod.

**Comment by gitthangbaby** [comment]
Agree and why Games is there? It filters out some apps from the basic view. 
But the main issue is this screen exists. Dangerous for my use as the newly installed apps don't get processed. For most plugins the selection doesn't even matter, and i selected some random item.

**Comment by runalsh** [comment]
we need options "select all", "reverese selecting"

**Comment by gitthangbaby** [comment]
> we need options "select all", "reverese selecting"

that will likely not select the new apps:/

**Comment by soumyamahunt** [comment]
> Agree and why Games is there? It filters out some apps from the basic view.

You figured it out. Most people don't hook games with xposed so filtering them out by default makes more sense.

> But the main issue is this screen exists. Dangerous for my use as the newly installed apps don't get processed. 

The approach of choosing which apps to hook makes LSPosed faster and use less resources by comparing to edxposed I guess. There are many new apps added to [LSPosed repo](https://github.com/Xposed-Modules-Repo) that support scope already. I think as development matures the issues will be solved to large extent.

> For most plugins the selection doesn't even matter, and i selected some random item.

What plugins have you tried?? All the plugins from [LSPosed repo](https://github.com/Xposed-Modules-Repo) work while for others you have to manually select scopes. You can contact developer of those mods to know which apps to select and also prompt them to add their mod to LSPosed repo following [this](https://github.com/Xposed-Modules-Repo/submission/blob/master/README.md) guide.

**Comment by gitthangbaby** [comment]
thanks soumyamahunt, i tried the first of foremost plugin XPrivacyLua (XPrivacy), which got its own app filter. Both filters conflict. XPrivacy is not filtering what is not selected in LSPosed and it's not filtering the **new apps** which is highly unpleasant. This is a showstopper, and it's an opinion i've also read in the community (xda). The important goal of privacy masking is to prevent leaks for new apps which get the protection from XPrivacy automatically right after installation, but it' blocked by LSPosed currently.

I've just noticed "Recommend" choice which selects "System Storage" and "System Framework". XPrivacy will not do its job in this setup. I have to select the apps manually.

Now for the rest of plugins, I use "XPosed Edge", "Exi for Swiftkey", "3C All-in-one Toolbox".  i just select something random as
- i have no clue what apps to select, it's out of my imagination.. until i review the code of each plugin i have no clue if for example 99% operations of XPosed Edge are on UI and then one day i will have one operation failing interacting with some app, and i will have to add the app to the selection.. and i will be doing these changes step by step for months coming..
- don't want to make 300 manual clicks per plugin unless it's super important plugin like XPrivacy

I was surprised not selecting Games actually removes some apps from the list but now i see its intention.

I think it's a good intention, but the execution is problematic. I worry even with UI improvements:
- select all, reverse selection   -> to make UI usage easier (however users might just select all and then lose benefit of speed.. but can't blame them!)
- new radio box "keep all apps enabled"   -> to please XPrivacy
it will be still confusing for the users unless we have selection profiles precooked for the plugins. But that's quite difficult work isn't it?

**Comment by gitthangbaby** [comment]
i've gathered some information and it looks like most of my plugins require access to all apps. Just SwiftKey is likely one on one addon until proven otherwise.
The good news is there will be half of speed benefit kept if we select all visual apps (apps with icon, installed apps..whatever method you choose). This is what potentional continual app enabler function might focus on. I think that function is more important than the group selection, because:
*120billion app downloads per year on Android
*each user has around 80 apps, that can be lot of new installs each year
*new phone is without apps and needs protection early
*supervised people like children need protection all of the time
thanks a lot!

**Comment by odnar-dev** [comment]
something like this would be amazing
![1](https://user-images.githubusercontent.com/73726132/109399306-02626900-793a-11eb-846e-36f0ae11f57f.png)
or 
![2](https://user-images.githubusercontent.com/73726132/109399317-0c846780-793a-11eb-9afe-8fe28922645a.png)
