### ISSUE TITLE
[Feature Request] Use an app other than `com.android.shell` as the parasitization host

### ISSUE THREAD

**Issue by Kazurin-775** [LSPosed/LSPosed#1393]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

The new, parasitic version of LSPosed Manager has the following (minor) issues compared to the old versions:

- The app does not show up in the recents. This sometimes makes it difficult to go back from another app, e.g. from a module's settings or a web page. (Tapping the LSPosed shortcut on the home screen does not help, as this will open the main page instead of the last page opened.)
- Some animations do not work properly, such as the "swipe to home" gesture on MIUI and the tap effect of the "enable module" button on the module details page. These animations seem to be stopping "the half way" (or even completely disabled), which does not seem to be normal.

These issues do not exist in other apps that supports parasitism, like Sui.

### Describe the solution you'd like/描述你想要的解决方案

I suppose that these issues may be due to the new LSPosed Manager using `com.android.shell` as the parasitization host. Therefore, I suggest using another app as the host, such as `com.android.settings` used by Sui.

(If I was wrong, please kindly point it out.)

### Additional context/其他信息

**OS version**: MIUI 12.5 (21.9.28), Android 11

**Comment by yujincheng08** [comment]
We, of course, have noticed your concern when choosing the parasitic target.
For a parasitic target, there are a couple of requirements:
1. has at least one activity
2. exists on as many as possible OS
3. be as simple as possible so there won't be modules hooking it
4. try not to share the system UID

And after filtering we found that `com.android.shell` is the best choice though somehow inconvenient. `com.android.settings` was our first consideration, but it violates the 3rd and 4th requirements.

Thus I would like to mark this FR as won't fix unless there's a better choice.
