### ISSUE TITLE
[Bug] Zygisk version not working on A12

### ISSUE THREAD

**Issue by joshoram80** [LSPosed/LSPosed#1395]
### Steps to reproduce/复现步骤

Install LSPosed 6217 Zygisk Module with latest Magisk canary build on A12\Pixel 6

### Expected behaviour/预期行为

LSPosed module will load in Magisk

### Actual behaviour/实际行为

LSposed cause Zygisk to be disabled after installing and rebooting through Magisk Manager

### Xposed Module List/Xposed 模块列表

```shell
none - Unable to install LSposed
```

### Magisk Module List/Magisk 模块列表

```shell
Systemless Hosts, USNF 2.2.0, LSposed 6217
```

### LSPosed version/LSPosed 版本

6217

### Android version/安卓版本

Android 12 Offical Picel build 036

### Magisk version/Magisk 版本

23013

### Riru version/Riru 版本

n\a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[verbose_2021-11-12T195511.191.log](https://github.com/LSPosed/LSPosed/files/7526262/verbose_2021-11-12T195511.191.log)

**Comment by yujincheng08** [comment]
Use this magisk to grab log again
[app-debug.zip](https://github.com/LSPosed/LSPosed/files/7526313/app-debug.zip)

**Comment by joshoram80** [comment]
Installing that version makes Magisk think it's not installed any more. The module list is blank. I'm not sure what I'm doing wrong.

**Comment by yujincheng08** [comment]
Weird. Could you try the previous canary version of Magisk?

**Comment by joshoram80** [comment]
NVM. Installing debug build made me temporarily lose root but a hard reboot fixed it
[verbose_2021-11-12T20:56:20.385.log](https://github.com/LSPosed/LSPosed/files/7526659/verbose_2021-11-12T20.56.20.385.log)

**Comment by yujincheng08** [comment]
You are still using the 258e89c9(23013) Magisk? Try this https://github.com/topjohnwu/Magisk/actions/runs/1412014488

**Comment by joshoram80** [comment]
[verbose_2021-11-12T21:05:36.23.log](https://github.com/LSPosed/LSPosed/files/7526721/verbose_2021-11-12T21.05.36.23.log)

**Comment by yujincheng08** [comment]
You didn't install magisk. Still the same version 258e89c9(23013)

You need to install magisk on the app.

**Comment by joshoram80** [comment]
![Screenshot_20211112-211533](https://user-images.githubusercontent.com/2093723/141450878-3fd81add-f2a3-49b5-9138-c474423374b9.png)
When I install the debug version, I lose root so I can't install Magisk. I need to reboot and that somehow reverts the app version back to 23013.  I don't know what else to do.

**Comment by yujincheng08** [comment]
Hmm, how about this version of LSPosed? https://github.com/LSPosed/LSPosed/actions/runs/1378226496

**Comment by yujincheng08** [comment]
And use this to capture log?
[LSPosed-v1.6.3-6213-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/7527012/LSPosed-v1.6.3-6213-zygisk-debug.zip)

**Comment by yujincheng08** [comment]
New Magisk canary released. Could you please also try that? It fixed a UB when loading multiple Zygisk modules, and I see there are two Zygisk modules you are using, so I think there could be a problem. I will close this issue and marked as an upstream issue. Let me know if it does not work, and I will reopen it.
