### ISSUE TITLE
[Bug] XResources.setSystemWideReplacement doesn't work

### ISSUE THREAD

**Issue by nijel8** [LSPosed/LSPosed#1399]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

XResources.setSystemWideReplacement doesn't work with the current LSPosed automatic resource hook enabling for modules that doesn't implement IXposedHookInitPackageResources. In my case I have to implement IXposedHookInitPackageResources with empty handleInitPackageResources method just to get XResources.setSystemWideReplacement working.

### Describe the solution you'd like/描述你想要的解决方案

Since XResources.setSystemWideReplacement executes with initZygote, modules which are instance of IXposedHookZygoteInit should also get [hookResources()](https://github.com/LSPosed/LSPosed/blob/master/core/src/main/java/de/robv/android/xposed/XposedInit.java#L73).
Or maybe you have better solution...

**Comment by aviraxp** [comment]
@nijel8

**Comment by yujincheng08** [comment]
Try #1400
