### ISSUE TITLE
[Feature Request] Select-All and Auto-select feature for apps

### ISSUE THREAD

**Issue by suroot66** [LSPosed/LSPosed#1405]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Hi ~
I'm new to LSPosed, it is lightweight and awesome :)

------
There are 400+ apps installed on my android phone, what I suffer is that I'm using privacy protection apps like thanos, apphook, appenv ... for delivering fake information to apps.
However, all these modules need manually selecting apps if I want it works. There is a dozen of apps I want to select, the work is troublesome.
What's more, each time after I install a new app, I have to go to lsposed to select it . If this can be done automatically in lsposed, it will help a lot. (The module (thanos) has already implemented similar feature, so actually I don't need to select in the module.)

### Describe the solution you'd like/描述你想要的解决方案

I hope that here will be a button for selecting all apps for a module by one tap, and a switch to enable auto-select for new installed apps for a module.

**Comment by yujincheng08** [comment]
See #9

**Comment by suroot66** [comment]
Cool
