### ISSUE TITLE
New Universal Safety Net version breaks Lsposed Zygisk

### ISSUE THREAD

**Issue by username227** [LSPosed/LSPosed#1415]
### Steps to reproduce/复现步骤

This issue is related to the new preview lsposed zygisk version. I know it hasn't been officially released yet, but I assume that you would want to know about issues.
1. I had Lsposed zygisk preview version 1.6.3 version installed. 
2. when I installed the latest release of universal safety-net fix from kdrag0n, Lsposed crashed. Even after reinstalling, didn't work. 
3. When i downgraded my universal safety-net fix back to 1.2, worked again.

### Expected behaviour/预期行为

Lsposed zygisk should be able to coexist with Safety Net fix.

### Actual behaviour/实际行为

The module crashes.

### Xposed Module List/Xposed 模块列表

```shell
gravitybox
xprivacylua
hidemyapplist
Xinternalsd
```

### Magisk Module List/Magisk 模块列表

```shell
AudioHQ
Busybox
Detach v 5
ExSDCard
MigkskHide Props config
rclone-mount
systemless hosts by magisk
universal safetynet fix 2.2 (1.2)
```

### LSPosed version/LSPosed 版本

1.6.3 (6228) zygisk-debug

### Android version/安卓版本

11

### Magisk version/Magisk 版本

canary 258e89c9

### Riru version/Riru 版本

n/a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

I can't get into lsposed to enable logs. the module crashes immediately.

**Comment by username227** [comment]
sorry I didn't include this - I am using a moto g8 plus and I had a typo above - it's android 10, not android 11.

**Comment by aviraxp** [comment]
Update to latest Magisk canary.
