### ISSUE TITLE
[Bug] Hooking (unknown symbol) (0x0) from /apex/com.android.runtime/lib64/libart.so (0x79c2618000)

### ISSUE THREAD

**Issue by Nagisakurumi** [LSPosed/LSPosed#1416]
### Steps to reproduce/复现步骤

1.Android 10  sdk 29
2.phone is 360 手机
3.run art::hidden_api::DisableHiddenApi(handle_libart) is error in InstallInlineHook()

### Expected behaviour/预期行为

正常加载模块

### Actual behaviour/实际行为

不能正常进入手机系统
查看logcat日志 Hooking (unknown symbol) (0x0) from /apex/com.android.runtime/lib64/libart.so (0x79c2618000)

### Xposed Module List/Xposed 模块列表

```shell
自定义模块
```

### Magisk Module List/Magisk 模块列表

```shell
自定义模块
```

### LSPosed version/LSPosed 版本

1.5.1

### Android version/安卓版本

android 10

### Magisk version/Magisk 版本

最新版

### Riru version/Riru 版本

26

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

11-16 21:51:15.202 27295 27295 D LSPosed : run art::hidden_api::DisableHiddenApi(handle_libart)

**Comment by yujincheng08** [comment]
That line of log is not a bug :) Don't overlook yourself.

**Comment by Nagisakurumi** [comment]
LSPosed : Hooking (unknown symbol) (0x0) from /apex/com.android.runtime/lib64/libart.so (0x79c2618000)

**Comment by yujincheng08** [comment]
AGAIN, THAT'S EXPECTED

**Comment by Nagisakurumi** [comment]
How can I get into the system normally？

**Comment by aviraxp** [comment]
@Nagisakurumi Provide full log or GTFO

**Comment by yujincheng08** [comment]
HOW COME I COULD KNOW. YOU DONT PROVIDE BUG :)

**Comment by Nagisakurumi** [comment]
[log.log](https://github.com/LSPosed/LSPosed/files/7547766/log.log)

**Comment by yujincheng08** [comment]
1.5.1 :)

**Comment by yujincheng08** [comment]
how can I fix an old version

**Comment by Nagisakurumi** [comment]
I modify some code.. on v 1.5.1

**Comment by yujincheng08** [comment]
Then you should fix it yourself, right?

Only technical support for **latest original** version

Try the latest CI build, and if you still face a bootloop on that, re-submit a valid bug report.

**Comment by Nagisakurumi** [comment]
I just added some logs

**Comment by yujincheng08** [comment]
Nothing to do with me. Only the official version could obtain technical support. This issue will be locked as off-topic.
