### ISSUE TITLE
"Ultimate Notification Control" of GravityBox Not Working With Zygisk LSposed

### ISSUE THREAD

**Issue by dr-kaisar** [LSPosed/LSPosed#1445]
### Steps to reproduce/复现步骤

1. Turn on Zygisk in Magisk after uninstalling Riru Core and Riru - LSPosed. (I removed Riru Core because it causes random reboots in Samsung Galaxy Note 10 Lite which was confirmed by other users also)
2. Install GravityBox and turn it on within LSPosed. Then reboot.
3. GravityBox > Ultimate Notifucation Control > Per-app settings > select an app > Turn on override notification sound and overwrite vibrations > Change custom notification sound and custom vibration pattern > save

### Expected behaviour/预期行为

When notification from that app appears, the predefined vibration and custom notification sound (that was set within GravityBox) occurs.

### Actual behaviour/实际行为

Per-app custom vibration is not working, though custom notification sound is working. Other features of GravityBox are working also.

(But Gravitybox Ultimate Notification Control worked fine with Riru Core and Riru LSPosed. Now with zygisk lsposed it is not working properly.)

### Xposed Module List/Xposed 模块列表

```shell
1. App Settings Reborn
2. Disable FLAG_SECURE
3. GravityBox [R]
4. SoundCloud Downloader
```

### Magisk Module List/Magisk 模块列表

```shell
1. Busybox for Android NDK
2. Debloater (Terminal Debloater)
3. Systemless Hosts
4. Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

v1.6.3 (6250)

### Android version/安卓版本

Android 11 (R)

### Magisk version/Magisk 版本

5d6d2417 (23015)

### Riru version/Riru 版本

Not using Riru, I'm using Zygisk - LSPosed

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2021-11-27T17_39_41.328.zip](https://github.com/LSPosed/LSPosed/files/7611652/LSPosed_2021-11-27T17_39_41.328.zip)

**Comment by yujincheng08** [comment]
Have you ever thought this issue might be caused by that GB does not work on non-AOSP rom?

```
[ 2021-11-27T17:37:07.925    10063:  1585:  1585 E/LSPosed-Bridge  ] java.lang.NullPointerException: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
	at com.ceco.r.gravitybox.ModStatusBar.isNotificationIconContainer(ModStatusBar.java:1111)
```

**Comment by dr-kaisar** [comment]
But GravityBox worked just fine with Riru Core and Riru - LSPosed

**Comment by yujincheng08** [comment]
From the lig its definitely caused by GB it self.
