### ISSUE TITLE
[FR] Why not disable module logging？

### ISSUE THREAD

**Issue by xiangfeidexiaohuo** [LSPosed/LSPosed#145]
为啥没有禁用模块日志了？

记得以前的版本可以禁用的，现在只有一个禁用详细日志，但是模块日志一大堆，看着烦，请问为啥不加开关来禁用了？

Why haven't the module logs been disabled?

Remember that the previous version can be disabled. Now there is only one disabled detailed log, but there are a lot of module logs, which is annoying. Why is it disabled without a switch?

**Comment by tehcneko** [comment]
> 看着烦

不看就不烦了

**Comment by xiangfeidexiaohuo** [comment]
> > 看着烦
> 
> 不看就不烦了

你们开发的态度很赞，就这态度，无话可说。

**Comment by yujincheng08** [comment]
@xiangfeidexiaohuo  这可不是我们的开发态度怎样，所有 xposed 框架的模块日志都关不掉，包括原版。而且我们是特意优化的日志的性能。
至于为什么：https://github.com/rovo89/Xposed/issues/209

**Comment by xiangfeidexiaohuo** [comment]
> @xiangfeidexiaohuo 这可不是我们的开发态度怎样，所有 xposed 框架的模块日志都关不掉，包括原版。而且我们是特意优化的日志的性能。
> 至于为什么：[rovo89/Xposed#209](https://github.com/rovo89/Xposed/issues/209)

你这个回答能接受，也能理解啊。上一个人回答的啥，之前记得有版本可以看不见，后面为啥没了？直接来一句，不看不烦了，他回答的啥啊。
