### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by aaeuft** [LSPosed/LSPosed#1451]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

غالي

### Describe the solution you'd like/描述你想要的解决方案

Feature Request

### Additional context/其他信息

Feature Request

**Comment by aaeuft** [comment]
1451

**Comment by canyie** [comment]
STOP SPAMMING. NEXT TIME YOU WILL BE BLOCKED!
