### ISSUE TITLE
When I don’t know the specific scope of the application, how to add scope to the module? [FR] 

### ISSUE THREAD

**Issue by johoney** [LSPosed/LSPosed#146]
**Detail**:
Such as mipush framework xposed modoule,it need to fake mi device,but i dont konw how to add specific scope.Beacuase I dont know which is its specific scope,some old modules wont update,author dont fit lsposed.Unless LSPosed can automatically add specific scope,i will still use edxposed.

**Comment by kotori2** [comment]
duplicate #93
