### ISSUE TITLE
[Bug] OnePlus5 not available LSP

### ISSUE THREAD

**Issue by justhy** [LSPosed/LSPosed#1474]
### Steps to reproduce/复现步骤

一加5刷入LSP后，magisk显示正常已开启模块，但是桌面没有管理器图标。解包安装管理器后，提示没有安装LSP。截图已附。

![photo_2021-12-09_14-27-25](https://user-images.githubusercontent.com/17880968/145345334-744aa0c6-15cb-476d-a989-479ec4588170.jpg)

![photo_2021-12-09_14-27-31](https://user-images.githubusercontent.com/17880968/145345377-6646020a-ff2a-4375-9227-96c68296ff6a.jpg)

![photo_2021-12-09_14-27-28](https://user-images.githubusercontent.com/17880968/145345390-1004f7fe-fc89-4aa4-9540-c3a5b2cc7c2f.jpg)

### Expected behaviour/预期行为

希望能够正常使用LSP。

### Actual behaviour/实际行为

刷入了LSP无法使用。

### Xposed Module List/Xposed 模块列表

```shell
无法使用，暂未安装模块。
```

### Magisk Module List/Magisk 模块列表

```shell
H-无障碍服务守护
Riru
Riru-LSPosed
Riru-指纹支付
字体模块
```

### LSPosed version/LSPosed 版本

1.6.5 (6272)

### Android version/安卓版本

9 (API 28)

### Magisk version/Magisk 版本

v23.0

### Riru version/Riru 版本

v26.1.3

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

没有日志

**Comment by yujincheng08** [comment]
没日志怎么修？
