### ISSUE TITLE
[Feature Request] Android 12 Themed Icon

### ISSUE THREAD

**Issue by DestroyerXyz** [LSPosed/LSPosed#1477]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

A new LSPosed icon for the themed icon feature in Android 12.

**Comment by vvb2060** [comment]
https://t.me/siubeng_store/299

**Comment by DestroyerXyz** [comment]
Yeah, I tried to find documentation on it before opening feature request, thought maybe only I couldn't find it

**Comment by yujincheng08** [comment]
In fact, all you need is ~attention~ to define color resources:
```
<resources>
    <color name="launcher_icon_background">@android:color/system_accent1_100</color>
    <color name="launcher_icon">@android:color/system_neutral2_700</color>
</resources>
```
And refer it in launcher drawable. But unluckily parasitic manager is fully based on a static image.

**Comment by DestroyerXyz** [comment]
Ok thanks
And btw is there any documentation on how Parasitic manager works, I am quite interested

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed/blob/master/core/src/main/java/org/lsposed/lspd/util/ParasiticManagerHooker.java
