### ISSUE TITLE
[Bug] Greenify app doesn't show in modules section

### ISSUE THREAD

**Issue by MdHusainhfz** [LSPosed/LSPosed#1478]
### Steps to reproduce/复现步骤

Install Greenify app, then check modules section, (Greenify works as xposed module in Xposed and Edxposed, but sorry to say this necessary app doesn't show in LSposed modules section.

### Expected behaviour/预期行为

Greenify app should be in modules list, as it is in xposed and edxposed.

### Actual behaviour/实际行为

This app isn't in the modules list.

### Xposed Module List/Xposed 模块列表

```shell
Lucky Patcher
```

### Magisk Module List/Magisk 模块列表

```shell
Riru - latest
Riru LSPosed - latest
```

### LSPosed version/LSPosed 版本

6272

### Android version/Android 版本

Android 11 (LineageOS 18.1)

### Magisk version/Magisk 版本

23.0

### Riru version/Riru 版本

26.1.3.r513

### Version requirement/版本要求

- [x] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2021-12-10T12_17_32.253.zip](https://github.com/LSPosed/LSPosed/files/7690480/LSPosed_2021-12-10T12_17_32.253.zip)

**Comment by yujincheng08** [comment]
![Screenshot_2021-12-10-14-56-34-759_com.android.shell.jpg.png](https://user-images.githubusercontent.com/5022927/145530881-3bff323d-c54c-43da-a1fc-7ced6071c598.png)

**Comment by yujincheng08** [comment]
BTW you didn't use the debug version as said

**Comment by MdHusainhfz** [comment]
> BTW you didn't use the debug version as said

Okay, but I thought Beta and canary versions (debug versions) might have bugs, so I installed stable version which we generally expect less issues.

**Comment by yujincheng08** [comment]
Please make sure you have installed Greenify, and other apps can query it.
