### ISSUE TITLE
MIUI second space security problem

### ISSUE THREAD

**Issue by Dreamray** [LSPosed/LSPosed#1480]
### Steps to reproduce/复现步骤

1. install wxposed in second space
2. open LSPosed in main space, press 'security space', enable wxposed and check Wechat app
3. then press setting icon right down
4. then the phone login in to second space without any password, it should not, second space become no longer safe.

### Expected behaviour/预期行为

do not show second space in main space, even if it is shown, do not login into without any password

### Actual behaviour/实际行为

second space become no longer safe.

### Xposed Module List/Xposed 模块列表

```shell
greenify
wxposed
zhiliao
qqshoushen
```

### Magisk Module List/Magisk 模块列表

```shell
riru
riru-lsposed
```

### LSPosed version/LSPosed 版本

1.6.5(6272)

### Android version/Android 版本

9

### Magisk version/Magisk 版本

23.0

### Riru version/Riru 版本

v26.1.3.r513

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

I think log file is not necessary

**Comment by vvb2060** [comment]
Expected behavior

**Comment by yujincheng08** [comment]
we only use `am switch-user`. So its your system's behavior. Nothing to do with us.

**Comment by yujincheng08** [comment]
This issue can be confirmed to be MIUI's problem.
You can try `adb shell su 1000 am switch-user 10` whenever you have unlocked the security space once after reboot. And you will see you don't have to enter password to switch between the two users. This issue does not happen on AOSP so it's MIUI's bug. I don't think MIUI can fix it though...

**Comment by thienvc** [comment]
![Screenshot_2023-09-26-20-52-28-906_xox vk dt tin bryk](https://github.com/LSPosed/LSPosed/assets/1115393/c3914f4c-b9fe-4902-a771-9150ab7c69b0)
![Screenshot_2023-09-27-08-21-38-573_org lsposed manager](https://github.com/LSPosed/LSPosed/assets/1115393/94371a23-844e-43d4-8f8b-5fa261e782f2)
How i can run LSPosed on Second Space user? All in first User is Ok, but can't not in Second Space user :(
