### ISSUE TITLE
[Bug] When Module‘s ModuleScope only has itself and has a Recommend ScopeList, AppListFragment will display error

### ISSUE THREAD

**Issue by keta1** [LSPosed/LSPosed#1493]
### Steps to reproduce/复现步骤
1. 打开一个有推荐作用域的模块设置
2. 取消勾选所有模块
3. 在最近任务界面划掉manager

### Expected behaviour/预期行为
模块已勾选模块显示为空

### Actual behaviour/实际行为
![image](https://user-images.githubusercontent.com/41381927/147322602-e54abd8d-e97e-4437-9455-beeb208c3706.png)
如果模块作用域只有自己
[ConfigManager.getModuleScope](https://github.com/LSPosed/LSPosed/blob/master/app/src/main/java/org/lsposed/manager/ConfigManager.java#L130)会拿到一个空列表
模块激活列表将会显示推荐作用域的所有应用
https://github.com/LSPosed/LSPosed/blob/master/app/src/main/java/org/lsposed/manager/adapters/ScopeAdapter.java#L506-L510

![image](https://user-images.githubusercontent.com/41381927/147321807-46e1132f-2a42-490b-8d76-ac09612f85b1.png)

### Xposed Module List/Xposed 模块列表

```shell
module_pkg_name
------------------
chili.xposed.chimi
cn.lovesykun.miui_
com.coderstory.too
com.fkzhang.wechat
com.ketal.qemoji
com.kieronquinn.ap
com.mhook.dialog
com.qingyu.rm
com.tsng.hidemyapp
com.xposed.miuiime
com.yuk.fuckclouds
com.yuk.miuihome
```

### Magisk Module List/Magisk 模块列表

```shell
riru-core
riru-lsp
riru-storage isolation
riru-sui
sqlite3
```

### LSPosed version/LSPosed 版本

6283

### Android version/Android 版本

12

### Magisk version/Magisk 版本

23016

### Riru version/Riru 版本

26.1

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

none

**Comment by canyie** [comment]
你是怎么搞出来只有自己的作用域的 改 db 吗

**Comment by keta1** [comment]
> 你是怎么搞出来只有自己的作用域的 改 db 吗

取消勾选&&kill manager

**Comment by yujincheng08** [comment]
This should be expected behavior.
