### ISSUE TITLE
[Feature Request] Is it possibel to let Shamiko can hide the modified traces of init.rc

### ISSUE THREAD

**Issue by rsps1008** [LSPosed/LSPosed#1498]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Shamiko Module of Magsik cannot hide the modified traces of init.rc when I use the Zygisk, but if I use the Magisk hide with MomoHider, it will be alright. Some bank apps will use this feature to ban the root user.

### Describe the solution you'd like/描述你想要的解决方案

I hope that the Shamiko Module support hiding the modified traces of init.rc in the future

**Comment by linux-leo** [comment]
Shamiko does not hide init.rc on my redmi note 11, this issue isn't fixed

**Comment by linux-leo** [comment]
![Screenshot_20220725-220630_crDroid Home](https://user-images.githubusercontent.com/63003858/180866201-116faabb-600c-467e-9a80-34f167b77647.png)

Heres a screenshot with shamiko enabled.
