### ISSUE TITLE
[TODO] Single Activity and androidx.navigation

### ISSUE THREAD

**Issue by jaqxues** [LSPosed/LSPosed#150]
I have noticed that this app uses multiple activities. However, there are multiple reasons why a single activity should be preferred. 

An entire talk about this can be found in the `Videos` section of this link: [Fragments](https://developer.android.com/guide/fragments)). Since Fragments are the (current) alternative, are there any plans to migrate to these? Would PRs be accepted that try to accomplish this?

Furthermore, navigation with Fragments is handled with the [androidx.navigation](https://developer.android.com/guide/navigation/navigation-getting-started) component, which could pretty easily handle the simple UI navigations.

I am willing to spend a bit of time on it, if these changes will be accepted and there are no other plans.

**Comment by yujincheng08** [comment]
I see your reason and PRs are warmly welcome. However, we are now migrating to a new backend (see branch `binder`) and the codes will be rewritten mostly so there may be big conflicting. So I think you could wait until our next release.

**Comment by jaqxues** [comment]
I also see that your language of choice for :app is Java and not Kotlin. Is Kotlin code allowed in the repository, or should it stay 100% Java? 

I am fine with Java and I do know the language, but it seems like a strange choice, considering that a vast majority of activate android development has now switched to Kotlin for obvious reasons.

**Comment by yujincheng08** [comment]
the mantainer of manager does not like kotlin so...

**Comment by jaqxues** [comment]
That is truly disappointing. 

I understand that it is pretty new, and the compilation process is a bit weird (e.g. it generates no static methods by default, but you can use it with `@JvmStatic`), but this makes no noticeable difference to the user. It is new, and everything seems a bit strange, but it does compile to Jvm bytecode and all of its features allow a much more fluid developer experience. 

It allows instructing more actions with less code in an extremely concise way. Even its interoperability with Java is remarkable, so there would be absolutely no issue writing new parts in Kotlin and slowly migrating.

I hope that it will make it in the repo at some point! 


As a heads-up, the new android UI toolkit "Jetpack Compose" 100% relies on Kotlin features, from language syntax itself to compiler plugins. This one still very much work in progress (an upcoming beta release is expected in February).

**Comment by yujincheng08** [comment]
Personally speaking, I am a fan of Kotlin.

**Comment by aviraxp** [comment]
@jaqxues 什么几把
