### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Q56662017** [LSPosed/LSPosed#1506]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

建议可以让模块全局生效，不用再一个个的勾选

### Describe the solution you'd like/描述你想要的解决方案

出个全局生效的模式，不需要再一个个的选择生效
![Screenshot_2021-12-30-20-34-07-983_org lsposed manager](https://user-images.githubusercontent.com/44309366/147757879-b6d0bbf9-fcc6-45eb-848b-0ca4d278f0c5.jpg)
![Screenshot_2021-12-30-20-34-10-067_org lsposed manager](https://user-images.githubusercontent.com/44309366/147757891-36688cd2-4f29-4043-b327-0d5e0b3597ae.jpg)

**Comment by yujincheng08** [comment]
别偷懒。而且这玩意儿也用不着全选。

**Comment by Q56662017** [comment]
真的需要全选那个系统框架只能屏蔽应用宝广告

**Comment by yujincheng08** [comment]
扯。你邮箱笔记这类应用需要选？你蓝牙相机这类需要选？你各大银行 app 这类检测 root 的应用能选？没广告的应用要选？再者这个模块能消所有 app 的广告？Telegram 的频道广告它能消？
不给全选就是为了让你一个一个确认。无脑全选然后某些应用出问题最后又过来找我们。

**Comment by Q56662017** [comment]
这出问题不是自己负责吗？

**Comment by yujincheng08** [comment]
重点不是出问题谁负责。重点是你要一个一个确认这个 app 需要这个模块，而不是无脑选了就完事。
况且不是每个人知道要自己负责。有人用了幸运破解器 bootloop 了还来找我们修呢，这种人见多了。

**Comment by Q56662017** [comment]
行吧，我的意思其实是，右上角可以添加一个一键开启，还是有人需要的，我这是去开屏广告，差不多一半的软件都有广告

**Comment by vvb2060** [comment]
你需要先确认模块能处理这个应用，再开启。

**Comment by Q56662017** [comment]
能，我是ed框架转过来的

**Comment by Q56662017** [comment]
OK
