### ISSUE TITLE
[BUG] Redmi k20 Pro will get stuck after clearing recent tasks

### ISSUE THREAD

**Issue by k650dg4d2** [LSPosed/LSPosed#151]
After my investigation, it is indeed caused by lsp. When I turn off the lsp framework in magisk, it will be normal. Turn on the lsp framework and disable all modules, and the phone will still get stuck(卡一下). Therefore, it is determined that the problem is caused by the lsp framework

**Comment by tehcneko** [comment]
请使用 issue 模板
