### ISSUE TITLE
[Feature Request] Add random package name to resist native detection

### ISSUE THREAD

**Issue by vivian8421** [LSPosed/LSPosed#1516]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Native detection

### Describe the solution you'd like/描述你想要的解决方案

Recently read the a code which called 'XposedDetector-master',many specific class detection methods are used, such as findLoadedClass (de/robv/android/xposed/XposedBridge),checkCallStack(de.robv.android.xposed.XC_MethodHook).
Their principle is to detect specific jar packages 'api-82-sources.jar'.Can we replace with a random package name(or Custom package name) scheme,like change de.robv.android.xposed.XC_MethodHook to a.b.c.d.XC_MethodHook.
 At the same time, in Dalvik, Replace the original de.robv android .xposed to a.b.c.d 
Is this scheme feasible? I'll try it by writing a case first.

### Additional context/其他信息

Thanks for the detection ideas provided by vvb2060.

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed/tree/dex-obfuscate
