### ISSUE TITLE
[FR] System install

### ISSUE THREAD

**Issue by bolbolfolfol** [LSPosed/LSPosed#152]
**Detail**:
Hi
i try to copy the lsposed and riru files to their folder in SYSTEM partition but it does not work
can you make a twrp system flashable zip instead of magisk please
or show me where to put files and their permissions
thank you

**Comment by yujincheng08** [comment]
riru stopped supporting twrp installation

**Comment by RikkaW** [comment]
Magisk provides post-fs-data mode and late_start service mode support, this is required for both Riru and LSPosed.
Without Magisk, there is no reliable way to run scripts at the correct time.

**Comment by aviraxp** [comment]
@RikkaW

**Comment by aviraxp** [comment]
@aviraxp 还可以这样？

**Comment by bolbolfolfol** [comment]
i have Magisk,i just want a system installation

**Comment by bolbolfolfol** [comment]
> Magisk provides the ability to run scripts with post-fs-data mode and late_start service mode, this is required for both Riru and LSPosed.
> Without Magisk, there is no reliable way to run scripts at the correct time.
> Also without Magisk, there must be some SELinux problem even if you manage to run the scripts.

i have Magisk,i just want a system installation

**Comment by RikkaW** [comment]
@bolbolfolfol Read the document of Magisk, you can do it yourself. No official support for this.

**Comment by yujincheng08** [comment]
If you have magisk, why not install via maigsk?

If you want to integrate LSPosed into your rom, you should mimic the result of `customize.sh` to let Magisk load Riru and LSPosed properly.
