### ISSUE TITLE
[FR] Documentations for native hook feature

### ISSUE THREAD

**Issue by black-binary** [LSPosed/LSPosed#154]
:)

**Comment by XspeedPL** [comment]
In the meantime, is there an example module somewhere that uses native hooking?

**Comment by etmatrix** [comment]
@XspeedPL [here](https://github.com/LSPosed/XposedUnitTest) there is a partial implementation but no real example. A native library with native_init invoked by LSPosed.

**Comment by XspeedPL** [comment]
Looks like "native hook" doesn't mean "native hooking"
Well, of course that wouldn't be so easy

**Comment by yujincheng08** [comment]
> Looks like "native hook" doesn't mean "native hooking"
> Well, of course that wouldn't be so easy

? of course it is native hooking. you can, for example, replace fopen to ur own one.

**Comment by XspeedPL** [comment]
Ah, my bad.
So, the "on library loaded" is called for each library loaded by the target application, cool

**Comment by etmatrix** [comment]
@XspeedPL [here](https://github.com/vvb2060/XposedDetector/issues/3#issuecomment-819684474) you can find an example of native hook. I don't know what you expecting from native hook, but I think is a good start of point.
native hooking doesn't exist, you must always hook java side the app and inject your so in the app. At least that's what I understand.
handleLoadPackage will be always in java module.

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed/wiki/Native-Hook
