### ISSUE TITLE
[Feature Request] Add Blacklist / Denylist

### ISSUE THREAD

**Issue by tehrzky** [LSPosed/LSPosed#1546]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

some modules suggest to use system framework like xposed edge so it will make run also on some apps that we dont need to run lsposed. and that will trigger the security of that app. 

im using riru so im still not upgrading to zygisk.

### Describe the solution you'd like/描述你想要的解决方案

add blacklist / denylist to those module whos using whole system framework, tnx

**Comment by yujincheng08** [comment]
> it will make run also on some apps that we dont need to run

Your understanding is wrong. So this FR is impracticable.
