### ISSUE TITLE
[Bug] System framework injection failed

### ISSUE THREAD

**Issue by ScreedFild** [LSPosed/LSPosed#1551]
### Steps to reproduce/复现步骤

After installing LSPosed, I get the following message

"System Framework injection failed
This is rare and may be caused by Magisk or
some low-quality Magisk modules.
Please try to disable Magisk modules other
than Riru and LSPosed or submit full log to
developers."

I don't know what the problem could be, I've been using these modules for a while and that didn't happen

### Expected behaviour/预期行为

Fully activated

### Actual behaviour/实际行为

Partially activated
System framework injection failed

### Xposed Module List/Xposed 模块列表

```shell
Pixelify Google Photos
```

### Magisk Module List/Magisk 模块列表

```shell
Audio Modification Library
BusyBox for Android NDK
KTweaks
Universal SafetyNet Fix
VIPER4Android FX
Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

1.6.5 (6317)

### Android version/Android 版本

Android 9 (SDK 28)

### Magisk version/Magisk 版本

cbe97cdf (23018)

### Riru version/Riru 版本

Without

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-01-23T16_28_05.120.zip](https://github.com/LSPosed/LSPosed/files/7921390/LSPosed_2022-01-23T16_28_05.120.zip)

**Comment by yujincheng08** [comment]
`[ 2022-01-23T16:22:54.113        0:  3795:  3795 I/Magisk          ] zygisk_lsposed: exec [post-fs-data.sh]`

Magisk says it executes our `post-fs-data` but actually it does not.
