### ISSUE TITLE
[Bug] High CPU usage, lspd seems stuck in endless loop

### ISSUE THREAD

**Issue by binarynoise** [LSPosed/LSPosed#1577]
### Steps to reproduce/复现步骤

I upgraded to Magisk 24.1, enabled Zygisk and installed the latest LSPosed (Zygisk).
Then I rebooted.

### Expected behaviour/预期行为

LSPosed continues to work as usual.

### Actual behaviour/实际行为

LSPosed works, but uses turns my phone into a heater.
A full core is constantly used by lspd.
Strace gives endless repetitions of `19:32:47.792106 futex(0x712f719004, FUTEX_WAIT, 0, NULL) = -1 EAGAIN (Try again) <0.000057>`.

### Xposed Module List/Xposed 模块列表

```shell
GravityBox [R] 11.0.5
Insaprefs 2.0
No Play Services Warning 1.01
```

### Magisk Module List/Magisk 模块列表

```shell
ADB & Fastboot for Android NDK
Advanced Charging Controller
Audio Compatibility Patch
Audio Modification Library
Bixby-Button remapper (selfmade, just patches keymapping)
F-Droid Privileged Extension
MagiskHide Props Config
Riru (disabled)
Riru LSPosed (disabled)
Systemless Hosts
Zygisk - LSPosed (1.6.5, 6337, debug)
```

### LSPosed version/LSPosed 版本

1.6.5, 6337, debug

### Android version/Android 版本

11

### Magisk version/Magisk 版本

24.1 (24100)

### Riru version/Riru 版本

26.1.4 (disabled)

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[log.zip](https://github.com/LSPosed/LSPosed/files/7961135/log.zip)

**Comment by yujincheng08** [comment]
could you have an ouput of `debuggerd $(pidof lspd)`?

**Comment by binarynoise** [comment]
`debuggerd $(pidof lspd)` didn't print anything, but I tried with the pid of the busy thread I found with htop and attached that.

[debuggerd.log](https://github.com/LSPosed/LSPosed/files/7961240/debuggerd.log)

**Comment by binarynoise** [comment]
Found this: (lines 1851 ff.)
```
01-28 20:12:14.456  5923  5923 I libc    : Requested dump for tid 5923 (main)
01-28 20:12:33.889  5923  6015 I libc    : Requested dump for tid 6015 (logcat)
01-28 20:12:41.751  5923  5988 D LSPosedService: Skipped de.rki.coronawarnapp/10249
01-28 20:12:42.789  5923  5988 D LSPosedService: pid=17978 uid=10091 is dead.
01-28 20:12:59.325  5923  6015 I libc    : Requested dump for tid 6015 (logcat)
```

It seems the logcat loop is the culprit, because 6015 is the tid/pid with high cpu usage

**Comment by yujincheng08** [comment]
[LSPosed-v1.6.5-6337-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/7962756/LSPosed-v1.6.5-6337-zygisk-debug.zip)
That's nice you know how to find the endless loop thread's name. However, there are two `logcat` threads and we don't know which is the exact one. I change their names and could you use this to see the name of the endless loop's thread again?

**Comment by binarynoise** [comment]
Now it's the watchdog thread.
![Screenshot_20220129-103355_Terminalemulator_1](https://user-images.githubusercontent.com/50302352/151656028-1a0cd008-720d-4107-b71c-631ee0c1eba8.png)
(sorry for the small screenshot, I took it on my phone and not on my pc like yesterday)

**Comment by binarynoise** [comment]
Would it be possible for me to attach a debugger to lspd to step through the code it's executing and see what it's doing like I do when I debug my android app?

**Comment by yujincheng08** [comment]
Try this:
[LSPosed-v1.6.5-6337-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/7963409/LSPosed-v1.6.5-6337-zygisk-debug.zip)

**Comment by binarynoise** [comment]
Cpu usage went back to normal.

**Comment by binarynoise** [comment]
Thank you
