### ISSUE TITLE
更新模块apk地址报错

### ISSUE THREAD

**Issue by 253551464** [LSPosed/LSPosed#16]
01-31 13:23:17.937  1369  2656 I LSPosed : updating uid: 0
01-31 13:23:17.950  1369  2656 E LSPosed : Unable to read enabled modules
01-31 13:23:17.950  1369  2656 E LSPosed : java.io.FileNotFoundException: /data/misc/lspd_fUsWfoBYcURP5HwX/0/conf/enabled_modules.list: open failed: EACCES (Permission denied)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at libcore.io.IoBridge.open(IoBridge.java:496)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at java.io.FileInputStream.<init>(FileInputStream.java:159)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at java.util.Scanner.<init>(Scanner.java:620)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at io.github.lsposed.lspd.service.PackageReceiver$1.loadEnabledModules(PackageReceiver.java:87)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at io.github.lsposed.lspd.service.PackageReceiver$1.updateModuleList(PackageReceiver.java:103)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at io.github.lsposed.lspd.service.PackageReceiver$1.onReceive(PackageReceiver.java:183)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at android.app.LoadedApk$ReceiverDispatcher$Args.lambda$getRunnable$0$LoadedApk$ReceiverDispatcher$Args(LoadedApk.java:1556)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at android.app.-$$Lambda$LoadedApk$ReceiverDispatcher$Args$_BumDX2UKsnxLVrE6UJsJZkotuA.run(Unknown Source:2)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at android.os.Handler.handleCallback(Handler.java:914)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at android.os.Handler.dispatchMessage(Handler.java:100)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at android.os.Looper.loop(Looper.java:228)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at android.os.HandlerThread.run(HandlerThread.java:67)
01-31 13:23:17.950  1369  2656 E LSPosed : Caused by: android.system.ErrnoException: open failed: EACCES (Permission denied)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at libcore.io.Linux.open(Native Method)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at libcore.io.ForwardingOs.open(ForwardingOs.java:167)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at libcore.io.BlockGuardOs.open(BlockGuardOs.java:252)
01-31 13:23:17.950  1369  2656 E LSPosed : 	at libcore.io.IoBridge.open(IoBridge.java:482)
01-31 13:23:17.950  1369  2656 E LSPosed : 	... 11 more
01-31 13:23:17.956  1369  2656 I LSPosed : broadcast to io.github.lsposed.manager

**Comment by yujincheng08** [comment]
重启再试试

**Comment by 253551464** [comment]
> 重启再试试

试过了不行，手动改权限才行

**Comment by yujincheng08** [comment]
文件权限看一下

**Comment by 253551464** [comment]
> 文件权限看一下

![Screenshot_2021-01-31-13-40-04-585_bin mt plus](https://user-images.githubusercontent.com/36783515/106375739-dc44ba00-63c9-11eb-81b1-ffcce48baa0a.jpg)
原本是这样的，会报错，我改成全读写就可以了，

**Comment by 253551464** [comment]
![Screenshot_2021-01-31-13-42-41-100_bin mt plus](https://user-images.githubusercontent.com/36783515/106375780-347bbc00-63ca-11eb-8775-ca3d6fc2b895.jpg)
原来是这样的，会报错，改成全读写才没事
