### ISSUE TITLE
[Bug] Icon in lsposed shortcut doesnt change even if the toggle is off

### ISSUE THREAD

**Issue by pokurt** [LSPosed/LSPosed#1602]
### Steps to reproduce/复现步骤

1. go to settings
2. Turn off system them color
3. close the manager and open again from shortcut dummy
4. you see everything is fine but the icon on top left isnt changed the color you pick

### Expected behaviour/预期行为

icon to be changed with the color user select

### Actual behaviour/实际行为

icon doesnt change to the color user select, its just weird monet engine thing

### Xposed Module List/Xposed 模块列表

```shell
doesn't matter ig
- CoreDump
```

### Magisk Module List/Magisk 模块列表

```shell
LSPosed
Systemizer
```

### LSPosed version/LSPosed 版本

1.6.5 6352

### Android version/Android 版本

Miui 13 - A12

### Magisk version/Magisk 版本

canary latest

### Riru version/Riru 版本

none

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

bruh

**Comment by pokurt** [comment]
![Screenshot_2022-02-02-01-12-43-078_com android shell](https://user-images.githubusercontent.com/43902347/152043956-a502eb35-eea9-4a5d-9584-959ac4d50635.jpg)
here is a screenshot for the reference

**Comment by yujincheng08** [comment]
This icon follows the color from your system. Change the system's color and enable the following system color option in the settings to fix this.

**Comment by pokurt** [comment]
> This icon always follows the color from your system. Change the system's color and enable the following system color option in the settings to fix this.

The problem is that MIUI doesn't follow AOSP native implementation. my MIUI version doesn't really have the Monet theme engine support even if it is Android 12, its just stuck on mint green color as you can see, i have changed my wallpaper to something pink. so i thought it is more of a ui bug producing by my system and it bothers alot to look at

**Comment by yujincheng08** [comment]
Icon colors does not support overriding the color, so cannot fix.
