### ISSUE TITLE
[Bug] log show unexpected behavior

### ISSUE THREAD

**Issue by gyq180** [LSPosed/LSPosed#1604]
### Steps to reproduce/复现步骤

update to riru 1.70

### Expected behaviour/预期行为

show log

### Actual behaviour/实际行为

log show: Logd maybe crashed, retrying in 1s...

### Xposed Module List/Xposed 模块列表

```shell
see the images
```

### Magisk Module List/Magisk 模块列表

```shell
see the images
```

### LSPosed version/LSPosed 版本

6353

### Android version/Android 版本

12 (API 31)

### Magisk version/Magisk 版本

24101

### Riru version/Riru 版本

v26.1.3.r513.8e95115fd4

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

![Screenshot_2022-02-02-12-24-31-938_com android shell](https://user-images.githubusercontent.com/20734242/152106942-50e67af4-444f-417c-b3a6-7e6ec32b18d4.jpg)
![Screenshot_2022-02-02-14-25-46-109_com android shell](https://user-images.githubusercontent.com/20734242/152107073-c59d5750-7e4f-4416-a06d-2061a9d94a7c.jpg)
![Screenshot_2022-02-02-14-49-32-383_p wtogl](https://user-images.githubusercontent.com/20734242/152107106-a64f8ef7-0d48-448f-b369-c6fe94a1d1cd.jpg)

**Comment by gyq180** [comment]
[LSPosed_2022-02-02T14_38_34.969.zip](https://github.com/LSPosed/LSPosed/files/7984192/LSPosed_2022-02-02T14_38_34.969.zip)

**Comment by yujincheng08** [comment]
Your system's issue.

**Comment by VD171** [comment]
This is happening to me too on LSPosed v1.7.2 on zygisk, Magisk v24.1.

**Comment by VD171** [comment]
This keeps happening to me too on LSPosed v1.8.0 on zygisk, Magisk v24.3.

**Comment by VD171** [comment]
Any solution?
How to disable logcat totally?
This keeps happening to me too on LSPosed v1.8.3 on zygisk, Magisk v24.3.

**Comment by Liberations** [comment]
same ..

**Comment by Liberations** [comment]
maybe vivo system's bug?
