### ISSUE TITLE
Sir Please update language translation in lsposed it is not translating all things in English  [Feature Request] 

### ISSUE THREAD

**Issue by thdeepakrajput** [LSPosed/LSPosed#1615]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

It is a translation problem 

### Describe the solution you'd like/描述你想要的解决方案

Pls update it

**Comment by thdeepakrajput** [comment]
Pls update translation

**Comment by yujincheng08** [comment]
what is not in eng? name them.
