### ISSUE TITLE
[Bug] 列表搜不到包名

### ISSUE THREAD

**Issue by Cmpote** [LSPosed/LSPosed#1619]
### Steps to reproduce/复现步骤

null
null
null

### Expected behaviour/预期行为

null

### Actual behaviour/实际行为

一款apk想HOOK一下搜不到包名

### Xposed Module List/Xposed 模块列表

```shell
https://wwi.lanzouw.com/iAorizk4pze
```

### Magisk Module List/Magisk 模块列表

```shell
null
```

### LSPosed version/LSPosed 版本

171

### Android version/Android 版本

11

### Magisk version/Magisk 版本

23

### Riru version/Riru 版本

Riru

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

null

**Comment by kotori2** [comment]
null

**Comment by rojunghwa** [comment]
Lol 😂
![image](https://user-images.githubusercontent.com/57177286/158954223-6f5f09be-ce5e-4690-985b-bb3b1b40e4d5.png)
