### ISSUE TITLE
[Bug] CI run twice on every merged pull request

### ISSUE THREAD

**Issue by DestroyerXyz** [LSPosed/LSPosed#1629]
### Steps to reproduce/复现步骤

I noticed that the GitHub actions CI was running twice for every merged pull request. Once on the PR and then on the merge commit. Is this intended?

### Expected behaviour/预期行为

CI runs only one for the PR and not again for the merge.

### Actual behaviour/实际行为

CI runs for PR and for merge.

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

6368

### Android version/Android 版本

N/A

### Magisk version/Magisk 版本

N/A

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

N/A

**Comment by yujincheng08** [comment]
yes

**Comment by DestroyerXyz** [comment]
Can I ask why? Just curious.
