### ISSUE TITLE
[Bug] Zygisk got disabled when enabling LSPosd

### ISSUE THREAD

**Issue by ag6ag1** [LSPosed/LSPosed#1634]
### Steps to reproduce/复现步骤

after installing LSPosed on Poco x3 pro global and after the first reboot device reboot 3 times and then booted normally with zygisk disabled 

we need to disabled LSPosed in order to enable zygisk

 ps: (zygisk enabled normally in magisk settings and using LSPosed zygisk version)

### Expected behaviour/预期行为

boot normally with zygisk enabled

### Actual behaviour/实际行为

zygisk disabled 

### Xposed Module List/Xposed 模块列表

```shell
LSPosed
```

### Magisk Module List/Magisk 模块列表

```shell
USNF, magisk hide
```

### LSPosed version/LSPosed 版本

1.7.1 - 6538

### Android version/Android 版本

11

### Magisk version/Magisk 版本

24.1

### Riru version/Riru 版本

N/a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2022-02-05T14_15_39.log](https://github.com/LSPosed/LSPosed/files/8008010/magisk_log_2022-02-05T14_15_39.log)

**Comment by yujincheng08** [comment]
full logcat or bugreport required.

**Comment by ag6ag1** [comment]
logs  attached 

[logs.zip](https://github.com/LSPosed/LSPosed/files/8008034/logs.zip)

**Comment by ag6ag1** [comment]
figured out that the problem was from a module named android faker, solved after Uninstalling
