### ISSUE TITLE
[Bug] Manager not launching

### ISSUE THREAD

**Issue by kotori2** [LSPosed/LSPosed#1645]
### Steps to reproduce/复现步骤

Launch LSP manager from shortcut or dialer

### Expected behaviour/预期行为

-

### Actual behaviour/实际行为

nothing happened

### Xposed Module List/Xposed 模块列表

```shell
com.virb3.trustmealready
me.iacn.biliroaming
com.xloger.exlink.app
```
```


### Magisk Module List/Magisk 模块列表

```shell
-
```

### LSPosed version/LSPosed 版本

~~latest~~ reproduced on 1.7.0 release & dex-obfuscate branch on different phones

### Android version/Android 版本

12

### Magisk version/Magisk 版本

24100

### Riru version/Riru 版本

Zygisk API v2

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Not much logs
```
02-08 16:35:20.156   887  1122 D LSPosedService: me.iacn.biliroaming did not change, skip caching it
02-08 16:35:20.159   887  1122 D LSPosedService: cached modules
02-08 16:35:20.159   887  1122 D LSPosedService: com.virb3.trustmealready /data/app/~~uYT0PzQpH5DUBkWgITBivw==/com.virb3.trustmealready-aslZyzryY7ZwaPSvAd2Hhg==/base.apk
02-08 16:35:20.159   887  1122 D LSPosedService: me.iacn.biliroaming /data/app/~~NcWMKVN0ITzlUjlxonkISw==/me.iacn.biliroaming-DNHE0AEuJPt49uDtBhDKTA==/base.apk
02-08 16:35:20.159   887  1122 D LSPosedService: com.xloger.exlink.app /data/app/~~h3CkU_WpLlsdnDrnweBQoQ==/com.xloger.exlink.app-QdrN-UhdfPB64vKb1l5pLA==/base.apk
02-08 16:35:20.159   887  1122 I LSPosedService: manager is not installed
02-08 16:35:20.159   887  1122 D LSPosed : obfuscation.cpp:198#jobject Java_org_lsposed_lspd_service_ObfuscationManager_obfuscateDex(JNIEnv *, jclass, jobject): fd=171, size=3900696
02-08 16:35:20.605  5670  5821 E Parcel  : Reading a NULL string not supported here.
```

**Comment by Hs1r1us** [comment]
@kotori2 
my shell also crash, is there any solution, thanks

**Comment by kotori2** [comment]
@Hs1r1us Please open a new issue and attach your log there. My issue was caused by #1652 so it's most probably not related.
