### ISSUE TITLE
[Bug] App keeps restarting after enabled to any scope

### ISSUE THREAD

**Issue by VD171** [LSPosed/LSPosed#1651]
### Steps to reproduce/复现步骤

1. Install com.picpay -> https://play.google.com/store/apps/details?id=com.picpay
2. Enable the app in scope list to any module

### Expected behaviour/预期行为

App would works perfectly.

### Actual behaviour/实际行为

App keeps restarting once opened.

### Xposed Module List/Xposed 模块列表

```shell
Tried some xposed modules and keeps same.
But I am aiming XPrivacyLua.
```

### Magisk Module List/Magisk 模块列表

```shell
LSPosed and Shamiko.
```

### LSPosed version/LSPosed 版本

v1.7.2-6379-zygisk

### Android version/Android 版本

11 RP1A.200720.011

### Magisk version/Magisk 版本

v24.1 (24100)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

----part 2 start----
[ 2022-02-09T01:42:43.491        0:   539:  1166 I/LSPosedLogcat   ] New log file: /data/adb/lspd/log/verbose_2022-02-09T01:42:43.491.log
[ 2022-02-09T01:42:50.411    10285:  7773:  7773 I/LSPosed         ] Loading modules for com.picpay/10285
[ 2022-02-09T01:42:50.413    10285:  7773:  7773 I/LSPosed-Bridge  ] Loading module eu.faircode.xlua from /data/app/~~SJkUoe7sB4N-QWs027EMzg==/eu.faircode.xlua-XwzXth27vcsSkX-cev4dew==/base.apk
[ 2022-02-09T01:42:50.436    10285:  7773:  7773 I/LSPosed-Bridge  ]   Loading class eu.faircode.xlua.XLua
[ 2022-02-09T01:42:50.535    10285:  7773:  7773 I/LSPosed-Bridge  ] XLua.Xposed Loaded com.picpay:10285

**Comment by vvb2060** [comment]
This app may be detecting xposed

**Comment by VD171** [comment]
No, it is not.

**Comment by VD171** [comment]
LSPosed and SHAMIKO are working PERFECTLY with zygisk.
I've never face any issue with LSPosed in any app before.
But, this app keeps starting from some time.
After some tests, I am sure the problem is to enable the app in any scope.

**Comment by VD171** [comment]
This is the screen for root/xposed detection, it can be avoided easily.
![Screenshot_2022-02-09-01-50-40-125_com picpay](https://user-images.githubusercontent.com/80125987/153124281-8e8bb731-5dd6-4615-aee3-ec2fe750c719.jpg)

**Comment by VD171** [comment]
I've found another app detecting if any module/scope is enabled:
https://play.google.com/store/apps/details?id=com.BanqueMisr.MobileBanking

**Comment by Stillhard** [comment]
> I've found another app detecting if any module/scope is enabled: https://play.google.com/store/apps/details?id=com.BanqueMisr.MobileBanking

Try this, it'll behave the same: https://play.google.com/store/apps/details?id=id.bmri.livin
