### ISSUE TITLE
[ISSUE] Restart notification doesn't follow the chosen LSPosed language

### ISSUE THREAD

**Issue by sn-o-w** [LSPosed/LSPosed#1658]
Not really a feature request, but an issue.

LSPosed app shows the restart notification in a language different than the language I chose within the app.

In my case, despite I chose English as the app language, the restart notification is displayed in Romanian.

It looks like restart notification follows the device's language that is indeed Romanian.

![Screenshot_20220210-012946_Shell](https://user-images.githubusercontent.com/2406819/153310196-a526bc1e-7ba6-4a08-8620-9d3de5a8205d.png)

**Comment by sn-o-w** [comment]
Have no idea if there are any other warning/notification messages affected, but this happens at least with the restart notification.

**Comment by sn-o-w** [comment]
@yujincheng08 I installed the build from the follwing link: https://github.com/LSPosed/LSPosed/actions/runs/1826331341

The issue is still present

![2022-02-11_003552](https://user-images.githubusercontent.com/2406819/153508260-4d3eb746-c46c-4556-b50e-3de0e30662b7.png)

**Comment by Stillhard** [comment]
@yujincheng08 
While you're on it, please check that when selecting Indonesian or SYSTEM (in Indonesian locale) as the language it'll stays at English

**Comment by sn-o-w** [comment]
@aviraxp @kotori2 @yujincheng08 @vvb2060 Please reopen this issue, this is not yet fixed.

**Comment by Stillhard** [comment]
> @aviraxp @kotori2 @yujincheng08 @vvb2060 Please reopen this issue, this is not yet fixed.

https://github.com/LSPosed/LSPosed/commit/a983f335512d245017ddcb1ddf7cc2610f5aee1e#commitcomment-66493783

**Comment by vvb2060** [comment]
We are already working on this issue #1670 and as a penalty for mentioning multiple admins at the same time, you will be banned for 7 days.

**Comment by sn-o-w** [comment]
It looks like there's still an issue. "Updated Xposed module" notification in the notification tray doesn't follow the chosen LSPosed language:

![Screenshot_20220503-010340_Neo_Backup](https://user-images.githubusercontent.com/2406819/166335037-f2c11eed-8f77-4db4-83d7-6e93f7045330.png)

**Comment by Howard20181** [comment]
The notification language follows the system and is not customizable.
