### ISSUE TITLE
[Bug] LSPosed log too much

### ISSUE THREAD

**Issue by QWQ2022** [LSPosed/LSPosed#1661]
### Steps to reproduce/复现步骤

打开目录/data/adb/lspd/log文件夹过大

### Expected behaviour/预期行为

log大小到达一定值后删除

### Actual behaviour/实际行为

积累到50GB+

### Xposed Module List/Xposed 模块列表

```shell
哔哩漫游
非残
核心破解
解锁MIUI+
拼多多免拼助手
淘米水
微x模块
ChiMi
知了
F**k Location
Qnotified
```

### Magisk Module List/Magisk 模块列表

```shell
Riru
Riru - LSPosed
Weeb Gapps on Android R
xmlpak
```

### LSPosed version/LSPosed 版本

6379

### Android version/Android 版本

11.0

### Magisk version/Magisk 版本

24101

### Riru version/Riru 版本

v26.1.4.r522.8b379cedb5

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-02-10T13_24_00.113.zip](https://github.com/LSPosed/LSPosed/files/8038313/LSPosed_2022-02-10T13_24_00.113.zip)

**Comment by vvb2060** [comment]
删除不断生成日志的模块

**Comment by QWQ2022** [comment]
已经关闭所有模块，log仍在写入

**Comment by yujincheng08** [comment]
应该是吃米，关掉要重启手机。

**Comment by QWQ2022** [comment]
不想关chimi，我的意思是能不能设定到一定阈值自动删除

**Comment by yujincheng08** [comment]
重启会自动删除上上次的日志。

另外 Xposed 文档清楚写着不能 spam XposedBridge.log，这是模块的锅

**Comment by yujincheng08** [comment]
而且你 CHIMI 你关掉时钟显秒就行。

**Comment by QWQ2022** [comment]
哦~
