### ISSUE TITLE
[Bug] Indonesian Translation

### ISSUE THREAD

**Issue by Stillhard** [LSPosed/LSPosed#1670]
### Steps to reproduce/复现步骤

Indonesian translation in crowdin is a fault for Java, so it afffecting LSPosed too, Settings > Indonesian = English :lol

### Expected behaviour/预期行为

The resources (app and daemon) for Indonesian language should use `values-in`

As an ex: Magisk use it correctly https://github.com/topjohnwu/Magisk/tree/master/app/src/main/res/values-in

Steps to fix:
- Change the resources folder name (app and daemon) from `values-id` to `values-in`
- Change this line in https://github.com/LSPosed/LSPosed/blob/e3a7256f01d29c277ca79d5bb2f2b0e5ede99942/app/build.gradle.kts#L177
to:
`}.map { it.language }
`

### Actual behaviour/实际行为

Crowdin as LSPosed use it from, using `values-id`

### Xposed Module List/Xposed 模块列表

```shell
Not important
```

### Magisk Module List/Magisk 模块列表

```shell
Not important
```

### LSPosed version/LSPosed 版本

Not important

### Android version/Android 版本

Not important

### Magisk version/Magisk 版本

Not important

### Riru version/Riru 版本

Not important

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Not important

**Comment by yujincheng08** [comment]
Hvnt indonisian changed its language code from in to id?

**Comment by yujincheng08** [comment]
https://www.loc.gov/standards/iso639-2/php/code_changes_bycode.php?code_ID=207

**Comment by Stillhard** [comment]
https://developer.android.com/reference/java/util/Locale#Locale(java.lang.String,%20java.lang.String,%20java.lang.String)

> https://www.loc.gov/standards/iso639-2/php/code_changes_bycode.php?code_ID=207

**Comment by Stillhard** [comment]
> Hvnt indonisian changed its language code from in to id?
True, but in Java, it'll read as "in" as in https://github.com/topjohnwu/Magisk/tree/master/app/src/main/res/
You can't find id, the correct one is in
