### ISSUE TITLE
[Bug] Android (System Framework) hooks do not appear to be working on Android 13 DP1

### ISSUE THREAD

**Issue by KieronQuinn** [LSPosed/LSPosed#1675]
### Steps to reproduce/复现步骤

1. Create a module with `handleLoadPackage` for `android`, simply logging when it is loaded is enough
2. Install the module, enable for `android` and reboot

### Expected behaviour/预期行为

The code is run when the package is loaded, the line is written to log and further changes including hooks can be made

### Actual behaviour/实际行为

The code is never run, the line is never logged. Hooks cannot be made.

Modules that hook apps (such as DiscoverKiller and Twitter Ad Eater) are working fine. Modules that hooked `android` in this way worked on previous Android versions.

### Xposed Module List/Xposed 模块列表

```shell
- Test module (barebones code will be attached)
- DarQ
- DiscoverKiller
- Twitter Ad Eater
- Three private modules that do not interfere (the issue also happens without them)
```

### Magisk Module List/Magisk 模块列表

```shell
- App Systemizer
- Extra Icons for Pixel Launcher
- GPay SQlite fix
- JamesDSP Manager
- SQlite for ARM
- Systemless Hosts
- USNF
- LSPosed Zygisk 
- Sui Zygisk
```

### LSPosed version/LSPosed 版本

6421

### Android version/Android 版本

13 DP1

### Magisk version/Magisk 版本

24102

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[bugreport.zip](https://github.com/LSPosed/LSPosed/files/8052236/bugreport.zip)
[example-module.zip](https://github.com/LSPosed/LSPosed/files/8052237/example-module.zip)

**Comment by yujincheng08** [comment]
Your log seems too late. I think the verbose log of LSPosed is enough. Could you post that one?

**Comment by yujincheng08** [comment]
Can you try #1676?

**Comment by KieronQuinn** [comment]
Sorry I was sleeping.

Can confirm the fix works, thanks!
