### ISSUE TITLE
[Bug] loadModule error when use lspoded

### ISSUE THREAD

**Issue by richarddavid1008** [LSPosed/LSPosed#1677]
### Steps to reproduce/复现步骤

when I install the lsposed in th android8.1  on pixel2.

I tried the module  
https://github.com/yujincheng08/BiliRoaming

soft verison:
riru 26.1.4
magisk 23
lsposed 1.6.5
when I check the code I found the dexFIles is null 
in the libcore/dalvik/src/main/java/dalvik/system/DexPathList.java

if (dexFiles == null) {
          throw new NullPointerException("dexFiles == null");
}

Could you help me check what's wrong with it  and what I can do for solved it ,thank you.

### Expected behaviour/预期行为

no error report.

### Actual behaviour/实际行为

02-12 07:11:53.850  4630  4630 E LSPosed : java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.List.toArray()' on a null object reference
02-12 07:11:53.850  4630  4630 E LSPosed :      at N1.toString(Unknown Source:18)
02-12 07:11:53.850  4630  4630 E LSPosed :      at java.lang.String.valueOf(String.java:2827)
02-12 07:11:53.850  4630  4630 E LSPosed :      at java.lang.StringBuilder.append(StringBuilder.java:132)
02-12 07:11:53.850  4630  4630 E LSPosed :      at dalvik.system.DexPathList.<init>(DexPathList.java:91)
02-12 07:11:53.850  4630  4630 E LSPosed :      at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:117)
02-12 07:11:53.850  4630  4630 E LSPosed :      at N1.<init>(Unknown Source:1)
02-12 07:11:53.850  4630  4630 E LSPosed :      at de.robv.android.xposed.XposedInit.loadModule(Unknown Source:1)
02-12 07:11:53.850  4630  4630 E LSPosed :      at de.robv.android.xposed.XposedInit.lambda$loadModules$0(Unknown Source:21)
02-12 07:11:53.850  4630  4630 E LSPosed :      at de.robv.android.xposed.XposedInit.a(Unknown Source:0)
02-12 07:11:53.850  4630  4630 E LSPosed :      at U2.accept(Unknown Source:12)
02-12 07:11:53.850  4630  4630 E LSPosed :      at java.util.ArrayList.forEach(ArrayList.java:1262)
02-12 07:11:53.850  4630  4630 E LSPosed :      at de.robv.android.xposed.XposedInit.loadModules(Unknown Source:2)
02-12 07:11:53.850  4630  4630 E LSPosed :      at org.lsposed.lspd.core.Main.a(Unknown Source:13)
02-12 07:11:53.850  4630  4630 E LSPosed :      at org.lsposed.lspd.core.Main.forkAndSpecializePost(Unknown Source:4)
02-12 07:11:53.850  4630  4630 E LSPosed :      at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native Method)
02-12 07:11:53.850  4630  4630 E LSPosed :      at com.android.internal.

### Xposed Module List/Xposed 模块列表

```shell
me.iacn.biliroaming 
https://github.com/Xposed-Modules-Repo/me.iacn.biliroaming
```

### Magisk Module List/Magisk 模块列表

```shell
riru v26.1.4 r522.

riru-lsposed: v1.6.5
```

### LSPosed version/LSPosed 版本

 1.6.5

### Android version/Android 版本

8.1-39

### Magisk version/Magisk 版本

23

### Riru version/Riru 版本

26.1.4

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

02-12 07:11:53.850  4630  4630 E LSPosed : java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object[] java.util.List.toArray()' on a null object reference
02-12 07:11:53.850  4630  4630 E LSPosed :      at N1.toString(Unknown Source:18)
02-12 07:11:53.850  4630  4630 E LSPosed :      at java.lang.String.valueOf(String.java:2827)
02-12 07:11:53.850  4630  4630 E LSPosed :      at java.lang.StringBuilder.append(StringBuilder.java:132)
02-12 07:11:53.850  4630  4630 E LSPosed :      at dalvik.system.DexPathList.<init>(DexPathList.java:91)
02-12 07:11:53.850  4630  4630 E LSPosed :      at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:117)
02-12 07:11:53.850  4630  4630 E LSPosed :      at N1.<init>(Unknown Source:1)
02-12 07:11:53.850  4630  4630 E LSPosed :      at de.robv.android.xposed.XposedInit.loadModule(Unknown Source:1)
02-12 07:11:53.850  4630  4630 E LSPosed :      at de.robv.android.xposed.XposedInit.lambda$loadModules$0(Unknown Source:21)
02-12 07:11:53.850  4630  4630 E LSPosed :      at de.robv.android.xposed.XposedInit.a(Unknown Source:0)
02-12 07:11:53.850  4630  4630 E LSPosed :      at U2.accept(Unknown Source:12)
02-12 07:11:53.850  4630  4630 E LSPosed :      at java.util.ArrayList.forEach(ArrayList.java:1262)
02-12 07:11:53.850  4630  4630 E LSPosed :      at de.robv.android.xposed.XposedInit.loadModules(Unknown Source:2)
02-12 07:11:53.850  4630  4630 E LSPosed :      at org.lsposed.lspd.core.Main.a(Unknown Source:13)
02-12 07:11:53.850  4630  4630 E LSPosed :      at org.lsposed.lspd.core.Main.forkAndSpecializePost(Unknown Source:4)
02-12 07:11:53.850  4630  4630 E LSPosed :      at com.android.internal.os.Zygote.nativeForkAndSpecialize(Native Method)
02-12 07:11:53.850  4630  4630 E LSPosed :      at com.android.internal.

**Comment by yujincheng08** [comment]
You are not using the debug version
