### ISSUE TITLE
[Feature Request] Hope to provide command line or development documentation for module updates

### ISSUE THREAD

**Issue by XIANDONGZHI** [LSPosed/LSPosed#1699]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

前提:   本问题出现在 hook系统api, 需要重启手机的那种
1.随意开发一个demo-xposed app  hook某个系统api
2.在lsposed中勾选并启用权限
3.重启手机
4.demo-xposed 正常实现hook , hook代码正常运作有效!
5. 此时, 修改demo-xposed app内的代码,  重新运行安装到手机, 检查lsposed中是否已经勾选权限(已勾选)
6.再次重启手机
7.demo-xposed的内部代码仍然是上一个版本的功能, 尽管去lsposed取消勾选重新勾选权限并重启手机仍然如此, 新的代码似乎无法更新?
8.唯一的解决办法是卸载demo-xposed app并重新安装,并重新勾选, 然后重启
无疑这对开发极不友好, 使用Edxposed并没有这个无法刷新代码的问题.  无奈Edxposed不支持安卓12

### Describe the solution you'd like/描述你想要的解决方案

1.希望能在每次安装app时lsposed自动刷新模块的代码, 提示重启手机, 便于开发者进行xposed开发工作
2.如果1无法实现,请告知有无解决办法
3.未见到官方有贴出任何的lsposed开发注意事项,如果是我的使用方式错误,请告知

**Comment by aviraxp** [comment]
https://github.com/LSPosed/LSPosed/issues/1025
