### ISSUE TITLE
[Feature Request] Allow Notification Hiding / Disable

### ISSUE THREAD

**Issue by ThePieMonster** [LSPosed/LSPosed#1710]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

N/A

### Describe the solution you'd like/描述你想要的解决方案

Allow hiding of notifications on module update.

![image](https://user-images.githubusercontent.com/11359134/154868290-b7be4ace-96b5-4545-acb9-18a1e5976b16.png)
![image](https://user-images.githubusercontent.com/11359134/154868315-fdca4d95-c29c-4a28-ace7-739b5d9a8865.png)

### Additional context/其他信息

N/A

**Comment by vvb2060** [comment]
Intended Behavior

**Comment by ThePieMonster** [comment]
> Intended Behavior

Bit annoying. Could include a option in settings to allow/disallow notifications.

**Comment by vvb2060** [comment]
You **must** reboot to apply changes.

**Comment by ThePieMonster** [comment]
> You **must** reboot to apply changes.

Going to assume English is not your first language. 

What's being mentioned is the option to turn off the notification. This GitHub issue has nothing to do with needing to reboot the device when a new module is installed or updated.

**Comment by yujincheng08** [comment]
you can disable the notification by disabling the notification channel.

**Comment by ThePieMonster** [comment]
> you can disable the notification by disabling the notification channel.

I have not found this option, where is it located?

**Comment by yujincheng08** [comment]
![screen](https://user-images.githubusercontent.com/5022927/154878883-ba1f7ef5-403f-4c1d-a1c5-fb5709315de8.png)

**Comment by ThePieMonster** [comment]
@yujincheng08 
So I installed LSPosed through Magisk store. Not sure if that could be why I don't have a LSPosed Manager application on my device. 
![image](https://user-images.githubusercontent.com/11359134/154884657-fa8c33a8-0bc7-4139-9377-923d99fbc11a.png)

**Comment by yujincheng08** [comment]
No.

**Comment by ThePieMonster** [comment]
@yujincheng08 Found it, thanks for the help.
Apps -> all apps -> show system -> Android System -> LSPosed
![Screenshot_20220220-214136](https://user-images.githubusercontent.com/11359134/154888163-9858c142-128a-49cd-a655-7d480967b0a5.png)
