### ISSUE TITLE
[Bug] LSPosed Manager cannot be used on latest MagiskOnWSA build

### ISSUE THREAD

**Issue by sn-o-w** [LSPosed/LSPosed#1711]
### Steps to reproduce/复现步骤

1. Install latest MagiskOnWSA build.
2. Install latest LSPosed build from GitHub Actions.
3. Open LSPosed Manager.

### Expected behaviour/预期行为

LSPosed Manager to work and to accept user input like clicking buttons.

### Actual behaviour/实际行为

The manager doesn't accept user input like clicking buttons.
It keeps pressing automatically and repeatedly on Overview?! 🤔

Have a look:

https://user-images.githubusercontent.com/2406819/155029765-e1e01a32-cd11-41af-a4e1-e73886793b75.mp4

### Xposed Module List/Xposed 模块列表

```shell
- FakeGapps v3.0
- Disable-FLAG_SECURE v2.0.0
```

### Magisk Module List/Magisk 模块列表

```shell
- Shamiko v0.4.3 (102)
- microG Installer Revived v2.6.0-3
- LSPosed v1.7.2 (6442)
```

### LSPosed version/LSPosed 版本

6442

### Android version/Android 版本

11 (this is what LSPosed tolds me)

### Magisk version/Magisk 版本

24102

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Have no idea how to collect the logs given that I cannot do anything inside LSPosed Manager.
I would gladly provide logs if there is another way to do that.

**Comment by yujincheng08** [comment]
Same as https://github.com/topjohnwu/Magisk/commit/3aa1a68cdcbfe25c9269e23760687ed0d45a8d6c
