### ISSUE TITLE
[Bug] system parasitation doesn't works [Zygisk]

### ISSUE THREAD

**Issue by skhrlx** [LSPosed/LSPosed#1712]
### Steps to reproduce/复现步骤

I just created the shortcut to open the manager, but when I click on it, it dont open

### Expected behaviour/预期行为

The shortcut is supposed to open the manager, but dont open

### Actual behaviour/实际行为

When I click on the shortcut, it dont open the LSposed manager

### Xposed Module List/Xposed 模块列表

```shell
Lucky patcher module, XPrivacyLua and Disable FLAG_SECURE
```

### Magisk Module List/Magisk 模块列表

```shell
Busybox for android NDK
Patches to android(Lucky Patcher Module)
System Apps(Lucky Patcher Module)
Systemless Hosts 
Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

1.7.2

### Android version/Android 版本

9.0

### Magisk version/Magisk 版本

24.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-02-21T20_22_23.208.zip](https://github.com/LSPosed/LSPosed/files/8112549/LSPosed_2022-02-21T20_22_23.208.zip)

**Comment by yujincheng08** [comment]
Not a debug log.

Moreover, try to launch it by dialer.
