### ISSUE TITLE
[Bug] switch tab after click in notice

### ISSUE THREAD

**Issue by coderstory** [LSPosed/LSPosed#1727]
### Steps to reproduce/复现步骤

1.open manager
2.click log tab
3.install a lsposed module
4. click notice (installed a module click to enable)
5. will auto open manager and into settings page with this module
6. but bottom banner not switch tab to module （BUG）
7. click module tab , wil show module list ,but title  is new module name （BUG）

### Expected behaviour/预期行为

点击 安装模块后的通知 打开模块设置页面 但底部的tab没有切换 导致 关系错乱

### Actual behaviour/实际行为

nothing

### Xposed Module List/Xposed 模块列表

```shell
nothing
```

### Magisk Module List/Magisk 模块列表

```shell
nothing
```

### LSPosed version/LSPosed 版本

nothing

### Android version/Android 版本

nothing

### Magisk version/Magisk 版本

nothing

### Riru version/Riru 版本

nothing

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

nothing

**Comment by yujincheng08** [comment]
This should be a bug from the upstream navigation lib. Can't fix by us.
