### ISSUE TITLE
[Bug] Dial code to open manager doesn't work

### ISSUE THREAD

**Issue by alexdonh** [LSPosed/LSPosed#1729]
### Steps to reproduce/复现步骤

Just flash latest LSPosed-Zygisk

### Expected behaviour/预期行为

Dial `*#*#5776733#*#*` should open the parasitic manager

### Actual behaviour/实际行为

The above code doesn't work

### Xposed Module List/Xposed 模块列表

```shell
Hide My Applist
```

### Magisk Module List/Magisk 模块列表

```shell
Bluetooth Library Patcher
Busybox
Debloater
Doze GMS
Enhance mode for HMA
Magisk Bootloop Protector
Shamiko
USNF
Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

1.7.2 (6379)

### Android version/Android 版本

12

### Magisk version/Magisk 版本

24.1 (24100)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-02-26T12_43_41.513.zip](https://github.com/LSPosed/LSPosed/files/8145985/LSPosed_2022-02-26T12_43_41.513.zip)

**Comment by ReMiOS** [comment]
Is this issue resolved ?
I have the same experience on my Samsung S10+ ( Android 12 / OneUI 4.1 / Magisk 26.1 / zygisk LSPosed )
