### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by HyperCriSiS** [LSPosed/LSPosed#1731]
### Steps to reproduce/复现步骤

Hi,

I just updated to the newest version v1.7.2 Latest  and restartet.
Now my Zenfone 8 is in RAM dump mode :cry: :cry: :cry:
Is there any way to fix this without reflashing? 

Thanks ans best regards,
Hyper

### Expected behaviour/预期行为

Successful update to newest version.

### Actual behaviour/实际行为

After update to v1.7.2 Latest the phone boots into RAM dump mode

### Xposed Module List/Xposed 模块列表

```shell
Exiswift
Sorry I do not know more, I have no possibility to look.
```

### Magisk Module List/Magisk 模块列表

```shell
RIRU and more.
Sorry I do not know more, I have no possibility to look.
```

### LSPosed version/LSPosed 版本

1.7.2 Latest 

### Android version/Android 版本

Android 11 Lineage

### Magisk version/Magisk 版本

v24.1

### Riru version/Riru 版本

I do not remember and I can't look sorry :(

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

I am not able to provide logs. My phone is in RAM dump mode.

**Comment by yujincheng08** [comment]
Flash official boot.img
