### ISSUE TITLE
[Bug] Unable to scroll readme of modules while touching in <pre> or <table>

### ISSUE THREAD

**Issue by AnnAngela** [LSPosed/LSPosed#1732]
### Steps to reproduce/复现步骤

1. Open a module in repo;
2. Put the finger in `<pre>` or `<table>`;
3. Try to scroll.

### Expected behaviour/预期行为

The content should be scrolled.

### Actual behaviour/实际行为

Nothing happened.

[Screen record](
https://user-images.githubusercontent.com/9762652/155927857-b2e8714d-a0d0-4dd9-833c-2d0f7206e8fb.mp4)

### Xposed Module List/Xposed 模块列表

```shell
* com.fkzhang.qqxposed
* me.kyuubiran.qqcleaner
* com.jy.xposed.skip
* com.bit747.clipboardfilter
* com.tsng.hidemyapplist
* com.lt2333.simplicitytools
* com.fankes.miui.notify
* me.iacn.biliroaming
* com.fkzhang.wechatxposed
* com.shatyuka.zhiliao
* gm.tieba.tabswitch
* com.test.unlockmiui
* com.shatyuka.killergram
* fi.veetipaananen.android.disableflagsecure
* com.yuk.fuckMiLinkService
```

### Magisk Module List/Magisk 模块列表

```shell
* hidemyapplist
* hosts
* shizuku-starter
* zygisk-sui
* zygisk_lsposed
* zygisk_shamiko
```

### LSPosed version/LSPosed 版本

6379

### Android version/Android 版本

12

### Magisk version/Magisk 版本

24.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [x] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-02-28T13_21_46.061.zip](https://github.com/LSPosed/LSPosed/files/8150786/LSPosed_2022-02-28T13_21_46.061.zip)

**Comment by yujincheng08** [comment]
expected behavior. we intentionally did it.

**Comment by AnnAngela** [comment]
> expected behavior. we intentionally did it.

But it makes the content unreadable if there is a large table or `<pre>`.

**Comment by yujincheng08** [comment]
if not, you cannot view wide code block

**Comment by AnnAngela** [comment]
> if not, you cannot view wide code block

Is there no solution to make the code block be scrolled both direction?

**Comment by yujincheng08** [comment]
at least I dont know.

**Comment by yujincheng08** [comment]
the scroll action is taken over by the code block. so you can scroll horizontally to view a wide code block. otherwise, scrolling code block will switch to release tab and you can never view the full content of the code block.
