### ISSUE TITLE
lsposed not activated [Bug] 

### ISSUE THREAD

**Issue by AndersonARS** [LSPosed/LSPosed#1738]
### Steps to reproduce/复现步骤

I installed lsposed framework zygisk and it is not enabling lsposed.

### Expected behaviour/预期行为

enable lsposed

### Actual behaviour/实际行为

Does not activate lsposed

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
None
```

### LSPosed version/LSPosed 版本

1.7.2 (6450)

### Android version/Android 版本

8.1

### Magisk version/Magisk 版本

24.1 (24100)

### Riru version/Riru 版本

N/a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2022-02-28T13:40:17.log](https://github.com/LSPosed/LSPosed/files/8155086/magisk_log_2022-02-28T13.40.17.log)

**Comment by yujincheng08** [comment]
Magisk log is useless.

**Comment by Hi-ImKyle** [comment]
I have this issue, what logs would be helpful. Rather than just saying the Magisk one is useless...
