### ISSUE TITLE
[Bug] Zygisk LSPosed shrinking space below GBoard

### ISSUE THREAD

**Issue by shaunkleyn** [LSPosed/LSPosed#1742]
### Steps to reproduce/复现步骤

Tap a text field to open GBoard. Notice the space below GBoard.
Install Zygisk LSPosed. 
Reboot. 
Tap on a text field to open GBoard. Notice the space is much smaller.

### Expected behaviour/预期行为

Should not affect spacing between the keyboard and bottom of the screen.

### Actual behaviour/实际行为

Space between GBoard and the bottom of the screen decreases making it very difficult to click the arrow that hides /collapses the keyboard.

### Xposed Module List/Xposed 模块列表

```shell
No modules need to be installed for this behavior
```

### Magisk Module List/Magisk 模块列表

```shell
Advanced Charging Controller (ACC) v2022.2.22.1 by VR25
Daily Job Scheduler (DJS) v2021.12.14 by VR25
Magisk Bootloop Protector v1.5 by HuskyDG
Systemless Hosts 1.0 by Magisk
Universal SafetyNet Fix v2.2.1 by kdragOn
Zygisk - LSPosed v1.7.2 (6442) by LSPosed Developers
```

### LSPosed version/LSPosed 版本

1.7.2 (6442)

### Android version/Android 版本

12

### Magisk version/Magisk 版本

24.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2022-03-05T10_05_08.log](https://github.com/LSPosed/LSPosed/files/8190276/magisk_log_2022-03-05T10_05_08.log)

**Comment by yujincheng08** [comment]
Magisk log is useless.
