### ISSUE TITLE
[Feature Request]  Add an option to select all apps for scope with one click

### ISSUE THREAD

**Issue by araafroyall** [LSPosed/LSPosed#1772]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Hi . There should be an option to to select all apps in scope list by one click..

### Describe the solution you'd like/描述你想要的解决方案

Hi . There should be an option to to select all apps in scope list by one click..

**Comment by yujincheng08** [comment]
nope

**Comment by araafroyall** [comment]
> nope

But i need. Because of some apps mechanism
