### ISSUE TITLE
[Bug] When I turn on flashlight from Quick Settings, the screen flickers and the phone reboots.

### ISSUE THREAD

**Issue by gamza88** [LSPosed/LSPosed#1773]
### Steps to reproduce/复现步骤

1. Turn on Flashlight from Quick Settings.
2. Screen Flickers
3. Phone reboots
4. When I disable LSposed from Magisk, Flashlight turns on normaly

### Expected behaviour/预期行为

Flashlight turns on normaly

### Actual behaviour/实际行为

Phone flickers and reboots

### Xposed Module List/Xposed 模块列表

```shell
Xposed edge
Android 12 extensions
```

### Magisk Module List/Magisk 模块列表

```shell
Magisk Bootloop Protector
LSposed Zygisk
```

### LSPosed version/LSPosed 版本

1.7.2 Zygisk

### Android version/Android 版本

12

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-03-18T14_55_07.045.zip](https://github.com/LSPosed/LSPosed/files/8306655/LSPosed_2022-03-18T14_55_07.045.zip)

**Comment by yujincheng08** [comment]
report to xposed edge.
