### ISSUE TITLE
[Bug] (?) Lsposer automatically makes icon on homescreen

### ISSUE THREAD

**Issue by Roshrach** [LSPosed/LSPosed#1774]
### Steps to reproduce/复现步骤

I don't know how, it's random

### Expected behaviour/预期行为

Making apps on homescreen should not be automatic

### Actual behaviour/实际行为

Lsposed randomly adds an icon in desktop even though i removed it. This did not happen before and I did not download any new modules before and after the bug happened. It just randomly occured. This happened thrice in the last 24 hours.

Also, lsposed on app drawer is not present, could be the reason why lsposed keeps on making icons on homescreen. Searching on all apps does not show lsposed too.

### Xposed Module List/Xposed 模块列表

```shell
Core patch v3.8
Lucky patcher v10.0.2
```

### Magisk Module List/Magisk 模块列表

```shell
IOS 15.4 emoji
Riru v26.1.4.r524.125daf3f89
Riru -lsposed v1.7.2
```

### LSPosed version/LSPosed 版本

6379

### Android version/Android 版本

Custom ROM android 12

### Magisk version/Magisk 版本

24.2

### Riru version/Riru 版本

1.7.2(6379)

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Can't find logs, see "actual behaviour"

**Comment by yujincheng08** [comment]
> Making apps on homescreen should not be automatic

It should.

**Comment by Roshrach** [comment]
A little clarification, in miui eu rom, I use the app drawer so my home screen is clean. But every now and then, lsposed makes an icon in the homescreen. I remove it, then a few hours later, it appears again. Was that really supposed to happen?

**Comment by yujincheng08** [comment]
Expected.
