### ISSUE TITLE
starting from 1.7.2 (6461) to latest [Bug] 

### ISSUE THREAD

**Issue by drakulaboy** [LSPosed/LSPosed#1782]
### Steps to reproduce/复现步骤

install LSPosed, reboot, install module from Xposed Module List, reboot, doesn't hook resources, for example on Android 12 i have a module that hide the lock icon from lockscreen

### Expected behaviour/预期行为

hide lock icon from lockscreen
![Screenshot_20220321-161022_Quickstep](https://user-images.githubusercontent.com/7822898/159279122-20797d3a-b879-407b-84f8-5bf52fdfa0c9.png)

### Actual behaviour/实际行为

doesn't hid
![Screenshot_20220321-160755_Magisk](https://user-images.githubusercontent.com/7822898/159279207-157327e9-9e82-47de-b39a-488d07eb7ee6.png)
e

### Xposed Module List/Xposed 模块列表

```shell
here is the module https://github.com/drakulaboy/A12LockIconRemover/blob/main/A12_lock_icon_remover%20signed.apk
```

### Magisk Module List/Magisk 模块列表

```shell
Busybox
LSPosed Zygisk
```

### LSPosed version/LSPosed 版本

6461

### Android version/Android 版本

Android 12

### Magisk version/Magisk 版本

24304

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-03-21T15_54_09.241.zip](https://github.com/LSPosed/LSPosed/files/8316041/LSPosed_2022-03-21T15_54_09.241.zip)

**Comment by drakulaboy** [comment]
yay, fixed, thank you very much!!

**Comment by Stillhard** [comment]
Pardon me if i seems to hijacked this, i just want to inform you that there's a bug too with the way New XSharedPreferences work since HookerBridge (LSplant) implemented, for ex. if you force a module to use 'xposedsharedprefs', strange behavior will occurs. Anyway, great job as always to all of you @LSPosed devs team.
