### ISSUE TITLE
[Bug] LSPosed manager 1.8.0 (6482) not detecting LSPosed 1.8.0 framework installation, unable to create parasitic shortcut

### ISSUE THREAD

**Issue by DealsBeam** [LSPosed/LSPosed#1792]
### Steps to reproduce/复现步骤

1. flash zygisk lsposed 1.8.0 in magisk
2. reboot
3. install manager.apk from lspd folder
4. run lsposed manager app
5. says lsposed is not installed

### Expected behaviour/预期行为

Should be able to detect latest installed lsposed version and allow for module management

### Actual behaviour/实际行为

Manager not detecting lsposed installation, unable to launch parasitic manager/shortcut even through dialer

### Xposed Module List/Xposed 模块列表

```shell
instaprefs
twitter ad eater
gravitybox
```

### Magisk Module List/Magisk 模块列表

```shell
busybox for android ndk
ios 15.4 beta (u14) emojis
screencam systemizer module
systemless hosts
universal safetynet fix
zygisk - sui
```

### LSPosed version/LSPosed 版本

1.8.0

### Android version/Android 版本

Android 11 based on ProtonAOSP 11.6.0 ROM

### Magisk version/Magisk 版本

24.3 (24300)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2022-03-25T08_35_47.log](https://github.com/LSPosed/LSPosed/files/8350603/magisk_log_2022-03-25T08_35_47.log)

**Comment by yujincheng08** [comment]
Magisk log is useless.

**Comment by yujincheng08** [comment]
[Log Catcher-v22.5(27) (2).zip](https://github.com/LSPosed/LSPosed/files/8350645/Log.Catcher-v22.5.27.2.zip)

A Magisk module that can help you save the log
required Magisk 20.4+
The log is saved to /cache/bootlog by default
If /cache does not exist, save to /data/local/bootlog
If you don't want to kill the logcat process after boot completed, you can create a file named boot.lcs to /data/local/logcatcher/ .

When the system boot normally and /data/local/logcatcher/boot.lcs is not detected, the logs will be packaged and copied to the Download folder.
