### ISSUE TITLE
[FR:] Define default behaviour for newly installed apps

### ISSUE THREAD

**Issue by just-Nob** [LSPosed/LSPosed#1808]
Hi,

I'm not sure of this is the right place for my concern, bit I hope so. Please let me know if it's not.

I really appreciate LSposed's ability to separately define for every module which app to be affected and which not. Anyway, I wish that it was possible to define LSposed default behaviour.

Currently, if one installs a new app, all LSposed modules will be disabled for that app by default.
For some modules this is very disadvantageous, e.g. for XPrivacyLua - because one have to activate XPrivacyLua in LSposed for every app after its installation.
I wish to be able to define for every module how to handle any newly installed app, i.e. if the module is disabled or enabled for the corresponding app by default.

That's it!

**Comment by mywalkb** [comment]
This is a very long, long story. 
There are many similar requests and the reply it's always been "wantfix". So you most likely your FR will be closed.
The modules should manage the scope in the code, but with the current version this is possible only statically and not dinamically. 
There are 2 issues #9 #405 very useful for set the scope dinamically but they will never be implemented (maybe).
LSPosed will never implement an "all applications button" and "event on new installed app".
