### ISSUE TITLE
[Bug] Installed success but no manager app on Android9

### ISSUE THREAD

**Issue by SabinLee** [LSPosed/LSPosed#1812]
### Steps to reproduce/复现步骤

1.enable zygisk(beta), install zygisk-lsposed, log shows install succeed.
2.restart phone, magisk shows lsposed module is enabled

### Expected behaviour/预期行为

1.There should be a lsposed manager app on the launcher and works fine

### Actual behaviour/实际行为

There is no lsposed manager app was installed on launcher.
Try to install manager app from zip unarchiver folder, installed success but it shows “first line: 未安装(LSPosed 未安装), second line:安装 点击安装LSPosed ”, 3 bottom tabs are: 仓库 概览 设置, no 模块 and 日志 tabs
So only can provide magisk logs

### Xposed Module List/Xposed 模块列表

```shell
Xposed has no modules tab
```

### Magisk Module List/Magisk 模块列表

```shell
1.Shamiko
2.Zygisk-LSPosed
3.神仙救砖
```

### LSPosed version/LSPosed 版本

1.8.0(6490) debug

### Android version/Android 版本

MIUI11.0.5.0(Android 9)

### Magisk version/Magisk 版本

canary 3dc7d77e(24304)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_install_log_2022-04-05T21_24_53.log](https://github.com/LSPosed/LSPosed/files/8418615/magisk_install_log_2022-04-05T21_24_53.log)

**Comment by yujincheng08** [comment]
send /data/adb/lspd/log

if you have read the report guide carefully, you should know it. magisk log is useless.

**Comment by SabinLee** [comment]
> send /data/adb/lspd/log
> 
> if you have read the report guide carefully, you should know it. magisk log is useless.

sorry @yujincheng08 , NO log in that folder, it just contain a manager.apk, I can provide any logs

**Comment by yujincheng08** [comment]
also mentioned in report guide: adb logcat or su -c logcat or bugreport.

**Comment by SabinLee** [comment]
I can't find the report guide😓, can you provid a link? thx @yujincheng08

**Comment by yujincheng08** [comment]
whenever you create an issue, you cam see it. Apparently you didmt read this when you create am issue. So this issue cannot be useful.

![Screenshot_2022-04-05-22-24-17-548-edit_com microsoft emmx](https://user-images.githubusercontent.com/5022927/161777041-339b95bc-54c3-41b4-a72a-c5e10f594d4b.jpg)

**Comment by SabinLee** [comment]
Hi @yujincheng08 , I captured the MIUI system bugreport log, file attached.pls have a look to help me solve this issue. thanks a lot.
[bugreport-2022-04-05-225525.zip](https://github.com/LSPosed/LSPosed/files/8419498/bugreport-2022-04-05-225525.zip)

**Comment by yujincheng08** [comment]
reboot your device and get the bugreport ASAP after it boots.

**Comment by yujincheng08** [comment]
@SabinLee ?

**Comment by SabinLee** [comment]
@yujincheng08 sorry for reply so late, pls check the log again, it was captured after the phone reboot. 
[bugreport-2022-04-09-122637.zip](https://github.com/LSPosed/LSPosed/files/8456277/bugreport-2022-04-09-122637.zip)

**Comment by yujincheng08** [comment]
still too late. Increase the log buffer size in developer options and grab the bugreport again. But since you have root you this magisk module to make it easier:
[Log Catcher-v22.5(27).zip](https://github.com/LSPosed/LSPosed/files/8456328/Log.Catcher-v22.5.27.2.zip)

A Magisk module that can help you save the log
required Magisk 20.4+
The log is saved to /cache/bootlog by default
If /cache does not exist, save to /data/local/bootlog
If you don't want to kill the logcat process after boot completed, you can create a file named boot.lcs to /data/local/logcatcher/ .

When the system boot normally and /data/local/logcatcher/boot.lcs is not detected, the logs will be packaged and copied to the Download folder

log抓取Magisk模块
要求 Magisk 20.4+
顺便打印dmesg
默认保存在 /cache/bootlog
cache 分区不存在就保存到 /data/local/bootlog
如果你想在进入系统后不停止 logcat 进程，你可以创建 /data/local/logcatcher/boot.lcs 文件

当正常启动系统并且未检测到/data/local/logcatcher/boot.lcs 时，会将log打包复制到Download文件夹

**Comment by SabinLee** [comment]
@yujincheng08  I installed this logcatcher, but no log 
saved to any directory whether create boot.lcs or not . Then I switchd the dev options log level from warning to error, but it still make a 6m size log file.  This is the reason why I reply so late, because I can't get any smaller log file and I almost give up. how can I clean the sysyem log cache and re-create a new one?

**Comment by yujincheng08** [comment]
if log catcher does not work, your system may be corrupted and will break many modules including LSPosed. if so, no help we can offer.

**Comment by SabinLee** [comment]
I reset my device to Miui factory last week, then flashed twrp and magisk, So I think there is not corrupted on my device. if really have no way to avtive lsp, thanks for all your help
