### ISSUE TITLE
[Bug] PHONE BOOTLOPED 

### ISSUE THREAD

**Issue by ale82to** [LSPosed/LSPosed#1814]
### Steps to reproduce/复现步骤

after updating lsposed from telegram archive chat to latest zigisk version phone will not boot only solution was to restore a twrp backup !!
screenshot of the issue :
https://i.imgur.com/qHvSop9.jpg

### Expected behaviour/预期行为

ehebhdjdjjdbdhd

### Actual behaviour/实际行为

ehbejrjjf

### Xposed Module List/Xposed 模块列表

```shell
ejeh
```

### Magisk Module List/Magisk 模块列表

```shell
ebbe
```

### LSPosed version/LSPosed 版本

1.8

### Android version/Android 版本

11

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

n/a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

hjrnrnf

**Comment by kotori2** [comment]
fdsdhsdgfsf

**Comment by yujincheng08** [comment]
igdooekg
