### ISSUE TITLE
[Feature Request] 不要在插件界面显示账户名啊

### ISSUE THREAD

**Issue by SSSSSSSan** [LSPosed/LSPosed#1821]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

如题

### Describe the solution you'd like/描述你想要的解决方案

允许在插件界面吧手机的账户名给*掉

**Comment by canyie** [comment]
@SSSSSSSan 为了截图吗，那可以自己抹掉呀

**Comment by JasonKhew96** [comment]
预期 行为，那是 当前 手机 用户名，某些 系统 直接 实名 了，实际 上，这个 值 可以 随便 设置
