### ISSUE TITLE
Please include an option to disable logging at will

### ISSUE THREAD

**Issue by zkollz** [LSPosed/LSPosed#1828]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

The number of logs produced is excessive even with a single module enabled and with verbose logs deactivated

### Describe the solution you'd like/描述你想要的解决方案

Add a switch to have the option to disable module logging if desired as well as verbose logging

### Additional context/其他信息

Although verbose logs are disabled they always occur after rebooting the device.

**Comment by yujincheng08** [comment]
logs are produced by modules. ask module developer not to log instead.
