### ISSUE TITLE
[Bug]LSPosed Framework doesn't load

### ISSUE THREAD

**Issue by techIndia-hacker** [LSPosed/LSPosed#1836]
### Steps to reproduce/复现步骤

I updated from version zyzisk lsposed 1.8.0 to 1.8.1 only to find out the framework doesn't load after reboot. All modules won't work obviously and manager shows not installed.

Device 1+ 7t

### Expected behaviour/预期行为

Lsposed should work

### Actual behaviour/实际行为

Framework doesn't load

### Xposed Module List/Xposed 模块列表

```shell
Luck patcher

Gravity Box
```

### Magisk Module List/Magisk 模块列表

```shell
Lsposed
BusyBox
OverlayFS
```

### LSPosed version/LSPosed 版本

6499(1.8.1)

### Android version/Android 版本

11

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Wait

**Comment by techIndia-hacker** [comment]
Hey why closed?

**Comment by techIndia-hacker** [comment]
Manger shows not installed so I don't have laposed logs

**Comment by techIndia-hacker** [comment]
![Screenshot_20220411-144153](https://user-images.githubusercontent.com/58086339/162710490-ba9a4042-a25a-414f-8cdc-61c565715c0a.jpg)
Magisk update log

**Comment by yujincheng08** [comment]
Sorry. No log, no fix.

**Comment by yujincheng08** [comment]
Stop wasting the time. We already mention how to grab the log if LSPosed does not activate. If you do not want to follow it, we won't offer any help.

**Comment by yujincheng08** [comment]
And you if try to lay to us, we will temporarily ban you because of your dishonesty. Apparently, you have lied to us: you didn't use the latest CI version but you check the option that you are using the latest CI version.

**Comment by techIndia-hacker** [comment]
I am not trying to blame anybody. It's just I use gravitybox module and laposed is not loading. So I am reporting.

Where is the doc on how to get logs if laposed doesn't load

**Comment by yujincheng08** [comment]
So you didn't even want to read the issue template, right?
![image](https://user-images.githubusercontent.com/5022927/162711964-46a3397a-8e0e-4799-88aa-52204f0f1b82.png)

**Comment by techIndia-hacker** [comment]
[Uploading bugreport-OnePlus7TPro-RKQ1.201022.002-2022-04-11-15-15-32.zip…]()
 This is android bug report.
Is this what is required to diagnose?

**Comment by yujincheng08** [comment]
file does not upload successfully... how can i check it...

**Comment by techIndia-hacker** [comment]
Check now

**Comment by yujincheng08** [comment]
> I also have that experiential security feature turned on

this was fixed in latest CI. But you refused to test...

**Comment by techIndia-hacker** [comment]
Hey I am not stupid. I am just pointing out a big in stable release😏 Come on man

Build 6505 seems to works
