### ISSUE TITLE
[Bug] Error reporting crash

### ISSUE THREAD

**Issue by qinyang1018** [LSPosed/LSPosed#1842]
### Steps to reproduce/复现步骤

update lsp to 1.8.1  use lataclysm hook  app crash 

### Expected behaviour/预期行为

app no crash

### Actual behaviour/实际行为

app crash

### Xposed Module List/Xposed 模块列表

```shell
lataclysm
```

### Magisk Module List/Magisk 模块列表

```shell
Riru
```

### LSPosed version/LSPosed 版本

1.8.1(6499)

### Android version/Android 版本

11

### Magisk version/Magisk 版本

23.0

### Riru version/Riru 版本

26.1.4r522

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-04-14T09_18_50.300.zip](https://github.com/LSPosed/LSPosed/files/8485580/LSPosed_2022-04-14T09_18_50.300.zip)

**Comment by yujincheng08** [comment]
6499 is not latest CI
