### ISSUE TITLE
[Bug] Module settings get reset after changing Riru to Zygisk

### ISSUE THREAD

**Issue by usmanovms** [LSPosed/LSPosed#1856]
### Steps to reproduce/复现步骤

1. Delete Riru and Riru LSPosed
2. Reboot
3. Enable Zygisk and install Zygisk LSPosed
4. Reboot
5. Check previously installed modules. 

### Expected behaviour/预期行为

Ideally, all previously installed modules should preserve their settings and continue to work as before

### Actual behaviour/实际行为

Settings of previously installed modules (if you had any and applied them to system or apps) get reset after Riru to Zygisk migration. 

### Xposed Module List/Xposed 模块列表

```shell
GravityBox
```

### Magisk Module List/Magisk 模块列表

```shell
Riru
Riru LSPosed
```

### LSPosed version/LSPosed 版本

1.8.0

### Android version/Android 版本

11

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

26.1.5

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[logs.txt](https://github.com/LSPosed/LSPosed/files/8499679/logs.txt)

**Comment by vvb2060** [comment]
> logs: none :)
