### ISSUE TITLE
[Feature Request]  let modules work on lsposed itself

### ISSUE THREAD

**Issue by aleph23** [LSPosed/LSPosed#1859]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Somewhat

### Describe the solution you'd like/描述你想要的解决方案

Allow modules like alltrans work on the lsposed app itself, so the module repository can be translated.

**Comment by vvb2060** [comment]
For security reasons, this is not allowed.

**Comment by vvb2060** [comment]
https://github.com/Xposed-Modules-Repo
You can use the browser translation.

**Comment by aleph23** [comment]
Good work around.  Thank you.

**Comment by pbanj** [comment]
> For security reasons, this is not allowed.

Could do a whitelist so only certain mods could do it. Or only allow alltrans as it's the only mod I can see ever needing to be able to hook into it. Or if possible, add the functionality to the manager itself.
