### ISSUE TITLE
The lsp6525 version will cause Zygisk to fail

### ISSUE THREAD

**Issue by ZXAS007** [LSPosed/LSPosed#1875]
### Steps to reproduce/复现步骤

Turn on the mask Zygisk function, install lsp6525debug (Zygisk version) and restart the device

### Expected behaviour/预期行为

lsp activation works normally

### Actual behaviour/实际行为

lsp not working, mask manager shows Zygisk not enabled, loading paused

### Xposed Module List/Xposed 模块列表

```shell
Core Crack 3.8 and WooBox For MIUI1.6.4
```

### Magisk Module List/Magisk 模块列表

```shell
The same module as the previous feedback, but one more to remove temperature control [official version] and Log Catcher
```

### LSPosed version/LSPosed 版本

6525

### Android version/Android 版本

12

### Magisk version/Magisk 版本

a609e 0aa-alpha (24306) (27)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[0.zip](https://github.com/LSPosed/LSPosed/files/8519337/0.zip)

**Comment by keta1** [comment]
fixed in #1876
