### ISSUE TITLE
[Feature Request] In-app update of modules

### ISSUE THREAD

**Issue by Dev0110** [LSPosed/LSPosed#1877]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Installing custom modules is great, but requiring a constant watch on github to ensure having the latest version of modules.

### Describe the solution you'd like/描述你想要的解决方案

As magisk did, implement a possibility to add an update URL and an update button to download the latest version of modules.

**Comment by yujincheng08** [comment]
we already have a repo and can showing update avaliable, right?
