### ISSUE TITLE
[Bug] XSharedPreferences doesn't work since v1.8.0-6489

### ISSUE THREAD

**Issue by fei-ke** [LSPosed/LSPosed#1878]
### Steps to reproduce/复现步骤

1. Module MainActivity with `context.getSharedPreferences("test", Context.MODE_WORLD_READABLE)`
2. Enable Module in parasitic manager
3. Launch the module App

Here is my demo project: https://github.com/fei-ke/XSharedPreferencesDemo

I tested the LSPosed zygisk version from v1.8.0-6482  to v1.8.1-6499 using Binary Search, v1.8.0-6489 is the first bad version.

```
v1.8.1-6499 bad
v1.8.0-6498
v1.8.0-6497
v1.8.0-6496
v1.8.0-6495
v1.8.0-6494
v1.8.0-6493
v1.8.0-6492
v1.8.0-6491 bad
v1.8.0-6490
v1.8.0-6489 bad
v1.8.0-6488 good   
v1.8.0-6487 good
v1.8.0-6486
v1.8.0-6484    
v1.8.0-6483
v1.8.0-6482 good
```

### Expected behaviour/预期行为

`context.getSharedPreferences("test", Context.MODE_WORLD_READABLE)` return a SharedPreferences instance.

### Actual behaviour/实际行为

`context.getSharedPreferences("test", Context.MODE_WORLD_READABLE) ` throw `SecurityException`

### Xposed Module List/Xposed 模块列表

```shell
[XposedDemo](https://github.com/fei-ke/XSharedPreferencesDemo)
```

### Magisk Module List/Magisk 模块列表

```shell
LSPosed-v1.8.0-6489-zygisk-debug
```

### LSPosed version/LSPosed 版本

 LSPosed-v1.8.0-6489-zygisk-debug

### Android version/Android 版本

12

### Magisk version/Magisk 版本

24.3(24300)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Use  LSPosed-v1.8.0-6489-zygisk-debug [LSPosed_2022-04-21T15_36_07.305.zip](https://github.com/LSPosed/LSPosed/files/8528742/LSPosed_2022-04-21T15_36_07.305.zip)

Use LSPosed-v1.8.2-6527-zygisk-debug [LSPosed_2022-04-21T16_22_04.499.zip](https://github.com/LSPosed/LSPosed/files/8529111/LSPosed_2022-04-21T16_22_04.499.zip)

**Comment by yujincheng08** [comment]
How about release build? Someone has reported that release build may work.

**Comment by fei-ke** [comment]
> How about release build of your module? Someone has reported that release build may work.

Build type with `debuggable false` works fine.

**Comment by yujincheng08** [comment]
我待会发几个版本给你测试一下

**Comment by mywalkb** [comment]
I think [this](https://github.com/fei-ke/XSharedPreferencesDemo/blob/71b5360df5f5a24623a2e1dbacd1bd7578ef6dcc/app/src/main/AndroidManifest.xml#L26-L28) `            android:value="93+" />` is wrong. 
You should use only 93 without plus. For me work also with latest version without +. 
It's not an issue, where did you read that you need to put a plus? 
[Wiki](https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences) don't report it, ignore wrong example on internet.

[This code](https://github.com/LSPosed/LSPosed/blob/59913258f96a05139e40186eef0fdd5cef110b7e/core/src/main/java/de/robv/android/xposed/XSharedPreferences.java#L172-L178) should exctract only IntPart from "93+" but something is wrong.

I think also is wrong enable this feature with xposedminversion, it should only be enabled with xposedsharedprefs, but this is another story.

**Comment by fei-ke** [comment]
> I think [this](https://github.com/fei-ke/XSharedPreferencesDemo/blob/71b5360df5f5a24623a2e1dbacd1bd7578ef6dcc/app/src/main/AndroidManifest.xml#L26-L28) ` android:value="93+" />` is wrong. You should use only 93 without plus. For me work also with latest version without +. It's not an issue, where did you read that you need to put a plus? [Wiki](https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences) don't report it, ignore wrong example on internet.
> 
> [This code](https://github.com/LSPosed/LSPosed/blob/59913258f96a05139e40186eef0fdd5cef110b7e/core/src/main/java/de/robv/android/xposed/XSharedPreferences.java#L172-L178) should exctract only IntPart from "93+" but something is wrong.
> 
> I think also is wrong enable this feature with xposedminversion, it should only be enabled with xposedsharedprefs, but this is another story.

[This code](https://github.com/LSPosed/LSPosed/blob/59913258f96a05139e40186eef0fdd5cef110b7e/core/src/main/java/de/robv/android/xposed/XSharedPreferences.java#L177) will extract the int part of version string, also tried without `+` and enabled `xposedsharedprefs`, got same result.

**Comment by mywalkb** [comment]
I tested on android 11, I will test on emulator android 12.
In your logs I can't see [this](https://github.com/LSPosed/LSPosed/blob/59913258f96a05139e40186eef0fdd5cef110b7e/core/src/main/java/org/lsposed/lspd/hooker/LoadedApkGetCLHooker.java#L122) "New modules detected, hook preferences", it should appear when `xposedminversion > 92 || xposedsharedprefs`

**Comment by mywalkb** [comment]
Could you upload your apk? I'd like test on my device.

**Comment by fei-ke** [comment]
> Could you upload your apk? I'd like test on my device.

You can download the apk from action page : https://github.com/fei-ke/XSharedPreferencesDemo/actions/runs/2200192997

**Comment by mywalkb** [comment]
I'd like test apk without +, in that apk there is 93+ and is confirmed which doesn't work with latest versions.

**Comment by yujincheng08** [comment]
Try #1892

**Comment by hitwhoyxw** [comment]
@fei-ke 我在我的android11设备上出现了这个问题，而且是必现的，通过sharedPreferences=context.getSharedPreferences(configName, Context.MODE_WORLD_READABLE);必定抛异常，想问下你知道怎么解决吗，感谢

**Comment by hitwhoyxw** [comment]
@fei-ke 或者说，有什么wiki里面没提到的步骤需要做吗？
