### ISSUE TITLE
[Bug] Zygisk - LSPosed 1.8.2 (6533): no prompt to create parasitic shortcut + not detecting LSPosed framework installation of manager.apk

### ISSUE THREAD

**Issue by Fl4sHNoX** [LSPosed/LSPosed#1888]
### Steps to reproduce/复现步骤

1. Flash LSPosed 1.8.2 (6533) in Magisk
2. Reboot
3. No prompt for parasitic shortcut (using default launcher: OxygenOS)
4. Try installing the manager.apk
5. Run the Manager app
6. Says LSPosed isn't installed

### Expected behaviour/预期行为

Getting prompted to add the parasitic shortcut after install / detect that LSPosed is installed at least.

### Actual behaviour/实际行为

- No prompt to add parasitic shortcut
- Manager not detecting LSPosed
- Unable to launch parasitic manager even while using the dialer code

### Xposed Module List/Xposed 模块列表

```shell
None yet.
```

### Magisk Module List/Magisk 模块列表

```shell
App Systemizer - (v17.3.1)
Busybox for Android NDK - (1.31.1)
Detach - (v5.3)
Fingerprint Swipe BackHomeRecents - (v3)
Log Catcher - (v22.5)
Rboard Themes - (v18t)
Substratum
Swift Installer Module - (v5)
Systemless Hosts
Twenmoji - (v14.0.2)
Universal SafetyNet Fix - (v2.2.1)
Zygisk - LSPosed - (v1.8.2 (6533))
```

### LSPosed version/LSPosed 版本

1.8.2 (6533)

### Android version/Android 版本

10

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

(I used LogCatcher as I saw it was recommended in another post, please feel free to advise me if I need to do anything else)
[bootlog-2022-04-24-20-14-53.tar.gz](https://github.com/LSPosed/LSPosed/files/8550312/bootlog-2022-04-24-20-14-53.tar.gz)

**Comment by yujincheng08** [comment]
Seem like daemon is not running. Even `$debug && log -p d -t "LSPosed" "start $flavor daemon $*"` is not running.

Could you get the log in the same way using the following build?
[LSPosed-v1.8.2-6533-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8550326/LSPosed-v1.8.2-6533-zygisk-debug.zip)

**Comment by Fl4sHNoX** [comment]
I thought I used the debug version from the Telegram group but just to be sure I uninstalled & rebooted, and then installed the one you just linked and rebooted again:
[bootlog-2022-04-24-21-03-43.tar.gz](https://github.com/LSPosed/LSPosed/files/8550337/bootlog-2022-04-24-21-03-43.tar.gz)

**Comment by yujincheng08** [comment]
> 05-17 17:07:59.583   708   708 I LSPosed : [post-fs-data] before running daemon
> 05-17 17:07:59.592   710   710 I LSPosed : [post-fs-data] run daemon

The daemon cannot be started by the script. Cannot even see the `start $flavor daemon` log. Weird.
Get log using this build:
[LSPosed-v1.8.2-6533-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8550343/LSPosed-v1.8.2-6533-zygisk-debug.zip)

**Comment by Fl4sHNoX** [comment]
Probably a noob question but, after installing the build, I reboot once and then get the log, there's no need for a second reboot right?
Anyway here's the log with the build you provided:
[bootlog-2022-04-24-22-22-37.tar.gz](https://github.com/LSPosed/LSPosed/files/8550461/bootlog-2022-04-24-22-22-37.tar.gz)

**Comment by yujincheng08** [comment]
You dont need to

how about this:
[LSPosed-v1.8.2-6533-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/8551335/LSPosed-v1.8.2-6533-zygisk-debug.zip)

**Comment by Fl4sHNoX** [comment]
Alright noted.

I'm confused, I don't get any log output in `data/adb/lspd/`, there's nothing other than "manager.apk".
Apologies for my lack of knowledge but do I need to do a specific action to get logs? Like using a specific terminal command maybe?

Please feel free to point me towards any documentation I might have missed while searching for a fix!

**Comment by yujincheng08** [comment]
in the same way you got the previous ones.

**Comment by Fl4sHNoX** [comment]
Oh okay!

Here's the log with the latest build as requested:
[bootlog-2022-04-25-12-23-21.tar.gz](https://github.com/LSPosed/LSPosed/files/8553696/bootlog-2022-04-25-12-23-21.tar.gz)

**Comment by yujincheng08** [comment]
Found the problem: unshare is not working on your device?
```
05-18 08:27:42.711   714   714 I LSPosed : unshare0 unshare: can't mount none on "LZ9_l[)�V�&ߜ�Edr�~�d4%BB
```

**Comment by yujincheng08** [comment]
What magisk version are you using?

**Comment by Fl4sHNoX** [comment]
I'm using version 24.3 (24300)

**Comment by yujincheng08** [comment]
try magisk canary?

**Comment by Fl4sHNoX** [comment]
Alright, just installed Magisk Canary "63z89f9f" (24306)
Rebooted and got prompted to create the parasitic shortcut for LSPosed!!

When opening LSPosed through it the correct version is detected and activated!

Here's a log just in case you need to review it still:
[bootlog-2022-04-25-13-23-51.tar.gz](https://github.com/LSPosed/LSPosed/files/8554084/bootlog-2022-04-25-13-23-51.tar.gz)

**Comment by yujincheng08** [comment]
looks like your magisk installation is corrupt: the busybox is broken. You can try to install the stable version of magisk again to see if it happens again.

**Comment by jyeric** [comment]
same issue met with WSA with Magisk(24300). solved by updating to the latest magisk (25200).
