### ISSUE TITLE
[Bug] 32位android x86 11, zygisk lsposed存在兼容问题，该模块未加载

### ISSUE THREAD

**Issue by youling257** [LSPosed/LSPosed#1906]
### Steps to reproduce/复现步骤

magisk启用zygisk
刷入lsposed zydisk版

### Expected behaviour/预期行为

给32位刷入32位的liblspd.so

### Actual behaviour/实际行为

给x86刷入了x86_64
![Screenshot_20220502-025905](https://user-images.githubusercontent.com/16304724/166161137-544b0eb3-031c-4ed6-a275-8e74d5b48f3d.png)
![Screenshot_20220502-025851](https://user-images.githubusercontent.com/16304724/166161142-8e816561-d46c-4dd3-bd40-9ebe292d5980.png)

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
zygisk lsposed
```

### LSPosed version/LSPosed 版本

1.8.2

### Android version/Android 版本

11

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[verbose_2022-05-02T03_02_05.735.log.txt](https://github.com/LSPosed/LSPosed/files/8599584/verbose_2022-05-02T03_02_05.735.log.txt)

**Comment by yujincheng08** [comment]
是应用无法打开 libart.so 文件

https://github.com/LSPosed/LSPosed/blob/c5c81377a5495b663875d26d9950d95fa2c0a38c/core/src/main/jni/src/elf_util.cpp#L47

跟你说的没关系。

**Comment by youling257** [comment]
删掉zygisk里面的x86_64.so，把压缩包里面的x86的liblspd.so重命名成x86.so复制到zygisk里面吗，试了之后，magisk里面zygisk lsp模块已加载，但是打开lsp manager显示未安装

![Screenshot_20220502-030628](https://user-images.githubusercontent.com/16304724/166161582-8f0d350c-f145-40a7-aae4-03e8988671d6.png)

**Comment by vvb2060** [comment]
```
[ 2022-05-02T03:02:23.345        0:  3421:  3421 E/LSPosed         ] failed to open /android/apex/com.android.art/lib/libart.so
[ 2022-05-02T03:02:23.346        0:  3421:  3421 E/LSPosed         ] failed to open /android/apex/com.android.runtime/bin/linker
```
确认这两个文件是否存在

**Comment by yujincheng08** [comment]
安装问题已经修复。激活问题请另开 issue。

**Comment by aviraxp** [comment]
@youling257 艹
