### ISSUE TITLE
[Bug] LSPosed crashes on second launch

### ISSUE THREAD

**Issue by woeijiunn88** [LSPosed/LSPosed#1919]
### Steps to reproduce/复现步骤

1. Open LSPosed after boots, it can be opened.
2. Swipe the process away from recents, and open again, it will not open and receives crash. (It will not crash if you retain it in the recents)
3. Same behaviour as LSPosed APK.

### Expected behaviour/预期行为

Open LSPosed, as usual.

### Actual behaviour/实际行为

LSPosed crashed, after open once and swipe off from recents, LSPosed never can be open again, only reboot the device, and LSPosed can be open *once*, and repeats the issue mentioned above.

~~Not sure is ROM side problem (using Awaken OS), my device is in **May Security Patch**, no issue with **April Security Patch**.~~
Looks like ROM problem, don't have any issue on another ROM.

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
Advanced Charging Controller (ACC)
ANXCamera
Call Recorder - SKVALEX
JamesDSP Manager
NLSound
NotoCJK
Shamiko
Universal SafetyNet Fix
Zygisk - Enhanced mode for Storage Isolation
Zygisk - IFW Enhance
Zygisk - InternalBrowserRedirect
Zygisk - LSPosed
Zygisk - Sui

```

### LSPosed version/LSPosed 版本

1.8.3-6550-zygisk-debug

### Android version/Android 版本

12L

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Log file extracted from /data/lspd/log
从 /data/lspd/log 提出的 verbose log
[verbose.log](https://github.com/LSPosed/LSPosed/files/8633693/verbose.log)

First time can open -> Second time can't open log
第一次可打开 -> 第二次打不开 log
[1.log](https://github.com/LSPosed/LSPosed/files/8633720/1.log)

**Comment by wushidia** [comment]
same appears on my device
Xiaomi 9 Awakenos 2.7(Android12.1)
[Crash log](https://wushidi.lanzouf.com/iOxlZ04s69gj) 
[lsposed log]( https://wushidi.lanzouf.com/iFH5104s68kh) 
magisk version 
24.3
lsposed version 
1.8.3-6550-zygisk-debug

**Comment by yujincheng08** [comment]
Looks like the issue is from Awaken. Tested PixelOS 12L without any issue.

**Comment by woeijiunn88** [comment]
Yes same here,

**Comment by equinol** [comment]
I also have the same issue on Pixel 5, ProtonAOSP, using the latest Magisk 24.3 and Zygisk - LSPosed. I have tried all versions from1.8.3 down to 1.7.2 with the same issue. Initially the 1.7.2 was working but then same issue occurred. First launch works fine. As soon as the app is dismissed from recents, it cannot be opened again: "Shell keeps stopping." Hopefully there's a workaround soon.

**Comment by aviraxp** [comment]
https://github.com/ProtonAOSP/android_art/commit/97f28123e714aceb2de359812ea0c9d6b8a64cee

**Comment by vvb2060** [comment]
https://github.com/GrapheneOS/platform_art/pull/1

**Comment by drakulaboy** [comment]
hmm, i found out that only on android 12L is this issue, just tried latest zygisk version on 12 only and it's not crashing
