### ISSUE TITLE
[Bug] Phone stuck on black screen after uninstalling LSPosed from magisk manager.

### ISSUE THREAD

**Issue by maidmeow4** [LSPosed/LSPosed#1939]
### Steps to reproduce/复现步骤

1. Remove `Zygisk - LSPosed` from magisk manager
2. Reboot
3. 

### Expected behaviour/预期行为

Uninstalling should not impact the phone boot up.

### Actual behaviour/实际行为

Phone stuck on black screen after boot animation (not a boot loop)

### Xposed Module List/Xposed 模块列表

```shell
Gravtiybox P - 9.2.1
QXmodule - 2.11
TwiFucker - 1.2.1
Greenify - 4.7.5
HideMyApplist - 2.3.2
```

### Magisk Module List/Magisk 模块列表

```shell
Busybox NDK
Callrecorder axet
Smalipatcher
Greenify4Magisk
HideMyApplist
Systemless hosts
MagiskHidePropsConf
Nexusmedia
NotoCJKVF
xmlpak
Zygisk-Sui
Zygisk-ifw enhance
Shamiko
```

### LSPosed version/LSPosed 版本

 LSPosed-v1.8.3-6552-zygisk

### Android version/Android 版本

9

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Unable to provide log file, since my phone cannot startup properly. Or anyone knows how to collect logs in this situation, you can guide me.

**Comment by yujincheng08** [comment]
log catcher or adb log.

**Comment by yujincheng08** [comment]
BTW, HideMyApplist will cause bootloop if it cannot detect its Xposed counterpart.

**Comment by maidmeow4** [comment]
> BTW, HideMyApplist will cause bootloop if it cannot detect its Xposed counterpart.

Looks like this is the problem, after created a `disable` file for **HideMyApplist** magisk module inside TWRP, my phone is working again. So it's not a LSPosed issue.
_(Not a bootloop though)_
