### ISSUE TITLE
[Bug] diler dose not launch the manager in samsung devices

### ISSUE THREAD

**Issue by amk316** [LSPosed/LSPosed#1942]
### Steps to reproduce/复现步骤

typed *#*#5776733#*#* in samsung s20 phone diler and pressed call

### Expected behaviour/预期行为

launch lsposed manager

### Actual behaviour/实际行为

make a phone call
![Screenshot_20220515-075154_Call](https://user-images.githubusercontent.com/63453650/168457823-f3f1af5e-dbd9-4022-a96f-e562bf33e1ea.jpg)
 

### Xposed Module List/Xposed 模块列表

```shell
disable-flag_secure 2.0.0
```

### Magisk Module List/Magisk 模块列表

```shell
shamiko 0.5
universal safetynet fix 2.2.1
zygisk - lsposed 1.8.3
```

### LSPosed version/LSPosed 版本

6552

### Android version/Android 版本

12 (one ui 4.1)

### Magisk version/Magisk 版本

24410

### Riru version/Riru 版本

n/a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

![Screenshot_20220515-075154_Call](https://user-images.githubusercontent.com/63453650/168457926-64883284-85b4-4ef0-8ce9-18d1e1bf79f4.jpg)

**Comment by yujincheng08** [comment]
you shouldnt press call button...

**Comment by amk316** [comment]
Even without press call nothing happens 
![Screenshot_20220515-091603_Phone](https://user-images.githubusercontent.com/63453650/168459852-75c8ff36-5b73-460b-934e-cf303fa68e77.jpg)

**Comment by yujincheng08** [comment]
No log no fix.
