### ISSUE TITLE
[Bug] When hiding the bottom bar on the module page, the left slide "+" button overlaps with the bottom bar

### ISSUE THREAD

**Issue by efojug** [LSPosed/LSPosed#1945]
### Steps to reproduce/复现步骤

Switch to the module page, click up to hide the bottom bar, and then slide left to switch to security space
切换到模块页面，上划使底栏隐藏后左滑切换到security space

### Expected behaviour/预期行为

The "+" button should always be suspended above the bottom bar
加号按钮应始终悬浮于底栏上方

### Actual behaviour/实际行为

When hiding the bottom bar on the module page, the left slide "+" button overlaps with the bottom bar
在模块页面时隐藏底栏后左滑 加号按钮与底栏重叠

### Xposed Module List/Xposed 模块列表

```shell
none
```

### Magisk Module List/Magisk 模块列表

```shell
none
```

### LSPosed version/LSPosed 版本

6558

### Android version/Android 版本

12

### Magisk version/Magisk 版本

d3fe3a71(24312)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-05-16T13_15_49.756.zip](https://github.com/LSPosed/LSPosed/files/8697320/LSPosed_2022-05-16T13_15_49.756.zip)

**Comment by yujincheng08** [comment]
我们低栏不隐藏。

**Comment by efojug** [comment]
> 我们低栏不隐藏。

Latest actions

**Comment by yujincheng08** [comment]
那里谁都能跑，为什么去那里下载？不怕被 rm -rf？
