### ISSUE TITLE
[Bug] xposed_scope not work when app install later

### ISSUE THREAD

**Issue by fr0zenrain** [LSPosed/LSPosed#1952]
### Steps to reproduce/复现步骤

1.build a xposed module with 1000 package name in array.xml
2.enable installed xposed module and reboot the device
3.continuously install app later which in the scope list

### Expected behaviour/预期行为

xposed module should inject installing app process

### Actual behaviour/实际行为

xposed module not work

### Xposed Module List/Xposed 模块列表

```shell
only one module written by me
```

### Magisk Module List/Magisk 模块列表

```shell
movecert
riru
shamiko
```

### LSPosed version/LSPosed 版本

v1.8.2

### Android version/Android 版本

10

### Magisk version/Magisk 版本

24.1

### Riru version/Riru 版本

v26.1.4

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

i don't have any code log.i think  the newest version have same issue.if you don't want to resolve this problem, you can give the issue key point, i can have a try,or it have another method to resolve it.thanks!

**Comment by vvb2060** [comment]
expected behavior
