### ISSUE TITLE
希望增加一个屏蔽模块新版本提醒

### ISSUE THREAD

**Issue by FinaFina233** [LSPosed/LSPosed#1955]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

否

### Describe the solution you'd like/描述你想要的解决方案

为用户已安装的每一个模块增加一个忽略更新功能

### Additional context/其他信息

![IMG_20220523_014000](https://user-images.githubusercontent.com/52440333/169708292-a12e70cc-994c-4b9b-bc66-e2ff7353e602.jpg)

**Comment by yujincheng08** [comment]
又不是强制更新，而且也没有一键更新全部的功能，你自己忽视一下就行。
