### ISSUE TITLE
[Bug] elf_util.cpp mmap extra libart.so segement cause bangcle crash

### ISSUE THREAD

**Issue by pxb1988** [LSPosed/LSPosed#1956]
### Steps to reproduce/复现步骤

1. build lspatch
2. lspatch a apk
3. run the patched apk

### Expected behaviour/预期行为

app run normally

### Actual behaviour/实际行为

app crashed

### Xposed Module List/Xposed 模块列表

```shell
n/a
```

### Magisk Module List/Magisk 模块列表

```shell
n/a
```

### LSPosed version/LSPosed 版本

lspatch master / 38496aee2c0543583841d508, lsposed master / b36c170

### Android version/Android 版本

11

### Magisk version/Magisk 版本

n/a

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

n/a

### Patch

i have dig into the code of LsPosed, and found the `ElfImg` `mmap`ed an extra  segment.

i guess the segment cause bangcle mis detect the start address of libart.so.

here is my patch, it is not good, but works.

line 55 of elf_util.cpp
```patch
-    header = reinterpret_cast<decltype(header)>(mmap(nullptr, size, PROT_READ, MAP_SHARED, fd, 0));
+    void* a = mmap(nullptr, size, PROT_WRITE | PROT_READ, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0);
+    void* b = mmap(nullptr, size, PROT_READ, MAP_PRIVATE, fd, 0);
+    memcpy(a, b, size);
+    munmap(b, size);
+    // ok
+    header = reinterpret_cast<decltype(header)>(a);
```

**Comment by pxb1988** [comment]
i have dig into the code of LsPosed, and found the `ElfImg` `mmap`ed an extra  segment.

i guess the segment cause bangcle mis detect the start address of libart.so.

here is my patch, it is not good, but works.

line 55 of elf_util.cpp
```patch
-    header = reinterpret_cast<decltype(header)>(mmap(nullptr, size, PROT_READ, MAP_SHARED, fd, 0));
+    void* a = mmap(nullptr, size, PROT_WRITE | PROT_READ, MAP_PRIVATE | MAP_ANONYMOUS, 0, 0);
+    void* b = mmap(nullptr, size, PROT_READ, MAP_PRIVATE, fd, 0);
+    memcpy(a, b, size);
+    munmap(b, size);
+    // ok
+    header = reinterpret_cast<decltype(header)>(a);
```

**Comment by pxb1988** [comment]
@yujincheng08  i have update the comment.

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed/blob/cbd19d17a81e1c87c20cb6ee8d3231964b35e1b6/core/src/main/jni/src/elf_util.cpp#L223

it should be unmaped unconditionally
