### ISSUE TITLE
[Bug] SystemUI crash loop

### ISSUE THREAD

**Issue by ShiroBlank** [LSPosed/LSPosed#1962]
### Steps to reproduce/复现步骤

1. install cherishOS rom on phone (redmi note 8 pro global)
2. install lsposed
3. reboot

### Expected behaviour/预期行为

phone boots normally

### Actual behaviour/实际行为

SystemUI crash loop until forced into rescue party

### Xposed Module List/Xposed 模块列表

```shell
LuckyPatcher
```

### Magisk Module List/Magisk 模块列表

```shell
Shamiko
LSposed
safetynet-fix
huskydg_bootloopsaver
```

### LSPosed version/LSPosed 版本

version 1.8.3 (6562)

### Android version/Android 版本

Android 11

### Magisk version/Magisk 版本

Magisk 24.3(24300)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[verbose_2022-05-26T06:37:45.366.log](https://github.com/LSPosed/LSPosed/files/8776614/verbose_2022-05-26T06.37.45.366.log)

**Comment by yujincheng08** [comment]
Uninstall lucky patcher.
