### ISSUE TITLE
[Bug] 无法刷入新版Zygisk - LSPosed

### ISSUE THREAD

**Issue by GHS-Studio** [LSPosed/LSPosed#1966]
### Steps to reproduce/复现步骤

设备：
设备名
bullhead
产品名称/产品代号
AWM-A0
版本号
G66T2011030CN00MQ4
SDK版本
29		安卓 10.0（Q）
刷入显示

### Expected behaviour/预期行为

刷入成功

### Actual behaviour/实际行为

使用面具刷入后提示
[https://gulijiang.oss-cn-hongkong.aliyuncs.com/Screenshot_2022-05-28-17-45-53-274_com.topjohnwu.magisk.jpg](https://gulijiang.oss-cn-hongkong.aliyuncs.com/Screenshot_2022-05-28-17-45-53-274_com.topjohnwu.magisk.jpg) 

使用爱玩机工具箱刷入提示红色的
Archive: /data/local/cache/20220528094045/tempModule.zip
inflating: module.prop
Archive: /data/local/cache/20220528094045/tempModule.zip
inflating: customize.sh
Archive: /data/local/cache/20220528094045/tempModule.zip
inflating: verify.sh
Archive: /data/local/cache/20220528094045/tempModule.zip
creating: META-INF/com/google/android/
inflating: META-INF/com/google/android/update-binary.sha256
inflating: META-INF/com/google/android/update-binary
inflating: META-INF/com/google/android/updater-script.sha256
inflating: META-INF/com/google/android/updater-script
Archive: /data/local/cache/20220528094045/tempModule.zip
inflating: customize.sh
Archive: /data/local/cache/20220528094045/tempModule.zip
inflating: customize.sh.sha256
Archive: /data/local/cache/20220528094045/tempModule.zip
inflating: verify.sh
Archive: /data/local/cache/20220528094045/tempModule.zip
inflating: verify.sh.sha256
Archive: /data/local/cache/20220528094045/tempModule.zip
inflating: util_functions.sh
Archive: /data/local/cache/20220528094045/tempModule.zip
inflating: util_functions.sh.sha256

### Xposed Module List/Xposed 模块列表

```shell
模块包名
chili.xposed.chimi
模块包名
com.omarea.vtools
模块包名
com.ldq.connect
模块包名
com.modify.installer
模块包名
com.intent.get
模块包名
com.byyoung.miuisetting
模块包名
com.byyang.appmodify
模块包名
ru.bluecat.android.xposed.mods.appsettings
模块包名
com.ejiaogl.bdtiebahook
模块包名
com.sdasdsa.BankRX
模块包名
com.ketal.bcrfullscreen
模块包名
me.iacn.biliroaming
模块包名
com.conch.bluedhook
模块包名
com.mikutart.bettermiui
模块包名
com.mhook.alipay
模块包名
com.plus.dy
模块包名
org.strawing.customiuizermod
模块包名
com.kieronquinn.app.darq
模块包名
com.sky.xposed.rimet
模块包名
com.raincat.dolby_alpha
模块包名
com.raincat.dolby_beta
模块包名
com.mhook.dialog.beta
模块包名
com.mhook.dialog.fix
模块包名
mapp.rm
模块包名
com.fuckcoolapk
模块包名
github.zerorooot.fuckbilibilivote
模块包名
org.hello.coolapk
模块包名
com.inject.helper
模块包名
com.god.vip
模块包名
com.mx.vpnjc
模块包名
weare.godvip
模块包名
com.hentai.q
模块包名
com.coderstory.toolkit
模块包名
com.skyhand.redbookhelper
模块包名
nsr679.IDMPlus_TrackerHelper
模块包名
pub.chara.cwui.pretendsharing_xposed
模块包名
com.zer0.historyprice
模块包名
io.github.lsposed.disableflagsecure
模块包名
me.jsonet.jshook
模块包名
just.trust.me
模块包名
club.youppgd.adhook
模块包名
com.rockz.frimirootdetectionbypass
模块包名
com.yuk.fuckMiLinkService
模块包名
cn.lovesykun.miui_force_fps
模块包名
com.yuk.miuicamera
模块包名
com.yuk.miuihome
模块包名
com.yuk.mediaeditor
模块包名
android.xiaolan.ppxshare.tools
模块包名
io.github.qauxv
模块包名
fi.veetipaananen.android.disableflagsecure
模块包名
pansong291.xposed.quickenergy.qiufeng
模块包名
nil.nadph.qnotified
模块包名
cc.hicore.qtool
模块包名
com.hicore.qtool
模块包名
com.pl.universalcopy
模块包名
ss.colytitse.fuckdmzj
模块包名
com.yxer.compo.module
模块包名
zone.yusei.godvip
模块包名
me.simpleHook
模块包名
com.junge.algorithmAide
模块包名
cn.coderstory.miui.water
模块包名
io.github.tehcneko.nonoforwards
模块包名
indi.conastin.textmodify
模块包名
github.tornaco.android.thanos
模块包名
com.CloudHook.myhook
模块包名
com.demo.tl_ing
模块包名
com.example.tl_ing
模块包名
com.fankes.tsbattery
模块包名
com.blanke.diaomao163
模块包名
com.wxapp.moment
模块包名
com.fkzhang.wechatxposed
模块包名
com.hiwechart.translate
模块包名
liubaoyua.customtext
模块包名
com.jasperhale.myprivacy
模块包名
com.Xcc.vip
模块包名
com.xcsp.application
模块包名
com.pyler.xinstaller
模块包名
com.jozein.xedgepro
模块包名
com.flarejune.xposedblacklist
模块包名
com.github.tianma8023.xposed.smscode
模块包名
pansong291.xposed.quickenergy
模块包名
cn.kwaiching.hook
模块包名
com.tsng.hidemyapplist
模块包名
com.variable.apkhook
模块包名
com.android.z
```

### Magisk Module List/Magisk 模块列表

```shell
模块ID（唯一识别码）
riru_lsposed
模块ID（唯一识别码）
WorkSettingPro
模块ID（唯一识别码）
hidemyapplist
模块ID（唯一识别码）
zjtkc
模块ID（唯一识别码）
theme_patch
模块ID（唯一识别码）
NLSound
模块ID（唯一识别码）
FuckQQWechat
模块ID（唯一识别码）
riru-core
模块ID（唯一识别码）
riru_dreamland
模块ID（唯一识别码）
riru_hidemyapplist
模块ID（唯一识别码）
scene_swap_controller
模块ID（唯一识别码）
RescueBrick
```

### LSPosed version/LSPosed 版本

1.7.2

### Android version/Android 版本

10

### Magisk version/Magisk 版本

24.3

### Riru version/Riru 版本

26.1.6

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

log：

**Comment by GHS-Studio** [comment]
log：https://gulijiang.oss-cn-hongkong.aliyuncs.com/magisk_log_2022-05-28T18%3A15%3A39.log

**Comment by kuohuanhuan** [comment]
看起來像是 Zygisk 跟 Riru 相衝？
Riru 刪了然後啟用 Zygisk（設定 -> Magisk -> Zgisk，重啟）試試
