### ISSUE TITLE
[Bug] LSPosed not installed

### ISSUE THREAD

**Issue by yunyu950908** [LSPosed/LSPosed#1981]
### Steps to reproduce/复现步骤

Install magisk v25.0
Enable Zygisk 
Install Zygisk - LSPosed v1.8.3
reboot
start  LSPosed manger

### Expected behaviour/预期行为

LSPosed  manger should work fine

### Actual behaviour/实际行为

LSPosed shows not installed and tap to install 

### Xposed Module List/Xposed 模块列表

```shell
none
```

### Magisk Module List/Magisk 模块列表

```shell
shamiko
Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

1.8.3

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.0

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[bugreport-aosp_vangogh-SP2A.220505.002-2022-06-09-13-59-41.zip](https://github.com/LSPosed/LSPosed/files/8867328/bugreport-aosp_vangogh-SP2A.220505.002-2022-06-09-13-59-41.zip)
[magisk_log_2022-06-09T13.52.48.log](https://github.com/LSPosed/LSPosed/files/8867356/magisk_log_2022-06-09T13.52.48.log)
![Screenshot_20220609-134646_Settings](https://user-images.githubusercontent.com/25625252/172776337-8b0c5c58-e934-4938-9c78-063ad204b1e9.png)
![Screenshot_20220609-134724_Settings](https://user-images.githubusercontent.com/25625252/172776350-c6a306ff-1b1a-4abc-b953-0c4d530a4d73.png)
![Screenshot_20220609-140821_LSPosed](https://user-images.githubusercontent.com/25625252/172776737-5b17f34c-7831-4fb5-a513-053aa2a44a13.png)

**Comment by yujincheng08** [comment]
No log no fix 😄

**Comment by LucasBS1** [comment]
Why is this thing closed if the problem remains ?

**Comment by yujincheng08** [comment]
> Why is this thing closed if the problem remains ?

because its fixed

**Comment by Stillhard** [comment]
> Why is this thing closed if the problem remains ?

Try [this artifact](https://github.com/LSPosed/LSPosed/actions/runs/2466592981#artifacts)
