### ISSUE TITLE
[Bug] Constant Crashes

### ISSUE THREAD

**Issue by JeffKineiDOGE** [LSPosed/LSPosed#1987]
### Steps to reproduce/复现步骤

Open Manager, close via recent tasks, open again.

### Expected behaviour/预期行为

Open manager on main tab.

### Actual behaviour/实际行为

App chrashes.

### Xposed Module List/Xposed 模块列表

```shell
AnyWebView;
CameraControl;
Lucky Patcher;
PrivacySpace;
VCAM;
```

### Magisk Module List/Magisk 模块列表

```shell
Magisk Bootloop Protector;
Shamiko;
System Apps (Lucky Patcher Module);
Universal SafetyNet Fix;
Zygisk - LSPosed;
```

### LSPosed version/LSPosed 版本

1.8.3 (6552)

### Android version/Android 版本

12L

### Magisk version/Magisk 版本

25.0 (25000)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-06-11T23_30_42.331.zip](https://github.com/LSPosed/LSPosed/files/8885096/LSPosed_2022-06-11T23_30_42.331.zip)
[LSPosed_2022-06-11T23_30_34.109.zip](https://github.com/LSPosed/LSPosed/files/8885097/LSPosed_2022-06-11T23_30_34.109.zip)

**Comment by yujincheng08** [comment]
Duplicate of #1919
