### ISSUE TITLE
[Bug] LSPosed breaks Universal Safetynet Fix by kdrag0n

### ISSUE THREAD

**Issue by luciph0r** [LSPosed/LSPosed#1998]
### Steps to reproduce/复现步骤

1) Install Universal Safetynet Fix by kdrag0n.
2) Run YASNAC. Safetynet attestation passes.
3) Install LSPosed, reboot.
4) Run YASNAC. Safetynet attestation fails. 

### Expected behaviour/预期行为

It shouldn't break the safetynet fix.

### Actual behaviour/实际行为

Device can only pass Safetynet with LSPosed disabled.

### Xposed Module List/Xposed 模块列表

```shell
Adblocker Reborn
Disable FLAG-SECURE
Hide USB debug mode
MinMinGuard
NekoSMS
Scoop
Statusbar download progress
XPrivacyLua
```

### Magisk Module List/Magisk 模块列表

```shell
Busybox for Android NDK
F-Droid privileged extension
Systemless hosts
Universal Safetynet fix (2.2.1)
Zygisk-LSPosed
```

### LSPosed version/LSPosed 版本

1.8.3

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed Magisk log.zip](https://github.com/LSPosed/LSPosed/files/8945544/LSPosed.Magisk.log.zip)

**Comment by luciph0r** [comment]
What is 'not planned' supposed to mean? You don't care about incompatibility with Safetynet?

**Comment by yujincheng08** [comment]
You don't read the report guide carefully so this issue is invalid and closed silently. Lock because of off-topic.
