### ISSUE TITLE
[BUG] Can't get the selinux status correctly?

### ISSUE THREAD

**Issue by lshilshi** [LSPosed/LSPosed#200]
**版本信息/Versions**

Android: H2OS 9.5.9 (Pie)

Magisk: 22.0

Riru:23.6

LSPosed:0.5.4.1

Prompt on the main manager interface："SELinux is not enforcing".

At the same time, I use getenforce to see SELinux state is enforcing in the shell.
Also he value of \sys\fs\selinux\enforce is 1.

How?

**Comment by yujincheng08** [comment]
We get the value of `/sys/fs/selinux/enforce when zygote is started. We only care about zygote's cache of the status of selinux.
