### ISSUE TITLE
[Feature Request] Hope to add a soft restoration function

### ISSUE THREAD

**Issue by k650dg4d2** [LSPosed/LSPosed#2007]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Because some modules are changged about system。then i have to reboot the system。or i can soft restart，It's getting faster。

### Describe the solution you'd like/描述你想要的解决方案

Can be added on the homepage。

**Comment by yujincheng08** [comment]
use magisk app.

**Comment by k650dg4d2** [comment]
> 

但是magisk好像没有软重启吧

**Comment by k650dg4d2** [comment]
> ![Screenshot_2022-06-24-20-00-02-921_lz.igzsz.brb.jpg](https://user-images.githubusercontent.com/5022927/175529962-3db1a648-6910-45f6-893d-bbef7b7f6119.jpg)
> 
> 我信了

我的magisk的问题，这玩意居然还不一样，我找找magisk的原因吧😂
![QQ图片20220624200120](https://user-images.githubusercontent.com/32454224/175530396-24ad1173-887a-4f01-9276-d83d073720b9.jpg)
