### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Austcool-Walker** [LSPosed/LSPosed#2013]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

I want to directly bake this into my system partition as a flashable zip.

### Describe the solution you'd like/描述你想要的解决方案

So if it can be installed directly into my devices ROM can you share with me how to do this?

### Additional context/其他信息

Yes I understand that this can break safety net. I am ok with this.

**Comment by Howard20181** [comment]
https://github.com/LSPosed/LSPosed/discussions/1935
