### ISSUE TITLE
[Bug] Cannot hook `com.hfbank.mobile`

### ISSUE THREAD

**Issue by Ninlives** [LSPosed/LSPosed#2019]
### Steps to reproduce/复现步骤

1. Build a xposed module with following code:
```java
    public void handleLoadPackage(XC_LoadPackage.LoadPackageParam lpparam) throws Throwable {
        int commaIndex = lpparam.processName.indexOf(':');
        String processname = commaIndex > 0 ? lpparam.processName.substring(0, commaIndex) : lpparam.processName;
        String packagename = lpparam.packageName;
        log(String.format("Package Name: %s, Process Name: %s", packagename, processname));
    }
```

2. Install the module, add `com.hfbank.mobile` to scope.
3. Open `com.hfbank.mobile`.

### Expected behaviour/预期行为

Should be able to see a few lines like `Package Name: com.hfbank.mobile, Process Name: com.hfbank.mobile` in the log.

### Actual behaviour/实际行为

The module is loaded according to the log, but no extra logs are printed.

### Xposed Module List/Xposed 模块列表

```shell
- CorePatch
- The module described above.
```

### Magisk Module List/Magisk 模块列表

```shell
- Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

v1.8.3 (6581)

### Android version/Android 版本

Android 12 / MIUI 13.0.4

### Magisk version/Magisk 版本

69978a94 (25101)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-07-04T03_02_18.787.zip](https://github.com/LSPosed/LSPosed/files/9035359/LSPosed_2022-07-04T03_02_18.787.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036184/LSPosed-v1.8.3-6580-zygisk-debug.zip)
plz get log using this ver

**Comment by Ninlives** [comment]
> [LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036184/LSPosed-v1.8.3-6580-zygisk-debug.zip) plz get log using this ver
[log.zip](https://github.com/LSPosed/LSPosed/files/9036240/log.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036384/LSPosed-v1.8.3-6580-zygisk-debug.zip)

again get the log

**Comment by Ninlives** [comment]
> [LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036384/LSPosed-v1.8.3-6580-zygisk-debug.zip)
> 
> again get the log

[LSPosed_2022-07-04T12_48_33.377.zip](https://github.com/LSPosed/LSPosed/files/9036425/LSPosed_2022-07-04T12_48_33.377.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036464/LSPosed-v1.8.3-6580-zygisk-debug.zip)

**Comment by Ninlives** [comment]
> [LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036464/LSPosed-v1.8.3-6580-zygisk-debug.zip)

[LSPosed_2022-07-04T13_07_45.264.zip](https://github.com/LSPosed/LSPosed/files/9036476/LSPosed_2022-07-04T13_07_45.264.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036516/LSPosed-v1.8.3-6580-zygisk-debug.zip)

**Comment by Ninlives** [comment]
> [LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036516/LSPosed-v1.8.3-6580-zygisk-debug.zip)

[LSPosed_2022-07-04T13_19_45.488.zip](https://github.com/LSPosed/LSPosed/files/9036534/LSPosed_2022-07-04T13_19_45.488.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036548/LSPosed-v1.8.3-6580-zygisk-debug.zip)

**Comment by Ninlives** [comment]
> [LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036548/LSPosed-v1.8.3-6580-zygisk-debug.zip)

LSPosed not activated using this version.l

**Comment by yujincheng08** [comment]
log

**Comment by Ninlives** [comment]
![Screenshot_2022-07-04-13-38-39-264_com android shell](https://user-images.githubusercontent.com/17873203/177088438-6d9274f2-05e8-43b0-8258-eea686284768.jpg)
Magisk log: 
[magisk_log_2022-07-04T13.38.56.log](https://github.com/LSPosed/LSPosed/files/9036625/magisk_log_2022-07-04T13.38.56.log)

**Comment by yujincheng08** [comment]
[LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036628/LSPosed-v1.8.3-6580-zygisk-debug.zip)

**Comment by Ninlives** [comment]
> [LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036628/LSPosed-v1.8.3-6580-zygisk-debug.zip)

[LSPosed_2022-07-04T13_45_54.417.zip](https://github.com/LSPosed/LSPosed/files/9036648/LSPosed_2022-07-04T13_45_54.417.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036869/LSPosed-v1.8.3-6580-zygisk-debug.zip)
Your prev log shows no module's hooking that app. Plz ensure you tick it in the scope in your module.

**Comment by Ninlives** [comment]
> [LSPosed-v1.8.3-6580-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9036869/LSPosed-v1.8.3-6580-zygisk-debug.zip) Your prev log shows no module's hooking that app. Plz ensure you tick it in the scope in your module.

Seems it finally worked: 
[LSPosed_2022-07-04T14_37_18.054.zip](https://github.com/LSPosed/LSPosed/files/9036920/LSPosed_2022-07-04T14_37_18.054.zip)

**Comment by yujincheng08** [comment]
Try to use `Log.e` instead. This app adjust the log level.

**Comment by yujincheng08** [comment]
Let's clarify the thing:
This app has a customized `AppComponentFactory` which disables the log. LSPosed calls `handlePackageLoad` after `LoadedApk.getClassloader`, where `AppComponentFactory` initializes the app classloader. So before `handlePackageLoad`, the app has done something (like disabling the log) before the first call of `handlePackageLoad`. You can hook `AppComponentFactory` in `initZygote` by hooking `LoadedApk.createAppFactory`. But this may not work since we cannot hook `clint`, which I assume the code disabling the log is. But anyway, you can prevent the app from disabling the log in `initZygote`.

**Comment by Ninlives** [comment]
Got it, thanks so much!

**Comment by Howard20181** [comment]
Please submit a new issue.
