### ISSUE TITLE
像Xposed一样直接安装并且使用

### ISSUE THREAD

**Issue by MochinYuu** [LSPosed/LSPosed#2029]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

我的手机是vivoy52s，使用修改版magisk才能有root权限，但是不能使用模块和zygisk功能
![Screenshot_20220710_192253](https://user-images.githubusercontent.com/106824861/178146225-0b199807-69f4-42fa-8f3b-ee601246caba.jpg)

### Describe the solution you'd like/描述你想要的解决方案

将lsposed制作一个像Xposed一样不用magisk模块挂载，直接安装的版本

**Comment by MochinYuu** [comment]
thankyou！

**Comment by yujincheng08** [comment]
我们不需要 magisk 挂载啊

**Comment by yujincheng08** [comment]
我们需要的是一个 permissive selinux context （目前写死了 magisk 和 magisk_file），然后注入 zygote。

https://github.com/LSPosed/LSPosed/tree/master/magisk-loader 这个只是一个基于 magisk 的封装，你完全可以根据自己的注入方式进行封装。

我们不打算自行实现「注入 zygote」，所以有这个特殊需求的人需要自行写一个 loader。
