### ISSUE TITLE
[Feature Request] 让模块作用范围显示自身

### ISSUE THREAD

**Issue by dttzyjw0012** [LSPosed/LSPosed#2035]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

安装模块后作用范围不显示自身，在6552版本上，对arm riru , x86 riru, x86 zygisk三个版本安装多个模块均测试过，每个模块作用范围都不会显示自身，但是会显示其他模块

### Describe the solution you'd like/描述你想要的解决方案

允许每个模块作用范围显示模块自身

### Additional context/其他信息

无

**Comment by yujincheng08** [comment]
没意义

**Comment by Howard20181** [comment]
只要模块激活且作用域内有其他应用，自身就会在作用域内
不需要显示出来再选
