### ISSUE TITLE
[Bug] lsposed 1.83 cause phone to freeze and reboot

### ISSUE THREAD

**Issue by frankli998** [LSPosed/LSPosed#2044]
### Steps to reproduce/复现步骤

same issue here https://github.com/LSPosed/LSPosed/discussions/1997
I don't know how to reproduce, it happens randomly.

### Expected behaviour/预期行为

don't freeze and reboot

### Actual behaviour/实际行为

freeze and reboot

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
Shamiko
Log Catcher
Zygisk-LSPOSED
```

### LSPosed version/LSPosed 版本

1.83(6577) 1.83(6552)

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.1/25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

If do not meet requirements, please feed back. I will catch log again
[boot-2022-07-22-15-29-25 (2).log](https://github.com/LSPosed/LSPosed/files/9165730/boot-2022-07-22-15-29-25.2.log)

**Comment by yujincheng08** [comment]
> Xposed Module List/Xposed 模块列表
N/A

???

**Comment by frankli998** [comment]
> > Xposed Module List/Xposed 模块列表
> > N/A
> 
> ???

for the time I catched log, those lsposed modules were on. But same freeze problem happens when I turn off all those modules and only leaves lspoed core on

**Comment by yujincheng08** [comment]
Most likely because of knox. Nothing we can help.

**Comment by frankli998** [comment]
1.8.0 works quite stable for me. Guess I will have to stick with 1.8.0.
