### ISSUE TITLE
Option to remove prompt for Parastic Shortcut on each boot

### ISSUE THREAD

**Issue by bengalih** [LSPosed/LSPosed#2048]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

On every boot, LSposed is asking to create a shortcut for Parasitic.  This is a modal request and you cannot proceed until answering this request.

When using Parasitic option, the default behavior is to have app create a shortcut on desktop.

Not every user wants an icon to this shown on their desktop.  Even when using custom launchers like Nova, there is an inability to remove/hide it from the desktop.

There are other ways to launch LSposed including dialer and shell intents as detailed here:
https://github.com/LSPosed/LSPosed/issues/1620

### Describe the solution you'd like/描述你想要的解决方案

There is a benefit of requesting the creation of the shortcut on each boot if it is not detected for the average user who may have deleted their shortcut.  However the installation of LSposed is already very clear on how to configure Parasitic and where to reinstall the apk from if there is an issue.

It would be nice to remove or to create a toggle option to prevent the request to always create a shortcut for those users who do not want it.

### Additional context/其他信息

Personally, I have created a Tasker app package with the intent to launch LSposed in order to have a shortcut that I can place anywhere within my launcher and not have to have it on my main screen.

**Comment by yujincheng08** [comment]
there is one.

**Comment by bengalih** [comment]
> there is one.

Can you explain where there is?

I only see an option in the Settings called "Create Shortcut" which will allow you to create a shortcut if it does not exist.

I do not see any option to DISABLE the creation of the shortcut on every launch.

thank you.

**Comment by Howard20181** [comment]
> Can you explain where there is?

Install manager from `/data/adb/lspd/manager.apk` then you find an option to disable automatically create shortcut.

**Comment by bengalih** [comment]
> > Can you explain where there is?
> 
> Install manager from `/data/adb/lspd/manager.apk` then you find an option to disable automatically create shortcut.

Thank you, that does appear to have fixed the issue.
I was unaware that there were different menu options in the apk and the Parasitic manager as they looked identical to me. 
The verbiage of the setting was also not very clear.

Steps:
1) Install manager.apk
2) Go to Settings
3) De-select "Automatically add a shortcut"
4) (optional) uninstall Manager.apk
5) Reboot and observe no prompt to create shortcut.
