### ISSUE TITLE
[Bug] Can't active local modules.

### ISSUE THREAD

**Issue by zlwen** [LSPosed/LSPosed#2051]
### Steps to reproduce/复现步骤

1. install local module apk
2. in LSPosed modules tab, I can't active the local module. Modules download from remote can be active normally.

### Expected behaviour/预期行为

Local modules should be active normally.

### Actual behaviour/实际行为

Local modules can't be active.

### Xposed Module List/Xposed 模块列表

```shell
Mi Water (remote module)
WKit (my local module)
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

1.8.3

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-07-23T15_21_07.218.zip](https://github.com/LSPosed/LSPosed/files/9180421/LSPosed_2022-07-23T15_21_07.218.zip)

My test local module manifest is 
```xml
<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="me.zlwen.wkit">

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/Theme.WKit">
        <activity android:name=".MainActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />

                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

        <meta-data
            android:name="xposedmodule"
            android:value="true" />

        <meta-data
            android:name="xposeddescription"
            android:value="WKit" />

        <meta-data
            android:name="xposedminversion"
            android:value="93" />

        <meta-data
            android:name="xposedscope"
            android:resource="@array/scope" />
    </application>

</manifest>
```
as below screencap shows, Mi Water module is remote module, i can active it. Wkit is my local module, when i click the "Enable module" switch, no effect happens.
![image](https://user-images.githubusercontent.com/5309014/180760872-f21d6375-104f-41d6-8330-555288a86492.png)

I also debug the code, it seems this binder invoke return false causes the problem.
![image](https://user-images.githubusercontent.com/5309014/180760781-8c9f74ea-50c7-424e-a938-b9dbaac212a3.png)

**Comment by yujincheng08** [comment]
Cannot see your apk.

**Comment by yujincheng08** [comment]
And you disabled the log:
> Logd maybe crashed (err=No such file or directory), retrying in 1s...

Thus , we cannot see useful log.

**Comment by zlwen** [comment]
> 

I haven't manually disabled the log, so is the log's problem? but the remote module works normally.

**Comment by Dr-TSNG** [comment]
Forget xposed_init?

**Comment by yujincheng08** [comment]
> Forget xposed_init?

Yes.

**Comment by zlwen** [comment]
@Dr-TSNG Yes! i forget it. Thank for all of you.
