### ISSUE TITLE
[Bug] `handleLayoutInflated` doesn't run

### ISSUE THREAD

**Issue by Krafi2** [LSPosed/LSPosed#2052]
### Steps to reproduce/复现步骤

Load a module with this code:
``` java
public class Module implements IXposedHookInitPackageResources {
    @Override
    public void handleInitPackageResources(InitPackageResourcesParam resparam) throws Throwable {
        if (!resparam.packageName.equals("com.android.systemui"))
            return;
 
        resparam.res.hookLayout("com.android.systemui", "layout", "status_bar", new XC_LayoutInflated() {
            @Override
            public void handleLayoutInflated(LayoutInflatedParam liparam) throws Throwable {
                XposedBridge.log("Hello from hook");
            }
        });
    }
}
```

### Expected behaviour/预期行为

The `handleLayoutInflated` hook should run and print `"Hello from hook"` to the log.

### Actual behaviour/实际行为

The hook doesn't run and doesn't log `"Hello from hook"`.

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
MagiskHide Props Config
Universal SafetyNet Fix
Zygisk - LSPosed
A custom module modifying volume curves
```

### LSPosed version/LSPosed 版本

6591

### Android version/Android 版本

12.1

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_log.zip](https://github.com/LSPosed/LSPosed/files/9189505/LSPosed_log.zip)

**Comment by xxr0ss** [comment]
Similar issue, `handleInitPackageResources()` not called at all.

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/189511550-33967639-ec3f-47bb-bdb5-a13203b976da.png)
Cannot reproduce on Android 13.

Please grab log using this ver: 
[LSPosed-v1.8.3-6600-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/9541733/LSPosed-v1.8.3-6600-zygisk-debug.zip)
