### ISSUE TITLE
[FR] Optimize all apps

### ISSUE THREAD

**Issue by OrbitronX** [LSPosed/LSPosed#206]
**Detail**:
I miss the "Optimize all apps with Dexopt" and "Optimize all apps with Dex2Oat (Speed mode)".
Will that be added to the manager?
Thanks

**Comment by yujincheng08** [comment]
Don't do that. This is SLOW and unnecessary

**Comment by kotori2** [comment]
Android will do that automatically in the background. 
This feature will only be necessary if hooks fails on any short method which was inline-compiled before LSPosed installed.
