### ISSUE TITLE
[Feature Request] Add developer mode

### ISSUE THREAD

**Issue by heqyoufree** [LSPosed/LSPosed#2063]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

When an Xposed module is installed as test package (using ```adb install -t```, Android Studio does this) and Developer Mode is enabled, apps in the recommended scope can be automatically force stop. And if only one app is presented in the recommended scope, maybe we can start the app automatically. I think this should be another option under the developer mode.

**Comment by vvb2060** [comment]
https://github.com/yujincheng08/BiliRoaming/blob/254f17a197c2e7725558543b5ac33fab6c502466/app/build.gradle.kts#L277-L287

**Comment by vvb2060** [comment]
We do not recommend using Android Studio run, use gradle installDebug instead. https://github.com/yujincheng08/BiliRoaming/blob/254f17a197c2e7725558543b5ac33fab6c502466/app/build.gradle.kts#L308-L317
