### ISSUE TITLE
[Bug] Broadcast to manager failed

### ISSUE THREAD

**Issue by What-Zit-Tooya** [LSPosed/LSPosed#2064]
### Steps to reproduce/复现步骤

1. Flash LSPosed from magisk manager
2. Reboot phone
3. Read logs

### Expected behaviour/预期行为

No error occured

### Actual behaviour/实际行为

There are error logs `Broadcast to manager failed`

### Xposed Module List/Xposed 模块列表

```shell
Hidemyapplist v3.0.0.r305.50a6fe2
Instaprefs v2.0
Killergram v22.0312
TwiFucker v1.4
XPrivacyLua v1.32
```

### Magisk Module List/Magisk 模块列表

```shell
Shamiko v0.5.2 (120)
Universal SafetyNet Fix v2.3.1
Unofficial ReVanced Build v17.29.34
Unooficial YouTube Music ReVanced Build v5.16.51
Zygisk - LSPosed v1.8.3 (6593) Debug version
```

### LSPosed version/LSPosed 版本

Zygisk - LSPosed v1.8.3 (6593) Debug version

### Android version/Android 版本

CrDroid 8.7 (A12L)

### Magisk version/Magisk 版本

25.2 Stable

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[verbose.log](https://github.com/LSPosed/LSPosed/files/9281905/verbose.log)

**Comment by yujincheng08** [comment]
send `/system/framework.jar`

**Comment by yujincheng08** [comment]
https://cs.android.com/android/_/android/platform/frameworks/base/+/a3bf26d6bc71d61566eabb842b6f420c3d5fcfb6

**Comment by yujincheng08** [comment]
Try #2065
