### ISSUE TITLE
[Bug] I can't find the APK file of the manager

### ISSUE THREAD

**Issue by colinxu2020** [LSPosed/LSPosed#2069]
### Steps to reproduce/复现步骤

1. Open WindowsSubsystemForAndroid
2. Install MagiskOnWSA(magisk pico) on WSA
3. Enable zygisk
4. Install LSPosed

### Expected behaviour/预期行为

APK is generated

### Actual behaviour/实际行为

I can't find the APK file

### Xposed Module List/Xposed 模块列表

```shell
(empty)
```

### Magisk Module List/Magisk 模块列表

```shell
LSPosed
```

### LSPosed version/LSPosed 版本

1.8.3-6596

### Android version/Android 版本

12.1

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2022-08-12T08.34.59.log](https://github.com/LSPosed/LSPosed/files/9312948/magisk_log_2022-08-12T08.34.59.log)

**Comment by Howard20181** [comment]
Do you mean the shortcut? On WSA you cannot use shortcuts. You should manually install the manager from `/data/adb/lspd/manager.apk`.
