### ISSUE TITLE
[Bug] Lsposed manager crashes 'shell' on reopen

### ISSUE THREAD

**Issue by sd369888** [LSPosed/LSPosed#2074]
### Steps to reproduce/复现步骤

##详细信息我就写中文了
1.打开桌面的寄生管理器
2.在最近任务里面关闭管理器
3.再次点击寄生管理器快捷方式/使用拨号盘暗码进入

### Expected behaviour/预期行为

LSPosed管理器正常打开

### Actual behaviour/实际行为

点了也没有反应
多点几下提示shell停止运行

### Xposed Module List/Xposed 模块列表

```shell
哔哩漫游
非残
deepsleep
微x模块
隐藏应用列表
qauxiliary
qq瘦身
tsbattery
xprivacylua
```

### Magisk Module List/Magisk 模块列表

```shell
Automatic_brick_rescue  hidemyapplist
Viper4Android           
mtk-wifi-bonding
WorkSettingPro          zygisk_lsposed
bootloop_save_key       zygisk_shamiko
doze_gms
```

### LSPosed version/LSPosed 版本

6552

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

     
[bugreport-dandelion_cn-SQ3A.220605.009.B1-2022-08-14-18-23-18.zip](https://github.com/LSPosed/LSPosed/files/9333186/bugreport-dandelion_cn-SQ3A.220605.009.B1-2022-08-14-18-23-18.zip)

**Comment by yujincheng08** [comment]
duplicate of #1919

**Comment by sd369888** [comment]
So is it normal to have the standalone installed lsposed manager crashing too?

**Comment by yujincheng08** [comment]
Y

**Comment by LeeBinder** [comment]
see [here](https://github.com/orgs/LSPosed/discussions/2602) for a possible work-around - it solved this issue for me.
