### ISSUE TITLE
Magisk not running module scripts, random incomplete copy of busybox on WSA

### ISSUE THREAD

**Issue by alexwilson1** [LSPosed/LSPosed#2081]
### Steps to reproduce/复现步骤

- Install WSA with Magisk (WSA-with-magisk-GApps-pico_x64, WSA_VER=2206.40000.15.0, WSA_MAIN_VER=2206)
- Enable Zygisk
- Reboot
- Install lsposed
- Reboot
- Install lsposed manager using shell apk method
- Open lsposed manager, it works
- Restart WSA/terminate process
- Open lsposed manager
- 'lsposed is not found' (sometimes it works, sometimes it doesn't)
![image](https://user-images.githubusercontent.com/25535957/185045066-07dcc05b-228a-4062-bf02-34aa99fb4f84.png)
![image](https://user-images.githubusercontent.com/25535957/185045529-01f42fc8-94f4-4c39-90d2-ab8be9e4fc61.png)

### Expected behaviour/预期行为

LSPosed should be running all the time and LSPosed Manager should detect the installation

### Actual behaviour/实际行为

When rebooting WSA, LSPosed manager often does not detect LSPosed. I have tried many other versions (including riru versions) and they all exhibit the same behavior. I have also tried different installations of Windows 11.

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk - lsposed
```

### LSPosed version/LSPosed 版本

LSPosed-v1.8.3-6597-zygisk-debug

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25201

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2022-08-16T22.44.20.log](https://github.com/LSPosed/LSPosed/files/9356715/magisk_log_2022-08-16T22.44.20.log)

**Comment by Howard20181** [comment]
Maybe it's a WSA problem, restarting after an inactive hang will not execute the `post-fs-date` and `server.d` scripts, using the restart in Magisk can solve this problem.

**Comment by alexwilson1** [comment]
I just tried this (magisk, reboot menu, reboot) and it did not work (from my experience, it randomly works this way).

Is there any more reliable method to get it started again please?

Thanks!

**Comment by Howard20181** [comment]
I also encountered this problem, no solution, maybe it would be better to set the subsystem resources to continuous and shut down manually when WSA is not in use.

**Comment by alexwilson1** [comment]
Just did a soft reboot from magisk and lsposed is detected again (for now)... very strange. 

I'm trying to figure out a way to get lsposed started in the event of an unexpected shutdown (this is for a server process). Please can you elaborate on what you mean by shut down manually?

**Comment by Howard20181** [comment]
Manually shutdown WSA in the subsystem settings page does not cause this problem.

**Comment by alexwilson1** [comment]
Just recreated the issue and soft rebooted - it didn't fix it this time, so it seems.intermittent.

Would there be a way to manually execute the `post-fs-date` and `server.d` scripts with shell or ADB?

**Comment by alexwilson1** [comment]
> Manually shutdown WSA in the subsystem settings page does not cause this problem.

I just experienced the issue when shutting down WSA properly with the mentioned page... 

1. LSPosed is working
2. Manually shut down WSA with subsystem settings page
3. Open LSPosed manager
4. 'LSPosed not installed' message shown

**Comment by Howard20181** [comment]
> from the logs it looks like the scripts are being run

But in fact it is not executed, I put a script to set the animation time in developer setting and proxy address for each boot, if LSPosed is not recognized at the same time the proxy settings are not executed.

**Comment by alexwilson1** [comment]
1. Turn off WSA using WSA settings
2. PowerShell command `PS C:\Users\xxx\Downloads\platform-tools_r33.0.2-windows\platform-tools> ./adb wait-for-device shell su -c cat /proc/kmsg > "kmsg.log"`
3. Open LSPosed app
4. WSA turns on
5. LSPosed shows 'not installed'
6. Open Magisk
7. Ctrl+C in PowerShell to stop logging
8. Upload log
9. [kmsg.log](https://github.com/LSPosed/LSPosed/files/9365882/kmsg.log)

**Comment by Howard20181** [comment]
The reasons we now know are:
Error while Magisk copying `busybox` from `/data/adb/magisk/busybox` to `$(magisk --path)/.magisk/busybox/busybox`, the copy is incomplete, causing the post-fs-data.d and service.d scripts to not execute

More specifically:
Get an incorrect file size when calling `getattr`.https://github.com/topjohnwu/Magisk/blob/4d9b7e711424f0df0a2f2e117468bd40546a287f/native/src/base/files.cpp#L146
![image](https://user-images.githubusercontent.com/40033067/185412449-29ec84d0-c373-4f8d-8357-943f87216ba1.png)

You can download the Debug version of Magisk with extra logs from [the link](https://github.com/Howard20181/Magisk/actions/runs/2881864498), put it in the `download` folder of [MagiskOnWSA](https://github.com/LSPosed/MagiskOnWSALocal) and rename it to `magisk.zip` to install it.

**Comment by alexwilson1** [comment]
> The reasons we now know are: Error while Magisk copying `busybox` from `/data/adb/magisk/busybox` to `$(magisk --path)/.magisk/busybox/busybox`, the copy is incomplete, causing the post-fs-data.d and service.d scripts to not execute
> 
> More specifically: Get an incorrect file size when calling `getattr`.https://github.com/topjohnwu/Magisk/blob/4d9b7e711424f0df0a2f2e117468bd40546a287f/native/src/base/files.cpp#L146 ![image](https://user-images.githubusercontent.com/40033067/185412449-29ec84d0-c373-4f8d-8357-943f87216ba1.png) ![image](https://user-images.githubusercontent.com/40033067/185413999-e3682dca-9384-4fb9-9e91-6615e46c790f.png)
> 
> You can download the Debug version of Magisk with extra logs from [this link](https://github.com/Howard20181/Magisk/actions/runs/2881864498), put it in the `download` folder of [MagiskOnWSA](https://github.com/LSPosed/MagiskOnWSALocal) and rename it to `magisk.zip` to install it.

Thanks for the reply. Couple of questions:

1. Rename `fc58f5ddc517a18589b6df436299c1df069eb336.zip` to `magisk.zip`? Or rename `app-debug.apk` to `magisk.zip`?
2. After this is done and installed, you want the magisk logs, correct? Or the kmsg logs?

**Comment by Howard20181** [comment]
Rename `app-debug.apk` to `magisk.zip`
Magisk logs

**Comment by alexwilson1** [comment]
1. Started run.sh
2. Put magisk.zip in output folder
3. Selected Debug version of magisk in installer
4. Installed output

Logs don't seem much different... I'm not sure this is the correct process.

[magisk_log_2022-08-23T11.39.33.log](https://github.com/LSPosed/LSPosed/files/9409776/magisk_log_2022-08-23T11.39.33.log)

**Comment by Howard20181** [comment]
In your log:
`08-23 18:37:43.567    86    88 D : xsendfile: 843776 bytes /data/adb/magisk/busybox -> /dev/FogKmXy8/.magisk/busybox/busybox`

Check the correct size using the command `stat /data/adb/magisk/busybox`

**Comment by alexwilson1** [comment]
redfin:/ # stat /data/adb/magisk/busybox
  File: /data/adb/magisk/busybox
  Size: 2265848  Blocks: 4432    IO Blocks: 512  regular file
Device: 800h/2048d       Inode: 2867206  Links: 1        Device type: 0,0
Access: (0755/-rwxr-xr-x)       Uid: (    0/    root)   Gid: (    0/    root)
Access: 2022-08-23 11:17:36.360000000 -0700
Modify: 2022-08-23 11:48:56.200000000 -0700
Change: 2022-08-23 11:48:56.340000000 -0700

**Comment by Howard20181** [comment]
843776 != 2265848 
We don't know what happened.

**Comment by Howard20181** [comment]
Maybe there is a bug in the kernel of WSA.

**Comment by alexwilson1** [comment]
Does this copy happen each time WSA is restarted? Could we manually copy and then restart magisk as a workaround?

**Comment by alexwilson1** [comment]
These commands show they are the same size however...

```
redfin:/ # ls -lh /dev/FogKmXy8/.magisk/busybox/busybox
-rwxr-xr-x 1 root root 2.1M 2022-08-23 11:48 /dev/FogKmXy8/.magisk/busybox/busybox
redfin:/ # ls -lh /data/adb/magisk/busybox
-rwxr-xr-x 1 root root 2.1M 2022-08-23 11:48 /data/adb/magisk/busybox
```

**Comment by Howard20181** [comment]
>Does this copy happen each time WSA is restarted?

Yes

Magisk copies this file early in the boot process.
Workaround needs to be added to MagiskOnWSA's script.
Whether it should be added or not needs to be discussed.

**Comment by Howard20181** [comment]
Curious about why magiskpolicy copy correctly every time, it does it almost at the same time as busybox.
`D : xsendfile: 368288 bytes /data/adb/magisk/magiskpolicy -> /dev/FogKmXy8/magiskpolicy`

**Comment by alexwilson1** [comment]
> These commands show they are the same size however...
> 
> ```
> redfin:/ # ls -lh /dev/FogKmXy8/.magisk/busybox/busybox
> -rwxr-xr-x 1 root root 2.1M 2022-08-23 11:48 /dev/FogKmXy8/.magisk/busybox/busybox
> redfin:/ # ls -lh /data/adb/magisk/busybox
> -rwxr-xr-x 1 root root 2.1M 2022-08-23 11:48 /data/adb/magisk/busybox
> ```

Any idea why this is the case?

**Comment by alexwilson1** [comment]
I think you are correct. The size of busybox in the /dev/ dir keeps changing when rebooting...

```
redfin:/ # ls -lh /dev/FogKmXy8/.magisk/busybox
total 852K
-rwxr-xr-x 1 root root 852K 2022-08-23 14:19 busybox
```
Reboot
```
redfin:/ # ls -lh /dev/FogKmXy8/.magisk/busybox
total 1.1M
-rwxr-xr-x 1 root root 1.1M 2022-08-23 14:16 busybox
```


Even though the size in the /data/ dir stays the same
```
redfin:/ # ls -lh /data/adb/magisk/busybox
-rwxr-xr-x 1 root root 2.1M 2022-08-23 14:19 /data/adb/magisk/busybox
```

**Comment by alexwilson1** [comment]
After some investigation, I think this may be due to a bug in the file copying mechanism defined in Magisk.

Using `cmp` to compare the two files, we find that they are exactly the same until EOF is reached in the copied file. This means that the copy partially copying the first part of the file only.

```
cmp /data/adb/magisk/busybox /dev/FogKmXy8/.magisk/busybox/busybox                                                     <
cmp: EOF on /dev/FogKmXy8/.magisk/busybox/busybox
```

So, we have to investigate why this is the case:

The copying occurs [here](https://github.com/topjohnwu/Magisk/blob/b9e89a1a2dd71b9f91bce8f4ebeff3ed8e232889/native/src/core/bootstages.cpp#L162) (snippet):

```
    sprintf(buf, "%s/" BBPATH "/busybox", MAGISKTMP.data());
    mkdir(dirname(buf), 0755);
    cp_afc(DATABIN "/busybox", buf);
```

The `cp_afc` function is defined [here](https://github.com/topjohnwu/Magisk/blob/6bfe34e5a854292866c34aa53d356866e8259683/native/src/base/files.cpp#L156) (snippet):

```
            int sfd = xopen(src, O_RDONLY | O_CLOEXEC);
            int dfd = xopen(dest, O_WRONLY | O_CREAT | O_TRUNC | O_CLOEXEC, 0);
            xsendfile(dfd, sfd, nullptr, a.st.st_size);
            close(sfd);
            close(dfd);
```
xsendfile is defined [here](https://github.com/topjohnwu/Magisk/blob/6bfe34e5a854292866c34aa53d356866e8259683/native/src/base/xwrap.cpp#L94) (function):

```
ssize_t xsendfile(int out_fd, int in_fd, off_t *offset, size_t count) {
    ssize_t ret = sendfile(out_fd, in_fd, offset, count);
    if (ret < 0) {
        PLOGE("sendfile");
    }
    return ret;
}
```

`sendfile()` is a Linux function defined [here](https://man7.org/linux/man-pages/man2/sendfile.2.html) (doc snippet):
```
**Note that a successful call to sendfile()
       may write fewer bytes than requested; the caller should be
       prepared to retry the call if there were unsent bytes.**
```
Since the implementation of `xsendfile` does not retry the `sendfile()` call when the number of bytes transferred is less than the number of bytes requested (as specified in the documentation), we see that this issue is happening.

This also explains the random behaviour - it is possible that sometimes `sendfile()` does successfully complete in a single call.

Since this is not an issue with the WSA kernel, I believe Magisk should redefine the `xsendfile` function to include retries of `sendfile()`, for example with the code specified [here](https://stackoverflow.com/a/11861074):
```
// Offset into buffer, this is where sendfile starts reading the buffer
off_t offset = 0;

// Loop while there's still some data to send
for (size_t size_to_send = fsize; size_to_send > 0; )
{
    ssize_t sent = sendfile(newsockd, fpl, &offset, size_to_send);

    if (sent <= 0)
    {
        // Error or end of file
        if (sent != 0)
            perror("sendfile");  // Was an error, report it
        break;
    }

    size_to_send -= sent;  // Decrease the length to send by the amount actually sent
}
```

I'll open a bug in the Magisk repo. Thank you for your help with this!

**Comment by yujincheng08** [comment]
Nah. That case, I suppose, only happens when either fd is a socket or some other stream fd.

The problem is that the filesize returned by `stat` is wrong.

**Comment by canyie** [comment]
![IMG_20220824_151516_573.jpg](https://user-images.githubusercontent.com/31466456/186355936-1c0142ec-e2e7-4786-89dd-03e8781b340c.jpg)
![IMG_20220824_151552_228.jpg](https://user-images.githubusercontent.com/31466456/186355953-6e0a4f67-f796-486f-aa28-7742075df7a2.jpg)

`getattr` (which uses lstat) randomly reports wrong file  size while manually execute /system/bin/stat reporting the correct value.

**Comment by alexwilson1** [comment]
Temporarily fixed this by completely replacing the copying function with one that does not require file size:

```
int cp(const char *to, const char *from)
{
    int fd_to, fd_from;
    char buf[4096];
    ssize_t nread;
    int saved_errno;

    fd_from = open(from, O_RDONLY);
    if (fd_from < 0)
        return -1;

    fd_to = open(to, O_WRONLY | O_CREAT | O_EXCL, 0666);
    if (fd_to < 0)
        goto out_error;

    while (nread = read(fd_from, buf, sizeof buf), nread > 0)
    {
        char *out_ptr = buf;
        ssize_t nwritten;

        do {
            nwritten = write(fd_to, out_ptr, nread);

            if (nwritten >= 0)
            {
                nread -= nwritten;
                out_ptr += nwritten;
            }
            else if (errno != EINTR)
            {
                goto out_error;
            }
        } while (nread > 0);
    }

    if (nread == 0)
    {
        if (close(fd_to) < 0)
        {
            fd_to = -1;
            goto out_error;
        }
        close(fd_from);

        /* Success! */
        return 0;
    }

  out_error:
    saved_errno = errno;

    close(fd_from);
    if (fd_to >= 0)
        close(fd_to);

    errno = saved_errno;
    return -1;
}

```

Using this function in the cp_afc function:

```
void cp_afc(const char *source, const char *destination) {
    file_attr a;
    getattr(source, &a);

    if (S_ISDIR(a.st.st_mode)) {
        xmkdirs(destination, 0);
        clone_dir(xopen(source, O_RDONLY | O_CLOEXEC), xopen(destination, O_RDONLY | O_CLOEXEC));
    } else{
        unlink(destination);
        if (S_ISREG(a.st.st_mode)) {
            LOGD("CP Copy: %s -> %s\n", source, destination);
            cp(destination,source);
        } else if (S_ISLNK(a.st.st_mode)) {
            char buf[4096];
            xreadlink(source, buf, sizeof(buf));
            xsymlink(buf, destination);
        }
    }
    setattr(destination, &a);
}

```
The build can be found [here](https://github.com/alexwilson1/Magisk/actions/runs/2923370288)

Seems to work fine now.
