### ISSUE TITLE
XPrivacyLua not starting/working

### ISSUE THREAD

**Issue by McHoffi** [LSPosed/LSPosed#2093]
### Steps to reproduce/复现步骤

Setting up XprivacyLua and XprivacyLuaPro
XPrivacyLuaPro not starting, when the restricted app is opened/no logs in XprivacyLuaPro

### Expected behaviour/预期行为

XprivacyLuaPro should restrict informations for app and show logs

### Actual behaviour/实际行为

Logs in XprivacyLuaPro are empty and the restricted app gets the information 

### Xposed Module List/Xposed 模块列表

```shell
AOSP mods 2.0.1 (120)
XPrivacyLua 1.3.1
```

### Magisk Module List/Magisk 模块列表

```shell
LSposed
Magisk Hide Propsconfig
Shamiko
Systemless Hosts
Universal Safteynetfix
Zygisk Sui
```

### LSPosed version/LSPosed 版本

1.8.3 (6599)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

 38ab6858 (25203)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-08-27T15_06_09.341745.zip](https://github.com/LSPosed/LSPosed/files/9438018/LSPosed_2022-08-27T15_06_09.341745.zip)

**Comment by yujincheng08** [comment]
Ask authors of this module.

**Comment by Howard20181** [comment]
Is XprivacyLuaPro adapted to Android 13 yet? Could it be a problem with the module itself?

**Comment by McHoffi** [comment]
Dev sa

> Is XprivacyLuaPro adapted to Android 13 yet? Could it be a problem with the module itself?

Dev said that it should work if there are no Problems with Lsposed and that Lsposed must be A13 compatible, then he would investigate further.

**Comment by yujincheng08** [comment]
@McHoffi 

At least no issue has been found on Android 13 for now.

**Comment by bush911** [comment]
Same issue here
