### ISSUE TITLE
Unusual Bug

### ISSUE THREAD

**Issue by Dimitrysaf** [LSPosed/LSPosed#2094]
### Steps to reproduce/复现步骤

Okey, I installed this module on an Arrow OS system running Android 13 and device name in Beryllium Poco F1 all good with the installation process.

### Expected behaviour/预期行为

I expect to open the info for those module 

### Actual behaviour/实际行为

It just crashes every time I clicking to see info or install i

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
• AOSP enchanter 
Revolutionary Android Optimizer 🚀
• unnofficial_iOS(u14)
This module was created by Emoji Replacer! 😬
• Zygisk - LSPosed 
Blah blah blah...
```

### LSPosed version/LSPosed 版本

1.8.3

### Android version/Android 版本

Android 13

### Magisk version/Magisk 版本

25.2 (25200)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-08-28T07_59_17.929732.zip](https://github.com/LSPosed/LSPosed/files/9439106/LSPosed_2022-08-28T07_59_17.929732.zip)
 Idk how to do it there's a zip file

**Comment by yujincheng08** [comment]
hardly understand what you mean. hv u learned english b4?

**Comment by yujincheng08** [comment]
> I am using latest debug CI version of LSPosed and enable verbose log

you arent
