### ISSUE TITLE
[Bug] handleInitPackageResources does not work, not called

### ISSUE THREAD

**Issue by xxr0ss** [LSPosed/LSPosed#2099]
### Steps to reproduce/复现步骤

write code
```kotlin
class Hook : IXposedHookLoadPackage, IXposedHookZygoteInit, IXposedHookInitPackageResources {
    // ...
    override fun handleInitPackageResources(resparam: XC_InitPackageResources.InitPackageResourcesParam) {
        Log.e(TAG, "handleInitPackageResources: =============RES==========") 
    }
}
```

Select apps that I want to hook.

Run any of these apps.

No log, this callback was not called.

### Expected behaviour/预期行为

`handleInitPackageResources()` should be called

### Actual behaviour/实际行为

The rest part of the code will run, such as `handleLoadPackage()`

### Xposed Module List/Xposed 模块列表

```shell
My Hook
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

6552

### Android version/Android 版本

12.1

### Magisk version/Magisk 版本

25.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-09-05T00_31_24.584.zip](https://github.com/LSPosed/LSPosed/files/9485076/LSPosed_2022-09-05T00_31_24.584.zip)

**Comment by xxr0ss** [comment]
Tested on both WSA and a real phone

**Comment by yujincheng08** [comment]
You are not using the debug version.

![image](https://user-images.githubusercontent.com/5022927/189508649-0a53638a-ebe5-42e5-b4fb-914a8949ebac.png)
Also, `handleInitPackageResources` works even on Android 13
