### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by Jhamaklimbu** [LSPosed/LSPosed#2100]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Vivo v20 mode number 2025 not root I am menu try

### Describe the solution you'd like/描述你想要的解决方案

I hope my phone root

### Additional context/其他信息

No thing any comply..

**Comment by Jhamaklimbu** [comment]
Good job...

**Comment by yujincheng08** [comment]
This is not a root solution.
