### ISSUE TITLE
[Feature Request] 

### ISSUE THREAD

**Issue by araafroyall** [LSPosed/LSPosed#2123]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Hi developers please add an in-built translation for module description for easily readable.
thanks

### Describe the solution you'd like/描述你想要的解决方案

Hi developers please add an in-built translation for module description for easily readable.
atleast must be in ENGLISH
thanks

**Comment by yujincheng08** [comment]
No money to pay for a machine translation API.
