### ISSUE TITLE
[Bug] LSPosed doesn't allow access to system apps so some modules can't work

### ISSUE THREAD

**Issue by robmausser** [LSPosed/LSPosed#2134]
### Steps to reproduce/复现步骤

I cannot use the module "OP CAMERA DEBUG" because LSPosed doesn't list the OnePlus apps that are baked into the system and not user apps. Please allow us to show system apps in the list of apps to apply the module to 

### Expected behaviour/预期行为

I should be able to see system installed apps

### Actual behaviour/实际行为

Cannot apply module tweaks to system apps

### Xposed Module List/Xposed 模块列表

```shell
OP Camera debug
```

### Magisk Module List/Magisk 模块列表

```shell
None
```

### LSPosed version/LSPosed 版本

1.8.4

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Na

**Comment by yujincheng08** [comment]
![IMG_20220918_102745](https://user-images.githubusercontent.com/5022927/190882940-2f9fc3cf-9237-41c7-8be7-6fb0b7d62853.jpg)

**Comment by robmausser** [comment]
Thank-you I'm dumb
