### ISSUE TITLE
[Feature Request] Lsposed app in the app drawer

### ISSUE THREAD

**Issue by theghostkill** [LSPosed/LSPosed#2137]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

I neither use lsposed often enough nor do I like root-related stuff to be kept on the home screen.

### Describe the solution you'd like/描述你想要的解决方案

Please make the module appear in the app drawer itself rather than as a shortcut on the home screen.

**Comment by yujincheng08** [comment]
install `/data/adb/lspd/manager.apk`

**Comment by steponmepls** [comment]
> install `/data/adb/lspd/manager.apk`

When I try to manually install the app, an error shows up saying "There was a problem parsing the package."

- Magisk 25.2
- Zygisk enabled
- Zygisk - LSPosed v1.8.4
- LineageOS 18.1

**Comment by Howard20181** [comment]
> > install `/data/adb/lspd/manager.apk`
> 
> When I try to manually install the app, an error shows up saying "There was a problem parsing the package."
> 
> * Magisk 25.2
> * Zygisk enabled
> * Zygisk - LSPosed v1.8.4
> * LineageOS 18.1

Copy the apk to `/sdcard`
