### ISSUE TITLE
[Bug] Broken permission SET_VOLUME_KEY_LONG_PRESS_LISTENER 

### ISSUE THREAD

**Issue by Stunnerr** [LSPosed/LSPosed#2154]
### Steps to reproduce/复现步骤

1. Install LSPosed Zygisk (not tested on Riru)
2. Install some app that uses SET_VOLUME_KEY_LONG_PRESS_LISTENER permission (e.g. VKX or [this](https://github.com/Cilenco/skipTrackLongPressVolume/releases/)) without giving this permission
4. Reboot
5. Launch the app that uses the permission
6. Try holding volume button

### Expected behaviour/预期行为

System/other app with permission cathes volume key long press event

### Actual behaviour/实际行为

Newly installed app without permission catches volume key long press event

### Xposed Module List/Xposed 模块列表

```shell
(disabled everything)
Pixelify Google Photos
TrustMeAlready
Lucky Patcher
```

### Magisk Module List/Magisk 模块列表

```shell
disabled everything except lsposed
```

### LSPosed version/LSPosed 版本

6620

### Android version/Android 版本

12.1

### Magisk version/Magisk 版本

25200

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-10-03T21_55_30.984.zip](https://github.com/LSPosed/LSPosed/files/9699397/LSPosed_2022-10-03T21_55_30.984.zip)

**Comment by yujincheng08** [comment]
cannot reproduce.

installed skipTrackSettings with lsposed, reboot and still shows permission required.

**Comment by Stunnerr** [comment]
Looks like there's something with Lucky Patcher's "Disable signature verification in package manager" patch and the LSPosed itself.
I tried these configurations:
1. LP uninstalled, but pm patched using LP's "Android patches" and not "Xposed patches" - bug reproduces
2. LP installed, module enabled with no system patches, pm patch removed - bug does not reproduce
3. LP installed, pm patched using Xposed patch - bug reproduces
4. LP installed, all xposed patches except pm patch enabled - bug does not reproduce

**Comment by yujincheng08** [comment]
disabling signature verficiation allows all apps to get some critical permission silently and this is expected. nothing to do with lsposed.
