### ISSUE TITLE
[Feature Request] package visibility from hooked app to xposed module

### ISSUE THREAD

**Issue by yashikada** [LSPosed/LSPosed#2157]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Yes, a hooked app should access to service/provider exported from xposed module, hooked app can't find my service/provider because from android 11 package visibility is limited from tag queries in AndroidManifest.

### Describe the solution you'd like/描述你想要的解决方案

LSPosed should hook the app and should allow access to the service/provider exported by xposed module.

**Comment by vvb2060** [comment]
android:forceQueryable=true
