### ISSUE TITLE
[Bug] downloadNewZipSync Permission Denied

### ISSUE THREAD

**Issue by kdjsisichdjandnf** [LSPosed/LSPosed#2158]
### Steps to reproduce/复现步骤

flash lsposed
reboot
install xprivacylua
turn on module
reboot
select app from xprivacylua
and to other module 
like android faker i install then turn on module and reboot. Choose imei change it and fast reboot but not work
and disable flag_secure i install and turn on module and reboot. Choose app from module but not work

### Expected behaviour/预期行为

xprivacylua, android faker and disable flag_secure work

### Actual behaviour/实际行为

xprivacylua, android faker and disable flag_secure not work

### Xposed Module List/Xposed 模块列表

```shell
xprivacylua
android faker
disable flag_secure
```

### Magisk Module List/Magisk 模块列表

```shell
Universal SafetyNet Fix
ANXVerse (Next-Gen ANXCamera)
```

### LSPosed version/LSPosed 版本

1.8.4 (6609)

### Android version/Android 版本

android 12.1

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-09-30T08_12_01.864.zip](https://github.com/LSPosed/LSPosed/files/9711383/LSPosed_2022-09-30T08_12_01.864.zip)

**Comment by yujincheng08** [comment]
title and the content not matched

**Comment by kdjsisichdjandnf** [comment]
Sorry i can't explain very well. But the modules can't run. Already turn on modules. And i use lsposed in another device, it's working good.  It's 3 module can't run.
