### ISSUE TITLE
双开微信无法生效[Feature Request] 

### ISSUE THREAD

**Issue by lygwql5631** [LSPosed/LSPosed#2161]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

原来riru版本可以对双开应用生效，zygisk版本开微信无法生效

### Describe the solution you'd like/描述你想要的解决方案

原来riru版本可以对双开应用生效，zygisk版本开微信无法生效，建议增加功能

**Comment by vvb2060** [comment]
无法复现
