### ISSUE TITLE
[Bug] the riru version doesn't work, says it isnt installed

### ISSUE THREAD

**Issue by dxcvvxd** [LSPosed/LSPosed#2162]
### Steps to reproduce/复现步骤

install riru
install lsposed riru
be amazed by how it doesnt work
![Screenshot_20221007-222110_Fox's_Magisk_Module_Manager](https://user-images.githubusercontent.com/77129815/194638536-6fb3c045-fa6a-4120-8780-197a51fdf3f8.png)
![Screenshot_20221007-222328_LSPosed](https://user-images.githubusercontent.com/77129815/194638585-dfc60ad2-3be0-4781-882e-75c4a9e396f7.png)

### Expected behaviour/预期行为

should say installed and work properly

### Actual behaviour/实际行为

doesn't work and says isn't installed

### Xposed Module List/Xposed 模块列表

```shell
no modules installed
```

### Magisk Module List/Magisk 模块列表

```shell
different modules that worked with zygisk version
```

### LSPosed version/LSPosed 版本

1.8.4 (6609)

### Android version/Android 版本

11

### Magisk version/Magisk 版本

e4b8d53d-delta (25203)

### Riru version/Riru 版本

26.1.7

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

I can't provide logs cuz the manager doesn't work

**Comment by mywalkb** [comment]
From riru README

```
Deprecated

All Riru users and Riru modules should migrate to Zygisk.
```

Why don't you use LSPosed zygisk version?

**Comment by yujincheng08** [comment]
no log, no fix.

**Comment by yujincheng08** [comment]
but anyway from ur screenshot, riru is not working properly. And since riru is deprecated, it cannot be fixed.

**Comment by nandlab** [comment]
@yujincheng08
Do you even read the issue?

> I can't provide logs cuz the manager doesn't work

**Comment by yujincheng08** [comment]
@nandlab yes. So what? log does not require manager.

**Comment by nandlab** [comment]
How to get the logs if LSPosed is not running?

**Comment by yujincheng08** [comment]
@nandlab 

When you click "new issue" in github, it will show u how:

![image](https://user-images.githubusercontent.com/5022927/195993369-f9f45b96-00e8-416d-8598-49fd20d445c7.png)

**Comment by nandlab** [comment]
So you mean the Android [bugreport](https://developer.android.com/studio/debug/bug-report)?

**Comment by yujincheng08** [comment]
Yes
