### ISSUE TITLE
[Bug] Problem with Lucky Patcher module in Android 13

### ISSUE THREAD

**Issue by ViktorVoloshko** [LSPosed/LSPosed#2167]
### Steps to reproduce/复现步骤

1) Install LP and enable it's module
2) Open LP and see that there is no Xposed module settings

### Expected behaviour/预期行为

Xposed Settings should appear and be available.

### Actual behaviour/实际行为

Seems like LP doesn't recognize LSPosed while it was on Android 12.1 and lower (that's why I think it's LSPosed problem).

### Xposed Module List/Xposed 模块列表

```shell
Only Lucky patcher module.
```

### Magisk Module List/Magisk 模块列表

```shell
Only LSPosed (Zygisk) module.
```

### LSPosed version/LSPosed 版本

1.8.4

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2 (25200)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-10-12T14_11_36.172521.zip](https://github.com/LSPosed/LSPosed/files/9764385/LSPosed_2022-10-12T14_11_36.172521.zip)
And also Lucky Patcher log since it can be useful to tell where the problem really is.
[error_log.zip](https://github.com/LSPosed/LSPosed/files/9764397/error_log.zip)
I've seen this in LP logs:
`10-12 13:40:09.992 W/Thread-12(14748): type=1400 audit(0.0:45036): avc: denied { read for name-"xposed" dev="sda11" ino43931 scontext=u:r:untrusted app_27:s0:c121,c257, c512,c768 tcontext=u:object _r:system_data_root_file:sO tclass=file permissive=0 app=ru.ojfgydkf.xrfhbshiq`
And I wonder what is this denial.

**Comment by yujincheng08** [comment]
this is lp's issue i think. contact lp's devs instead.

**Comment by aviraxp** [comment]
@ViktorVoloshko 他把配置文件放在/data/system

**Comment by ViktorVoloshko** [comment]
> @ViktorVoloshko 他把配置文件放在/data/system

So, I need to report LP dev that /data/system is a bad place for config files? I used translator to understand Chinese so making sure that I got it correct.
