### ISSUE TITLE
[Feature Request] 当安装于sd卡中的应用非[推荐的应用]时，重启会导致作用域失效，需要重新勾选

### ISSUE THREAD

**Issue by 33nn** [LSPosed/LSPosed#2168]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

1.应用被安装于sd卡中
2.非[推荐应用]
3.重启/重新挂载sd卡
导致每次重启系统都需要重新勾选作用域

### Describe the solution you'd like/描述你想要的解决方案

应该记住作用域，当应用重新安装时

**Comment by Howard20181** [comment]
需要保证作用域里面的应用都是存在的，所以当未挂载时可能会被移除

如果某个APP因为模块原因闪退了，一般会尝试卸载重装，如果记住历史选中的并激活模块会给排查带来问题
