### ISSUE TITLE
The latest version of Huawei P30 cannot be activated. The old version 0.5.4.1 can be activated[BUG] 

### ISSUE THREAD

**Issue by linysl** [LSPosed/LSPosed#217]
华为P30使用最新版无法激活lsposed，旧版本0.5.4.1可以正常激活使用

**Magisk模块列表/Magisk Module List**
riru23.6
riru-lsposed0.5.4.1

**版本信息/Versions**

Android:9

Magisk:22.0

Riru:23.6

LSPosed:0.5.4.1

**相关日志/Related Logs**
[LSPosed_Verbose_20210227_163017.log](https://github.com/LSPosed/LSPosed/files/6054044/LSPosed_Verbose_20210227_163017.log)

**Comment by tehcneko** [comment]
日志文件不完整

**Comment by tehcneko** [comment]
以及版本？
