### ISSUE TITLE
[Bug] LSPosed is "not installed or active"

### ISSUE THREAD

**Issue by nandlab** [LSPosed/LSPosed#2176]
### Steps to reproduce/复现步骤

Cannot reproduce.

### Expected behaviour/预期行为

LSPosed should be started automatically on every boot.

### Actual behaviour/实际行为

Although it works fine for multiple month, after some point when I boot the phone the app says "Tap to install LSPosed", LSPosed and its modules are not running. I get the same problem after reboot.

In Magisk LSPosed is still installed and the Magisk logs look ok, I can see `riru_lsposed: exec [service.sh]`.

### Xposed Module List/Xposed 模块列表

```shell
- XPrivacyLua
```

### Magisk Module List/Magisk 模块列表

```shell
- Move certificates
- Riru
- Riru - LSPosed
- Systemless hosts
```

### LSPosed version/LSPosed 版本

Riru - LSPosed is 1.7.2 but in the app it says 1.5.3

### Android version/Android 版本

9.0

### Magisk version/Magisk 版本

23.0

### Riru version/Riru 版本

26.1.4.r522.8b379cedb5

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[bugreport-kccat6xx-PQ3A.190801.002-2022-10-15-13-30-59.zip](https://github.com/LSPosed/LSPosed/files/9791937/bugreport-kccat6xx-PQ3A.190801.002-2022-10-15-13-30-59.zip)

**Comment by yujincheng08** [comment]
You are not using latest debug CI version or not enabling the verbose log.
