### ISSUE TITLE
[Bug] LSPosed does not start

### ISSUE THREAD

**Issue by nandlab** [LSPosed/LSPosed#2177]
### Steps to reproduce/复现步骤

Install Magisk, Riru and Riru-LSPosed.

### Expected behaviour/预期行为

LSPosed should be installed and active after reboot. I should be able to control LSPosed through the LSPosed manager app.

### Actual behaviour/实际行为

The manager app says "LSPosed is not installed". The LSPosed modules (XPrivacyLua) are not running.

### Xposed Module List/Xposed 模块列表

```shell
- XPrivacyLua
```

### Magisk Module List/Magisk 模块列表

```shell
- Move certificates
- Riru
- Riru - LSPosed
- Systemless hosts
```

### LSPosed version/LSPosed 版本

1.8.4 (6609)

### Android version/Android 版本

9.0

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

26.1.7.r530.ab3086ec9f

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[bugreport-kccat6xx-PQ3A.190801.002-2022-10-15-15-30-32.zip](https://github.com/LSPosed/LSPosed/files/9792286/bugreport-kccat6xx-PQ3A.190801.002-2022-10-15-15-30-32.zip)

**Comment by yujincheng08** [comment]
You are not using latest debug CI version or not enabling the verbose log.
