### ISSUE TITLE
[BUG] Huawei P30 cannot be activated with the latest version, and the old version 0.5.4.1 can be used normally.

### ISSUE THREAD

**Issue by linysl** [LSPosed/LSPosed#218]
**什么情况/What happened?**
Huawei P30 cannot be activated with the latest version, and the old version 0.5.4.1 can be used normally.

**Magisk模块列表/Magisk Module List**
riru.23.6
riru-lsposed1.0.2-5350

**版本信息/Versions**

Android:9

Magisk:22.0

Riru:23.6

LSPosed:1.0.2-5350

**相关日志/Related Logs**
[modules.log](https://github.com/LSPosed/LSPosed/files/6054221/modules.log)

**Comment by yujincheng08** [comment]
需要 debug 版的 bootlog

**Comment by yujincheng08** [comment]
有 log 你可以 reopen 而不用再开一个

**Comment by linysl** [comment]
> 需要debug版的bootlog

Get the debug log again, please take a look again to see where my problem is。

**Comment by linysl** [comment]
重新获取的debug日志  已经上传上去了  麻烦看一下 linysl 邮箱：linysl@88.com 签名由 网易邮箱大师 定制 On 02/27/2021 18:18, LoveSy wrote: 需要 debug 版的 bootlog — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by aviraxp** [comment]
传哪去了？

**Comment by linysl** [comment]
> 传哪去了？

In this post, the bottom log, I changed it to a new one. Have a look

**Comment by linysl** [comment]
> 传哪去了？

[modules.log](https://github.com/LSPosed/LSPosed/files/6054250/modules.log)

**Comment by aviraxp** [comment]
@linysl 我们意思是你得装debug版模块然后抓启动时候的日志

**Comment by linysl** [comment]
> @linysl我们的意思是你得装debug版模块然后抓启动时候的日志

这个日志还不对吗？我就是在电报里面重新下载的1.0.2-5252-debug.zip和最新的lspmanager，然后在magisk里面刷入，重启后获取的日志。这个流程不正确吗？

**Comment by aviraxp** [comment]
@linysl 起码给一下verbose log啊

**Comment by linysl** [comment]
> @linysl起码给一下verbose log啊

[Uploading boot-2021-02-27-11-29-35.log…]()

**Comment by aviraxp** [comment]
@linysl 你压根没传上来

**Comment by linysl** [comment]
> @linysl起码给一下verbose log啊


[verbose_log.log](https://github.com/LSPosed/LSPosed/files/6054294/verbose_log.log)
[boot-2021-02-27-11-29-35.log](https://github.com/LSPosed/LSPosed/files/6054295/boot-2021-02-27-11-29-35.log)
再麻烦大佬看看，第一个文件没有后缀名上传不了，我在后边添了.log

**Comment by kotori2** [comment]
<img width="292" alt="image" src="https://user-images.githubusercontent.com/17663689/109386100-6fbecb80-7933-11eb-83cf-7b81f76eeea8.png">
传log之前能不能自己打开看看，就这几字节的东西你传上来有什么用
