### ISSUE TITLE
[Bug] Manager crash (Both)

### ISSUE THREAD

**Issue by ZeloIsGay** [LSPosed/LSPosed#2186]
### Steps to reproduce/复现步骤

Open latest version of the manager

### Expected behaviour/预期行为

Manager opens

### Actual behaviour/实际行为

Manager crashes without GUI for both the regular and parasitic manager, even after uninstalling and reinstalling. LSPosed framework seems to run normally though

### Xposed Module List/Xposed 模块列表

```shell
aospmods, lucky patcher, snapmod, disableflagsecure, hidemyapplist, pixelify gphotos
```

### Magisk Module List/Magisk 模块列表

```shell
adreno gpu driver, aospmods, app data isolation, audio modification library, builtin busybox, cloudflare dns, fullscreen gestures, hide userdebug, lesseraudioswitch, oh my font, pixelify, quickswitch, riru, riru lsposed, modified riru momohider, modified universal safetynet fix, revanced
```

### LSPosed version/LSPosed 版本

v1.8.4 build 6631

### Android version/Android 版本

12.1

### Magisk version/Magisk 版本

25205

### Riru version/Riru 版本

26.1.6.r257

### Version requirement/版本要求

- [x] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

with regular manager: https://bin.kv2.dev/~635070eae599576ea02af600

with parasitic manager: https://bin.kv2.dev/~63506c98e599576ea02af5fd

verbose and module log: [log.zip](https://github.com/LSPosed/LSPosed/files/9824702/log.zip)

**Comment by Howard20181** [comment]
What the output of `getprop | grep .brand`

**Comment by ZeloIsGay** [comment]
> What the output of `getprop | grep .brand`

`[ro.product.brand]: [Xiaomi]
[ro.product.odm.brand]: [Xiaomi]
[ro.product.product.brand]: [Xiaomi]
[ro.product.system.brand]: [Xiaomi]
[ro.product.system_ext.brand]: [Xiaomi]
[ro.product.vendor.brand]: [Xiaomi]
[ro.product.vendor_dlkm.brand]: [Xiaomi]`

**Comment by Howard20181** [comment]
Use this build to get some log https://github.com/LSPosed/LSPosed/suites/8866809671/artifacts/404847072

**Comment by ZeloIsGay** [comment]
> Save log from manager

the logs i have in my original post are from the manager, is there a sort of setting i can enable for more detailed logging?

**Comment by vvb2060** [comment]
Issue closed due to not uploading logs as required.

**Comment by ZeloIsGay** [comment]
> Issue closed due to not uploading logs as required.

the logs are in the original post, nevertheless here they are again

with regular manager: https://bin.kv2.dev/~635070eae599576ea02af600

with parasitic manager: https://bin.kv2.dev/~63506c98e599576ea02af5fd

**Comment by yujincheng08** [comment]
Zip is not generated by the manager but by yourself.

**Comment by ZeloIsGay** [comment]
> Zip is not generated by the manager but by yourself.

yes, i took the logs from /data/adb/lspd/log and put them in a zip file. do i do anything differently?

**Comment by vvb2060** [comment]
why del props.txt

**Comment by ZeloIsGay** [comment]
> you don't provide all files in /data/adb/lspd/log.

my bad, here they are
[log2.zip](https://github.com/LSPosed/LSPosed/files/9827442/log2.zip)

**Comment by vvb2060** [comment]
Why not install the specified version as we ask.

**Comment by ZeloIsGay** [comment]
> Why not install the specified version as we ask.

it should be the version installed, but i will reinstall again and send logs again

![Screenshot_20221020-094518_Magisk Delta](https://user-images.githubusercontent.com/30455297/196887973-8be6739f-11ea-444e-bfe4-fa5d11d36574.png)

![Screenshot_20221020-094503_Chrome Dev](https://user-images.githubusercontent.com/30455297/196887994-b844c4a7-d877-494e-9f00-d28a1f1d8b70.png)

**Comment by ZeloIsGay** [comment]
i did not realise it was a different build under the same name, it is working with the version sent. i apologize for taking up more of your time than needed!
