### ISSUE TITLE
[Bug] Abnormal CPU Core Loaded After Optimize Apps In Lsposed

### ISSUE THREAD

**Issue by cbrown666** [LSPosed/LSPosed#2195]
### Steps to reproduce/复现步骤

1.Open Lsposed apps
2.Randomly open a module list
3.Choose an app which have been selected to be the scope.
3.Longpress the app selected.
4.Click to Optimize the app.
5.Lsposed app display "optimizing"
6.Phone get heated continually.And open scene 5 to check CPU frequency and load.
7.All the core are fully loaded and occupied especially the big core.
8.Open scene 5 to check the background process.And I find that dex2oat is highly manipulate CPU which get the load precentage to 100%.Thats why phone gets heat after optimizing apps in Lsposed.
9.Force stop dex2oat process.
10.Cpu is down and temperature of phone is down.

### Expected behaviour/预期行为

Optimize Apps quickly and don't get CPU core to high loaded for too long.

### Actual behaviour/实际行为

CPU core is persistently loaded to 100% and the temperature of phone goes straightly high. 

### Xposed Module List/Xposed 模块列表

```shell
1.对话框取消新版
2.拒绝强制亮度
3.米窗-全局小窗
4.墨-状态栏歌词
5.通话录音
6.小图标通知优化
7.fcmfix
8.HmsPush
9.NoActive
10.Thanox
11.Noticefix
```

### Magisk Module List/Magisk 模块列表

```shell
1.fcmfix for China
2.fix China carrier
3.Hms core
4.scene的附加模块
5.shamiko
6.Ui process optimization
7.zygisk_lsposed
8.zygisk_sui
9.禁用millet
10.骁龙888最佳能耗比频率
```

### LSPosed version/LSPosed 版本

v1.8.4(6609)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Detailed logcat:
[LSPosed_2022-10-26T16_57_26.688577.zip](https://github.com/LSPosed/LSPosed/files/9868370/LSPosed_2022-10-26T16_57_26.688577.zip)

**Comment by yujincheng08** [comment]
I think this is expected

**Comment by cbrown666** [comment]
> I think this is expected.
> 
> Optimizing an app, especially a large one, requires many computation resources.

Yes.I choose another app relatively tiny.Optimizing process quickly compete.
