### ISSUE TITLE
[Bug] Resources hooking not automaticlly initialized

### ISSUE THREAD

**Issue by blackwind** [LSPosed/LSPosed#2209]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

In v1.6.3, "Automatically enable Resources Hook if needed" was added to LSPosed. I immediately noted in the release discussion that [this breaks at least one module](https://github.com/LSPosed/LSPosed/discussions/1384#discussioncomment-1630152). I just upgraded from v1.6.2, the last working version, to v1.8.4, and apparently this functionality still hasn't been improved.

### Describe the solution you'd like/描述你想要的解决方案

If it's not possible to accurately detect when resource hooking should be enabled, I'd settle for an option to force enable it.

**Comment by yujincheng08** [comment]
You should open an bug report issue **with log**.

**Comment by blackwind** [comment]
Problem isn't a bug, merely an oversight, and there's absolutely nothing of interest in the log.

LSPosed appears to be [checking for instances of `IXposedHookInitPackageResources`](https://github.com/LSPosed/LSPosed/commit/a160bdca9e377a6bcacf7d16834a2f1e0353b284), and if it doesn't find one, resource hooking is disabled. The [official Xposed docs](https://github.com/rovo89/XposedBridge/wiki/Replacing-resources) indicate that you can also operate on resources by calling `XResources` from `IXposedHookZygoteInit`, and indeed, [this is what the module I'm having trouble with does](https://github.com/rapperskull/BurntToastRevived/blob/master/app/src/main/java/me/rapperskull/burnttoastrevived/Main.java). Because the module contains no instances of `IXposedHookInitPackageResources`, LSPosed disables resource hooking, the class is loaded and does nothing, and the module that previously worked in v1.6.2 and below therefore no longer works in v1.6.3 and above. Log confirms that both the module and class are correctly loaded every time they should be based on my scope, but nothing happens.

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed/commit/b26c8bc59e46ca8ece1a40da90be8bdb1060fd72

**Comment by yujincheng08** [comment]
It should be a bug. Open a bug issue. No one knows if the log is helpful, just upload it.

**Comment by blackwind** [comment]
Will this impact the module in question's use of [`hookSystemWideLayout`](https://github.com/rapperskull/BurntToastRevived/blob/master/app/src/main/java/me/rapperskull/burnttoastrevived/Main.java#L125) as well?

**Comment by blackwind** [comment]
Awesome, thanks guys!

**Comment by blackwind** [comment]
I can now confirm the latest canary build fully resolves the issue.
