### ISSUE TITLE
[Feature Request] Install automatically modules on upgrade

### ISSUE THREAD

**Issue by j0110** [LSPosed/LSPosed#2211]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

LSP provides an indicator while a module in the repo is updatable. However, it only downloads the module but do not install it automatically, we have to install it manually (finding the apk in the download folder and install it).

### Describe the solution you'd like/描述你想要的解决方案

Would it be possible to have modules automatically installed by LSP ?
Thanks a lot !

**Comment by yujincheng08** [comment]
LSPosed cannot even download module itself (it is done by your default browser), let alone installing.
