### ISSUE TITLE
[Feature Request] SuperSU (full root for Android 9+) support for LSPosed

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [LSPosed/LSPosed#2213]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No

### Describe the solution you'd like/描述你想要的解决方案

LSPosed Framework for full root rw users that is not module, it's for full-root based roots (example: SuperSU) + flashable zip port for newer Android OS versions (9+, 10+, 11+, 12+ and extra experimental 13+)

### Additional context/其他信息

Can we get LSPosed (full root/non systemless) support for SuperSU newer Android versions anytime (I can wait and I'm sure that others can wait too as long as necessary) so we can root Android 10+ with SuperSU and flash LSPosed but this time to be flashable full-root rw LSPosed framework.

**Comment by Howard20181** [comment]
1. SuperSU cannot provide injection interface
2. the ability to mount the system partition to rw is not a criterion for full-root

**Comment by admin-elvistrujanovic** [comment]
> 1. SuperSU cannot provide injection interface
> 2. the ability to mount the system partition to rw is not a criterion for full-root
> 

So, SuperSU is not full-root and SuperSU can't do any hooks or etc... like Magisk can to support LSPosed tweaks?

**Comment by Howard20181** [comment]
Anyway, you have to get Riru or Zygisk working on SuperSU before you can consider whether LSPosed is compatible.
