### ISSUE TITLE
[Bug] The LSPosed become blank when I switch from LSPosed to others

### ISSUE THREAD

**Issue by Lcify** [LSPosed/LSPosed#2223]
### Steps to reproduce/复现步骤

1.open LSPosed
2.switch task bar

### Expected behaviour/预期行为

display LSPosed and others task

### Actual behaviour/实际行为

LSPosed display blank
![Screenshot_2022-11-11-23-07-50-973_com miui mediaeditor](https://user-images.githubusercontent.com/60638114/201368114-6651cb61-45f6-482f-a745-61011e25a153.jpg)

### Xposed Module List/Xposed 模块列表

```shell
隐藏应用列表
Miui原生主题
```

### Magisk Module List/Magisk 模块列表

```shell
shamiko
LSPosed
```

### LSPosed version/LSPosed 版本

6649

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25200

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[Uploading LSPosed_2022-11-11T23_11_05.139.zip…]()

**Comment by yujincheng08** [comment]
wontfix.
