### ISSUE TITLE
[Bug] LSPosed更新到185后工商银行卡在开屏画面

### ISSUE THREAD

**Issue by njtony11** [LSPosed/LSPosed#2224]
### Steps to reproduce/复现步骤

更新到1.8.5-6649后工商银行都一直卡在开屏画面，退回到184后就又正常了

### Expected behaviour/预期行为

N/A

### Actual behaviour/实际行为

N/A

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

LSPosed v1.8.5-6649

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-11-12T12_26_09.781999.zip](https://github.com/LSPosed/LSPosed/files/9994112/LSPosed_2022-11-12T12_26_09.781999.zip)

**Comment by EdiTurn** [comment]
存在此现象的应用还有建行生活、个人所得税。
相关应用只要被添加到任意模块的作用域中，就会卡在启动界面。

**Comment by Howard20181** [comment]
对于已经在作用域内的应用被检测到是正常的，如果你确定LSPosed有bug请找出哪个提交导致的。
