### ISSUE TITLE
[Bug] 1.8.5最新版无法打开工商银行

### ISSUE THREAD

**Issue by bugme2** [LSPosed/LSPosed#2230]
### Steps to reproduce/复现步骤

无论任何xp模块，只要作用域为工商银行，就会导致工商银行卡在启动页面无法打开

### Expected behaviour/预期行为

N/A

### Actual behaviour/实际行为

N/A

### Xposed Module List/Xposed 模块列表

```shell
BankRX
对话框取消
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

1.8.5-6650

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

N/A

**Comment by yujincheng08** [comment]
https://github.com/jmpews/Dobby/issues/201
