### ISSUE TITLE
[Bug] Bluetooth will crash on 1.8.x

### ISSUE THREAD

**Issue by Hayao0819** [LSPosed/LSPosed#2234]
### Steps to reproduce/复现步骤

1. Install LSPosed 1.8.x (I tested 1.8.1~1.8.5)
2. Restart Android.

### Expected behaviour/预期行为

Bt should work correctly.

### Actual behaviour/实际行为

Same as #2083 

### Xposed Module List/Xposed 模块列表

```shell
I disabled all modules but it changed nothing.
I usually use Lucky Patcher and Hide USB Debugging
```

### Magisk Module List/Magisk 模块列表

```shell
I disabled all modules same as LSPosed without LSPosed but it did too.
```

### LSPosed version/LSPosed 版本

LSPosed 1.8.x Zygisk

### Android version/Android 版本

PixelExperience 13

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-11-18T16_14_33.110843.zip](https://github.com/LSPosed/LSPosed/files/10038931/LSPosed_2022-11-18T16_14_33.110843.zip)

### Additional/增补
 
Before upgrading Android 12 to Android 13, I had used LSPosed 1.7.2 and worked correctly.

**Comment by yujincheng08** [comment]
#2079

**Comment by Hayao0819** [comment]
I have read that but I have disabled *all* modules and restart but Bluetooth does not work

**Comment by yujincheng08** [comment]
lucky patcher cannot be fully disabled even if you disable it in magisk. It persists in the dex cache.
