### ISSUE TITLE
希望能够支持应用方式出现

### ISSUE THREAD

**Issue by StrollStars** [LSPosed/LSPosed#2241]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

否

### Describe the solution you'd like/描述你想要的解决方案

目前安装以寄生方式出现（没找到其他选择），这样的特点是仅在桌面有个图标，其他什么都没留下，不好的地方是若不小心把桌面图标删了，就没有入口了。
如果以应用方式出现，至少不那么容易被误删，要到应用管理里去特意删除。

**Comment by yujincheng08** [comment]
有没有一种可能，我们支持。
