### ISSUE TITLE
[Bug] Iqoo Z5 寄生管理器不起作用

### ISSUE THREAD

**Issue by zxlrj** [LSPosed/LSPosed#2242]
### Steps to reproduce/复现步骤

安装以后，提示创建快捷方式，快捷方式创建成功，点击快捷方式没有反应，只能打开原来的管理器。

### Expected behaviour/预期行为

安装以后，提示创建快捷方式，快捷方式创建成功，点击快捷方式没有反应，只能打开原来的管理器。

### Actual behaviour/实际行为

安装以后，提示创建快捷方式，快捷方式创建成功，点击快捷方式没有反应，只能打开原来的管理器。

### Xposed Module List/Xposed 模块列表

```shell
知了
运动修改器
隐藏应用列表
```

### Magisk Module List/Magisk 模块列表

```shell
隐藏应用列表
shamiko
originos优化
zygisk
自动神仙救砖
```

### LSPosed version/LSPosed 版本

1.8.5（6649）

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-11-22T07_33_41.744.zip](https://github.com/LSPosed/LSPosed/files/10061335/LSPosed_2022-11-22T07_33_41.744.zip)

**Comment by Star-ZER0** [comment]
我可能也有相似的问题，每次刚重启LSPosed寄生管理器和管理应用都能正常使用，过一段时间后寄生管理器就无法打开，管理应用提示LSPosed未安装
LSPosed版本1.8.5，Magisk版本25.2，安卓10（/e/OS1.5）

**Comment by yujincheng08** [comment]
启动器问题，经测试换启动器可以解决。我们这边不修。

@Star-ZER0 你的问题属于 #1919。

**Comment by Star-ZER0** [comment]
> 

更换启动器也不可以使用，如图所示
使用寄生管理器显示Shell频繁停止运行，使用独立的管理器显示LSPosed未安装
![Screenshot_20221122-091528_LSPosed](https://user-images.githubusercontent.com/65442169/203190739-7c9a0164-b89b-4fa8-a0d7-2b9b10f93f04.png)
![Screenshot_20221122-091546_Magisk](https://user-images.githubusercontent.com/65442169/203190750-ae68d9c6-c89a-4f53-840d-c166f8958625.png)

**Comment by yujincheng08** [comment]
@Star-ZER0 你仔细看我说的话。

**Comment by Star-ZER0** [comment]
> @Star-ZER0 你仔细看我说的话。

@yujincheng08 更换桌面启动器为Lawnchair，Nova Launcher，Pixel Launcher也无法使用

**Comment by yujincheng08** [comment]
@Star-ZER0 我说楼主的问题属于启动器问题，你的问题属于 #1919。我什么时候说你的问题是启动器问题？能不能不要浪费大家的时间？

**Comment by Star-ZER0** [comment]
> @Star-ZER0 我说楼主的问题属于启动器问题，你的问题属于 #1919。我什么时候说你的问题是启动器问题？能不能不要浪费大家的时间？

抱歉是我的问题，没仔细看消息
