### ISSUE TITLE
[Bug] Can not launch with dial

### ISSUE THREAD

**Issue by paladin4fan** [LSPosed/LSPosed#2245]
### Steps to reproduce/复现步骤

input *#*#5776733#*#* in 'phone' app

### Expected behaviour/预期行为

Launch the manager app

### Actual behaviour/实际行为

the number inputed disapeared, 
the manager doesn't show up.

### Xposed Module List/Xposed 模块列表

```shell
Thanox
NFC Card Emulator (Disabled)
```

### Magisk Module List/Magisk 模块列表

```shell
Shamiko
LSPosed
Zygisk-Fingerprints-Alipay
NFC Card Emulator
Universal SafetyNet Fix
```

### LSPosed version/LSPosed 版本

1.8.5 6649

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2 （25200）

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-11-24T17_31_39.090435.zip](https://github.com/LSPosed/LSPosed/files/10083267/LSPosed_2022-11-24T17_31_39.090435.zip)

No permission Error in the last line of Log.
Manager App can be opened through the icon in launcher, but if I delete the icon I wouldn't access it using dial.

**Comment by yujincheng08** [comment]
You are not using the debug version.
