### ISSUE TITLE
[Bug] 太平保宝app设置隐藏无效，无法启动，闪退

### ISSUE THREAD

**Issue by cantonadong** [LSPosed/LSPosed#2250]
### Steps to reproduce/复现步骤

下载地址：https://img.life.cntaiping.com/tpbb/app/download/index.html
开启magisk和隐藏后，对这个app无效。强制闪退。

求帮忙解决。谢谢

### Expected behaviour/预期行为

正常启动运行

### Actual behaviour/实际行为

闪退

### Xposed Module List/Xposed 模块列表

```shell
微x
```

### Magisk Module List/Magisk 模块列表

```shell
lsposed
```

### LSPosed version/LSPosed 版本

1.8.5.6649

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2022-11-28T20.08.14.log](https://github.com/LSPosed/LSPosed/files/10104031/magisk_log_2022-11-28T20.08.14.log)

**Comment by yujincheng08** [comment]
![Screenshot_2022-11-28-21-22-43-356_com.android.shell.jpg](https://user-images.githubusercontent.com/5022927/204288460-c5c70cf1-7c45-49c9-8af3-87b326e3059c.jpg)
