### ISSUE TITLE
[Bug] realme V3 Mobile LSPosed APP Flash back and Caton

### ISSUE THREAD

**Issue by xsbb666** [LSPosed/LSPosed#2255]
### Steps to reproduce/复现步骤

重启之后首次打开很慢
过了一会后就打不开了

### Expected behaviour/预期行为

进入软件页面

### Actual behaviour/实际行为

进入软件页面

### Xposed Module List/Xposed 模块列表

```shell
QX模块
微X模块
Fuck Location
禁用FLAG_SECURE
```

### Magisk Module List/Magisk 模块列表

```shell
.core
Shamiko
Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

6649

### Android version/Android 版本

10

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-12-01T17_32_58.197.zip](https://github.com/LSPosed/LSPosed/files/10131133/LSPosed_2022-12-01T17_32_58.197.zip)

**Comment by yujincheng08** [comment]
Duplicate of #1919
