### ISSUE TITLE
[Wiki-Bug]  Wiki中有一行代码有误

### ISSUE THREAD

**Issue by zhbzhbzhbz** [LSPosed/LSPosed#2258]
在 https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences#for-the-hooked-app 中，
```
SharedPreferences pref = new XSharedPreferences(BuildConfig.APPLICATION_ID, path);
return pref.getFile().canRead() ? pref : null;
```
的`SharedPreferences`应为`XSharedPreferences`，否则无法调用到`getFile()`函数

**Comment by Howard20181** [comment]
已修正
