### ISSUE TITLE
[Feature Request] hide "security space" plz

### ISSUE THREAD

**Issue by httpsColon** [LSPosed/LSPosed#2267]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

When security space appears, it means that the user has enabled the Android multi-user feature, which is mostly used for privacy protection in mainland China, such as miui's second space. when the police check the phone and see security space, they will most likely suspect that you have installed vpn software in the second space, the so-called "illegal" behavior

### Describe the solution you'd like/描述你想要的解决方案

Put the security space tab in the settings or use a special way to call out

**Comment by yujincheng08** [comment]
Will police check LSPosed? lol.
