### ISSUE TITLE
[Bug] System launcher crashes

### ISSUE THREAD

**Issue by cyberboh** [LSPosed/LSPosed#2271]
### Steps to reproduce/复现步骤

1. Install from magisk
2. Reboot phone
3. Pull down notification bar to add icon from lsposed manager (yes bcz lsposed won't place icon after phone reboot)
4. After icon has been adden, then press and hold it
5. System launcher crashes as soon as i pressed it

### Expected behaviour/预期行为

It does not crashes

### Actual behaviour/实际行为

It crashes

### Xposed Module List/Xposed 模块列表

```shell
Hide my applist
Instaprefs
Killergram
TwiFucker
XprivacyLua
```

### Magisk Module List/Magisk 模块列表

```shell
Music Revanced
Shamiko
Universal SafetyNet Fix
YouTube Revanced
Zygisk - LSposed
```

### LSPosed version/LSPosed 版本

1.8.5-6675

### Android version/Android 版本

CrDroid 9 Official (Android 13)

### Magisk version/Magisk 版本

44643ad7-alpha 25205

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-12-04T17_22_20.797720.zip](https://github.com/LSPosed/LSPosed/files/10148300/LSPosed_2022-12-04T17_22_20.797720.zip)

**Comment by Howard20181** [comment]
Try [LSPosed-v1.8.5-6676-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/10148535/LSPosed-v1.8.5-6676-zygisk-debug.zip)

**Comment by cyberboh** [comment]
> Try [LSPosed-v1.8.5-6676-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/10148535/LSPosed-v1.8.5-6676-zygisk-debug.zip)

Still crashes :(
[LSPosed_2022-12-04T20_10_02.817628.zip](https://github.com/LSPosed/LSPosed/files/10148553/LSPosed_2022-12-04T20_10_02.817628.zip)
Log from the rom:
`http://paste.crdroid.net/YN3DBu`

**Comment by Howard20181** [comment]
@cyberboh Did you remove the previous shortcut?

**Comment by cyberboh** [comment]
> @cyberboh Did you remove the previous shortcut?

Uooh.. now works after removed old shortcut. 
Thank you. :)

**Comment by cyberboh** [comment]
@Howard20181 Um.. but somehow its getting weird
It still crashes if i drag and drop the LSposed shortcut icon
It works just if i select "add to home screen"

**Comment by Howard20181** [comment]
Try to create a shortcut from Magisk Manager with random package name to see if dragging will crash

**Comment by cyberboh** [comment]
> Try to create a shortcut from Magisk Manager with random package name to see if dragging will crash

How to do it? Does magisk manager let create lsposed shorcut? 
Do i need to Hide magisk app name to random package ID?

**Comment by Howard20181** [comment]
No, we need to make sure that your launcher or system has no problem creating shortcuts to other applications

**Comment by cyberboh** [comment]
> > Does magisk manager let create lsposed shorcut?
> 
> No, we need to make sure that your launcher or system has no problem creating shortcuts to other applications

Ok, tested with magisk alpha, i recently create shortcut for it, dragging the shortcut then press and hold it , does not make launcher crashes.

**Comment by Howard20181** [comment]
@cyberboh Which launcher are you using?

**Comment by cyberboh** [comment]
> @cyberboh Which launcher are you using?

Its stock crdroid launcher, named CrDroid Home based on Launcher3 by AOSP.
You can grab it here: `https://we.tl/t-2nbbBQ3jag`

**Comment by Howard20181** [comment]
Try this 
[LSPosed-v1.8.5-6676-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/10148867/LSPosed-v1.8.5-6676-zygisk-debug.zip)

**Comment by Howard20181** [comment]
Try this https://github.com/LSPosed/LSPosed/actions/runs/3613964754

**Comment by cyberboh** [comment]
> Try this https://github.com/LSPosed/LSPosed/actions/runs/3613964754

Yea, thank you
Finally it works. 
Sorry, for late reply>,<

**Comment by Howard20181** [comment]
Does CI build 6682 also work properly?
