### ISSUE TITLE
[Bug] NotificationService: No Channel found for pkg=android, channelId=lsposed_status

### ISSUE THREAD

**Issue by mywalkb** [LSPosed/LSPosed#2276]
### Steps to reproduce/复现步骤

- Install LSPosed on Android 9
- Reboot
- Got error on logcat and a toast with a warning

### Expected behaviour/预期行为

No error in log and no toast with a warning. Should appear an android notification.

### Actual behaviour/实际行为

Appear a toast with a warning: 
```
Developer warning for package "android" 
Failed to post notification on channel....
```

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk - Lsposed
```

### LSPosed version/LSPosed 版本

6682

### Android version/Android 版本

9

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[logcat.zip](https://github.com/LSPosed/LSPosed/files/10149470/logcat.zip)

**Comment by mywalkb** [comment]
I think this issue is related to this commit 2aec14482bf96406fe1c5a5d153175fbd5a9075c
@vvb2060 could you confirm?

**Comment by Hacker-rep** [comment]
I fixed it
