### ISSUE TITLE
native hook maps文件会留下痕迹

### ISSUE THREAD

**Issue by ndl1302732** [LSPosed/LSPosed#2289]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

lsposed native hook功能非常好用。但是使用native hook功能时，会在目标App的maps文件中会留下痕迹：
PD2115:/ # cat /proc/2607/maps | grep yyk
731fa92000-731fad1000 r-xp 00001000 fd:08 197900                         /data/app/~~zWw7cIVSd4RKTrpDkDlcAw==/com.yyk.xp-P27jwZ-oV5NS3zNDkZ5Z4Q==/base.apk
731fae0000-731fae2000 r--p 0003f000 fd:08 197900                         /data/app/~~zWw7cIVSd4RKTrpDkDlcAw==/com.yyk.xp-P27jwZ-oV5NS3zNDkZ5Z4Q==/base.apk
731fae2000-731fae3000 rw-p 00041000 fd:08 197900                         /data/app/~~zWw7cIVSd4RKTrpDkDlcAw==/com.yyk.xp-P27jwZ-oV5NS3zNDkZ5Z4Q==/base.apk

如果仅仅hook java好像没有这个痕迹

### Describe the solution you'd like/描述你想要的解决方案

期待大佬下个版本能隐藏这个特征

**Comment by vvb2060** [comment]
预期行为
