### ISSUE TITLE
你到底在干嘛？直接 block 了。

### ISSUE THREAD

**Issue by mymine** [LSPosed/LSPosed#229]
你到底在干嘛？直接 block 了。

_Originally posted by @yujincheng08 in https://github.com/LSPosed/LSPosed/issues/227#issuecomment-787401476_
报错，我就直接关闭了。

**Comment by canyie** [comment]
pull 是从仓库里拉取代码，pull request是把自己的代码申请提交到仓库，请分清这两者。
