### ISSUE TITLE
[Feature Request] native hook 时能否提供dlopen dlsym增强函数

### ISSUE THREAD

**Issue by ndl1302732** [LSPosed/LSPosed#2294]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

如果要hook系统so，比如libart.so中的某些函数, 因为android高版本的限制，直接调用系统提供的dlopen会失败。
能否在框架层直接提供增强版的dlopen和dlsym呢。这样的好处是，每个使用LSP框架的人，将获得开箱即用的功能，不需要自己再去处理这些问题。

### Describe the solution you'd like/描述你想要的解决方案

期待改善

**Comment by buffiano** [comment]
No

**Comment by PhyoPhyochit** [comment]
LDP

**Comment by HandsomeBoy01** [comment]
English, please.
