### ISSUE TITLE
[Bug] lsposed get error: FAILED BINDER TRANSACTION

### ISSUE THREAD

**Issue by zhangjun7461** [LSPosed/LSPosed#2304]
### Steps to reproduce/复现步骤

1.  install lsposed1.8.5(6649)  for zygisk
2.  install Fuck VIP 6.0 from lsposed
3.  enable Fuck VIP and enable 加压缩全能王(com.cjtec.uncompress)
4.  lanuch 加压缩全能王(com.cjtec.uncompress) but nothing happen
5.  check lsposed log 

### Expected behaviour/预期行为

加压缩全能王(com.cjtec.uncompress) should have vip

### Actual behaviour/实际行为

nothing happen

### Xposed Module List/Xposed 模块列表

```shell
Fuck VIP 6.0 (enable)
对话框取消修复版 (disable)
mHOOK管理器(disable)
```

### Magisk Module List/Magisk 模块列表

```shell
Shamiko v0.6(126)
Zygisk - LSPosed v1.8.5(6649)
```

### LSPosed version/LSPosed 版本

v1.8.5(6649) for zygisk

### Android version/Android 版本

10

### Magisk version/Magisk 版本

25.2(25200)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2022-12-30T11_04_45.335.zip](https://github.com/LSPosed/LSPosed/files/10322989/LSPosed_2022-12-30T11_04_45.335.zip)

**Comment by vvb2060** [comment]
no log

**Comment by zhangjun7461** [comment]
[LSPosed_2022-12-30T11_04_45.335.zip](https://github.com/LSPosed/LSPosed/files/10322980/LSPosed_2022-12-30T11_04_45.335.zip)

**Comment by zhangjun7461** [comment]
sorry , log upload failure ，i have upload again.

**Comment by vvb2060** [comment]
> I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志


latest version is 6695

**Comment by zhangjun7461** [comment]
https://github.com/LSPosed/LSPosed/releases

but from this url, i  can only find 6649, where can i find 6695? thank you .

**Comment by Howard20181** [comment]
@zhangjun7461 https://t.me/s/LSPosedArchives
