### ISSUE TITLE
[Feature Request] 能否支持http socket之类的代理功能

### ISSUE THREAD

**Issue by lengyefenghan** [LSPosed/LSPosed#2309]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

很多情况下 由于网络原因 无法刷新出模块列表

### Describe the solution you'd like/描述你想要的解决方案

支持http socket之类的常规代理协议，通过使用代理软件加速访问

### Additional context/其他信息

无

**Comment by vvb2060** [comment]
还有人直接用socks5？换 VPN 吧
