### ISSUE TITLE
[Feature Request] Dynamic LSPosed module scope.

### ISSUE THREAD

**Issue by WinterOfBit** [LSPosed/LSPosed#2312]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

**Yes.** 
I'm writting an app whose scope varies according to user's installed apps, and my app would startup and then scan for apps that support the service my app provides. 
Of course telling the user which app supports my service and guide he/she to add these apps to my app's LSPosed scope is okay, but it's annoying a bit and not graceful. 
So I hope to take use of the "Suggeted app" or "Suggested scope" feature of LSPosed Manager, make it possible for LSPosed module develpoers to modify and update module scope("Suggeted app" or "Suggested scope").

### Describe the solution you'd like/描述你想要的解决方案

I noticed that class `org.lsposed.manager.util.ModuleUtil$InstalledModule` method `getScopeList()` takes charge of the scope load function. So I.m wondering if LSPosed could expose the api to module developer? Or alter current get scope list behavior to something like read from a file stored in the system.
I tried to hook LSPosed Manager to implement the function mentioned above...... But it's not graceful and may cause instability.

### Additional context/其他信息

![image](https://user-images.githubusercontent.com/68735689/211160835-2aca0c40-ddc6-4427-b64d-394bdb2aaf06.png)

**Comment by yujincheng08** [comment]
#2303

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/211161066-9ab5ff40-37cc-4002-a8b0-c0fe9d7c08c6.png)

**Comment by WinterOfBit** [comment]
> ![image](https://user-images.githubusercontent.com/5022927/211161066-9ab5ff40-37cc-4002-a8b0-c0fe9d7c08c6.png)

Quite like what I'm talking about. Thanks for creating this great app by the way!
Suggetion: What If I want to add a lot of packages to the scope?

**Comment by yujincheng08** [comment]
@WinterOfBit request multiple times.

**Comment by WinterOfBit** [comment]
> @WinterOfBit request multiple times.

I mean.... the notification banner would pop up constantly then....

**Comment by yujincheng08** [comment]
no worries, there can only be one notification for each module.

**Comment by WinterOfBit** [comment]
> no worries, there can only be one notification for each module.

that would be awesome.

**Comment by WinterOfBit** [comment]
ok I just noticed this feature is a Todo already...... Sorry for disturbing, I guess I could just keep expecting.
