### ISSUE TITLE
[Bug] Crash/Can't open LSpose after installed on Realme 6

### ISSUE THREAD

**Issue by gaduaxe** [LSPosed/LSPosed#2316]
### Steps to reproduce/复现步骤

1. Install LSPode v1.8.5 (6649) successfully on Realme 6 Pro, Android 10, Magisk v25 with 
2. Reboot
3. Open LSPod > No thing happen, seem Crash - refer logs

### Expected behaviour/预期行为

Can open

### Actual behaviour/实际行为

Crash
01-12 11:43:09.208 24514 24514 E AndroidRuntime: FATAL EXCEPTION: main
01-12 11:43:09.208 24514 24514 E AndroidRuntime: Process: com.android.shell, PID: 24514
01-12 11:43:09.208 24514 24514 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3499)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3653)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:151)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:111)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2224)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:228)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7826)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7962)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7951)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3474)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	... 11 more

### Xposed Module List/Xposed 模块列表

```shell
LSPode
MagiskHide Props
Shamiko
SystemHost Less
Universal SafetyNet
```

### Magisk Module List/Magisk 模块列表

```shell
LSPode
MagiskHide Props
Shamiko
SystemHost Less
Universal SafetyNet
```

### LSPosed version/LSPosed 版本

1.8.5 (6649)

### Android version/Android 版本

10

### Magisk version/Magisk 版本

25

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

01-12 11:43:09.208 24514 24514 E AndroidRuntime: FATAL EXCEPTION: main
01-12 11:43:09.208 24514 24514 E AndroidRuntime: Process: com.android.shell, PID: 24514
01-12 11:43:09.208 24514 24514 E AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.android.shell/com.android.shell.BugreportWarningActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3499)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3653)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:83)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:151)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:111)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2224)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:107)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:228)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7826)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:981)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'boolean android.content.Intent.hasExtra(java.lang.String)' on a null object reference
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at com.android.shell.BugreportWarningActivity.onCreate(BugreportWarningActivity.java:54)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.Activity.perform
[LSPOse_Realme 6 Pro_bugreport.zip](https://github.com/LSPosed/LSPosed/files/10398355/LSPOse_Realme.6.Pro_bugreport.zip)
Create(Activity.java:7962)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.Activity.performCreate(Activity.java:7951)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1307)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3474)
01-12 11:43:09.208 24514 24514 E AndroidRuntime: 	... 11 more

**Comment by yujincheng08** [comment]
send full log

**Comment by gaduaxe** [comment]
> send full log

HI I already attached full logs above
https://github.com/LSPosed/LSPosed/files/10398355/LSPOse_Realme.6.Pro_bugreport.zip

Plz check...

**Comment by gaduaxe** [comment]
@yujincheng08 

HI I already attached full logs above
https://github.com/LSPosed/LSPosed/files/10398355/LSPOse_Realme.6.Pro_bugreport.zip
