### ISSUE TITLE
[Bug] 在 WSA 中安装后无法创建寄生管理器快捷方式

### ISSUE THREAD

**Issue by flaccida** [LSPosed/LSPosed#2330]
### Steps to reproduce/复现步骤

1. 使用 [MagiskOnWSALocal](https://github.com/LSPosed/MagiskOnWSALocal) 安装 WSA，然后安装 [LSPosed-v1.8.5-6649-zygisk-release.zip](https://github.com/LSPosed/LSPosed/releases/download/v1.8.5/LSPosed-v1.8.5-6649-zygisk-release.zip)
2. 没有寄生管理器快捷方式，无法打开寄生管理器
3. 在 Google Play 中找到并安装 LSPosed ，打开后在设置中点击「创建快捷方式」，卸载管理器后依然没有寄生管理器快捷方式

### Expected behaviour/预期行为

出现寄生管理器快捷方式

### Actual behaviour/实际行为

没有寄生管理器快捷方式

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

1.8.5

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

N/A

**Comment by Howard20181** [comment]
@flaccida 你手动安装个桌面
