### ISSUE TITLE
[Bug] video is not being recorded in Netflix in Redmi Note 9 android 12

### ISSUE THREAD

**Issue by suman709423** [LSPosed/LSPosed#2339]
### Steps to reproduce/复现步骤

Flashed module rebooted
Screenshot is okay with all apps
Video not recording

### Expected behaviour/预期行为

Video should be recorded.

### Actual behaviour/实际行为

Black screen recording.

### Xposed Module List/Xposed 模块列表

```shell
Disable-flag_secure
YouTube AdAway
```

### Magisk Module List/Magisk 模块列表

```shell
Magisk bootloop saver
Systemless host
Universal safetynet
Zygisk lsposed
```

### LSPosed version/LSPosed 版本

1.8.6-6712

### Android version/Android 版本

12

### Magisk version/Magisk 版本

24.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-01-17T02_02_11.727945.zip](https://github.com/LSPosed/LSPosed/files/10429298/LSPosed_2023-01-17T02_02_11.727945.zip)

[LSPosed_2023-01-17T02_01_55.354914.zip](https://github.com/LSPosed/LSPosed/files/10429300/LSPosed_2023-01-17T02_01_55.354914.zip)

**Comment by yujincheng08** [comment]
not lsposed's issue
