### ISSUE TITLE
[BUG] boot loop

### ISSUE THREAD

**Issue by hsheidaryarad** [LSPosed/LSPosed#234]
Hi,  please suppor API 26 (android8), again. Dont drop it support,  my devise galaxy s7edge and android8 , when up to date to new lsposed framework update stuck in boot loop,  please fix it again,  thanks alot.

**Comment by yujincheng08** [comment]
We use [DelegateLastClassLoader](https://developer.android.com/reference/dalvik/system/DelegateLastClassLoader) which only supports Android 8.1+ so sorry it won't be fixed. You can use third-party rom.
