### ISSUE TITLE
[Bug] Lsposed notifications can't be disabled 

### ISSUE THREAD

**Issue by whitewallman** [LSPosed/LSPosed#2340]
### Steps to reproduce/复现步骤

Disable Lsposed notifications by long press notification and save
Reboot
Lsposed notifications return

### Expected behaviour/预期行为

Lsposed notifications should stay disabled once disabled.

### Actual behaviour/实际行为

Notifications return after reboot.

### Xposed Module List/Xposed 模块列表

```shell
AOSPMods
```

### Magisk Module List/Magisk 模块列表

```shell
Lsposed
Universal Safetynet fix
AOSPMods
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

13 (January update)

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-01-16T18_59_56.509641.zip](https://github.com/LSPosed/LSPosed/files/10430066/LSPosed_2023-01-16T18_59_56.509641.zip)

**Comment by asamofal** [comment]
Why is it closed without an answer? Or are you saying there that "closed as not planned" means this is not a bug but a feature?
That notification is just trash. Why should I see it all the time?

**Comment by yujincheng08** [comment]
closed it as not planned because it can already be disabled. You don't know how to disable it does not mean it cannot be disabled.
