### ISSUE TITLE
请提供一个选项来关闭应用程序的通知. Please offer an option to turn off the notification from the app itself. Android system on OneUI does not allow turning off notifications via system settings[Bug] 

### ISSUE THREAD

**Issue by ertmuirm** [LSPosed/LSPosed#2341]
### Steps to reproduce/复现步骤

Startup system
Lsposed notification appears
Unable to remove notification

### Expected behaviour/预期行为

Android system should allow notification removal 

### Actual behaviour/实际行为

Android system not able to turn off Lsposed notification (option is grayed out)

### Xposed Module List/Xposed 模块列表

```shell
N.A.
```

### Magisk Module List/Magisk 模块列表

```shell
N.A.
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

N/A

**Comment by youling257** [comment]
systemui tuner, set notification time.
![Screenshot_2023-02-24-19-54-37-49_da9f505c70c297210596b05469ecc5de](https://user-images.githubusercontent.com/16304724/221241209-0595119a-2d62-4c82-bdb5-23e4e691cf85.jpg)
![Screenshot_2023-02-24-19-48-05-53_92b64b2a7aa6eb3771ed6e18d0029815](https://user-images.githubusercontent.com/16304724/221241248-f54e43e4-f363-426f-b666-0a14f23f55f7.jpg)
