### ISSUE TITLE
[Bug] after upgrade to 1.8.6 in lsposed Manager it's not installed 

### ISSUE THREAD

**Issue by xperia-droid** [LSPosed/LSPosed#2350]
### Steps to reproduce/复现步骤

When I try to upgrade from 1.8.5 to 1.8.6 and restart the phone I got the message in lsposed Manager it is not installed. But in Foxx magisk Manager it's says it's installed.
I tried different variations to update.
In fox magisk Manager downloaded and installed. Discouraged l downloaded it from GitHub and installed inside fox magisk Manager and in normal magisk Manager. Result is the same in the lsposed Manager.
The installation progress never returned an error message. 

My phone is an Pixel 5 with Android 13 and December 2022 update on crdroid.

### Expected behaviour/预期行为

It should be shown inside the Manager that it's installed and I can use it

### Actual behaviour/实际行为

Return message it's not installed 

### Xposed Module List/Xposed 模块列表

```shell
Aosp mods
Hide my app list
Hide app updates
```

### Magisk Module List/Magisk 模块列表

```shell
Aosp mods
Afwall boot anti leak
Busybox built-in
Dialer Framework for Google phonee
Hide userdebug
Shamiko
Universal safetynet fix
Zygisk lsposed
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

The log function is greyed out inside the Manager app.
Their it says version 1.8.5 (6649).
As provided inside the release notes their should be an notification to open the Manager. But I can't enable notifications inside the app settings menu from phone

**Comment by cooltronicpl** [comment]
On Magisk 26.1 on Huawei P10 Lite also app is not avalaible after installing
