### ISSUE TITLE
[Bug] LSPosed-v1.8.6-zygisk-release.zip 更新后卡屏？

### ISSUE THREAD

**Issue by aabababb** [LSPosed/LSPosed#2352]
### Steps to reproduce/复现步骤

在 magisk 25.2 更新LSPosed-v1.8.6-zygisk-release.zip 

### Expected behaviour/预期行为

开机

### Actual behaviour/实际行为

小米10青春版  卡在5G屏？

### Xposed Module List/Xposed 模块列表

```shell
LSPosed
Shamiko-v0.5.2
```

### Magisk Module List/Magisk 模块列表

```shell
LSPosed
Shamiko-v0.5.2
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

10

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

n/a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

卡在5G屏

**Comment by yujincheng08** [comment]
没日志不修。
