### ISSUE TITLE
[Bug] Notification lsposed is displayed for life

### ISSUE THREAD

**Issue by grysor** [LSPosed/LSPosed#2355]
### Steps to reproduce/复现步骤

Hello
after installing lsposed lsposed 1.8.6 (6712) ,this notification stays all the time 24h/24h impossible to delete it :(
How to solve this problem please?

![Screenshot_20230123-214913_Nova Launcher](https://user-images.githubusercontent.com/35570935/214166061-429558fe-ceb9-44f9-af40-68282608069c.png)

![Screenshot_20230123-214926_Nova Launcher](https://user-images.githubusercontent.com/35570935/214166082-5ae1932b-1c50-460f-8616-e69e5492ddf2.png)

### Expected behaviour/预期行为

the notification should disappear

### Actual behaviour/实际行为

the notification never disappears

### Xposed Module List/Xposed 模块列表

```shell
youtube adaway 5.0.4
```

### Magisk Module List/Magisk 模块列表

```shell
shamiko
universal safetynet fix 
zygisk lsposed 1.8.6 (6712)
```

### LSPosed version/LSPosed 版本

zygisk lsposed 1.8.6 (6712)

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.2 (25200) 

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[logs-2023-01-24-01-12-35.zip](https://github.com/LSPosed/LSPosed/files/10484738/logs-2023-01-24-01-12-35.zip)

**Comment by grysor** [comment]
@vvb2060  what do you mean by what you wrote? : " closed this as not planned " Can you explain it to me? :(

**Comment by objestik** [comment]
It can be disabled in manager settings after creating a shortcut.
