### ISSUE TITLE
[Bug] Dex优化器包装 挂载失败

### ISSUE THREAD

**Issue by pchpub** [LSPosed/LSPosed#2357]
### Steps to reproduce/复现步骤

安装最新ci debug版
打开lsposed管理器

### Expected behaviour/预期行为

Dex优化器包装 正常工作

### Actual behaviour/实际行为

Dex优化器包装 挂载失败

### Xposed Module List/Xposed 模块列表

```shell
未启用任何xposed模块
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

6714

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25206

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[log.zip](https://github.com/LSPosed/LSPosed/files/10498190/log.zip)

**Comment by vvb2060** [comment]
https://t.me/magiskalpha/542

**Comment by yujincheng08** [comment]
alpha 引起的，不会修复。
