### ISSUE TITLE
[Bug] Inability to load New-API (libxposed) modules even on Canary build. (1.8.6-6714)

### ISSUE THREAD

**Issue by autisoid** [LSPosed/LSPosed#2358]
### Steps to reproduce/复现步骤

I've made a module with new api as I couldn't find old (de.robv) anywhere (I mean the jars)
So upon the module loads I get this:
Loading legacy module net.aal.wrapped.ru.xWhitey from {}
Loading class net.aal.wrapped.ru.xWhitey.DisableCriticalBatteryShutdown
This class doesn't implement any sub-interface of IXposedMod, skipping it!

### Expected behaviour/预期行为

The new-api module shouldn't load as legacy module

### Actual behaviour/实际行为

The new-api module loads as "legacy"

### Xposed Module List/Xposed 模块列表

```shell
CorePatch, FakeGApps
```

### Magisk Module List/Magisk 模块列表

```shell
BlockADs, Looki75's Product Sans font, Magisk Bootloop Protector, MagiskHide Props Config, Universal SafetyNet Fix, LSPosed
```

### LSPosed version/LSPosed 版本

6714

### Android version/Android 版本

13 (Tiramisu)

### Magisk version/Magisk 版本

25206 Debug

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-01-25T22_59_53.477283.zip](https://github.com/LSPosed/LSPosed/files/10503206/LSPosed_2023-01-25T22_59_53.477283.zip)

**Comment by vvb2060** [comment]
Using CI build from PR is very dangerous and we do not support it in any way.

**Comment by yujincheng08** [comment]
You have to define `META-INF/xposed/java_init.list`
