### ISSUE TITLE
[Bug] Unable to open LSPosed manager on GrapheneOS due to a crash (Segmentation fault)

### ISSUE THREAD

**Issue by mmm29** [LSPosed/LSPosed#2363]
### Steps to reproduce/复现步骤

1. Install Magisk
2. Install LSPosed Zygisk module
3. Reboot
4. Open LSPosed manager (from either a shortcut, dialer sequence or notification tap).

### Expected behaviour/预期行为

Expect LSPosed manager to open wiithout a crash.

### Actual behaviour/实际行为

When I open LSPosed manager (from either a shortcut, dialer sequence or notification tap), everything freezes for about 2 seconds, and then I see a message that is apparently a GrapheneOS crash message dialog:
"Bug reports contain data from system's verious log files, which may include data you consider sensitive (such as app-usage and location data). Only share bug reports with people and apps you trust.".
After pressing either Cancel or Ok the dialog closes and I can continue to use the phone, but LSPosed manager was not opened.

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
Systemless Hosts (default magisk module)
```

### LSPosed version/LSPosed 版本

1.8.6 (6712)

### Android version/Android 版本

Graphene OS (Android 13)

### Magisk version/Magisk 版本

25.2 (25200)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志
[logs.txt](https://github.com/LSPosed/LSPosed/files/10571644/logs.txt)

**Comment by yujincheng08** [comment]
we are not going to support Graphene
