### ISSUE TITLE
[Feature Request] 针对老旧应用兼容exposed框架

### ISSUE THREAD

**Issue by ajasonwang** [LSPosed/LSPosed#2366]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

像socery图标库这种很久没有更新的应用，安装了lsposed的情况下，依然提示未安装xposed框架

### Describe the solution you'd like/描述你想要的解决方案

当然是socery软件没有及时适配的问题，但是如果lsposed本身能向下兼容就太好了，感谢付出

### Additional context/其他信息

![Screenshot_2023-02-04-07-51-38-494_com sorcerer sorcery iconpack-edit](https://user-images.githubusercontent.com/11936017/216731894-9fb538e0-3ff1-4a9f-8118-c52204d850d5.jpg)

**Comment by yujincheng08** [comment]
吃力不讨好，不搞。

**Comment by ajasonwang** [comment]
> 吃力不讨好，不搞。

好吧，可以理解

**Comment by vvb2060** [comment]
八成是需要安装 xposed installer，lsposed不会兼容这种行为。
