### ISSUE TITLE
[TODO] Hide manager package 

### ISSUE THREAD

**Issue by yujincheng08** [LSPosed/LSPosed#238]

**Comment by VD171** [comment]
Repacking the manager will be very useful for privacy.
On LSPosed v1.2.2, the zip file now contains a manager.
May I enjoy the issue and suggest to change the expression "LSPosed Manager" to "LSPosed App" like Magisk did? :-)
We was using "Xposed Installer" in past, but now we have modules and apps merged into only one file.

**Comment by gabrc52** [comment]
In a few years, corporations like banks will catch up and start refusing to operate if they detect this package ID. So, it would certainly be helpful.

**Comment by xerta555** [comment]
This feature would indeed be much appreciated.
Many financial institutions & other companies have already set up checks with lists of package names...

I hope that in the near future a system protection enforcement will be implemented to exclude the possibility for any non-system application to get the package names of other applications installed on a device, all of which would cause less headaches for everyone.

**Comment by gabrc52** [comment]
>  Many financial institutions & other companies have already set up checks with lists of package names...

This could be fixed with an LSPosed module ;)

> I hope that in the near future a system protection enforcement will be implemented to exclude the possibility for any non-system application to get the package names of other applications installed on a device, all of which would cause less headaches for everyone.

Precisely. Some of their blocklists are just straight ridiculous

**Comment by VD171** [comment]
We need to understand the problem.
Every security app, reallys need to check for root/xposed, this is basic.
Every security app, really needs to check for root/xposed, this is basic.
So any basic user will be avoided.
We, as experienced users, can bypass the check because we know what we are doing.
But we can't ask everyone to disable the check because it really needs to be realized.
I mean, basic users need to be avoided !

**Comment by xerta555** [comment]
> This could be fixed with an LSPosed module ;)

You still need to know the programming language..

> Precisely. Some of their blocklists are just straight ridiculous

Totally agree.

@VD171 it could be implemented in the LSPosed Framework as an option disabled by default, if for an reason a user need it, he will just have to enable this feature.

**Comment by SekiBetu** [comment]
> it could be implemented in the LSPosed Framework as an option disabled by default, if for an reason a user need it, he will just have to enable this feature.

Totally agree.

**Comment by DIYgod** [comment]
The HSBC HK app already detects the package name and makes itself unusable. I hope this feature will be implemented soon.

**Comment by yujincheng08** [comment]
> The HSBC HK app already detects the package name and makes itself unusable. I hope this feature will be implemented soon.

Its save for u to temporally uninstall the manager.

**Comment by xerta555** [comment]
Hi, would it be possible to have an idea if this function is planned soon or if its implementation is postponed?

Not that i want to force anyone's hand, far from it, but i ask the question to have an idea of time.
Thanks in advance.

**Comment by SekiBetu** [comment]
> We need to understand the problem.
> Every security app, really needs to check for root/xposed, this is basic.
> So any basic user will be avoided.
> We, as experienced users, can bypass the check because we know what we are doing.
> But we can't ask everyone to disable the check because it really needs to be realized.
> I mean, basic users need to be avoided !

once you unlocked the bootloader, you are no longer a basic user.

**Comment by doclucas** [comment]
This is actually a critical issue. Lots of banking apps are failing because they can detect LSposed is installed, even when they don't have storage permission and even when safetynet pass just fine.
Hopefully there will be a way to hide it very soon.

**Comment by kevin01523** [comment]
you can hide it via some apps but thats kinda bruteforcing hiding all apps from it.
yeah i found some apps updated that added lsposed to its check it exist then if true = root user list
like
 com.evozi.injector
a local bank
shoppee
lazada etc 
the apps i mentioned kinda have exotic ways of finding root etc they don't use safetynet but its kinda straight up hacky and privacy violating methods

**Comment by VD171** [comment]
You can hide lsposed easily.
Just hide it.

**Comment by xerta555** [comment]
> 
> 
> You can hide lsposed easily.
> Just hide it.

With wich app/tools do you hide lsposed?

**Comment by vishvendrasingh** [comment]
[Hide my applist] module is able to hide lsposed but If I check with applist detector lsposed gets detected under abnormal environment for xprivacyLua module and syscall file detection for lsposed manager found. So still waiting for fix of randomised package name.

**Comment by kevin01523** [comment]
Testing it now seems no issues so far

**Comment by kevin01523** [comment]
@yujincheng08 @canyie latest build LSPosed-v1.5.4-6043-release.zip seems to brake the shortcut of lsposed on the launcher if you try to tap and hold the lsposed shortcut the launcher crashes.tapping the launcher works and enters lsposed gui but cant seems to remove shortcut even after disabling lsposed on magisk manager and restarting phone
