### ISSUE TITLE
[Feature Request] native hook not support the child process / 原生钩子不支持子进程

### ISSUE THREAD

**Issue by r21N8AeVeov8** [LSPosed/LSPosed#2380]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Runtime.getRuntime().exec("child");
the child process not hooked. / 子进程未被钩住

### Describe the solution you'd like/描述你想要的解决方案

hook the child process /  钩住子进程

**Comment by yujincheng08** [comment]
expected.
