### ISSUE TITLE
[Bug] Updated to 1.8.6 from 1.8.5 and Now a Permanent Notification!

### ISSUE THREAD

**Issue by whitedavidp** [LSPosed/LSPosed#2381]
### Steps to reproduce/复现步骤

1. Updated to 1.8.6 from 1.8.5 on my Android 9, LG V40
2. Rebooted after update
3. Now there is a permanent notification "LSPosed loaded /  Tap to pen manager" that was not there before

### Expected behaviour/预期行为

I don't see why this is suddenly necessary. If I want to open the manager, I can do it easily enough from the app drawer.

### Actual behaviour/实际行为

I would wish there is some way to at least make this optional. I do not recall seeing it in 1.8.5

### Xposed Module List/Xposed 模块列表

```shell
Gravity Box P
UnToaster
XDowngrader
Xposed Edge
Secure Settings (not enabled)
```

### Magisk Module List/Magisk 模块列表

```shell
Debloater
Busybox
App Systemizer
Zygisk
Viper4AndroidFX
Systemless hosts
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

9

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Not sure how to get this or if needed. I think the description is pretty clear.

**Comment by yujincheng08** [comment]
disable it if u dont like the notification

**Comment by whitedavidp** [comment]
Thanks for the speedy response. But how? The notification's settings say "notifications form this app can't be turned off".

**Comment by yujincheng08** [comment]
i wish u take at least a minute to read the changelog.

**Comment by whitedavidp** [comment]
You mean this "Add notification to open parasitic manager"? I gotta tell you I have no idea what this even means. Sorry to bother you. I will just restore 1.8.5 from TWRP backup last night and not update.

**Comment by whitedavidp** [comment]
And you say above "disable it if u dont like the notification" but there is no way to disable it (that I can find).

**Comment by yujincheng08** [comment]
![](https://user-images.githubusercontent.com/5022927/218219345-dfaf0345-e872-4b3c-957e-30332fc87002.jpg)

**Comment by whitedavidp** [comment]
Didn't want no shortcut. So this wouldn't work. Finally I just told the thing NO SHORTCUT - NEVER and it worked. Thanks so much.

**Comment by yujincheng08** [comment]
cannot understand ur engish. please refine it.

**Comment by whitedavidp** [comment]
Thanks. Never mind. This is all too hard and I have finally been able to disable the notification by telling LsPosed manager app to NEVER create shortcut to parasitic manager (whatever that is). Thanks for your time and help.

**Comment by smhc** [comment]
The reason this isn't very obvious is because to hide notifications you first have to create a shortcut, which is not documented anywhere. On top of this, if you upgrade you may already have a shortcut, thus no reason to create another one. It definitely isn't as obvious as just reading the changelog.

**Comment by NuLL3rr0r** [comment]
Where can I find the option to create or not to create the shortcut? It asked me the first time. I don't remember what I answered. Now, it does not matter whether I install or remove the manager app from Google Play, the notification is persistent and I cannot turn off the notification from LSPOSED settings.
