### ISSUE TITLE
[Bug]  LSPosed 在小米平板4基于 Android 8.1 的 MIUI 下的兼容性问题

### ISSUE THREAD

**Issue by oubeichen** [LSPosed/LSPosed#2382]
### Steps to reproduce/复现步骤

使用小米平板4一直最后一个开发版，基于Android8.1的MIUI10。
最新版LSPosed 1.6.8，后述模块也都是仓库里能下载的最新的。

### Expected behaviour/预期行为

模块正常使用

### Actual behaviour/实际行为

一部分模块开启之后也没有起到作用（比如FUCKDMZJ，不仅没有效果，而且没有界面，同样模块和大妈之家的版本，在手机上能正常使用）
一部分又能正常使用（哔哩漫游、Customiuinizer）

### Xposed Module List/Xposed 模块列表

```shell
FUCKDMZJ
哔哩漫游（现已禁用，无改善）
Customiuinizer（现已禁用，无改善）
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk-LSPosed
之前用Riru，是一样的情况
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

8.1

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[ae490f66c682c2dfa83d9b3b69818081.zip](https://github.com/LSPosed/LSPosed/files/10724104/ae490f66c682c2dfa83d9b3b69818081.zip)
看LSPosed日志没有报模块的错，所以有点怀疑是LSPosed和这个系统兼容性问题，当然也不排除是模块兼容性问题。
实在不行就尝试把平板升级一下系统了。

**Comment by oubeichen** [comment]
> 在 lsposed 的应用列表里面，长按 dmzj 然后重新优化。
@yujincheng08 
这个早就试过了啊，没有效果，忘记说了

**Comment by oubeichen** [comment]
[b8d9976af9178efcdb548e133680ce7a.zip](https://github.com/LSPosed/LSPosed/files/10724298/b8d9976af9178efcdb548e133680ce7a.zip)
没仔细看说明，重新用CI版（v1.8.6-6719-zygisk）刷了之后问题依旧，上传了一份日志。
顺便现在FUCKDMZJ 是v1.1.9-4(1987)，dmzj普通版 v3.8.1，dmzj社区版是 v2.8.0，被强制更新的。
之前用的dmzj旧版本v3.7.21普通版，同样的模块和应用版本在手机上一切正常而在平板上无效果。

**Comment by yujincheng08** [comment]
先反馈给模块作者。如果有 hook 失效的问题再让模块作者反馈。
