### ISSUE TITLE
Add translator

### ISSUE THREAD

**Issue by Mahantor** [LSPosed/LSPosed#2387]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

The description part of most of the modules is in Chinese and Japanese, and translating it in Google Translate is really time-consuming

### Describe the solution you'd like/描述你想要的解决方案

Since most of the modules are in Chinese, please add a translator to the repository to translate the descriptions and functions of modules written in Chinese, Russian, etc. into English or any other language.

**Comment by Howard20181** [comment]
The module descriptions and names in the repository are provided by the module authors. If you need to translate, please use the [web version](https://modules.lsposed.org/) of the repository and use your browser's translation function.

**Comment by yujincheng08** [comment]
The problem is, there's no free translate API. And there's also privacy concern. So you can only translate it yourself.
