### ISSUE TITLE
[Bug] Cannot create Create shortcut on Flyme

### ISSUE THREAD

**Issue by zsytqnxy** [LSPosed/LSPosed#2388]
### Steps to reproduce/复现步骤

1.Using flyme 9.3.1.0A
2.Start lsposed in the notification bar
3.Click on "Create shortcut"

### Expected behaviour/预期行为

Shortcuts appear on the desktop

### Actual behaviour/实际行为

Nothing is happening

### Xposed Module List/Xposed 模块列表

```shell
N/A（All have been disabled）
```

### Magisk Module List/Magisk 模块列表

```shell
FUCK-SHIT-FILE
JPI-Fonts
MagiskHidePropsConf
rboard-themes
scene_resurgence
scene_swap_controller
STMToolBox
zygisk-storage-isolation
zygisk_lsposed
zygisk_shamiko
```

### LSPosed version/LSPosed 版本

6719

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25.2(25200)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-02-15T23_41_16.835.zip](https://github.com/LSPosed/LSPosed/files/10744933/LSPosed_2023-02-15T23_41_16.835.zip)

**Comment by try2hack** [comment]
extract manager.apk from zip file.
install manager.apk

**Comment by zsytqnxy** [comment]
> extract manager.apk from zip file.
> install manager.apk

This is actually the method I'm currently using.
And, it's not a very important mistake.
