### ISSUE TITLE
[Bug] None of the modules working on LSPosed zygisk

### ISSUE THREAD

**Issue by Abinash-G** [LSPosed/LSPosed#2392]
### Steps to reproduce/复现步骤

. Install snapmod or any modules
. Enable them
. Try to use them
. But not working (but works on riru version)

### Expected behaviour/预期行为

Modules should work fine like in riru version

### Actual behaviour/实际行为

None of the modules working with zygisk version

### Xposed Module List/Xposed 模块列表

```shell
SnapMod
Longshot png
Lucky Patcher
```

### Magisk Module List/Magisk 模块列表

```shell
Universal safety Netfix
Lucky patcher system application
iOS 16 emojis
```

### LSPosed version/LSPosed 版本

6721

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-02-23T11_34_36.064910.zip](https://github.com/LSPosed/LSPosed/files/10810696/LSPosed_2023-02-23T11_34_36.064910.zip)

**Comment by vvb2060** [comment]
Using CI builds from PR outside of our guidance is very dangerous and we do not support it in any way.
