### ISSUE TITLE
[Bug] Unable to breakpoint debug the xposed target app, such as wechat

### ISSUE THREAD

**Issue by xuxingcan** [LSPosed/LSPosed#2401]
### Steps to reproduce/复现步骤

0.I am a xposed developer, I often breakpoint debug the xposed target app so that I can got the right method point.
1.install magisk, open zygisk. all apps are Debuggable after typing "magisk resetprop ro.debuggable 1" on adb
2.install zygosk-lsposed 1.8.6, the debuger of android studio can attach to the target app, but the breakpoint cannot be reached.
3.but install zygosk-lsposed 1.7.2, the debuger of android studio works well.

### Expected behaviour/预期行为

nomatter what lsposed version I install, the debuger of android studio can attach to the target app, and the breakpoint can be reached.

### Actual behaviour/实际行为

install zygosk-lsposed 1.8.6, the debuger of android studio can attach to the target app, but the breakpoint cannot be reached.
but install zygosk-lsposed 1.7.2, the debuger of android studio works well.

### Xposed Module List/Xposed 模块列表

```shell
only one xposed module for wechat which i develop it myself. buy the way, wechat version is 8.0.33
```

### Magisk Module List/Magisk 模块列表

```shell
zygosk-lsposed 1.8.6
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

10

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2023-02-26T20.59.42.log](https://github.com/LSPosed/LSPosed/files/10833738/magisk_log_2023-02-26T20.59.42.log)

**Comment by yujincheng08** [comment]
https://github.com/topjohnwu/Magisk/issues/6229

**Comment by xuxingcan** [comment]
> [topjohnwu/Magisk#6229](https://github.com/topjohnwu/Magisk/issues/6229)

I have read the issue of magisk you wrote, its not the same with this issue. In my issue, what cannot be breakpoint debug is java, and with specific versions. For zygosk-lsposed 1.7.2, the debuger of android studio works well.
