### ISSUE TITLE
[Bug][Native Hook][armeabi-v7a][Thumb mode] Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC)

### ISSUE THREAD

**Issue by r21N8AeVeov8** [LSPosed/LSPosed#2412]
### Steps to reproduce/复现步骤

Doesn't support Thumb mode ?

### Expected behaviour/预期行为

app running

### Actual behaviour/实际行为

app crash
Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC)

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

6712

### Android version/Android 版本

11

### Magisk version/Magisk 版本

25200

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

libc: Fatal signal 4 (SIGILL), code 1 (ILL_ILLOPC), fault addr

**Comment by yujincheng08** [comment]
We directly call Dobby for the native hook. Please report to Dobby instead.
