### ISSUE TITLE
LSPosed could cause Play Integrity API Checker and YASNAC to be off

### ISSUE THREAD

**Issue by supermansaga** [LSPosed/LSPosed#2417]
### Steps to reproduce/复现步骤

1. Install Magisk Canary 25209 and Displax Safety Net Fix mod 1.2 on Kdrag0n 2.4. Play Integrity and YASNAC will be fine.
2. Install LSPosed 1.8.6 and it works great with say Geo Setter 1.3.0 beta. But then you realized Play Integrity would be all off with red X and YASNAC failing safety net on appearance, despite in substance they might still be ok.
3. Turn off LSPosed and reboot. Play Integrity and YASNAC are back to normal.

Not sure what's going on.

### Expected behaviour/预期行为

Play Integrity and YASNAC should be fine even with LSPosed module turned on.

### Actual behaviour/实际行为

In form only, maybe Play Integrity and YASNAC aren't well.

### Xposed Module List/Xposed 模块列表

```shell
Geo Setter 1.3.0 beta
```

### Magisk Module List/Magisk 模块列表

```shell
Shamiko 0.6
Displax Safety Net mod
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

13.0 QPR1 Feb 2023 stable

### Magisk version/Magisk 版本

25209 Canary

### Riru version/Riru 版本

Not applicable

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

N/A. Not really using debut CI version coz I am just a newbie. But checking the box is the only way to submit

**Comment by yujincheng08** [comment]
Wont fix.

**Comment by supermansaga** [comment]
> Wont fix.

Could you please provide more contexts? The bug could be impacting the app called Company Portal

**Comment by Howard20181** [comment]
![Screenshot_2023-03-10-15-14-46-075_com android vending](https://user-images.githubusercontent.com/40033067/224248872-4c9114a0-edfe-49c2-9c58-4f32f85d66c6.jpg)

**Comment by supermansaga** [comment]
> ![Screenshot_2023-03-10-15-14-46-075_com android vending](https://user-images.githubusercontent.com/40033067/224248872-4c9114a0-edfe-49c2-9c58-4f32f85d66c6.jpg)
> 

Didn't work on a pixel 7 pro with a particular banking app. The app keeps crashing when Displax/LSPosed is turned on. Or says phone is rooted if Displax/LSPosed is turned off.
