### ISSUE TITLE
[Bug] Module causes Zygisk to fail

### ISSUE THREAD

**Issue by DaRealCodeWritten** [LSPosed/LSPosed#2419]
### Steps to reproduce/复现步骤

Unsure how to reproduce, Zygisk fails to load while module is active causing the module to become suspended. Zygisk does however work fine if the module is disabled. Note that the module and Zygisk used to work fine until today

### Expected behaviour/预期行为

Zygisk should load as expected with the module enabled

### Actual behaviour/实际行为

Zygisk fails to load causing the module to die

### Xposed Module List/Xposed 模块列表

```shell
Can't access
```

### Magisk Module List/Magisk 模块列表

```shell
Kali Nethunter for Android Dynamic v1.2.0
MagiskHide Props Config v6.1.2-v137
Patches to Android (Lucky Patcher Module) v1.0
System Apps (Lucky Patcher Module) v1.0
Systemless Hosts v1.0
Wireless Firmware for Nethunter v2.0.3
```

### LSPosed version/LSPosed 版本

6840 (v1.8.6)

### Android version/Android 版本

10, Kernel Version 3.18.14

### Magisk version/Magisk 版本

2717feac (25209) (D)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[bugreport-lineage_a5y17lte-QQ3A.200805.001-2023-03-05-16-50-20-dumpstate_log-19178.txt](https://github.com/LSPosed/LSPosed/files/10893451/bugreport-lineage_a5y17lte-QQ3A.200805.001-2023-03-05-16-50-20-dumpstate_log-19178.txt)
[magiskNoLSPosed.log](https://github.com/LSPosed/LSPosed/files/10893452/magiskNoLSPosed.log)
[magiskLSPosedDebug.log](https://github.com/LSPosed/LSPosed/files/10893453/magiskLSPosedDebug.log)
Cannot upload bugreport zip file due to file size, sorry!

**Comment by yujincheng08** [comment]
Sorry, those logs are useless. We cannot help you. Please zip and upload `/data/adb/lspd/log`.
