### ISSUE TITLE
[Bug] Can not hook android framework(lpparam.packageName.equals("android"))

### ISSUE THREAD

**Issue by zhaohengyi** [LSPosed/LSPosed#2421]
### Steps to reproduce/复现步骤

hook system server faild

`

public class XposedModule implements IXposedHookLoadPackage {
    public void handleLoadPackage(final XC_LoadPackage.LoadPackageParam lpparam) {

        if (lpparam.packageName.equals("android")) {
            XposedBridge.log("get in android framework .............");
        }

        try {
            Class<?> ConnectivityService = findClass("com.android.server.ConnectivityService", lpparam.classLoader);
            XposedBridge.log("find class ConnectivityService xxxxxxxxxxxxxxxxxx");
        } catch (Throwable t) {
        }

        try {
            Class<?> ActivityManagerService = findClass("com.android.server.am.ActivityManagerService", lpparam.classLoader);
            XposedBridge.log("find class ActivityManagerService xxxxxxxxxxxxxxxxxx");
        } catch (Throwable t) {
        }
    }
}

`

### Expected behaviour/预期行为

find class ConnectivityService xxxxxxxxxxxxxxxxxx
find class ActivityManagerService xxxxxxxxxxxxxxxxxx

### Actual behaviour/实际行为

only "find class ActivityManagerService xxxxxxxxxxxxxxxxxx" logout

### Xposed Module List/Xposed 模块列表

```shell
only current module
```

### Magisk Module List/Magisk 模块列表

```shell
no module
```

### LSPosed version/LSPosed 版本

1.8.6 (6841)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25.2(25200)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志
[LSPosed_2023-03-06T07_24_24.781372.zip](https://github.com/LSPosed/LSPosed/files/10894526/LSPosed_2023-03-06T07_24_24.781372.zip)

**Comment by yujincheng08** [comment]
its likely your hookees are inlined. you should try to deoptimize caller.

**Comment by yujincheng08** [comment]
you didnt hook anything. how comes hook fails?

**Comment by zhaohengyi** [comment]
i want hook ConnectivityService.getActiveNetworkInfo , but can not find class.

**Comment by zhaohengyi** [comment]
sorry , in fact this is not a bug of lsposed, i use wrong word.
i don't known how to find out the classloader of ConnectivityService .
this code can work on android 10
can you help me, thank you very much

**Comment by yujincheng08** [comment]
https://cs.android.com/android/platform/superproject/+/master:frameworks/base/services/java/com/android/server/SystemServer.java;drc=5ca657189aac546af0aafaba11bbc9c5d889eab3;l=2019

**Comment by zhaohengyi** [comment]
Thank you very much
