### ISSUE TITLE
[Bug] Riru is not installed

### ISSUE THREAD

**Issue by wz36125** [LSPosed/LSPosed#2429]
### Steps to reproduce/复现步骤

1. install Magisk v25210，restart the phone
2. install Riru v25.4.4，restart the phone
3. install [LSPosed-v1.8.6-6712-riru-release.zip](https://github.com/LSPosed/LSPosed/releases/download/v1.8.6/LSPosed-v1.8.6-6712-riru-release.zip)
4. report “Riru is not installed”

### Expected behaviour/预期行为

Successfully installed

### Actual behaviour/实际行为

installation failed

### Xposed Module List/Xposed 模块列表

```shell
empty
```

### Magisk Module List/Magisk 模块列表

```shell
Riru v25.4.4
Shamiko v0.6
```

### LSPosed version/LSPosed 版本

v1.8.6-6712

### Android version/Android 版本

Android 13

### Magisk version/Magisk 版本

25210

### Riru version/Riru 版本

v25.4.4

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

- Copying zip to temp directory
- Installing LSPosed-v1.8.6-6712-riru-release.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
***********************
 Riru - LSPosed 
 by LSPosed Developers 
***********************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
   creating: META-INF/com/google/android/
  inflating: META-INF/com/google/android/update-binary.sha256
  inflating: META-INF/com/google/android/updater-script.sha256
  inflating: META-INF/com/google/android/update-binary
  inflating: META-INF/com/google/android/updater-script
- LSPosed version v1.8.6 (6712)
- Extracting verify.sh
- Verified META-INF/com/google/android/update-binary
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh.sha256
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh.sha256
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: util_functions.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: util_functions.sh.sha256
- Verified customize.sh
- Verified verify.sh
- Verified util_functions.sh
- Android SDK version: 33
- Magisk version: 25210
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: riru.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: riru.sh.sha256
- Verified riru.sh
*********************************************************
! Riru is not installed
! Please install Riru from Magisk Manager or https://github.com/RikkaApps/Riru/releases
*********************************************************
! Installation failed

**Comment by yujincheng08** [comment]
use riru 26

**Comment by wz36125** [comment]
> use riru 26

yes, i switched to this version riru-v26.1.7.r530.ab3086ec9f-release, still can not install LSPosed-v1.8.6-6712-riru-release, report the same error

**Comment by Howard20181** [comment]
@wz36125 Tested, no problem

**Comment by wz36125** [comment]
> @wz36125 Tested, no problem

Why am I having this problem?

**Comment by wz36125** [comment]
> use riru 26

@yujincheng08 
`- Copying zip to temp directory
- Installing riru-v26.1.7.r530.ab3086ec9f-release.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
************************
 Riru 
 by Rikka, yujincheng08 
************************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
*******************
 Powered by Magisk 
*******************
- Installing from Magisk app
- Installing Riru v26.1.7.r530.ab3086ec9f (Riru API 26)
- Magisk version: 981ccabb (25210)
- Device sdk: 33
- Device platform: arm64
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
   creating: META-INF/com/google/android/
  inflating: META-INF/com/google/android/update-binary.sha256sum
  inflating: META-INF/com/google/android/update-binary
  inflating: META-INF/com/google/android/updater-script.sha256sum
  inflating: META-INF/com/google/android/updater-script
- Verified META-INF/com/google/android/update-binary
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh.sha256sum
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh.sha256sum
- Verified customize.sh
- Verified verify.sh
- Extracting Magisk files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop.sha256sum
- Verified module.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh.sha256sum
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: service.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: service.sh.sha256sum
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: system.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: system.prop.sha256sum
- Verified post-fs-data.sh
- Verified service.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: util_functions.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: util_functions.sh.sha256sum
- Verified system.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: uninstall.sh
- Verified util_functions.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: uninstall.sh.sha256sum
- Verified uninstall.sh
mkdir: can't create directory '/dev/zO0q/.magisk/modules/riru-core': No such file or directory
rm: can't remove '/dev/zO0q/.magisk/modules/riru-core/util_functions.sh': No such file or directory
cp: can't create '/dev/zO0q/.magisk/modules/riru-core/util_functions.sh': No such file or directory
- Extracting arm libraries
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriru.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriru.so.sha256sum
- Verified lib/armeabi-v7a/libriru.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriruhide.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriruhide.so.sha256sum
- Verified lib/armeabi-v7a/libriruhide.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriruloader.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriruloader.so.sha256sum
- Verified lib/armeabi-v7a/libriruloader.so
- Extracting arm64 libraries
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriru.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriru.so.sha256sum
- Verified lib/arm64-v8a/libriru.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriruhide.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriruhide.so.sha256sum
- Verified lib/arm64-v8a/libriruhide.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriruloader.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: libriruloader.so.sha256sum
- Verified lib/arm64-v8a/libriruloader.so
- Setting permissions
- Extracting rirud
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: rirud.apk
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: rirud.apk.sha256sum
- Verified rirud.apk
- Checking if your ROM has incorrect SELinux rules
- Start checks...
- No problem found
- Removing old files
rm: can't remove '/data/adb/riru/native_bridge': No such file or directory
rm: can't remove '/data/adb/riru/api_version.new': No such file or directory
rm: can't remove '/data/adb/riru/version_code.new': No such file or directory
rm: can't remove '/data/adb/riru/version_name.new': No such file or directory
rm: can't remove '/data/adb/riru/enable_hide': No such file or directory
rm: can't remove '/data/adb/riru/api_version': No such file or directory
rm: can't remove '/data/adb/riru/util_functions.sh': No such file or directory
rm: can't remove '/data/misc/riru/api_version': No such file or directory
rm: can't remove '/data/misc/riru/version_code': No such file or directory
rm: can't remove '/data/misc/riru/version_name': No such file or directory
sh: 1: unknown operand
- Done
`
