### ISSUE TITLE
[Bug] List of packages you can activate a module on is incomplete

### ISSUE THREAD

**Issue by jpstotz** [LSPosed/LSPosed#2463]
### Steps to reproduce/复现步骤

1. Install an LSPosed module (doesn't matter which)
2. Open the LSPosed manager
3. Open the configuration page of the installed module
4. Check the list of apps/packages you can enable the module for - system apps and services like Play Services are missing. Selecting "System Framework" does not include those apps & services.

### Expected behaviour/预期行为

Alls apps and services should be selectable, not only user installed apps. Or even better a checkbox "Enable for all apps and services" should be available.

### Actual behaviour/实际行为

LSPosed modules can not be enabled on system services and system apps. 

This makes modules like SSLUnpinning useless as HTTPS interception fails as some apps7services (those that can not be selected in LSPosed Manager) continue to make certificate pinning and thus TLS interception fails for these apps/services.

### Xposed Module List/Xposed 模块列表

```shell
SSLUnpinning 1.0.0
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk - LSPosed 1.8.6 (6712)
Universal SafetyNet Fix 2.4.0
```

### LSPosed version/LSPosed 版本

1.8.6 (6712) - Zygisk

### Android version/Android 版本

Andorid 12

### Magisk version/Magisk 版本

25.2 (25200) (33)

### Riru version/Riru 版本

-

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

-

**Comment by yujincheng08** [comment]
expected

**Comment by jpstotz** [comment]
Is this a limitation (system, UI?) or just you don't want it to implement?

**Comment by yujincheng08** [comment]
its meaningless to hook a package wothout process.

**Comment by jpstotz** [comment]
Why should system services not have a process? Take for example GooglePlayServices. 

It definitely have a process. I can see it in ps list `com.google.process.gservices`.

**Comment by jpstotz** [comment]
Not on my system, they are all missing.

**Comment by yujincheng08** [comment]
why not uncheck system apps in the hide option
