### ISSUE TITLE
Parasitic Manager [Bug] 

### ISSUE THREAD

**Issue by iD3vCxt** [LSPosed/LSPosed#2464]
### Steps to reproduce/复现步骤

I don't know what's the cause of this bug or if I have done something wrong. I did try reinstalling. I don't think that the issue is on my end. 

### Expected behaviour/预期行为

1. When starting the device normally you have the ''LSPosed Symbol Indicator'', which you can use it to a create shortcut.
2. When opening LSPosed Manager usually the first thing that happens is you get a pop up saying ''Parasitic Manager Recommended'' with the options: Create Shortcut, Never show, Ok

### Actual behaviour/实际行为

1. No LSPosed Indicator / Message shown
2. No option to create a shortcut

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk LSPosed (v1.8.6)
```

### LSPosed version/LSPosed 版本

6712

### Android version/Android 版本

10

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[shared_text.txt](https://github.com/LSPosed/LSPosed/files/11064131/shared_text.txt)

**Comment by yujincheng08** [comment]
''LSPosed Symbol Indicator''? what is this?

**Comment by Howard20181** [comment]
@iD3vCxt You are using the installed manager instead of the parasitic one.

**Comment by vvb2060** [comment]
> I am using latest debug CI version of LSPosed and enable verbose log
