### ISSUE TITLE
[Feature Request] Could LSPosed support Android Oreo?

### ISSUE THREAD

**Issue by LeviMarvin** [LSPosed/LSPosed#2466]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Version support.

### Describe the solution you'd like/描述你想要的解决方案

Could LSPosed support Android Oreo (8.0)? The Magisk 25.2 is supported Android Oreo

**Comment by vvb2060** [comment]
https://forum.xda-developers.com/t/3034811/

**Comment by Ikura9** [comment]
> https://forum.xda-developers.com/t/3034811/

Apps detect that I have edxposed installed, xposed hide doesn't work, lsposed has parasitic manager feature which I think it might work
