### ISSUE TITLE
[Bug] Can't read libgojni.so

### ISSUE THREAD

**Issue by elvizlai** [LSPosed/LSPosed#2467]
### Steps to reproduce/复现步骤

1、Using example provided by [gomobile](https://github.com/golang/mobile/tree/master/example/bind/android) to generate `hello.aar`

2、Embed and call jni method in LSPosed module.
```
System.out.println(Hello.greetings("xxx"));
```

### Expected behaviour/预期行为

I wrote an android application, it works fine, but LSPosed module failed with no `so` found error. I tried to unzip apk, it also has the given so file.

### Actual behaviour/实际行为

LSPosed-Bridge: Caused by: java.lang.UnsatisfiedLinkError: LspModuleClassLoader[module=/data/app/~~kLz-SeAe1mcI2eklgdLfGA==/mock.test.xhook-6S3SbCb2FJWy3rseYxaD1A==/base.apk, J[DexPathList[[dex file "InMemoryDexFile[cookie=[0, -5476376662400554496]]"],nativeLibraryDirectories=[/data/app/~~kLz-SeAe1mcI2eklgdLfGA==/mock.test.xhook-6S3SbCb2FJWy3rseYxaD1A==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]] couldn't find "libgojni.so"

### Xposed Module List/Xposed 模块列表

```shell
NOT RELATED
```

### Magisk Module List/Magisk 模块列表

```shell
NOT RELATED
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

12/13

### Magisk version/Magisk 版本

25.2

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

LSPosed-Bridge: Caused by: java.lang.UnsatisfiedLinkError: LspModuleClassLoader[module=/data/app/~~kLz-SeAe1mcI2eklgdLfGA==/mock.test.xhook-6S3SbCb2FJWy3rseYxaD1A==/base.apk, J[DexPathList[[dex file "InMemoryDexFile[cookie=[0, -5476376662400554496]]"],nativeLibraryDirectories=[/data/app/~~kLz-SeAe1mcI2eklgdLfGA==/mock.test.xhook-6S3SbCb2FJWy3rseYxaD1A==/base.apk!/lib/arm64-v8a, /system/lib64, /system_ext/lib64]]]] couldn't find "libgojni.so"

**Comment by yujincheng08** [comment]
https://developer.android.com/topic/performance/reduce-apk-size#extract-false

https://developer.android.com/studio/command-line/zipalign#usage

**Comment by vvb2060** [comment]
```
    packagingOptions {
        jniLibs {
            useLegacyPackaging false
        }
    }
```
