### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Kostamn** [LSPosed/LSPosed#2477]
### Steps to reproduce/复现步骤

1.Open it
2.Cut into the background
3.After a while
4.Open manager and it chash

### Expected behaviour/预期行为

Just normal

### Actual behaviour/实际行为

LSPosed Manager crash

### Xposed Module List/Xposed 模块列表

```shell
Woobox For MIUI
Unlock CN GMS
Fuck Loction
cn.fuckhome.xiaowine
cn.geektang.privacyspace
```

### Magisk Module List/Magisk 模块列表

```shell
MIUI MONET
MONET-ALL
ZYGISK-LSPOSED
GPS PRO TEST
```

### LSPosed version/LSPosed 版本

6871

### Android version/Android 版本

12 API31

### Magisk version/Magisk 版本

fdac22ba-delta

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-04-06T11_16_22.016.zip](https://github.com/LSPosed/LSPosed/files/11166071/LSPosed_2023-04-06T11_16_22.016.zip)
[Crash_Log.txt](https://github.com/LSPosed/LSPosed/files/11166085/Crash_Log.txt)

**Comment by yujincheng08** [comment]
>  I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志
