### ISSUE TITLE
Lsposed shows ??? after flashing with magisk zygisk version.

### ISSUE THREAD

**Issue by thewalkingcat** [LSPosed/LSPosed#2478]
### Steps to reproduce/复现步骤

1.Flash Lsposed module to magisk

### Expected behaviour/预期行为

Shows version number and Lsposed behaves normally.

### Actual behaviour/实际行为

Lsposed shows (???) And xposed modules does not work.
![Screenshot_2023-04-07-20-33-52-753_org lsposed manager](https://user-images.githubusercontent.com/72502050/230612563-2cea0a2f-335e-490a-909e-698e2e49087e.jpg)

### Xposed Module List/Xposed 模块列表

```shell
Customiuizer 14
```

### Magisk Module List/Magisk 模块列表

```shell
90hz module
Yt revanced extended
Lsposed
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.6

### Riru version/Riru 版本

n/a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-04-07T20_42_14.092.zip](https://github.com/LSPosed/LSPosed/files/11179044/LSPosed_2023-04-07T20_42_14.092.zip)

**Comment by yujincheng08** [comment]
You are not using magisk.

**Comment by thewalkingcat** [comment]
For some reason magisk was corrupted so (althrough it's saying it's working)  zygisk was not working properly, reflashing magisk fixes this. Thanks anyway.
