### ISSUE TITLE
[BUG] encountered boot loop

### ISSUE THREAD

**Issue by Eric-Joker** [LSPosed/LSPosed#248]
我的手机(Redmi Note9 Pro)在更新了manager(仅更新magisk模块后重启不会出现问题)后会出现无限软重启的情况(或者开机完马上关机)
我并没有关闭与lsposed无关的magisk模块，但是以前可以正常使用

My mobile phone(Redmi Note9 Pro) will have infinite soft restart after update the manager (there will be no problem when only restart after update the magick module) (or shut down immediately after starting)
I didn't turn off the lsposed independent magick module, but it used to work.

**Comment by yujincheng08** [comment]
no log, no fix.

**Comment by coderstory** [comment]
no log no bug
