### ISSUE TITLE
[Bug] IQOO z5  notification cann't work

### ISSUE THREAD

**Issue by zxlrj** [LSPosed/LSPosed#2480]
### Steps to reproduce/复现步骤

在管理器里设置状态通知为打开
通知栏显示LSPosed已加载，点按通知以打开管理器
管理器没有打开

### Expected behaviour/预期行为

打开管理器

### Actual behaviour/实际行为

管理器没有打开

### Xposed Module List/Xposed 模块列表

```shell
锤锤
非残
贴吧ts
隐藏应用列表
运动修改器
知了
disable-flag_secure 2.0.0
vmos pro++
钉钉助手
微X模块
```

### Magisk Module List/Magisk 模块列表

```shell
originos优化
shamiko
zygisk-lsposed
安卓ui流畅度优化
自动神仙救砖
```

### LSPosed version/LSPosed 版本

1.8.6（6712）

### Android version/Android 版本

12

### Magisk version/Magisk 版本

25.2（25200）

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [x] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-04-09T15_03_01.085.zip](https://github.com/LSPosed/LSPosed/files/11185129/LSPosed_2023-04-09T15_03_01.085.zip)

**Comment by yujincheng08** [comment]
看来是因为这个

`Sending non-protected broadcast ac51b645-91f7-4cb1-88aa-676a64685452 from system uid 0 pkg android`

**Comment by yujincheng08** [comment]
但是 https://github.com/LSPosed/LSPosed/commit/af1223e4a5b6b194118eb77baa7693bb7b7bc604 应该已经修复了

**Comment by yujincheng08** [comment]
发一下 `/system/framework/services.jar`

**Comment by zxlrj** [comment]
[jar.zip](https://github.com/LSPosed/LSPosed/files/11186794/jar.zip)
别的app通知栏都是正常可以打开的，就是lsposed不能打开没反应。

**Comment by zxlrj** [comment]
安装新模块以后通知栏提示有新模块，点击通知也不能打开。

**Comment by yujincheng08** [comment]
6849 通知能打开吗？

**Comment by zxlrj** [comment]
6849 6872都一样，能显示通知 点击通知没反应 打不开管理器

**Comment by zxlrj** [comment]
[LSPosed_2023-04-10T13_59_00.535.zip](https://github.com/LSPosed/LSPosed/files/11188082/LSPosed_2023-04-10T13_59_00.535.zip)
这个是6872的日志

**Comment by yujincheng08** [comment]
你关掉了系统日志，日志啥都看不到
