### ISSUE TITLE
Doesn't work on Redmi 7A 

### ISSUE THREAD

**Issue by lequangcuong123** [LSPosed/LSPosed#2485]
### Steps to reproduce/复现步骤

1. You have to have  Redmi 7A 
2. Installed rom miui 12.5.2
3. Own magisk delta version fdac22ba-delta (25210) (Latest release)
4. Enabled zygisk
5. Get the latest (current) LSPosed module (release version for zygisk) and flash it to magisk. 
6. Restart your device
7. Error appeared

### Expected behaviour/预期行为

The LSPosed application or the lspod application appears to notify you that the module has been installed 

### Actual behaviour/实际行为

Once flashed through magisk LSPosed didn't show up even though magisk said it installed successfully and I rebooted. I tried to install the LSPosed version on chplay but it still doesn't work 

### Xposed Module List/Xposed 模块列表

```shell
LSPosed-v1.8.6-6712-zygisk-release 
(latest release version of LSPosed)
```

### Magisk Module List/Magisk 模块列表

```shell
fdac22ba-delta(25210)
(latest release version of magisk delta)
```

### LSPosed version/LSPosed 版本

1.8.6 (6712)

### Android version/Android 版本

MIUI global 12.5.2

### Magisk version/Magisk 版本

fdac22ba-delta(25210)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[bugreport-pine-QKQ1.191014.001-2023-04-12-17-25-43.zip](https://github.com/LSPosed/LSPosed/files/11210300/bugreport-pine-QKQ1.191014.001-2023-04-12-17-25-43.zip)

**Comment by Howard20181** [comment]
Please install the CI version and use the official Magisk.

**Comment by yujincheng08** [comment]
`Magisk  : execve /sbin/.magisk/busybox/busybox failed with 8: Exec format error`

Magisk is broken.

**Comment by lequangcuong123** [comment]
> `Magisk : execve /sbin/.magisk/busybox/busybox failed with 8: Exec format error`
> 
> Magisk bị hỏng.

I don't know what to do next, if I install the official version, it won't block root detection from the bank

**Comment by lequangcuong123** [comment]
> `Magisk : execve /sbin/.magisk/busybox/busybox failed with 8: Exec format error`
> 
> Magisk is broken.
which you remind me, before that I installed 2 official magisk versions 26.0 and 25.2 and got the same error, I don't know how but most of them have the same error. I also don't know where I found the module before to install LSPosed for magisk 25.2 😂
