### ISSUE TITLE
[FR] New security mode

### ISSUE THREAD

**Issue by Eric-Joker** [LSPosed/LSPosed#250]
**Detail**:
希望在开机时检测android的错误日志，然后让lsposed进入安全模式，关闭所有模块之类的，以便正常开机抓取日志

I hope to detect the Android error log when I boot, and then let lsposed enter safe mode, close all modules and so on, so as to grab the log when I boot normally

**Comment by Eric-Joker** [comment]
I've seen similar features in an xposed module https://github.com/eairou/X-APM
我曾在一个xposed模块见过类似的功能https://github.com/eairou/X-APM

**Comment by Eric-Joker** [comment]
I've seen similar features in an xposed module https://590m.com/file/19604958-367085698 (should not be the latest version)

我曾在一个xposed模块见过类似的功能https://590m.com/file/19604958-367085698(应该不是最新版)
不知道行不行。。

**Comment by coderstory** [comment]
magisk自带了安全模式   重复需求
