### ISSUE TITLE
LSPosed inability to re-create shortcuts after launcher changes

### ISSUE THREAD

**Issue by admin-elvistrujanovic** [LSPosed/LSPosed#2501]
It's not solved for me - I'm using the latest LSPosed version in 2023 and I deleted LSPosed Shortcut due to the launcher bug changes so I was forced to re-create all shortcuts from the beginning.

How can I do that **without reinstalling LSposed Module** - what command I need to enter via shell or etc... because the question about creating a new shortcut doesn't appearing in the default LSPosed application I've installed from /data/adb/lspd

_Originally posted by @admin-elvistrujanovic in https://github.com/LSPosed/LSPosed/discussions/1573#discussioncomment-5645320_

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed/pull/1497

**Comment by vjburic1** [comment]
I solved it by installing manager.apk from the Magisk module zip, deleted app data and relaunched Magisk version from notification - the option to add a shortcut wasn't greyed out anymore. I then uninstalled the manager.apk and that's it.
