### ISSUE TITLE
Can't work under Android14

### ISSUE THREAD

**Issue by YangguangZhou** [LSPosed/LSPosed#2503]
### Steps to reproduce/复现步骤

在Pixel6上安装Android14 beta1

### Expected behaviour/预期行为

可以打开管理器，模块正常工作

### Actual behaviour/实际行为

LSPosed Loaded的通知存在，但点击后无反应，管理器无法打开，模块无法运行

### Xposed Module List/Xposed 模块列表

```shell
记不得了
```

### Magisk Module List/Magisk 模块列表

```shell
![Screenshot_20230421-215343](https://user-images.githubusercontent.com/61733195/233654432-4fef7d60-a954-46d4-a895-d9af11cbc1af.png)
![Screenshot_20230421-215404](https://user-images.githubusercontent.com/61733195/233654455-45a2c789-86f6-4f17-ab03-b2882b7df935.png)
![Screenshot_20230421-215333](https://user-images.githubusercontent.com/61733195/233654464-623eec24-3b8d-41f5-9b99-5c9bf9ef7d83.png)
![Screenshot_20230421-215428](https://user-images.githubusercontent.com/61733195/233654471-a2dc9b63-0d83-4aa3-8f55-5db0a7ffdf6c.png)
![Screenshot_20230421-215422](https://user-images.githubusercontent.com/61733195/233654477-22fdd2ba-ba75-4320-83ee-255afd2b4026.png)
![Screenshot_20230421-215320](https://user-images.githubusercontent.com/61733195/233654482-a94a144b-7808-4bc7-80e3-8571a0705895.png)
![Screenshot_20230421-215142](https://user-images.githubusercontent.com/61733195/233654486-49d05b7d-2a44-439e-bc05-459436410586.png)
![Screenshot_20230421-215410](https://user-images.githubusercontent.com/61733195/233654497-76a507c0-f55e-4e3c-b7ed-48bc34b2b81a.png)
```

### LSPosed version/LSPosed 版本

1.8.6（6712）

### Android version/Android 版本

Android14 beta1  UPB1.230309.014

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[bugreport-oriole_beta_64-UPB1.230309.014-2023-04-21-21-57-48.zip](https://github.com/LSPosed/LSPosed/files/11296376/bugreport-oriole_beta_64-UPB1.230309.014-2023-04-21-21-57-48.zip)
[bugreport-oriole_beta_64-UPB1.230309.014-2023-04-21-21-57-49-dumpstate_log-23451.txt](https://github.com/LSPosed/LSPosed/files/11296377/bugreport-oriole_beta_64-UPB1.230309.014-2023-04-21-21-57-49-dumpstate_log-23451.txt)

**Comment by yujincheng08** [comment]
6712...

**Comment by YangguangZhou** [comment]
？
