### ISSUE TITLE
[BUG] The phone suddenly does not have any sound

### ISSUE THREAD

**Issue by mjyhj** [LSPosed/LSPosed#251]
使用环境：
红米K30 PRO  MIUI12.5 Android11 开发版（期间升过级，问题也一样）
Riru v23.6 
Riru-LSPosedv1.1.0

之前使用太极没有此问题，转用LSP后一个星期出现了3次，目前转回太极后问题没有复现。
表现为日常刷着某个APP，突然卡屏动不了，只能关闭屏幕过一会程序会FC。
然后手机打开APP刷视频，会一卡一卡的，然后整个手机的扬声器，听筒完全没声音，包括闹钟电话
重启才会恢复正常。

**Comment by yujincheng08** [comment]
no log, no fix.
