### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by Vader77Darth** [LSPosed/LSPosed#2510]
### Steps to reproduce/复现步骤

go to scope list of any module

### Expected behaviour/预期行为

can find miui dual apps

### Actual behaviour/实际行为

cannot find miui dual apps

### Xposed Module List/Xposed 模块列表

```shell
?
```

### Magisk Module List/Magisk 模块列表

```shell
?
```

### LSPosed version/LSPosed 版本

6712

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-04-26T10_11_03.115511.zip](https://github.com/LSPosed/LSPosed/files/11331071/LSPosed_2023-04-26T10_11_03.115511.zip)

**Comment by yujincheng08** [comment]
?

**Comment by Vader77Darth** [comment]
Why is this not planned to be fixed? We cannot select miui dual apps in LSPosed scope list.
![Uploading Screenshot_2023-04-26-10-21-51-605-edit_com.android.shell.jpg…]()

**Comment by yujincheng08** [comment]
Cannot see your pic.

**Comment by yujincheng08** [comment]
> Why is this not planned to be fixed?

You are not following the issue template.


> We cannot select miui dual apps in LSPosed scope list

We can.

**Comment by Vader77Darth** [comment]
I cannot find my dual app on any of my several miui devices.The picture that you cannot see is a screenshot of me searching for Instagram. The results only shows one of the two Instagram dual apps

**Comment by yujincheng08** [comment]
You cannot find your dual app doesn't mean LSPosed does not support MIUI dual app. It's because you don't know how.

**Comment by yujincheng08** [comment]
We don't have time to teach everyone in the world. You should find it yourself by searching.

**Comment by Vader77Darth** [comment]
Cannot find any mention of this anywhere

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/234533893-6907e8be-3060-4365-9d17-2a4d2f411128.png)

FYI, we don't have time to teach every user to use Google, either.

**Comment by Vader77Darth** [comment]
lmao. Google search Stan.
