### ISSUE TITLE
[Bug] Unable to run correctly on Android 14 UPB1

### ISSUE THREAD

**Issue by a-lannin** [LSPosed/LSPosed#2521]
### Steps to reproduce/复现步骤

Device: Pixel5a
1.更新到Android14UPB1
2.面具25210版本刷入Lsposed6887版本
3.从通知栏无法打开Lsposed
4.可以从ManagerAPP打开Lsposed并显示已激活
5.PixelLauncher也无法像刷入前一样工作，无法打开多任务界面，强行停止PixelLauncher一次后解决

### Expected behaviour/预期行为

从通知栏能正常打开寄主管理器

模块能正常工作

### Actual behaviour/实际行为

无法打开，而且Pixel启动器也无法正常工作

### Xposed Module List/Xposed 模块列表

```shell
None

但我尝试安装墨-状态栏歌词和HMSPush，模块并不起作用

可以推断Lsposed可能并没有被正确加载
```

### Magisk Module List/Magisk 模块列表

```shell
Pixel5 VoLTE/WiFi/5G
iOS16 Emoji
Uperf
Zygisk-Sui
Zygisk-Lsposed
```

### LSPosed version/LSPosed 版本

6887

### Android version/Android 版本

14 UPB1

### Magisk version/Magisk 版本

25210

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-05-03T02_17_10.760525.zip](https://github.com/LSPosed/LSPosed/files/11376479/LSPosed_2023-05-03T02_17_10.760525.zip)

似乎日志中并没有什么特别的

**Comment by yujincheng08** [comment]
模块不能正常工作为什么不能是模块没适配？

**Comment by a-lannin** [comment]
> 模块不能正常工作为什么不能是模块没适配？

模块没有工作，但是Lsposed也没有正确工作，无法打开寄主管理器

**Comment by yujincheng08** [comment]
打不开寄生管理器跟模块不能工作有必然联系吗？

**Comment by a-lannin** [comment]
> 打不开寄生管理器跟模块不能工作有必然联系吗？

我的Pixel启动器也无法正常工作了

日志中的问题：
java.lang.NullPointerException: Attempt to invoke interface method 'void android.os.IBinder.linkToDeath(android.os.IBinder$DeathRecipient, int)' on a null object reference
	at B1.g(Unknown Source:19)
	at B1.j(Unknown Source:102)
	at E1.accept(Unknown Source:109)
	at Z1.run(Unknown Source:21)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
[ 2023-05-03T02:14:58.514        0:   996:  2531 W/System          ] No Compatibility callbacks set! Querying change 160794467
[ 2023-05-03T02:14:58.515        0:   996:  2531 E/LSPosedService  ] performReceive: 
java.lang.NullPointerException: Attempt to invoke interface method 'void android.os.IBinder.linkToDeath(android.os.IBinder$DeathRecipient, int)' on a null object reference
	at B1.g(Unknown Source:19)
	at B1.j(Unknown Source:102)
	at E1.accept(Unknown Source:109)
	at Z1.run(Unknown Source:21)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

**Comment by a-lannin** [comment]
目前没有任何模块被加载，但是我的启动器仍不能正常工作

**Comment by yujincheng08** [comment]
这个如此又不是 pixel luancher 的入职

**Comment by yujincheng08** [comment]
而且这个日志是正常日志。你在 13 上也能看到。

**Comment by a-lannin** [comment]
先试一下其他模块

**Comment by yujincheng08** [comment]
我们不会对不在作用域的进程进行修改，所以 pixel launcher 的问题与我们无关。

**Comment by yujincheng08** [comment]
而且你也没有使用 debug 版本进行反馈。

**Comment by yujincheng08** [comment]
我自己使用 14 beta1 测试并无问题

**Comment by yujincheng08** [comment]
![IMG_20230503_024512_386.jpg](https://user-images.githubusercontent.com/5022927/235757215-e7f30807-8978-4d65-aedb-cb67522ed68b.jpg)

**Comment by a-lannin** [comment]
> 这个日志又不是 pixel launcher 的日志

我无法得到启动器的日志

又测试了下其他模块：
Pixelify GPhotos
核心破解
F__k Coolapk

都没有正常工作

**Comment by yujincheng08** [comment]
我的哔哩漫游没问题

**Comment by a-lannin** [comment]
![Uploading Screenshot_20230503-024709.png…]()

**Comment by a-lannin** [comment]
安卓版本UPB1.230309.017

我试下哔哩漫游

> ![IMG_20230503_024512_386.jpg](https://user-images.githubusercontent.com/5022927/235757215-e7f30807-8978-4d65-aedb-cb67522ed68b.jpg)

**Comment by a-lannin** [comment]
> 我的哔哩漫游没问题，怎么说

很神奇，我的哔哩漫游能运行

**Comment by yujincheng08** [comment]
那就是没问题。

**Comment by a-lannin** [comment]
> 那就是没问题。

那寄主管理器怎么解决

**Comment by yujincheng08** [comment]
试试能否用拨号盘打开。

这个问题理论上已经修过了。还是不行就等 14 的 framework 开源再说。目前只能保证 gsi 和模拟器都能用。

**Comment by a-lannin** [comment]
> 试试能否用拨号盘打开。
> 
> 这个问题理论上已经修过了。还是不行就等 14 的 framework 开源再说。目前只能保证 gsi 和模拟器都能用。

启动器是没法解决了吗（
很神奇启动器还是api33
强行停止一次就恢复正常，可能是systemui的问题

**Comment by yujincheng08** [comment]
启动器没理由跟我们有关系
