### ISSUE TITLE
[Bug] App crashes when starting if enabled for any LSposed module

### ISSUE THREAD

**Issue by eustilou** [LSPosed/LSPosed#2531]
### Steps to reproduce/复现步骤

1. Enable app [com.ebankit.com.bt](https://play.google.com/store/apps/details?id=com.ebankit.com.bt) on any LSposed module
2. Start app

### Expected behaviour/预期行为

App should not crash.

### Actual behaviour/实际行为

App crashes when starting.

### Xposed Module List/Xposed 模块列表

```shell
Any one or more modules.
```

### Magisk Module List/Magisk 模块列表

```shell
Shamiko 0.7.1 (166)
Universal SafetyNet Fix v2.4.0
Zygisk - LSposed
```

### LSPosed version/LSPosed 版本

1.8.6 (6893) debug

### Android version/Android 版本

10

### Magisk version/Magisk 版本

26.1 (26100)

### Riru version/Riru 版本

n/a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-05-12T08_23_42.786.zip](https://github.com/LSPosed/LSPosed/files/11464523/LSPosed_2023-05-12T08_23_42.786.zip)

**Comment by yujincheng08** [comment]
it detects xposed and then crashes.

**Comment by eustilou** [comment]
> it detects xposed and then crashes.

It runs out of memory

**Comment by yujincheng08** [comment]
it intently runs out of memory because it detects xposed :)

**Comment by yujincheng08** [comment]
yes, but we wont do this. let third party modules to do it.
