### ISSUE TITLE
[New language request]

### ISSUE THREAD

**Issue by gnrZoop** [LSPosed/LSPosed#2533]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

 Translate into Sinhala language https://lsposed.crowdin.com/lsposed Not available here.

### Describe the solution you'd like/描述你想要的解决方案

Add me (@zoopbt) I will translate "Sinhala (si)" language.

### Additional context/其他信息

![Screenshot_20230513-102204_Chrome](https://github.com/LSPosed/LSPosed/assets/59320808/905ed3a4-fb2a-44be-8b34-c91281cf65cf)

**Comment by yujincheng08** [comment]
added
