### ISSUE TITLE
[Feature Request] Sinhala language

### ISSUE THREAD

**Issue by gnrZoop** [LSPosed/LSPosed#2534]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Sinhala language is not available on the translation page (Crowdin) here

### Describe the solution you'd like/描述你想要的解决方案

Add Sinhala (si) language to translation page. I will translate (@zoopbt).

### Additional context/其他信息

![Screenshot_20230513-102204_Chrome](https://github.com/LSPosed/LSPosed/assets/59320808/30a6288c-b34e-4e00-9218-af57bee942bb)

**Comment by yujincheng08** [comment]
added
