### ISSUE TITLE
There is no notification bar after flashing flyme 10[Bug] 

### ISSUE THREAD

**Issue by LQ2002** [LSPosed/LSPosed#2537]
### Steps to reproduce/复现步骤

Magisk Delta brushed into the latest version lsposed restart without notification bar

### Expected behaviour/预期行为

There will be a notification bar when Magisk Delta is flashed in and restarted

### Actual behaviour/实际行为

Magisk Delta brushed into the latest version lsposed restart without notification bar

### Xposed Module List/Xposed 模块列表

```shell
don't vertical screen
non-disabled
core crack
Disable FLAG_SECURE
Pipi Shrimp Assistant
Micro X Assistant
System Update Assistant
hide app list
motion modifier
juiceSSHBypass
NoShareSignCheck
Q sound assistant
QAuxiliary
Scene5
TeleSpeed
Thanox
WPeng_Ext
Xq_Crystal
```

### Magisk Module List/Magisk 模块列表

```shell
SafetyNet sensitive props
TrichromeLibrary Squoosh
LSPosed
```

### LSPosed version/LSPosed 版本

6894

### Android version/Android 版本

13

### Magisk version/Magisk 版本

25210

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-05-14T18_01_19.662233.zip](https://github.com/LSPosed/LSPosed/files/11471620/LSPosed_2023-05-14T18_01_19.662233.zip)

**Comment by yujincheng08** [comment]
Not using debug ver

**Comment by LQ2002** [comment]
The official version is also the problem, 6721
