### ISSUE TITLE
[BUG] Search buttoms missing label 搜索按钮用autoinput找不到

### ISSUE THREAD

**Issue by gzyguo** [LSPosed/LSPosed#2539]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

没有名字，只能点位置
2个搜索都是

### Describe the solution you'd like/描述你想要的解决方案

起个名字呗

**Comment by Howard20181** [comment]
是无障碍读屏吗？

**Comment by gzyguo** [comment]
> 是无障碍读屏吗？

是，名字，描述或id都行

**Comment by gzyguo** [comment]
> 关于无障碍，除了这个还有哪些需要改进的？

后退退不干净，总能切回来，这个算吗
然后就是在桌面建图标删app后不会用Tasker启动LSP，用shell建的是不是用shell也可以启动？
都是些鸡毛蒜皮的，脸红

**Comment by Howard20181** [comment]
> 后退退不干净，总能切回来，用那个last app

这个是什么表现？能录个视频吗？

> 是在桌面建图标删app后不会用Tasker启动LSP，用shell建的是不是用shell也可以启动？ 

Tasker指的是 https://tasker.joaoapps.com/ 吗？这个可以创建一个以root权限执行命令的任务
`am start -c "org.lsposed.manager.LAUNCH_MANAGER" "com.android.shell/.BugreportWarningActivity"`
就可以了

**Comment by gzyguo** [comment]
> > 后退退不干净，总能切回来，用那个last app
> 
> 这个是什么表现？能录个视频吗？
> 
> > 是在桌面建图标删app后不会用Tasker启动LSP，用shell建的是不是用shell也可以启动？
> 
> Tasker指的是 https://tasker.joaoapps.com/ 吗？这个可以创建一个以root权限执行命令的任务 `am start -c "org.lsposed.manager.LAUNCH_MANAGER" "com.android.shell/.BugreportWarningActivity"` 就可以了

就这样，不过现在好多app都这样了，谢谢去用tasker建一个
