### ISSUE TITLE
似乎不支持短方法的hook。

### ISSUE THREAD

**Issue by jiumoshou** [LSPosed/LSPosed#255]
似乎不支持对短方法体的hook，之前我以为是对构造方法的hook失效。
类似方法，可以找到类和方法体，但是无hook结果。
    public static long getLastTouchTime() {
        return lastTouchTime;
    }

测试系统安卓11，MIUI12.5

**Comment by yujincheng08** [comment]
你反射调用试试

**Comment by jiumoshou** [comment]
好的，我试试

**Comment by yujincheng08** [comment]
未按照模板提交 issue，未使用英文标题，关闭。
