### ISSUE TITLE
Any reason for not supporting GrapheneOS[Bug]? 

### ISSUE THREAD

**Issue by matt873** [LSPosed/LSPosed#2551]
### Steps to reproduce/复现步骤

Nil

### Expected behaviour/预期行为

Modules doesn't open from notification but can be opened by installing lsposed APK and then modules can be activated as usual and app can be uninstalled thereafter.
So why not fixing notification problem for accessing modules and creating shortcut?

### Actual behaviour/实际行为

Nil

### Xposed Module List/Xposed 模块列表

```shell
Nil
```

### Magisk Module List/Magisk 模块列表

```shell
Nil
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

13

### Magisk version/Magisk 版本

Nil

### Riru version/Riru 版本

Nil

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Nil

**Comment by Howard20181** [comment]
https://github.com/LSPosed/LSPosed/issues/2481#issuecomment-1501243597
