### ISSUE TITLE
[Bug] Blind App Displays "LIAPP ALERT" Root Detection Error when LSPosed module is enabled.

### ISSUE THREAD

**Issue by RecursiveRegistrations** [LSPosed/LSPosed#2569]
### Steps to reproduce/复现步骤

1. Install [Blind](https://play.google.com/store/apps/details?id=com.teamblind.blind)
2. With Shamiko installed and running, add Blind to the Magisk DenyList. Make sure all options for the app are toggled on in the list.
3. Launch the app. Upon doing so, the app will open with an "LIAPP ALERT" error stating that root was detected.
4. Disable the LSPosed module in Magisk and reboot the phone.
5. After the phone reboots, launch Blind. It will work as intended.
6. Enable the LSPosed module in Magisk and reboot the phone again.
7. After the phone reboots, launch Blind. The error message described in step 3 will show again.

### Expected behaviour/预期行为

Root should not be detected when the LSPosed module is enabled.

### Actual behaviour/实际行为

Root is detected when the LSPosed module is enabled.

### Xposed Module List/Xposed 模块列表

```shell
- Hide My Applist
- Pixel Mods
```

### Magisk Module List/Magisk 模块列表

```shell
- App Systemizer (Terminal Emulator) v17.3.1
- Blobmoji Emoji 15, Release 2
- Busybox for Android NDK 1.34.1
- Shamiko v0.7.3 (174)
- Enhanced mode for Storage Isolation (Zygisk) v28.1.0
- LSPosed (Zygisk) v1.8.6
```

### LSPosed version/LSPosed 版本

v1.8.6 (6904)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-06-18T22_50_26.866649.zip](https://github.com/LSPosed/LSPosed/files/11783635/LSPosed_2023-06-18T22_50_26.866649.zip)

**Comment by yujincheng08** [comment]
![Screenshot_2023-06-19-10-55-21-551_com miui home](https://github.com/LSPosed/LSPosed/assets/5022927/3bf6764b-9dfd-4e76-9489-28ab4edcedce)

**Comment by RecursiveRegistrations** [comment]
@yujincheng08 Could you tell me what Magisk modules you have installed so that I can try to match your setup?
