### ISSUE TITLE
[Bug] Blind App Displays "LIAPP ALERT" Root Detection Error when LSPosed and Universal SafetyNet Fix modules are enabled at the same time.

### ISSUE THREAD

**Issue by RecursiveRegistrations** [LSPosed/LSPosed#2570]
### Steps to reproduce/复现步骤

1. Install [Universal SafetyNet Fix](https://github.com/kdrag0n/safetynet-fix) and reboot the phone.
2. Install [Blind](https://play.google.com/store/apps/details?id=com.teamblind.blind)
3. With Shamiko installed and running, add Blind to the Magisk DenyList. Make sure all options for the app are toggled on in the list.
4. Launch the app. Upon doing so, the app will open with an "LIAPP ALERT" error stating that root was detected.
5. Disable the LSPosed module in Magisk and reboot the phone.
6. After the phone reboots, launch Blind. It will work as intended.
7. Enable the LSPosed module again, disable the Universal SafetyNet Fix module, and reboot the phone again.
8. After the phone reboots, launch Blind. It will work as intended.
9. Enable Universal SafetyNet Fix and reboot the phone again.
11. After the phone reboots, launch Blind. The error message described in step 4 will show again.

### Expected behaviour/预期行为

Root should not be detected.

### Actual behaviour/实际行为

Root is detected when LSPosed and Universal SafetyNet Fix are enabled at the same time. If only one of the two is enabled, the app loads fine, but if they are both enabled, the root detection message shows.

### Xposed Module List/Xposed 模块列表

```shell
- Hide My Applist
- Pixel Mods
```

### Magisk Module List/Magisk 模块列表

```shell
- App Systemizer (Terminal Emulator) v17.3.1
- Blobmoji Emoji 15, Release 2
- Busybox for Android NDK 1.34.1
- Shamiko v0.7.3 (174)
- Enhanced mode for Storage Isolation (Zygisk) v28.1.0
- LSPosed (Zygisk) v1.8.6
```

### LSPosed version/LSPosed 版本

v1.8.6 (6904)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-06-18T22_50_26.866649.zip](https://github.com/LSPosed/LSPosed/files/11783635/LSPosed_2023-06-18T22_50_26.866649.zip)

**Comment by yujincheng08** [comment]
This is not lsposed's issue!!!
https://github.com/Displax/safetynet-fix/pull/4

**Comment by RecursiveRegistrations** [comment]
Thanks for pointing this out!

**Comment by RecursiveRegistrations** [comment]
@yujincheng08 Please reopen this. @Displax has already published a release with this PR merged. I am using that version but the problem is still present, so no, this PR is not relevant.

**Comment by yujincheng08** [comment]
Why reopen? it's not lsposed's issue.

**Comment by RecursiveRegistrations** [comment]
@yujincheng08 Then where does it come from? :cry: Do you know who I should be asking? You obviously know more about this than I do. It really looks like LSPosed could be at fault here.

**Comment by yujincheng08** [comment]
As you said,

> Enable the LSPosed module again, disable the Universal SafetyNet Fix module, and reboot the phone again.
> After the phone reboots, launch Blind. It will work as intended.

So it's not lsposed's issue.

**Comment by 5ec1cff** [comment]
![image](https://github.com/LSPosed/LSPosed/assets/56485584/35709516-82e6-4e3b-8af4-1e42c1b3b5e5)

**Comment by RecursiveRegistrations** [comment]
@yujincheng08 So is it a Zygisk issue then?? I am so confused.

@5ec1cff Well hopefully it goes away then. My phone is rooted though so I am worried about this. :cry:

**Comment by RecursiveRegistrations** [comment]
Blind v3.10.0 is out and the detection still happens, so it looks like the complaints on Google Play about faulty detections are garbage. :sob:
