### ISSUE TITLE
[Bug] Android 14 Beta 3 can't launch parasitic app

### ISSUE THREAD

**Issue by tangcla** [LSPosed/LSPosed#2573]
### Steps to reproduce/复现步骤

1. Try to start LSposed either by home screen icon, or silent notification

### Expected behaviour/预期行为

App should launch

### Actual behaviour/实际行为

Screenshot attached to show launched behaviour.
Home icon shows bug report dialog
Silent notification times out with an error
![Screenshot_20230620-172845](https://github.com/LSPosed/LSPosed/assets/8278114/258c6df0-250c-4e22-8bce-83c95518504c)
![Screenshot_20230620-172929](https://github.com/LSPosed/LSPosed/assets/8278114/66bd9329-6bf8-4f30-bef2-573c7a512795)

### Xposed Module List/Xposed 模块列表

```shell
None yet
```

### Magisk Module List/Magisk 模块列表

```shell
Safetynet fix
LSPosed
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

14 Beta 3

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Can't generate log as I can't start the app.

**Comment by githubcatw** [comment]
I installed the version mentioned in https://github.com/LSPosed/LSPosed/issues/2573#issuecomment-1598268457 and LSPosed doesn't appear in any way (notification, icon etc). Using a Pixel 5, Android 14 beta 3 and Magisk canary 26102.

**Comment by githubcatw** [comment]
@yujincheng08 I installed the version mentioned in https://github.com/LSPosed/LSPosed/issues/2573#issuecomment-1598268457 (Zygisk) and LSPosed doesn't appear in any way (notification, icon etc). Using a Pixel 5, Android 14 beta 3 and Magisk canary 26102.
