### ISSUE TITLE
Android 14 parasitic menu doesn't open[Bug] 

### ISSUE THREAD

**Issue by termonaitor2004** [LSPosed/LSPosed#2604]
### Steps to reproduce/复现步骤

Install android 14 beta 3 
Try to launch from notifications

### Expected behaviour/预期行为

Open parasitic menu 

### Actual behaviour/实际行为

Does nothing
Launching from secret number shows the bug reporting pop up doesn't launch menu after that

### Xposed Module List/Xposed 模块列表

```shell
Asopmods
Classic power menu
```

### Magisk Module List/Magisk 模块列表

```shell
Adb and fastboot ndk
Asopmods full
Fdroid privileged extension
Liboemcrypto disabler
Magisk built-in busybox
Magiskhide props config
Nano for Android ndk
Nostoragerestrict
Systemless hosts
Systemui bootloop saver
Universal safteynet fix
Lsposed zygisk
```

### LSPosed version/LSPosed 版本

1.8.6(6712)

### Android version/Android 版本

14 beta 3

### Magisk version/Magisk 版本

A8c4a33e

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Nothing in log file or verbose log file. Also am not in canary or debug

**Comment by yujincheng08** [comment]
fixed
