### ISSUE TITLE
[Bug] Cannot download assets on repository

### ISSUE THREAD

**Issue by Nep-Timeline** [LSPosed/LSPosed#2605]
### Steps to reproduce/复现步骤

1.Click Assets
2.Select browser

### Expected behaviour/预期行为

Open browser and jump to download link

### Actual behaviour/实际行为

nothing happened

### Xposed Module List/Xposed 模块列表

```shell
Nothing
```

### Magisk Module List/Magisk 模块列表

```shell
Uperf
HC_memory
MIUI Monet Project
Universal SafetyNet Fix
Universal GMS Doze
Dfps
Zygisk - LSPosed
Shamiko
Zygisk on KernelSU
```

### LSPosed version/LSPosed 版本

6924 (1.8.6)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

KernelSU 11075

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-07-06T17_29_43.881358.zip](https://github.com/LSPosed/LSPosed/files/11966737/LSPosed_2023-07-06T17_29_43.881358.zip)

**Comment by vvb2060** [comment]
We open browser with standard API, so there is nothing we can do.  It is recommended to check your browser settings.

**Comment by Nep-Timeline** [comment]
Default browser has been set, using Google Chrome
If all browsers in the device are removed and only the default browser is left, the problem will be solved

**Comment by Nep-Timeline** [comment]
Sorry, the issue has been resolved
The cause of the problem comes from Github Mobile
