### ISSUE TITLE
second space enhancement 

### ISSUE THREAD

**Issue by pablovinicius332** [LSPosed/LSPosed#2610]
hello, I would like to know if there is the possibility of making an improvement in the second space, I use the second space on my phone with Android 12 custom rom, and every time I need to use a module to work in it I need to create two versions of the same app in the first and second space, in previous version Android 10 on a Xiaomi, I just activated the module in either space and it worked without needing to have the same module in both spaces

**Comment by yujincheng08** [comment]
I dont understand what you are talking about.

**Comment by pablovinicius332** [comment]
sorry because i'm using translator, when i'm going to use a module, example Alltrans only in the second space, it won't work, i have to create a clone of the app in the first space,so activate both in lsposed for it to work, instead of, for example, having this app in the second space, and having to activate it only there, I think because I can't select the  framework from the second space in lsposed, Can you understand?

**Comment by yujincheng08** [comment]
barely.

> Alltrans only in the second space, it won't work

a module can work even if it is only installed on a secondary user.

>  I can't select the framework from the second space

expected. there's only one system framework, which is on the primary user.

**Comment by pablovinicius332** [comment]
so I think it could be a problem in the module itself, because I'm using another guise that can pull the apps from the second space, thanks man
