### ISSUE TITLE
[Feature Request] 希望可以加个隐藏指定模块的桌面图标功能

### ISSUE THREAD

**Issue by Mrqqeat** [LSPosed/LSPosed#2623]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

某些模块界面几乎用不到还不自带隐藏桌面图标功能，这种模块一多起来简直是灾难而且强迫症。

### Describe the solution you'd like/描述你想要的解决方案

希望可以加一个功能，隐藏指定模块，让该模块在桌面上不显示图标。

**Comment by yujincheng08** [comment]
你可以 pm hide 这个模块
