### ISSUE TITLE
[Bug] LSPosed最新稳定版1.8.6 导致 dex2oat 无法生成编译文件

### ISSUE THREAD

**Issue by anonymous12357** [LSPosed/LSPosed#2634]
### Steps to reproduce/复现步骤

1. 启用magisk delta和Zygisk版LSPosed最新稳定版
2. 编译oat文件：
adb shell cmd package compile -m speed -f XXXXX
3. 实际执行触发优化 dexopt job：
adb shell pm bg-dexopt-job
4. 查看oat文件是否编译：
adb shell dumpsys package XXXXX

### Expected behaviour/预期行为

dex2oat实际运行，并编译成功

### Actual behaviour/实际行为

Dexopt state:
  [com.taobao.idlefish]
    path: /data/app/~~gmI5tCNHnUjXpu_Sl0Bqqg==/com.taobao.idlefish-MSjmF8N6Ws8BIIMROw5Uew==/base.apk
      arm64: [status=run-from-apk] [reason=unknown]
      odex file size: base.art: **0Kb base.odex: 0Kb base.vdex: 0Kb**

### Xposed Module List/Xposed 模块列表

```shell
未启用任何模块
```

### Magisk Module List/Magisk 模块列表

```shell
LSPosed
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

miui13.0.13 安卓12

### Magisk version/Magisk 版本

Magisk delta 最新版

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-07-18T10_40_11.781.zip](https://github.com/LSPosed/LSPosed/files/12075346/LSPosed_2023-07-18T10_40_11.781.zip)

**Comment by yujincheng08** [comment]
修了。

**Comment by anonymous12357** [comment]
> 修了。

确实没有，MIUI13复现了

**Comment by anonymous12357** [comment]
> 修了。

请问是哪个版本修复了？LSPosed 1.8.6 可复现该问题

**Comment by yujincheng08** [comment]
修了你不用那有什么办法？README 写好的提 issue 时候用英文标题、用 ci 版、发 debug 日志，一个都没有遵守。拿着一个稳定版我们怎么修？发明时间机器然后回到稳定版发版之前修好这个 bug 再发布这个稳定版？

**Comment by anonymous12357** [comment]
ci 版已解决，感谢。因为1.8.6更新日志写着修复 dex2oat 回退，我以为问题修复了
