### ISSUE TITLE
希望能支持对system_server进程进行hook[Feature Request] 

### ISSUE THREAD

**Issue by lt541013990** [LSPosed/LSPosed#2637]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

希望能支持对system_server进程进行hook

### Describe the solution you'd like/描述你想要的解决方案

希望选择目标模块时可以支持

**Comment by yujincheng08** [comment]
已添加支持

**Comment by lt541013990** [comment]
大佬，求问那我应该要勾选哪个目标程序？ 系统框架么？
