### ISSUE TITLE
[Bug] Lsposed doesn't on Magisk alpha

### ISSUE THREAD

**Issue by MarisaDAZA** [LSPosed/LSPosed#2652]
### Steps to reproduce/复现步骤

1. Install Magisk alpha.
2. Open Zgisk.
3. Install Zgisk-Lsposed.
4. Reboot.

### Expected behaviour/预期行为

LSPosed worked.

### Actual behaviour/实际行为

Lsposed didn't work and Magisk said "Module suspended because Zgisk is not enable. (It did be enabled in setting.)

### Xposed Module List/Xposed 模块列表

```shell
none
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk-Lsposed v1.8.6(6951)
```

### LSPosed version/LSPosed 版本

6951

### Android version/Android 版本

13

### Magisk version/Magisk 版本

46770db1-alpha(26103)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[magisk_log_2023-07-29T23.11.58.log](https://github.com/LSPosed/LSPosed/files/12207467/magisk_log_2023-07-29T23.11.58.log)
[BugReport.zip](https://github.com/LSPosed/LSPosed/files/12207468/BugReport.zip)

**Comment by yujincheng08** [comment]
Are you sure you are using debug version of LSPosed?

**Comment by vvb2060** [comment]
07-29 23:05:33.412  1050  1052 W : zygote crashes too many times, rolling-back

**Comment by MarisaDAZA** [comment]
> Are you sure you are using debug version of LSPosed?

I am sure it is debug version.

**Comment by yujincheng08** [comment]
but i cannot see lsposed's debug log

**Comment by MarisaDAZA** [comment]
I used `adb bugreport`. Is't that right?

**Comment by yujincheng08** [comment]
right

**Comment by MarisaDAZA** [comment]
Sorry, I may made some mistake.
[BugReport.zip](https://github.com/LSPosed/LSPosed/files/12208952/BugReport.zip)

**Comment by yujincheng08** [comment]
Zip and send `/data/adb/lspd/log/` as well.

**Comment by MarisaDAZA** [comment]
[log.zip](https://github.com/LSPosed/LSPosed/files/12209194/log.zip)
[BugReport2.zip](https://github.com/LSPosed/LSPosed/files/12209195/BugReport2.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.8.6-6951-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12209330/LSPosed-v1.8.6-6951-zygisk-debug.zip)
Install this ver, reboot and send `/data/adb/lspd/log/`. I only add some logs, and it should not work.

**Comment by MarisaDAZA** [comment]
[log (1).zip](https://github.com/LSPosed/LSPosed/files/12209576/log.1.zip)

**Comment by yujincheng08** [comment]
[LSPosed-v1.8.6-6951-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12209589/LSPosed-v1.8.6-6951-zygisk-debug.zip)
Use this to get log again

**Comment by yujincheng08** [comment]
also, zip and send `/apex/com.android.art/lib64/libart.so`

**Comment by yujincheng08** [comment]
also, does official Magisk works?

**Comment by MarisaDAZA** [comment]
[log (2).zip](https://github.com/LSPosed/LSPosed/files/12209718/log.2.zip)
[libart.zip](https://github.com/LSPosed/LSPosed/files/12209719/libart.zip)

**Comment by MarisaDAZA** [comment]
official Magisk 26100 worked

**Comment by MarisaDAZA** [comment]
official Magisk Canary worked, as well.

**Comment by MarisaDAZA** [comment]
> [LSPosed-v1.8.6-6951-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12209589/LSPosed-v1.8.6-6951-zygisk-debug.zip)
> Use this to get log again

And, this worked on alpha

**Comment by yujincheng08** [comment]
> And, this worked on alpha

[LSPosed-v1.8.6-6951-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12211771/LSPosed-v1.8.6-6951-zygisk-debug.zip)

Strange. Use this ver to get the log using alpha again.

**Comment by MarisaDAZA** [comment]
[Uploading log (3).zip…]()

**Comment by MarisaDAZA** [comment]
[log (4).zip](https://github.com/LSPosed/LSPosed/files/12213021/log.4.zip)

**Comment by MarisaDAZA** [comment]
Well, guys, are you still solving this problem?

**Comment by 24matan** [comment]
i have same bug on lsposed 1.9.1
