### ISSUE TITLE
[Bug] Xposed module which applies changes to system will break NFC on MIUI v14.0.23

### ISSUE THREAD

**Issue by LeviMarvin** [LSPosed/LSPosed#2653]
### Steps to reproduce/复现步骤

1. Tested on Redmi Note 12 Turbo, Running MIUI V14.0.23 CN.
2. Install [LSPosed-v1.8.6-6951-zygisk-release](https://github.com/LSPosed/LSPosed/suites/14658533788/artifacts/831785379) on KernelSU.
3. Install an Xposed module which applys changes to system (系统框架) and enable it.
4. Reboot the phone.

### Expected behaviour/预期行为

NFC is working. (Auto enable without set disabled)

### Actual behaviour/实际行为

NFC can not be enabled and auto disabled. The settings page of NFC can not open.

### Xposed Module List/Xposed 模块列表

```shell
CorePatch (核心破解)
HideMyAppList (隐藏应用列表)
```

### Magisk Module List/Magisk 模块列表

```shell
ZygiskOnKernelSU
Shamiko
LSPosed-Zygisk
```

### LSPosed version/LSPosed 版本

6951

### Android version/Android 版本

13

### Magisk version/Magisk 版本

11155

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-08-01T01_56_31.554342.zip](https://github.com/LSPosed/LSPosed/files/12217844/LSPosed_2023-08-01T01_56_31.554342.zip)

**Comment by yujincheng08** [comment]
Invalid log.

**Comment by yujincheng08** [comment]
Also, tested with MIUI 14.0.27 CN and Magisk, and NFC works.

**Comment by LeviMarvin** [comment]
Can not save the log file. After click the button on Log tab, it creates an null zip file (size 0).
