### ISSUE TITLE
Lsposed not installed 

### ISSUE THREAD

**Issue by Ranit19081** [LSPosed/LSPosed#2657]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

API version
Not installed

Xposed API call protection
Not installed

Dex Optimizer Wrapper
Not installed

Framework version
Not installed

Manager version
1.8.6 (6712)

System version
13 (API 33)

Device
OnePlus CPH2487 

System ABI
arm64-v8a

### Describe the solution you'd like/描述你想要的解决方案

I need a fix for this problem 

### Additional context/其他信息

![Screenshot_2023-08-01-15-28-27-73_b7e9024f54bdc0532418cb6e23c85a7c](https://github.com/LSPosed/LSPosed/assets/133151302/0df2e660-7779-4e07-9c35-34d46d71df8c)

**Comment by yujincheng08** [comment]
then install.

**Comment by Ranit19081** [comment]
Sir I've already flashed lsposed but still it's not showing any
notification as it should be

**Comment by kutlay1653** [comment]
same issue, magisk module already installed but in lsposed app it says it doesnt. seems like dev isnt intented to fix it. it happened after reboot

**Comment by Ranit19081** [comment]
> same issue, magisk module already installed but in lsposed app it says it doesnt. seems like dev isnt intented to fix it. it happened after reboot

Brother I have a solution you can DM me in telegram @Sosukeaizen99.
