### ISSUE TITLE
[Bug] 6953版本无法正常导出日志

### ISSUE THREAD

**Issue by Yangleis** [LSPosed/LSPosed#2662]
### Steps to reproduce/复现步骤

![b366a6a9ed12ac8edd5414c52ca65cb4](https://github.com/LSPosed/LSPosed/assets/10060492/c75ed11f-62b5-43ec-892b-4ba244bdd308)
在日志页面点击右上方保存按钮，保存至Download目录。

### Expected behaviour/预期行为

得到包含日志文件的压缩包。

### Actual behaviour/实际行为

![839184fcd0a7fd5fb3dea999ec5d2aaa](https://github.com/LSPosed/LSPosed/assets/10060492/97940d36-95a5-476e-94f0-a6cced3336f6)
得到大小为0B的空zip包。

### Xposed Module List/Xposed 模块列表

```shell
哔哩漫游
大圣净化
ColorOS通知图标增强
LuckyTool
QAuxiliary
Scene5
TSBattery
```

### Magisk Module List/Magisk 模块列表

```shell
Scene的附加模块
Scene的附加模块(二)
Shamiko
Zygisk-LSPosed
```

### LSPosed version/LSPosed 版本

6953

### Android version/Android 版本

13 （API 33）

### Magisk version/Magisk 版本

d390ca2f(26104) （Canary Channel ）

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [x] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

由于无法正常自动导出日志，以下日志是我自行从/data/adb/lspd/log中得到的，如有缺失请提醒我补充。
[log.zip](https://github.com/LSPosed/LSPosed/files/12258589/log.zip)

**Comment by matthius7** [comment]
OnePlus 9 13.1 build latest zygisk lsposed is broken. When I click to configure says not installed. It is installed and I can't activate any modules :(

**Comment by Yangleis** [comment]
> OnePlus 9 13.1 build latest zygisk lsposed is broken. When I click to configure says not installed. It is installed and I can't activate any modules :(

Try using the latest auto-build version in action, it works.

**Comment by matthius7** [comment]
Where is this auto build? Sorry I don't know where to find
