### ISSUE TITLE
[Bug] LSPosed not installed

### ISSUE THREAD

**Issue by kaliiiiiiiiii** [LSPosed/LSPosed#2663]
### Steps to reproduce/复现步骤

1. OTA-Update (install magisk to ota-slot)
2. Install `LSPosed-v1.8.6-6712-zygisk-release.zip` with magisk
3. reboot

### Expected behaviour/预期行为

LSPosed notification is shown

### Actual behaviour/实际行为

- no notification shown
- installing LSPosed-manger as apk:
    - reported as not-installed

### Xposed Module List/Xposed 模块列表

```shell
-
```

### Magisk Module List/Magisk 模块列表

```shell
-
```

### LSPosed version/LSPosed 版本

1.8.6-6712

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[verbose_2023-08-04T16:40:18.368803.log](https://github.com/LSPosed/LSPosed/files/12262713/verbose_2023-08-04T16.40.18.368803.log)

**Comment by yujincheng08** [comment]
Not debug ver
