### ISSUE TITLE
[Bug] Do not automatically update module while reinstall a new module apk

### ISSUE THREAD

**Issue by AiziChen** [LSPosed/LSPosed#2665]
### Steps to reproduce/复现步骤

1. 使用Android Studio 开发一个XP插件。
2. 运行并安装至手机，第一次安装会有通知拦提示：“Xposed Module Updated”。
3. 更改Hook代码的逻辑，并重新运行至手机，LSPosed不会提示“Xposed Module Updated”。此时Hook代码的逻辑也没有被改变。

### Expected behaviour/预期行为

在重新安装插件后，会在通知栏有模块更新的提示，Hook代码的逻辑也会跟着改变。

### Actual behaviour/实际行为

在重新安装插件后，没有模块更新的提示，Hook代码的逻辑也不会跟着改变。

### Xposed Module List/Xposed 模块列表

```shell
WxPocketHook
```

### Magisk Module List/Magisk 模块列表

```shell
Shamiko
Systemless Hosts
Universal SaftyNet Fix
Zygisk - LSPosed
Zygisk - Sui
```

### LSPosed version/LSPosed 版本

1.8.6 (6955)

### Android version/Android 版本

Android 13 (API 33)

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-08-05T02_11_29.130079.zip](https://github.com/LSPosed/LSPosed/files/12263560/LSPosed_2023-08-05T02_11_29.130079.zip)

**Comment by yujincheng08** [comment]
![image](https://github.com/LSPosed/LSPosed/assets/5022927/6a78ae83-a657-4826-9e89-cae680bd3695)
