### ISSUE TITLE
[Bug] Modules installed via USB debugging using Android Studio will not be updated

### ISSUE THREAD

**Issue by ElainaForever** [LSPosed/LSPosed#2669]
### Steps to reproduce/复现步骤

1. Develop the module in Android Studio as usual and install it using ADB
2. The module should be installed properly
3. When you change your code in Android Studio and install it again, LSPosed doesn't give you the "<module name> has been updated" message.
4. At this point the code for the module is from the first installation, not from the modification

### Expected behaviour/预期行为

LSPosed should give a hint and the module code is correctly updated

### Actual behaviour/实际行为

In fact, the installation is shown as successful in Android Studio, but the actual module in the phone is not updated

### Xposed Module List/Xposed 模块列表

```shell
Enable self-developed modules only
```

### Magisk Module List/Magisk 模块列表

```shell
Zygisk - LSPosed
Shamiko
Box for magisk
RescueBrick
WorkSettingPro
```

### LSPosed version/LSPosed 版本

v1.8.6 (6712)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-08-06T18_07_56.111404.zip](https://github.com/LSPosed/LSPosed/files/12269148/LSPosed_2023-08-06T18_07_56.111404.zip)

**Comment by vvb2060** [comment]
https://github.com/LSPosed/LSPosed/issues/2665#issuecomment-1666005059

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed/issues/2665#issuecomment-1666005059
