### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by uvawp** [LSPosed/LSPosed#2675]
### Steps to reproduce/复现步骤

1, Flash LSPosed Zygisk
2. Install some modules
3. Turn it on with all requirements

### Expected behaviour/预期行为

All modules shows, and should work all fine

### Actual behaviour/实际行为

Modules do show all good, i was able to toggle it all and configure it. But they just doesn't work. For example, I'm trying to use CustoMIUIzer14 90fps screen recording, but it doesn't do anything. Core Patcher, NFG, Cemiuiler or any module doesn't work either, even if LSPosed (says) it's active.

### Xposed Module List/Xposed 模块列表

```shell
CustoMIUIzer14
Core Patcher
Cemiuiler
NFG
```

### Magisk Module List/Magisk 模块列表

```shell
Only LSPosed Zygisk
```

### LSPosed version/LSPosed 版本

1.8.6 (6712)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-08-09T01_29_44.799773.zip](https://github.com/LSPosed/LSPosed/files/12298284/LSPosed_2023-08-09T01_29_44.799773.zip)
[magisk_log_2023-08-09T01.29.59.log](https://github.com/LSPosed/LSPosed/files/12298286/magisk_log_2023-08-09T01.29.59.log)

**Comment by uvawp** [comment]
What i've done wrong?

**Comment by Howard20181** [comment]
1. Not using latest CI build. 
2. For modules issues, report to its authors.
