### ISSUE TITLE
[Bug] lsposed not working

### ISSUE THREAD

**Issue by petmarb** [LSPosed/LSPosed#2684]
### Steps to reproduce/复现步骤

just updated my op9pro via ota and system updater to oxygen os 13.1 (le2123_13.1.0.590(ex01), resinstalled magisk in inactive slot, rebooted, root is fine, but lsposed doesn't work anymore. manager says it isn't installed, but the magisk module (zygisk) is installed and reinstallation doesn't change anything

### Expected behaviour/预期行为

just updated my op9pro via ota and system updater to oxygen os 13.1 (le2123_13.1.0.590(ex01), resinstalled magisk in inactive slot, rebooted, root is fine, but lsposed doesn't work anymore. manager says it isn't installed, but the magisk module (zygisk) is installed and reinstallation doesn't change anything

### Actual behaviour/实际行为

just updated my op9pro via ota and system updater to oxygen os 13.1 (le2123_13.1.0.590(ex01), resinstalled magisk in inactive slot, rebooted, root is fine, but lsposed doesn't work anymore. manager says it isn't installed, but the magisk module (zygisk) is installed and reinstallation doesn't change anything

### Xposed Module List/Xposed 模块列表

```shell
just updated my op9pro via ota and system updater to oxygen os 13.1 (le2123_13.1.0.590(ex01), resinstalled magisk in inactive slot, rebooted, root is fine, but lsposed doesn't work anymore. manager says it isn't installed, but the magisk module (zygisk) is installed and reinstallation doesn't change anything
```

### Magisk Module List/Magisk 模块列表

```shell
just updated my op9pro via ota and system updater to oxygen os 13.1 (le2123_13.1.0.590(ex01), resinstalled magisk in inactive slot, rebooted, root is fine, but lsposed doesn't work anymore. manager says it isn't installed, but the magisk module (zygisk) is installed and reinstallation doesn't change anything
```

### LSPosed version/LSPosed 版本

1.8.6(6712)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

n/a

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

just updated my op9pro via ota and system updater to oxygen os 13.1 (le2123_13.1.0.590(ex01), resinstalled magisk in inactive slot, rebooted, root is fine, but lsposed doesn't work anymore. manager says it isn't installed, but the magisk module (zygisk) is installed and reinstallation doesn't change anything

**Comment by yujincheng08** [comment]
fixed

**Comment by petmarb** [comment]
cool, could u tell how to fix it?

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed/commit/8b3e331c5e1b4cf303d83d3364b5cd2437a44ca2

**Comment by FCBThunder** [comment]
Could you please show me the steps to fix this issue. Thank you. (OOS 13 1 latest OnePlus 9 (Lsposed not installed message)

**Comment by petmarb** [comment]
[LSPosed-v1.8.6-6963-zygisk-release.zip](https://github.com/LSPosed/LSPosed/files/12332750/LSPosed-v1.8.6-6963-zygisk-release.zip)
just install this version, worked for me.

**Comment by FCBThunder** [comment]
> [LSPosed-v1.8.6-6963-zygisk-release.zip](https://github.com/LSPosed/LSPosed/files/12332750/LSPosed-v1.8.6-6963-zygisk-release.zip) just install this version, worked for me.

Works like a sharm thanks!

**Comment by fatalcoder524** [comment]
> [LSPosed-v1.8.6-6963-zygisk-release.zip](https://github.com/LSPosed/LSPosed/files/12332750/LSPosed-v1.8.6-6963-zygisk-release.zip) just install this version, worked for me.

How to get such links? I need for some other version?

**Comment by petmarb** [comment]
there is a Telegram channel called LSposedArchives, have a look there
