### ISSUE TITLE
[Bug] System Freezes on Android 14 

### ISSUE THREAD

**Issue by DrKetan** [LSPosed/LSPosed#2685]
### Steps to reproduce/复现步骤

Install LSposed framework on A14 on Samsung Galaxy S23 Ultra OneUi 6.0

### Expected behaviour/预期行为

No freeze

### Actual behaviour/实际行为

System Freezing after reboot

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
SafetyNet fix 2.4.0
```

### LSPosed version/LSPosed 版本

1.8.6

### Android version/Android 版本

14

### Magisk version/Magisk 版本

Alpha 26105

### Riru version/Riru 版本

No

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-08-14T01_23_24.150581.zip](https://github.com/LSPosed/LSPosed/files/12330295/LSPosed_2023-08-14T01_23_24.150581.zip)
[LSPosed_2023-08-14T01_43_29.138501.zip](https://github.com/LSPosed/LSPosed/files/12330328/LSPosed_2023-08-14T01_43_29.138501.zip)

**Comment by DrKetan** [comment]
[LSPosed_2023-08-14T01_43_29.138501.zip](https://github.com/LSPosed/LSPosed/files/12330326/LSPosed_2023-08-14T01_43_29.138501.zip)

**Comment by yujincheng08** [comment]
Similar reports were received. The system_server freezes will handling `android.intent.action.LOCKED_BOOT_COMPLETED`. Will investigate after sources of Android 14 release.

**Comment by IGProd** [comment]
Lsposed icon does not show in coloros 13.1
[lsposed.log](https://github.com/LSPosed/LSPosed/files/12346329/lsposed.log)

**Comment by Howard20181** [comment]
Please test with this build
[LSPosed-v1.8.6-6968-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12366170/LSPosed-v1.8.6-6968-zygisk-debug.zip)

**Comment by DrKetan** [comment]
> Please test with this build [LSPosed-v1.8.6-6968-zygisk-debug.zip](https://github.com/LSPosed/LSPosed/files/12366170/LSPosed-v1.8.6-6968-zygisk-debug.zip)

This worked! Thank you very much.
