### ISSUE TITLE
[Bug] Breaks revolut 9.16 onwards

### ISSUE THREAD

**Issue by infinity0** [LSPosed/LSPosed#2686]
### Steps to reproduce/复现步骤

1. Install Revolut 9.16 or later and open it.

### Expected behaviour/预期行为

App should open normally.

### Actual behaviour/实际行为

App crashes immediately when starting up.

Workaround for now is to downgrade to Revolut 9.15, but they will stop supporting that at some point.

### Xposed Module List/Xposed 模块列表

```shell
* XPrivacyLua 1.35
```

### Magisk Module List/Magisk 模块列表

```shell
* LSPosed 1.8.6-6712
* Shamiko 0.7.3-174
* Universal SafetynetFix 2.4.0
* MagiskHide Props Config 6.1.2-137
```

### LSPosed version/LSPosed 版本

6712

### Android version/Android 版本

13 / LineageOS 20 with MicroG

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

~~~~
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: Crash unexpectedly: java.lang.RuntimeException: Unable to create application com.revolut.ProtectedRevolutApplication: com.revolut.MessageGuardException_RFA6IDc1OSBbMjAyMzA4MDMtMjAyMzA4MDkxOTE1IGI3OmFybTY0LXY4YSAzMyBPbmVQbHVzL09uZVBsdXM4VF9FRUEvT25lUGx1czhUOjEzL1JLUTEuMjExMTE5LjAwMS9SLjEwMzgxNTMtNWNlLThlNTQ5OnVzZXIvcmVsZWFzZS1rZXlzIGJsb2NrZWRd: DP: 759
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6810)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at android.os.Looper.loopOnce(Looper.java:201)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at android.os.Looper.loop(Looper.java:288)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: Caused by: com.revolut.MessageGuardException_RFA6IDc1OSBbMjAyMzA4MDMtMjAyMzA4MDkxOTE1IGI3OmFybTY0LXY4YSAzMyBPbmVQbHVzL09uZVBsdXM4VF9FRUEvT25lUGx1czhUOjEzL1JLUTEuMjExMTE5LjAwMS9SLjEwMzgxNTMtNWNlLThlNTQ5OnVzZXIvcmVsZWFzZS1rZXlzIGJsb2NrZWRd: DP: 759
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at com.revolut.ProtectedRevolutApplication.EDwia(Unknown Source:2)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at com.revolut.ProtectedRevolutApplication.onCreate(Unknown Source:54)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6805)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	... 9 more
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: Caused by: java.lang.RuntimeException: DP: 759
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at com.revolut.ProtectedRevolutApplication.tiCAm(Native Method)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at java.lang.reflect.Method.invoke(Native Method)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at com.revolut.ProtectedRevolutApplication$RevolutApplication$initRxJavaGlobalErrorHandling$1.HiC(Unknown Source:31)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at com.revolut.ProtectedRevolutApplication$RevolutApplication$initRxJavaGlobalErrorHandling$1.igHgjr(Unknown Source:472)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at com.revolut.ProtectedRevolutApplication.tiCAm(Native Method)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	at com.revolut.ProtectedRevolutApplication.onCreate(Unknown Source:46)
08-14 00:08:38.975 20101 20101 I LSPosed-Bridge: 	... 11 more
--------- beginning of crash
08-14 00:08:38.975 20101 20101 E AndroidRuntime: FATAL EXCEPTION: main
08-14 00:08:38.975 20101 20101 E AndroidRuntime: Process: com.revolut.revolut, PID: 20101
08-14 00:08:38.975 20101 20101 E AndroidRuntime: java.lang.RuntimeException: Unable to create application com.revolut.ProtectedRevolutApplication: com.revolut.MessageGuardException_RFA6IDc1OSBbMjAyMzA4MDMtMjAyMzA4MDkxOTE1IGI3OmFybTY0LXY4YSAzMyBPbmVQbHVzL09uZVBsdXM4VF9FRUEvT25lUGx1czhUOjEzL1JLUTEuMjExMTE5LjAwMS9SLjEwMzgxNTMtNWNlLThlNTQ5OnVzZXIvcmVsZWFzZS1rZXlzIGJsb2NrZWRd: DP: 759
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6810)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at android.app.ActivityThread.-$$Nest$mhandleBindApplication(Unknown Source:0)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2132)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:106)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at android.os.Looper.loopOnce(Looper.java:201)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:288)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:7918)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: Caused by: com.revolut.MessageGuardException_RFA6IDc1OSBbMjAyMzA4MDMtMjAyMzA4MDkxOTE1IGI3OmFybTY0LXY4YSAzMyBPbmVQbHVzL09uZVBsdXM4VF9FRUEvT25lUGx1czhUOjEzL1JLUTEuMjExMTE5LjAwMS9SLjEwMzgxNTMtNWNlLThlNTQ5OnVzZXIvcmVsZWFzZS1rZXlzIGJsb2NrZWRd: DP: 759
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at com.revolut.ProtectedRevolutApplication.EDwia(Unknown Source:2)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at com.revolut.ProtectedRevolutApplication.onCreate(Unknown Source:54)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1277)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6805)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	... 9 more
08-14 00:08:38.975 20101 20101 E AndroidRuntime: Caused by: java.lang.RuntimeException: DP: 759
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at com.revolut.ProtectedRevolutApplication.tiCAm(Native Method)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at com.revolut.ProtectedRevolutApplication$RevolutApplication$initRxJavaGlobalErrorHandling$1.HiC(Unknown Source:31)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at com.revolut.ProtectedRevolutApplication$RevolutApplication$initRxJavaGlobalErrorHandling$1.igHgjr(Unknown Source:472)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at com.revolut.ProtectedRevolutApplication.tiCAm(Native Method)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	at com.revolut.ProtectedRevolutApplication.onCreate(Unknown Source:46)
08-14 00:08:38.975 20101 20101 E AndroidRuntime: 	... 11 more
~~~~

**Comment by infinity0** [comment]
The problem might not be related to LSPosed, the base64 in the exception message decodes to "DP: 759 [20230803-202308091915 b7:arm64-v8a 33 OnePlus/OnePlus8T_EEA/OnePlus8T:13/RKQ1.211119.001/R.1038153-5ce-8e549:user/release-keys blocked]" which sounds like either a SafetyNet issue or they are manually blacklisting my build fingerprint. Will close for now and keep investigating on my end...

**Comment by infinity0** [comment]
Upon further investigation, the bug is to do with LSPosed.

1. I have got SafetyNet working, so the problem is not with SafetyNet.
2. If I disable all LSPosed modules on the Revolut app, it works again.
3. If I enable *any* single LSPosed module on the Revolut app, it breaks. It does not matter which module I enable, so the problem is not with any specific module.

Therefore the issue is caused by LSPosed, therefore re-opening. Please look into it.

I am using Shamkio to hide root from revolut, otherwise it complains. However I did not change this between steps (2) and (3) above either, so the problem is probably not related to Shamiko.

The exception `java.lang.RuntimeException: DP: 759` seems to be caused by some sort of protection library that the banking app uses. I have found two other places on the web with a similar problem:

* https://forum.xda-developers.com/t/magisk-general-support-discussion.3432382/page-2586#post-86825595
* https://new.c.mi.com/id/post/370083

The app in those cases is different, but the stack traces are similar, with this unique pattern:

~~~~
[..]
Caused by: java.lang.RuntimeException: DP: XXX
    at xxx.ProtectedApplication.xxx(Native Method)
    at java.lang.reflect.Method.invoke(Native Method)
    at xxx.ProtectedApplication$ProtectedApplication$Foo$d.xxx(Unknown Source:31)
    at xxx.ProtectedApplication$ProtectedApplication$Foo$d.xxx(Unknown Source:472)
[..]
~~~~

**Comment by yujincheng08** [comment]
lsposed will not focusing on passing a single app. you can develop a module for it.

**Comment by infinity0** [comment]
As I mentioned, the same problem occurs with a bunch of different apps that use the same technique. Furthermore as I explained the problem is not related to any particular module, therefore it is impossible to "develop a module for it" as the problem happens in LSPosed, before the module does anything.

The behaviour is a bit nuanced:

1. Enable the module + check the app in LSPosed
2. Force stop + restart -> App is still working
3. Enable "App" inside the module settings.
4. Force stop + restart -> App breaks.
5. Disable "App" inside the module settings.
6. Force stop + restart -> App is still broken
7. Uncheck the app in LSPosed.
8. Force stop + restart -> App works again

Again, it does not matter which module you use. It is a LSPosed problem, not a module problem.

**Comment by yujincheng08** [comment]
> the problem happens in LSPosed

No.

**Comment by infinity0** [comment]
Why, what's wrong with my explanation?

**Comment by infinity0** [comment]
Seems somebody else has had a similar problem with a different app here: https://github.com/orgs/LSPosed/discussions/2055

The app is certainly not Revolut, as he had his problem last July, but Revolut only stopped working recently.

**Comment by yujincheng08** [comment]
LSPosed will try to avoid being detected by apps NOT in any modules' scope. But once the app is in a module's scope, there are a bunch of ways to detect LSPosed. And LSPosed does not care about it. You can develop a module for them, but LSPosed won't do it.

**Comment by infinity0** [comment]
Can you document the "bunch of ways to detect" somewhere?

What is the value of [developing and distributing Shamiko](https://github.com/LSPosed/LSPosed.github.io/releases) to hide Magisk from apps, but not caring about hiding of LSPosed?

**Comment by yujincheng08** [comment]
Shamiko tries to hide Magisk from apps. And make sure LSPosed is not detected by apps that are not in any modules' scope.

**Comment by infinity0** [comment]
Could you elaborate on the specific technical reasons how a separate module would help in this case, when the app breaks on *any* LSPosed module.

Are there any examples of other modules that hide LSPosed for other specific apps, that you can point me to so I learn from them?

I'm a developer but not an Android developer and I don't have the background for all this root stuff, I just want to run my payments app.

**Comment by infinity0** [comment]
I just paid you $20. If you can help me unbreak the app I'll be able to pay you more in future because it's coming from the payments app that is being broken.

**Comment by powellnorma** [comment]
I am experiencing this issue too

**Comment by Hi-ImKyle** [comment]
> I just paid you $20

I'm sure they are grateful but I don't think they care unfortunately. Sad to hear. Guess we will just have to suffer as is unless someone can figure something out in the mean time...

**Comment by C0rn3j** [comment]
Workaround is to enable Enforce DenyList in Magisk for only Revolut and add it to the deny list.

Also, if you still use SafetyNetFix, you probably want to replace it with https://github.com/chiteroman/PlayIntegrityFix

**Comment by infinity0** [comment]
Enforcing Denylist in Magisk for that app without having Shamiko installed, is the same as disabling Magisk for that app. So LSPosed is out of the picture entirely in that case.

**Comment by C0rn3j** [comment]
Indeed, which is why I am tagging it as workaround and not a fix.

**Comment by infinity0** [comment]
Or just disable the module inside LSPosed itself for Revolut and other affected apps, much more direct and to-the-point. Other non-LSPosed things that use Magisk can then still be used with those apps.
