### ISSUE TITLE
[Bug] LSPosed-zygisk fails to open manager UI on masgisk 26.1

### ISSUE THREAD

**Issue by bugsyb** [LSPosed/LSPosed#2687]
### Steps to reproduce/复现步骤

1. Install Zygisk LSPosed module.
2. Reboot
3. A notification is there ("LSPosed loaded"), tap on it.
4. A popup "Bug reports contain data from the system's various log files ......" shows up.
5. Regardless of options selected, i.e. don't show again and ok, brings same pop-up again on next try.

Seems to be the same as: https://github.com/LSPosed/LSPosed/issues/2561

Apologies, can't find a way to download debug version from "actions" section.

### Expected behaviour/预期行为

Open LSPosed app.

### Actual behaviour/实际行为

A popup "Bug reports contain data from the system's various log files ......" shows up.
Regardless of options selected, i.e. don't show again and ok, brings same pop-up again on next try.

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
microG Installer Revived (problem with installation, though unrelated most probably - Play Store is reporting issues)
Module Manager
Shamiko
Universal SafetyNet fix
Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

1,8,6

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[lsposed.log](https://github.com/LSPosed/LSPosed/files/12340076/lsposed.log)

**Comment by bugsyb** [comment]
Debug was tricky to find - it is on Telegram channel (https://t.me/s/LSPosedArchives) and couldn't find anything in actions.
After running latest and in debug version LSPosed-v1.8.6-6963-zygisk-{debug,release}.
It worked if run from task list. If tried to run from icon, same error pops up.

**Comment by Howard20181** [comment]
Your log does not contain useful information, please try again!
