### ISSUE TITLE
[BUG] app not hooked

### ISSUE THREAD

**Issue by etmatrix** [LSPosed/LSPosed#269]
I opened a similar issue also on edxposed.
I have a Android 8.1 x86 installed on virtualbox. I have the same issue on Android 8.0 arm with EdXposed.
LSPosed don't support android 8.0 so I tested on Android 8.1 x86.
Magisk 21.4
Magisk modules: riru core, lsposed 1.1.0 (lastest)
Riru core: 23.7 (lastest)

```
Manufacturer: innotek GmbH
Brand: Android-x86
Device: x86
Product: x86
Model: VirtualBox
Fingerprint: Android-x86/android_x86/x86:8.1.0/OPM8.190605.005/cwhuang0318:userdebug/test-keys
ROM description: android_x86-userdebug 8.1.0 OPM8.190605.005 eng.cwhuang.0318 test-keys
Architecture: x86
Android build: OPM8.190605.005
Android version: 8.1.0
Android sdk: 27
LSPosed version: v1.1.0
LSPosed version code: 5368
LSPosed api: 93
Riru version: v23.7 (57)
Riru api: 10
Magisk: 21.4 (21400)

```

LSPosed modules: my testing module

My module is simple hook the constructor of class android.content.Intent and log string parameter.

            Class<?> clsIntent = XposedHelpers.findClass("android.content.Intent", classLoader);
            XC_MethodHook.Unhook un = XposedHelpers.findAndHookConstructor(clsIntent, String.class, new XC_MethodHook() {
                @Override
                protected void beforeHookedMethod(MethodHookParam param) throws Throwable
                {
                    logV("Intent " + param.args[0].toString());
                }
            });

It's work with all tested apps except for rikka appops. Until version 5.1.3 I can log intent but from version 5.2.0 Intent is not logged. I tried the same code with frida and log intent works with all versions of rikka appops. My scope is not debug rikka appops but understand because my module doesn't work with this app.

Is there a debug version of LSPosed? I will try to build and post logs.

**Comment by etmatrix** [comment]
I tried the lastest version debug 1.2.0 [here](https://controlc.com/6f8de095) the debug log

```
Manufacturer: innotek GmbH
Brand: Android-x86
Device: x86
Product: x86
Model: VirtualBox
Fingerprint: Android-x86/android_x86/x86:8.1.0/OPM8.190605.005/cwhuang0318:userdebug/test-keys
ROM description: android_x86-userdebug 8.1.0 OPM8.190605.005 eng.cwhuang.0318 test-keys
Architecture: x86
Android build: OPM8.190605.005
Android version: 8.1.0
Android sdk: 27
LSPosed version: v1.2.0
LSPosed version code: 5395
LSPosed api: 93
Riru version: v23.8 (58)
Riru api: 10
Magisk: 21.4 (21400)

```

I updated riru core to 21.8

**Comment by yujincheng08** [comment]
No, we need verbose log instead.

**Comment by yujincheng08** [comment]
Oh btw, rikka apps are anti-xposed. You will need native hook to anti-anti-xposed.

**Comment by etmatrix** [comment]
@yujincheng08 have you some example?

**Comment by yujincheng08** [comment]
Rikka apps' anti-xposed is from https://github.com/vvb2060/XposedDetector.
For inline hook, plz see example: https://github.com/LSPosed/XposedUnitTest

**Comment by etmatrix** [comment]
@yujincheng08 so a day when many apps implement this protection Xposed, EdXposed and LSPosed will be useless.
Have you an example of anti-anti-xposed?

**Comment by yujincheng08** [comment]
@etmatrix that's why we introduced native hook.

No example. Different apps have different strategies.

No more explaination.
