### ISSUE TITLE
[Bug] XsharedPreferences change listener

### ISSUE THREAD

**Issue by mwilky** [LSPosed/LSPosed#2690]
[LSPosed_2023-08-16T09_26_29.686353.zip](https://github.com/LSPosed/LSPosed/files/12357296/LSPosed_2023-08-16T09_26_29.686353.zip)
### Steps to reproduce/复现步骤

1. Implement new XSharedPreferences (API 93+)
2. Change value of a pref from inside module
3. Monitor listener in hooked app

### Expected behaviour/预期行为

Listener should run the code when the preference is changed

### Actual behaviour/实际行为

`tryRegisterWatcher: access denied to /data/misc/71af82a5-bcac-476d-bdbe-1e58a70af358/prefs/com.mwilky.androidenhanced/sysui_prefs.xml `

Nothing, value is successfully read when the method is hooked, but changes afterwards aren't spotted by the listener.

```
fun init(classLoader: ClassLoader?) {
            XposedHelpers.findAndHookMethod(
                PhoneStatusBarView,
                classLoader,
                "onAttachedToWindow",
                object : XC_MethodHook() {
                    override fun afterHookedMethod(param: MethodHookParam) {
                        log("mwilky: in PhoneStatusBarView")
                        val prefs = XposedInit.prefForSystemUI
                        if (prefs != null) {
                            //Get prefs
                            val switchOneEnabled = prefs.getBoolean("switch_one", false)
                            log("mwilky: switchOneEnabled = $switchOneEnabled")

                            // Add a listener to the shared preferences to track changes
                            val listener =
                                SharedPreferences.OnSharedPreferenceChangeListener { sharedPreferences, key ->
                                    prefs.reload()
                                    val switchOneEnabledNew = prefs.getBoolean("switch_one", false)
                                    log("mwilky: new value = $switchOneEnabledNew")
                                }

                            prefs.registerOnSharedPreferenceChangeListener(listener)
                        }
                    }
                }
            )
        }
```

`log("mwilky: switchOneEnabled = $switchOneEnabled")` - Reads the value set from the module correctly when method is hooked.

I toggle the switch which sets the new pref value

`log("mwilky: new value = $switchOneEnabledNew")` - Never gets executed

XposedInit class is:

```
class XposedInit : IXposedHookLoadPackage {

    companion object {
        private fun getPref(path: String) : XSharedPreferences? {
            val pref = XSharedPreferences("com.mwilky.androidenhanced", path)
            return if(pref.file.canRead()) pref else null
        }

        const val SYSTEMUI_PREFS = "sysui_prefs"

        // lazy loads when needed
        val prefForSystemUI by lazy { getPref(SYSTEMUI_PREFS) }
    }

    override fun handleLoadPackage(lpparam: XC_LoadPackage.LoadPackageParam?) {
        //Packages to hook
        val SystemUI = "com.android.systemui"

        when(lpparam?.packageName) {
            SystemUI -> {
                SystemUIStatusbar.init(lpparam.classLoader)
            }
        }
    }

}
```

### Xposed Module List/Xposed 模块列表

```shell
None apart from this WIP app
```

### Magisk Module List/Magisk 模块列表

```shell
USNF
Zygisk - LSPOSED v1.8.6 (6712)
```

### LSPosed version/LSPosed 版本

6712

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26105

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志
[LSPosed_2023-08-16T09_26_29.686353.zip](https://github.com/LSPosed/LSPosed/files/12357316/LSPosed_2023-08-16T09_26_29.686353.zip)

**Comment by mwilky** [comment]
Doesn't the document need updating then if it isn't going to be resolved?

https://github.com/LSPosed/LSPosed/wiki/New-XSharedPreferences#preference-change-listener-in-a-hooked-process

**Comment by yujincheng08** [comment]
If there's a problem, we would fix it. But since you don't follow the issue instruction, we don't even bother to look at it.

**Comment by mwilky** [comment]
> If there's a problem, we would fix it. But since you don't follow the issue instruction, we don't even bother to look at it.

Sorry, I am not sure what I have missed?

**Comment by mwilky** [comment]
> If there's a problem, we would fix it. But since you don't follow the issue instruction, we don't even bother to look at it.

Sorry, debug log attached

`tryRegisterWatcher: access denied to /data/misc/71af82a5-bcac-476d-bdbe-1e58a70af358/prefs/com.mwilky.androidenhanced/sysui_prefs.xml
`
[LSPosed_2023-08-16T09_26_29.686353.zip](https://github.com/LSPosed/LSPosed/files/12357309/LSPosed_2023-08-16T09_26_29.686353.zip)

**Comment by Howard20181** [comment]
Please try again with the latest CI

**Comment by mwilky** [comment]
> 

6968 gives same error:

`e/EXSharedPreferences ] tryRegisterWatcher: access denied to /data/misc/71af82a5-bcac-476d-bdbe-1e58a70af358/prefs/com.mwilky.androidenhanced/sysui_prefs.xml`

**Comment by vvb2060** [comment]
expected behavior, use remote preference

**Comment by Dr-TSNG** [comment]
1. New XSharedPreferences is going to be deprecated in the next major version. We may fully remove this feature (that's to say, return to the OG Xposed behavior) several versions later after the official release of the modern Xposed API.
2. The modern Xposed API has supported this feature, because it stores K-V data in our database instead of an xml. See the example [here](https://github.com/libxposed/example/blob/master/app/src/main/java/io/github/libxposed/example/ModuleMain.kt).

**Comment by MonwF** [comment]
> 1. New XSharedPreferences is going to be deprecated in the next major version. We may fully remove this feature (that's to say, return to the OG Xposed behavior) several versions later after the official release of the modern Xposed API.
> 2. The modern Xposed API has supported this feature, because it stores K-V data in our database instead of an xml. See the example [here](https://github.com/libxposed/example/blob/master/app/src/main/java/io/github/libxposed/example/ModuleMain.kt).

hello. i get crazy that remotepreference listener doesnt trigger with both the given example and my module.

magisk 26.2
lsposef 1.9.1
miui 14 with android 13
