### ISSUE TITLE
[Bug] random reboot

### ISSUE THREAD

**Issue by Onionfish2** [LSPosed/LSPosed#2696]
### Steps to reproduce/复现步骤

1.install lsposed (6712 and up on) 
2.phone will random reboot 

### Expected behaviour/预期行为

No crash

### Actual behaviour/实际行为

Random reboot when using

### Xposed Module List/Xposed 模块列表

```shell
1.555NoAd 1.0.5
2.哔哩发评反诈 2.6.5
3.哔哩漫游 1.6.12
4.逗音小能手 2.0
5.拒绝强制亮度 1.1
6.微x模块 2.41
7.隐藏应用列表 3.2
8.A1-内存-附加 1.2
9.iconify 6.4.0
10.Qa 1.4.3
11.tsbattery 4.3
12.fuckcoolapk 1.16.4
```

### Magisk Module List/Magisk 模块列表

```shell
kernel su 
A1内存管理
shamiko 0.7.3 174
zygisk on kernelsu
zygisk lsposed
zygisk 微信指纹支付
scene 附加模块2
iconify
```

### LSPosed version/LSPosed 版本

6971

### Android version/Android 版本

13

### Magisk version/Magisk 版本

kernelsu 11203

### Riru version/Riru 版本

N/A V4.0.7.1 (91-ceaa 2d4-release)

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[modules_1970-02-28T12:31:55.078509.log](https://github.com/LSPosed/LSPosed/files/12378739/modules_1970-02-28T12.31.55.078509.log)
[verbose_2023-08-18T18:36:22.69021.log](https://github.com/LSPosed/LSPosed/files/12378743/verbose_2023-08-18T18.36.22.69021.log)

**Comment by Onionfish2** [comment]
this is a log which use wireless logcat to get .i use one night to get it . SO it a little big ,it will reboot when the phone wake up. 
hope this can help you solve some problem
https://github.com/Onionfish2/BootIMGExtractAction/releases/download/log/logcat.txt

**Comment by vvb2060** [comment]
AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: cannot find "libandroid.so" from verneed[0] in DT_NEEDED list for "/apex/com.android.tethering/lib64/libframework-connectivity-tiramisu-jni.so"

**Comment by Onionfish2** [comment]
emm, how about modules.log and verbose.log ,they all be fine? actully the logcat one is lmaodroid os , but now i am on void ui.I thought they were the same bug.... i find void(using now ) system/lib/ does exist "libandroid.so'  .so is there a possible another problem? thank you
![4GLH)}9(DTHR1E)7}~ Y35C_tmb](https://github.com/LSPosed/LSPosed/assets/123535045/87fad9fe-4dc3-4246-8a17-872004d7f329)
