### ISSUE TITLE
[Bug] Starbuck China app crash with LSPosed

### ISSUE THREAD

**Issue by MaverickYing** [LSPosed/LSPosed#2702]
### Steps to reproduce/复现步骤

1. Install Zygisk-LSPosed module in Magisk/KernelSU
2. Install Starbuck China APP (≥9.4.0)
3. Open Starbuck China APP then crash
4. Turn-OFF the Zygisk module in Magisk/KernelSU
5. Restart the phone
6. Starbucks work normally

### Expected behaviour/预期行为

buy a coffee

### Actual behaviour/实际行为

crash/quit unexpectedly

### Xposed Module List/Xposed 模块列表

```shell
Hide my Applist
哔哩漫游
```

### Magisk Module List/Magisk 模块列表

```shell
NOTOCJK
Zygisk on KernelSU
Zygisk - Enchance mode for Stroage Isolation
Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

1.8.6(6712)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

KernelSU 10057

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[bugreport-OnePlus8T-RKQ1.211119.001-2023-08-21-20-24-22.zip](https://github.com/LSPosed/LSPosed/files/12395950/bugreport-OnePlus8T-RKQ1.211119.001-2023-08-21-20-24-22.zip)

**Comment by yujincheng08** [comment]
![Screenshot_2023-08-21-21-03-58-162_com.miui.home-edit.jpg](https://github.com/LSPosed/LSPosed/assets/5022927/d4656f36-a6c6-4a6c-af86-53cedaaa51f5)

**Comment by Howard20181** [comment]
@liufeias 确认不是反模拟器？

**Comment by liufeias** [comment]
> @liufeias 确认不是反模拟器？

应该是梆梆加固执行什么骚操作和lsp冲突导致的问题,我在安卓8.1真机测试也闪退
