### ISSUE TITLE
[Feature Request] Application icon in the launcher

### ISSUE THREAD

**Issue by GREAT-DNG** [LSPosed/LSPosed#2709]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

My feature request is not in error

### Describe the solution you'd like/描述你想要的解决方案

It would be nice to have an icon in the application menu, and not on the main screen, as implemented now.  This would be much more convenient when the user does not want to see a notification and still keep the main screen clean.

**Comment by yujincheng08** [comment]
install /data/adb/lspd/manager.apk

**Comment by GREAT-DNG** [comment]
> install /data/adb/lspd/manager.apk

Installation fails with error: Failed to process package

**Comment by Howard20181** [comment]
@GREAT-DNG Copy apk to /sdcard/download first

**Comment by GREAT-DNG** [comment]
> @GREAT-DNG Copy apk to /sdcard/download first

Thanks, this helped
