### ISSUE TITLE
[Feature Request] Make it possible to disable status notification when the manager.apk is installed

### ISSUE THREAD

**Issue by mio-19** [LSPosed/LSPosed#2722]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

I am running LSPosed on WSA and want to disable status notification.

### Describe the solution you'd like/描述你想要的解决方案

Make it possible to disable status notification when /data/adb/lspd/manager.apk is installed

**Comment by Howard20181** [comment]
#2667
