### ISSUE TITLE
[Bug] 无法寄生管理器

### ISSUE THREAD

**Issue by wxt1221** [LSPosed/LSPosed#2724]
### Steps to reproduce/复现步骤

1. 打开寄生管理器
2. 点击确定
3. 回到桌面

### Expected behaviour/预期行为

打开寄生管理器

### Actual behaviour/实际行为

未打开

### Xposed Module List/Xposed 模块列表

```shell
不重要
```

### Magisk Module List/Magisk 模块列表

```shell
不重要
```

### LSPosed version/LSPosed 版本

1.9.0

### Android version/Android 版本

13

### Magisk version/Magisk 版本

KernelSU

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

打不开管理器啊啊啊

**Comment by vvvvvvvalong** [comment]
我也遇到了，1.9.1版本magisk Delta最新版，A13pep
