### ISSUE TITLE
LSPosed module causes the small window fillet of MIUI system to turn into a right angle.[Bug] 

### ISSUE THREAD

**Issue by xiaomengxinyo** [LSPosed/LSPosed#2742]
### Steps to reproduce/复现步骤

小米13刷入官方最新稳定版系统 MIUI14.0.31.0
通过官网下载并刷入alpha面具最新版
通过Github LSPosed发布页下载最新版并刷入重启
小窗圆角正常
启用Cemiuiler模块并勾选对应作用域后重启(未启用任何修改 未授权root)
小窗圆角变直角
关闭模块并清除数据卸载后重启
小窗圆角未恢复
禁用并移除Magisk中的LSPosed模块后重启
小窗圆角恢复正常
重新刷入LSPosed后重启且未启用任何LSPosed模块
小窗圆角变直角
重新在第三方rec刷入完整ROM后刷入面具及LSPosed
小窗依旧是直角
从LSPosed 1.8.4-1.9.1都试过 始终无法让小窗变正常

### Expected behaviour/预期行为

![0d636bc689746f5f4031b3fe96e70c6e](https://github.com/LSPosed/LSPosed/assets/48215946/e792ffc7-907d-4678-8c2b-76a698094b70)
正常的圆角是这样的

### Actual behaviour/实际行为

![Screenshot_2023-09-06-21-11-05-121_m nfa fztk](https://github.com/LSPosed/LSPosed/assets/48215946/d5c7b005-f128-430f-8a40-7f25075caab3)
刷了lsp模块后变成直角，关闭所有xp模块也是如此，关闭Magisk中的lsp就变正常了

### Xposed Module List/Xposed 模块列表

```shell
杜比大喇叭α
墨-状态栏歌词
隐藏应用列表
Cemiuiler
Lyric Getter
```

### Magisk Module List/Magisk 模块列表

```shell
Shamiko
Zygisk-LSPosed
爱玩机工具箱(应用核心功能拓展)
音量键极速救砖
```

### LSPosed version/LSPosed 版本

v1.9.1(6990)

### Android version/Android 版本

Android13

### Magisk version/Magisk 版本

ae9d270a-alpha (26201)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-09-06T21_11_19.160081.zip](https://github.com/LSPosed/LSPosed/files/12539132/LSPosed_2023-09-06T21_11_19.160081.zip)

**Comment by yujincheng08** [comment]
跟我们没关系。

**Comment by xiaomengxinyo** [comment]
> 跟我们没关系。

可以请问一下这个情况除了恢复出厂有什么办法恢复正常吗？
