### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kali-allen** [LSPosed/LSPosed#2749]
### Steps to reproduce/复现步骤

最新LSPosed master分支编译报错，编译命令./gradlew zipZygiskRelease
https://dl.google.com/dl/android/maven2/io/github/libxposed/interface/100/interface-100.pom 该链接打开报404

### Expected behaviour/预期行为

 N/A

### Actual behaviour/实际行为

 N/A

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

 N/A

### Android version/Android 版本

 N/A

### Magisk version/Magisk 版本

 N/A

### Riru version/Riru 版本

 N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

* What went wrong:
Execution failed for task ':daemon:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':daemon:releaseRuntimeClasspath'.
   > Could not find io.github.libxposed:interface:100.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/github/libxposed/interface/100/interface-100.pom
       - https://repo.maven.apache.org/maven2/io/github/libxposed/interface/100/interface-100.pom
       - file:/Users/qi.yan/.m2/repository/io/github/libxposed/interface/100/interface-100.pom
     Required by:
         project :daemon

**Comment by yujincheng08** [comment]
github action 都能编译

**Comment by Eeyhan** [comment]
遇到同样的问题，找半天没找到解决办法

**Comment by torrentshare** [comment]
> 遇到同样的问题，找半天没找到解决办法

解决了吗？我看到这篇，还是不知道怎么弄
https://github.com/orgs/LSPosed/discussions/2444

**Comment by torrentshare** [comment]
楼主解决了吗？
