### ISSUE TITLE
目前所有已安装模块都无法使用

### ISSUE THREAD

**Issue by luohaike** [LSPosed/LSPosed#2750]
### Steps to reproduce/复现步骤

设备:onepplus acepro
在仓库安装了六个模块，能启用,进入模块设置也显示已激活。但是都无实际效果。

### Expected behaviour/预期行为

模块能有实际效果

### Actual behaviour/实际行为

已安装模块均无实际效果，其中微X模块和QX模块无法进入模块设置,并且QX模块显示Xposed框架未安装。
![Cache_-29797ad9c3bf368b](https://github.com/LSPosed/LSPosed/assets/140830948/67fba5eb-4880-4eed-90c7-8fc13b966c4f)

### Xposed Module List/Xposed 模块列表

```shell
1.微X模块
2.应用伪装
3.这个世界太乱了
4.LukyTool
5.QX模块
6.WaterMark
```

### Magisk Module List/Magisk 模块列表

```shell
Systemless Hosts
Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

6990

### Android version/Android 版本

12

### Magisk version/Magisk 版本

26.1-delta(26100)

### Riru version/Riru 版本

zygisk

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-09-11T10_18_27.091.zip](https://github.com/LSPosed/LSPosed/files/12571635/LSPosed_2023-09-11T10_18_27.091.zip)

**Comment by yujincheng08** [comment]
日志显示所有模块均已加载

**Comment by luohaike** [comment]
@yujincheng08 是能加载，但是无实际效果。NO Compatibility callbacks set! Querying change 160794467 (日志中的一段）说没有兼容性回调集。我去了Android Developers查询，得到的结果是:对于以 Android 12（API 级别 31）及更高版本为目标平台的应用，您必须指定应用创建的每个 PendingIntent 对象的可变性。这项额外的要求可提高应用的安全性。我不知道是否跟这个有关

**Comment by luohaike** [comment]
NO Compatibility callbacks set! Querying change 160794467

**Comment by yujincheng08** [comment]
加载模块之后只能说模块的问题，跟框架无关。

**Comment by luohaike** [comment]
我现在所有模块无法使用，有解决方法吗？

**Comment by yujincheng08** [comment]
让模块修。

**Comment by nasheep** [comment]
最新版1.9.1似乎的确存在问题，如果是升级后模块失效，可以找到/data/apex/active这个目录，把文件夹里面的文件删除掉重新安装框架并重启

**Comment by nasheep** [comment]
> 让模块修。

所有的模块都失效显然不是模块的问题
