### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by kali-allen** [LSPosed/LSPosed#2751]
### Steps to reproduce/复现步骤

LSPosed source code：commit id is  b2ab117380ce4d6a35d56b0285999b659dcb067d  compilation error
Compilation command： ./gradlew generateAPI
Compiler Environment：jdk 20 + Android Studio Hedgehog | 2023.1.1 Beta 3

### Expected behaviour/预期行为

 N/A

### Actual behaviour/实际行为

 N/A

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
N/A
```

### LSPosed version/LSPosed 版本

 N/A

### Android version/Android 版本

 N/A

### Magisk version/Magisk 版本

 N/A

### Riru version/Riru 版本

 N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':daemon:checkReleaseDuplicateClasses'.
> Could not resolve all files for configuration ':daemon:releaseRuntimeClasspath'.
   > Could not find io.github.libxposed:interface:100.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/github/libxposed/interface/100/interface-100.pom
       - https://repo.maven.apache.org/maven2/io/github/libxposed/interface/100/interface-100.pom
       - file:/Users/kali/.m2/repository/io/github/libxposed/interface/100/interface-100.pom
     Required by:
         project :daemon

**Comment by yujincheng08** [comment]
All actions pass: https://github.com/LSPosed/LSPosed/actions

**Comment by torrentshare** [comment]
解决了吗？我看到这篇，还是不知道怎么弄
https://github.com/orgs/LSPosed/discussions/2444

**Comment by kali-allen** [comment]
根据这个帖子操作就可以了：https://github.com/orgs/LSPosed/discussions/2444

git clone --depth 1 https://github.com/libxposed/api.git libxposed/api
git clone --depth 1 https://github.com/libxposed/service.git libxposed/service

cd libxposed/api
./gradlew :api:publishApiPublicationToMavenLocal
cd ../service
./gradlew :interface:publishInterfacePublicationToMavenLocal

**Comment by kali-allen** [comment]
根据这个帖子操作就可以了：https://github.com/orgs/LSPosed/discussions/2444

git clone --depth 1 https://github.com/libxposed/api.git libxposed/api
git clone --depth 1 https://github.com/libxposed/service.git libxposed/service

cd libxposed/api
./gradlew :api:publishApiPublicationToMavenLocal
cd ../service
./gradlew :interface:publishInterfacePublicationToMavenLocal
