### ISSUE TITLE
[Bug]It seems that there is a new detection method, I don’t know if it is considered a bug.

### ISSUE THREAD

**Issue by HyperLYP** [LSPosed/LSPosed#2756]
### Steps to reproduce/复现步骤

安装名为“圣境之塔”的游戏

### Expected behaviour/预期行为

不会将此应用认定为lsposed模块

### Actual behaviour/实际行为

被认定为lsposed模块，如图所示
![Screenshot_2023-09-14-12-13-59-056-edit_com android shell](https://github.com/LSPosed/LSPosed/assets/63620765/d7df02a3-e611-4b91-92cb-6e8c76a200de)

### Xposed Module List/Xposed 模块列表

```shell
Guise
QA
```

### Magisk Module List/Magisk 模块列表

```shell
zygisk lsposed
shamiko
```

### LSPosed version/LSPosed 版本

6990

### Android version/Android 版本

12

### Magisk version/Magisk 版本

26.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-09-14T12_23_36.195.zip](https://github.com/LSPosed/LSPosed/files/12604751/LSPosed_2023-09-14T12_23_36.195.zip)

**Comment by vvb2060** [comment]
预期行为

**Comment by Howard20181** [comment]
@HyperLYP 游戏自己声明自己是一个 Xposed 模块

**Comment by HyperLYP** [comment]
> @HyperLYP 游戏自己声明自己是一个 Xposed 模块

啊这，没注意看，，，这可太奇葩了
