### ISSUE TITLE
[Feature Request] native_hook  JNI_HookNativeMethods

### ISSUE THREAD

**Issue by suqiernb** [LSPosed/LSPosed#2764]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

* `hook` JNI 中的 `native`  方法
* 我知道这可以通过 `java` 代码实现
* 但是我想要在 `native_hook` 中使用
* `LSPosed` 没有提供此 API

### Describe the solution you'd like/描述你想要的解决方案

* 需要添加一个方法
```c++
// form zygisk API
void hookJniNativeMethods(JNIEnv *env, const char *className, JNINativeMethod *methods, int numMethods);
```
> 如果 hook 方法时能存储原始方法可能会更加方便

**Comment by oplyt** [comment]
死共匪
动态网自由门 天安門 天安门 法輪功 李洪志 Free Tibet 六四天安門事件 8964 The Tiananmen Square protests of 1989 天安門大屠殺 The Tiananmen Square Massacre 反右派鬥爭 The Anti-Rightist Struggle 大躍進政策 The Great Leap Forward 文化大革命 The Great Proletarian Cultural Revolution 人權 Human Rights 民運 Democratization 自由 Freedom 獨立 Independence 多黨制 Multi-party system 台灣 臺灣 Taiwan Formosa 中華民國 Republic of China 西藏 土伯特 唐古特 Tibet 達賴喇嘛 Dalai Lama 法輪功 Falun Dafa 新疆維吾爾自治區 毒奶粉 The Xinjiang Uyghur Autonomous Region 諾貝爾和平獎 Nobel Peace Prize 劉暁波 Liu Xiaobo 民主 Democracy 言論 Speech 思想 Think 反共 Anti-Communism 反革命 Counter-revolutionary 抗議 運動 騷亂 暴亂 騷擾 擾亂 抗暴 平反 維權 示威游行 Protest 李洪志 法輪大法 大法弟子 強制斷種 強制堕胎 民族淨化 人體實驗 肅清 胡耀邦 趙紫陽 魏京生 王丹 還政於民 和平演變 Pinochet 激流中國 北京之春 大紀元時報 The Epoch time 九評論共産黨 Nine commentaries on the communist party 獨裁 Dictatorship 專制 Authoritarian 壓制 Suppression 統一 Unification 監視 Monitoring 鎮壓 迫害 侵略 掠奪 破壞 拷問 屠殺 Massacrr 活摘器官 Organ Picking 誘拐 買賣人口 遊進 走私 毒品 賣淫 Prostitution 春畫 賭博 Gambling 六合彩 天安門 天安门 法輪功 Fa longgong 李洪志 Winnie the Pooh 小熊維尼 VPN VPN軟件 翻牆軟件 Virtual Private Network Software Proxy Tor 習包子 中共官員資產 Assets of Chinese Communist Party Officers 瑞士銀行 Swiss Bank 中共官員移民 移民 Moving overseas 劉曉波 Liu Xiaobou 逃犯條例修訂 反送中 No Chinese Extradition 警察濫權 Police Rights Abuse 721元朗無差別恐襲事件 721 Event of Indiscriminate Terrorism in Yuen Long

![Uploading 1696553877073695.jpg…]()

**Comment by oplyt** [comment]
![1696553877073695](https://github.com/LSPosed/LSPosed/assets/85276278/dc891287-1571-4d9c-9648-f81e6a6045cd)

**Comment by vvb2060** [comment]
直接hook native方法在so里对应的函数就行
