### ISSUE TITLE
[Feature Request] Oreo 8.0 Support at users' own risk

### ISSUE THREAD

**Issue by cjdw94** [LSPosed/LSPosed#2765]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

LSPosed originally intended to support Oreo 8.0, but dropped support because it was "too buggy".  As of today, only Oreo 8.1 and above are capable of installing LSPosed.

### Describe the solution you'd like/描述你想要的解决方案

I have an LG V20 that I enjoy still very much.  I have unlocked the bootloader and rooted the phone, and I am currently running a custom stock Oreo 8.0 ROM.  Unfortunately, there is no such thing as a stock Oreo 8.1 ROM for this device.  

I would like to pass SafetyNet Basic Integrity and CTS profile match, while maintaining some kind of Xposed framework/manager.  Unfortunately, system-less Xposed on Oreo 8.0 will always fail SafetyNet.  I think the best I ever managed was passing Basic Integrity, but failing CTS profile match.

### Additional context/其他信息

Is it possible that there may just be a header or flag that can be changed to allow installation on Oreo 8.0?  It doesn't have to be advertised, and even if so, it could be stressed that it is under the user's own risk.  Please consider.   Thanks for your time.

**Comment by Howard20181** [comment]
Since it's been a long time since 8.0 support was dropped, most of the code is not compatible now, and it would take a lot of effort to re-adapt it, so it won't be considered to be added back.

**Comment by vvb2060** [comment]
We are open source, and I understand it at user's own risk as you should modify the source code yourself.

**Comment by cjdw94** [comment]
That's fair - I'm not very familiar programming for Android, and I thought it wouldn't hurt to ask.  I appreciate you both responding so promptly.

**Comment by cjdw94** [comment]
> Since it's been a long time since 8.0 support was dropped, most of the code is not compatible now, and it would take a lot of effort to re-adapt it, so it won't be considered to be added back.

Completely understandable.  Thank you for explaining it for me.
