### ISSUE TITLE
SEPolicy not loaded properly.

### ISSUE THREAD

**Issue by abdulhkeemGit** [LSPosed/LSPosed#2772]
### Steps to reproduce/复现步骤

Just install layest google system update from settings.
This is on S23 ultra latest software WHR build.
I had this once restart fixed it last time but not this time sadly.

### Expected behaviour/预期行为

No error.

### Actual behaviour/实际行为

Getting error:
SEPolicy not loaded properly.

### Xposed Module List/Xposed 模块列表

```shell
Lucky patcher "random letters and numbers"
Force dark
Youtube ad away
Knox Patch
```

### Magisk Module List/Magisk 模块列表

```shell
Knox patch enhancer
Shamiko
System apps (lucky patcher module)
Systemless hists
Universal SafetyNet fix
Zygisk
```

### LSPosed version/LSPosed 版本

1.9.1 (6990)

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26301

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [ ] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

#
[LSPosed_2023-09-30T14_14_45.990407.zip](https://github.com/LSPosed/LSPosed/files/12774416/LSPosed_2023-09-30T14_14_45.990407.zip)

**Comment by yujincheng08** [comment]
report to magisk
