### ISSUE TITLE
No LSPosed module works even though they are all active

### ISSUE THREAD

**Issue by gab12** [LSPosed/LSPosed#2773]
### Steps to reproduce/复现步骤

Running out of battery power until your phone switches itself off... recharging it and switching it on.

### Expected behaviour/预期行为

Magisk and LSPosed work as before.

### Actual behaviour/实际行为

Magisk was still running and indicated that root was active.
All root applications were working correctly.
Zygisk, ramdisk and magisk modules remained active and did not seem to have moved.

In LSPOsed, LSPOsed indicated that it was active.
All LSPOsed modules were still active.
But none of them applied their modification

- When I open Firefds kit, it says it's active, but the options are still enabled, but no changes are applied.
- When I open Hide my appList, it says it's working, but no changes are applied.
- When I open Xprivacy, it tells me that the module is not running.

Basically, no module can apply their modification and I have the impression that only Xprivacy can detect that there is a typo.

I've tried several things with no improvement:
- Disabled LSPOSED modules, restart. Reactivate modules, restart
- I removed LSPOSED modules in magisk, rebooted and reinstalled (reboot).
- I deactivated Zyb, rebooted, reactivated and rebooted.
- I updated version 1.8.5 to 1.9.1.

all these actions had no improvement. No LSPOsed Module can apply their modification

![Screenshot_20231001_233647_LSPosed](https://github.com/LSPosed/LSPosed/assets/6320898/977c264c-7b9e-46b8-9bfb-e1e78bf516bf)
![Screenshot_20231001_233701_Firefds Kit  Tiramisu](https://github.com/LSPosed/LSPosed/assets/6320898/a7c8b32e-4d66-4968-b36d-34e8a3f8e45f)

### Xposed Module List/Xposed 模块列表

```shell
XPrivacy
Firefds kit (Titanium)
Hide my appList
```

### Magisk Module List/Magisk 模块列表

```shell
zygisk - lsposed
universal safetynet fix
systemless hosts
aurora services
adguard certificate
```

### LSPosed version/LSPosed 版本

1.8.5 and 1.9.1

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.3

### Riru version/Riru 版本

Zygisk 

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-10-01T21_47_07.302536.zip](https://github.com/LSPosed/LSPosed/files/12778217/LSPosed_2023-10-01T21_47_07.302536.zip)

**Comment by Howard20181** [comment]
Not official build

**Comment by gab12** [comment]
Hello,

Sorry @Howard20181  as indicated I tested several versions before contacting you. I got mixed up with the logs. I am attaching the correct log outputs from the latest official version. Would it be possible to reopen the bug if it is accepted? 

![Screenshot_20231002_092306_LSPosed](https://github.com/LSPosed/LSPosed/assets/6320898/c013b582-a0ba-4011-8fa6-a5e92df5c4d4)
[LSPosed_2023-10-02T09_25_45.680840.zip](https://github.com/LSPosed/LSPosed/files/12780476/LSPosed_2023-10-02T09_25_45.680840.zip)
[LSPosed_2023-10-02T09_25_51.128714.zip](https://github.com/LSPosed/LSPosed/files/12780477/LSPosed_2023-10-02T09_25_51.128714.zip)

**Comment by gab12** [comment]
I've identified a similar reported bug on the EdXposed project with an identical log extract.
https://github.com/ElderDrivers/EdXposed/issues/779

So I deleted /data/adb/modules/zygisk_lsposed/sepolicy.rule
as indicated. But there was no improvement :(

**Comment by Howard20181** [comment]
@gab12 Not the latest debug build
Due to database updates, downgrading will result in data corruption, please uninstall LSPosed completely and reinstall.

Deleting sepolicy will cause all system stop working
