### ISSUE TITLE
No LSPosed module works even though they are all active

### ISSUE THREAD

**Issue by gab12** [LSPosed/LSPosed#2775]
### Steps to reproduce/复现步骤

Running out of battery power until your phone switches itself off... recharging it and switching it on.
(perhaps a normal reboot would have caused the same problem - I was unable to reproduce the problem as I was still stuck).

Note: the previous ticket was locked (#2773). I recreated it here with the debug version (after deleting the old version)

### Expected behaviour/预期行为

Magisk and LSPosed work as before.

### Actual behaviour/实际行为

Magisk was still running and indicated that root was active.
All root applications were working correctly.
Zygisk, ramdisk and magisk modules remained active and did not seem to have moved.

In LSPOsed, LSPOsed indicated that it was active.
All LSPOsed modules were still active.
But none of them applied their modification

    When I open Firefds kit, it says it's active, but the options are still enabled, but no changes are applied.
    When I open Hide my appList, it says it's working, but no changes are applied.
    When I open Xprivacy, it tells me that the module is not running.

Basically, no module can apply their modification and I have the impression that only Xprivacy can detect that there is a typo.

I've tried several things with no improvement:

    Disabled LSPOSED modules, restart. Reactivate modules, restart
    I removed LSPOSED modules in magisk, rebooted and reinstalled (reboot).
    I deactivated Zyb, rebooted, reactivated and rebooted.
    I updated version 1.8.5 to 1.9.1.

all these actions had no improvement. No LSPOsed Module can apply their modification

### Xposed Module List/Xposed 模块列表

```shell
XPrivacy
Firefds kit (Titanium)
Hide my appList
```

### Magisk Module List/Magisk 模块列表

```shell
zygisk - lsposed
universal safetynet fix
systemless hosts
aurora services
adguard certificate
```

### LSPosed version/LSPosed 版本

1.9.1 debug version

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.3

### Riru version/Riru 版本

Zygisk 

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-10-02T14_32_58.246503.zip](https://github.com/LSPosed/LSPosed/files/12782643/LSPosed_2023-10-02T14_32_58.246503.zip)
[LSPosed_2023-10-02T14_33_09.820283.zip](https://github.com/LSPosed/LSPosed/files/12782646/LSPosed_2023-10-02T14_33_09.820283.zip)

**Comment by yujincheng08** [comment]
From log, all looks good. Report to modules' dev instead.

**Comment by amakuramio** [comment]
Try to delete /root/data/apex/active, reinstall lsposed, then after ''optimizing'' all will work. It worked for me. Thanks to Nasheep.

**Comment by gab12** [comment]
Incredible! Thank you so much @amakuramio. It worked! I was just about to format my phone in despair. Thank you so much. Everything is back to normal.

**Comment by elvisisvan** [comment]
> Try to delete /root/data/apex/active, reinstall lsposed, then after ''optimizing'' all will work. It worked for me. Thanks to Nasheep.

my device is a samsung foldable phone running android 12 and i have had to use this solution many times even for normal reboot, why does this work? how did you know? is there a more elegant solution for this?

**Comment by elvisisvan** [comment]
> Try to delete /root/data/apex/active, reinstall lsposed, then after ''optimizing'' all will work. It worked for me. Thanks to Nasheep.

thank you i have had to use this solution many times even for normal reboot, why does this work? how did you know? is there a more elegant solution for this issue?
