### ISSUE TITLE
模块更新推荐作用域时给出提示

### ISSUE THREAD

**Issue by SkipM4** [LSPosed/LSPosed#2777]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

一些修改定制UI组件的模块更新后需要hook新的app或旧的app不再需要hook
而LSPosed作用域没有更改
模块运行出错时用户一般不会考虑到是作用域有更改的问题，看到模块已启用就认为配置无误

### Describe the solution you'd like/描述你想要的解决方案

在模块更新后作用域发生变更时提示用户或在模块信息下写出

### Additional context/其他信息

![Screenshot_2023-10-03-15-05-34-669_com android shell](https://github.com/LSPosed/LSPosed/assets/40311581/2090f983-ebe7-46e2-af8a-6a7c58640e4d)

**Comment by vvb2060** [comment]
已经在新API解决
