### ISSUE TITLE
希望在模块设置中添加全选反选等快捷功能

### ISSUE THREAD

**Issue by cuijianzhuang** [LSPosed/LSPosed#28]
希望在模块设置中添加全选反选等快捷功能，方便选择应用
![Screenshot_2021-01-31-23-42-58-285_io github lsposed manager](https://user-images.githubusercontent.com/31424401/106389443-4e46ee80-641e-11eb-92f7-890a80f187ba.jpg)

**Comment by yujincheng08** [comment]
什么时候 magisk hide 支持全选再说

**Comment by cuijianzhuang** [comment]
这回复够快啊
