### ISSUE TITLE
Xposed hooking every TextView in my device

### ISSUE THREAD

**Issue by davidlip123** [LSPosed/LSPosed#2813]
### Steps to reproduce/复现步骤

I'm hooking the android framework itself,not a specific app,this is my code:

```
public void handleLoadPackage(XC_LoadPackage.LoadPackageParam lpparam) throws Throwable {
        
        if (lpparam == null||lpparam.packageName == null || lpparam.processName == null)
            return;

        if (lpparam.packageName.equals("android")) {
            XposedBridge.log("Hooked into Android framework.");


            if (!sInitialized) {
                sInitialized = true;
                hookSetVisibility(lpparam);
            }
        }
    }


    private void hookSetVisibility(XC_LoadPackage.LoadPackageParam lpparam) {

        final Class<?> mViewGroup = XposedHelpers.findClass("android.widget.TextView", lpparam.classLoader);
        for (final Method method : mViewGroup.getDeclaredMethods()) {
            if (true == Modifier.isAbstract(method.getModifiers())) {
                XposedBridge.log("skip abstract:" + method.getName());
                continue;
            }
            XposedBridge.log("----" + method.getName());
            XposedBridge.hookMethod(method, methodHook);
        }
    }

    final StringBuilder sb = new StringBuilder();
    XC_MethodHook methodHook = new XC_MethodHook() {
        @Override
        protected void beforeHookedMethod(XC_MethodHook.MethodHookParam param) throws Throwable {

            XposedBridge.log("before hook log");
        }

        @Override
        protected void afterHookedMethod(XC_MethodHook.MethodHookParam param) throws Throwable {
            //param.setResult(false);
            XposedBridge.log("after hook log");       
        }
    };
```

### Expected behaviour/预期行为

to trigger the before hook for any method!!(I don't really need to hook any method in the TextView class..,this is just a test ...but still...

### Actual behaviour/实际行为

nothing triggered.
The module indeed prints nicely the all class method names as can seen in the [android framework](https://android.googlesource.com/platform/frameworks/base/+/jb-mr0-release/core/java/android/widget/TextView.java),but the BeforeHookedMethod and the afterHookMethod never get called......

### Xposed Module List/Xposed 模块列表

```shell
only current module
```

### Magisk Module List/Magisk 模块列表

```shell
only lsposed(zygisk)
```

### LSPosed version/LSPosed 版本

1.9.2-7024

### Android version/Android 版本

11

### Magisk version/Magisk 版本

26.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[lsposed.zip](https://github.com/LSPosed/LSPosed/files/12891247/lsposed.zip)

**Comment by yujincheng08** [comment]
Learn how Android works first.
