### ISSUE TITLE
Automatic update repository and notification new modules to update

### ISSUE THREAD

**Issue by yashikada** [LSPosed/LSPosed#2815]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

Every day I have to check if there are updates available for the modules I have installed

### Describe the solution you'd like/描述你想要的解决方案

I would like to automate this check and receive a notification when there are new updates available, tap on the notification, open the app on the repository and decide whether to update or not
I don't want automatic update of apps, only automatic update of repository and check for new updates.

**Comment by vvb2060** [comment]
This is not possible because we can't register scheduled tasks.

**Comment by yashikada** [comment]
Not even from the daemon, I saw that you record intents like BOOT_COMPLETED. 
Couldn't you register an intent with AlarmManager and tell the app to update repositoty?
