### ISSUE TITLE
Lsposed doesn't starting 

### ISSUE THREAD

**Issue by Albert753258** [LSPosed/LSPosed#2817]
### Steps to reproduce/复现步骤

Install latest zygisk lsposed

### Expected behaviour/预期行为

Working lsposed 

### Actual behaviour/实际行为

Hello! Yesterday I tried installing zygisk lsposed to my phone. Installation completed without errors and after I rebooted my phone lsposed notification appeared. But after I click on it some error message appeares
![Screenshot_20231017-093631_Shell](https://github.com/LSPosed/LSPosed/assets/56261876/3642082a-2550-49b3-a7c3-ebe0aff15bce)

### Xposed Module List/Xposed 模块列表

```shell
No
```

### Magisk Module List/Magisk 模块列表

```shell
J-hc yt music revanced
J-hc YouTube revanced
Lucky patcher patches to android
RSSP(removes stock audio processing to make viper4android working)
Selinux permissive (also for viper4android)
Viper4androidFX repackagedhich77
Shamico
Systemless hosts
Universal safetynet fix
Wireless firmware for nethunter
```

### LSPosed version/LSPosed 版本

1.9.2, 1.9.1

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

Screenshot:  
[0.zip](https://github.com/LSPosed/LSPosed/files/12925138/0.zip)

**Comment by Howard20181** [comment]
No logs

**Comment by Albert753258** [comment]
[tombstone.zip](https://github.com/LSPosed/LSPosed/files/12925173/tombstone.zip)

**Comment by Albert753258** [comment]
Please check screenshot with error and tombstone 
![Screenshot_20231016-103300_CatLog](https://github.com/LSPosed/LSPosed/assets/56261876/8af03539-5d8c-43d7-865b-52b3b70b6d08)

**Comment by Albert753258** [comment]
I installed CI build but got absolutely same behavior. Attached correct bug report 
[bugreport-lineage_munch-TQ3A.230805.001-2023-10-17-09-58-55.zip](https://github.com/LSPosed/LSPosed/files/12925310/bugreport-lineage_munch-TQ3A.230805.001-2023-10-17-09-58-55.zip)

**Comment by vvb2060** [comment]
We do not support your rom. Please back to stock rom or wait for the art apex module to be officially pushed.

**Comment by Albert753258** [comment]
Could you please say what is art apex module?

**Comment by Albert753258** [comment]
Did you meant this https://android.googlesource.com/platform//art/+/efc03b831c35062f51589adc0ec509d4bfa2ef33/build/README.md?

**Comment by aviraxp** [comment]
Provide your rom source.

**Comment by Albert753258** [comment]
Rom developer said what problem was in com.android.art compliled with -Ofast
 https://github.com/KuroNekoDroid/android

**Comment by yujincheng08** [comment]
yup we knew this. just wait when we hv bandwidth for it. we may wait untill it pushes to official pixel roms.
