### ISSUE TITLE
App seems able to detect Lsposed is enabled or not

### ISSUE THREAD

**Issue by diedbug2002** [LSPosed/LSPosed#2821]
### Steps to reproduce/复现步骤

1. 安装应用：https://play.google.com/store/apps/details?id=com.sinopac.dawho&hl=zh_TW&gl=US
2. 不启用Lsposed
3. 应用正常启动
4. 启用Lspoesd
5. 应用崩溃

### Expected behaviour/预期行为

应用正常启动

### Actual behaviour/实际行为

应用崩溃，似乎可侦测到Lsposed载入，也在以下环境复现
Android 12
KernelSU v0.6.6-11194
Zygisk on KernelSU v4-0.7.1-89
Shamiko v0.7.3-174

### Xposed Module List/Xposed 模块列表

```shell
无安装任何Xposed模块
```

### Magisk Module List/Magisk 模块列表

```shell
Shamiko 0.7.3(184)
LSPosed-v1.9.2-7029-zygisk-debug
```

### LSPosed version/LSPosed 版本

LSPosed-v1.9.2-7029-zygisk-debug

### Android version/Android 版本

Android 10

### Magisk version/Magisk 版本

Magisk alpha：15e13a8d-alpha 26302

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-10-19T18_40_12.675.zip](https://github.com/LSPosed/LSPosed/files/13041509/LSPosed_2023-10-19T18_40_12.675.zip)

**Comment by diedbug2002** [comment]
是Magsik

Magisk alpha：15e13a8d-alpha 26302

**Comment by yujincheng08** [comment]
我這邊沒被偵測到載入。嘗試原版 magisk，或者看看舊版 lsposed 是否有問題。

**Comment by diedbug2002** [comment]
用原版Magisk 26.3测试Lsposed三个版本，只有1.8.6应用正常启动

[1.9.1 LSPosed_2023-10-19T19_36_01.621.zip](https://github.com/LSPosed/LSPosed/files/13042099/1.9.1.LSPosed_2023-10-19T19_36_01.621.zip)

[1.9.2 LSPosed_2023-10-19T19_27_49.791.zip](https://github.com/LSPosed/LSPosed/files/13042101/1.9.2.LSPosed_2023-10-19T19_27_49.791.zip)

[1.8.6 LSPosed_2023-10-19T19_39_50.433.zip](https://github.com/LSPosed/LSPosed/files/13042102/1.8.6.LSPosed_2023-10-19T19_39_50.433.zip)

**Comment by Dr-TSNG** [comment]
![Screenshot_2023-10-23-21-41-17-103_com miui home](https://github.com/LSPosed/LSPosed/assets/52071314/d58cd050-47b0-44bd-9e8a-1a1507ee4fce)

**Comment by diedbug2002** [comment]
非常感謝幫忙測試，我真的是摸不著頭緒了～

**Comment by fsyy** [comment]
I have another app detecting root with shamiko 0.7.4 and Magisk 26.3 (263002)

https://play.google.com/store/apps/details?id=com.entersekt.authapp.sparkasse&amp;hl=de&amp;gl=US
