### ISSUE TITLE
LPosed not work when uninstall and install an apk

### ISSUE THREAD

**Issue by Margular** [LSPosed/LSPosed#2824]
### Steps to reproduce/复现步骤

1. uninstall a target apk
2. install a target apk

### Expected behaviour/预期行为

hook new installed apk

### Actual behaviour/实际行为

LPosed not work for target apk. If you want to make LPosed work correctly, you need to uncheck button on target apk, and restart LPosed, and recheck button on new installed apk

### Xposed Module List/Xposed 模块列表

```shell
custom
```

### Magisk Module List/Magisk 模块列表

```shell
custom
```

### LSPosed version/LSPosed 版本

1.9.2

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.3

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

no logs need

**Comment by yujincheng08** [comment]
expected.
