### ISSUE TITLE
An app with its own LSPosed module won't show on the scope (apps list) of other modules

### ISSUE THREAD

**Issue by intruder777** [LSPosed/LSPosed#2826]
### Steps to reproduce/复现步骤

1. Install 3C All-in-One Toolbox (https://play.google.com/store/apps/details?id=ccc71.at.free)
2. Open LSPosed and navigate to "Modules" section.
3. Tap on any of installed module from the list.
4. Observe that there is no "3C All-in-One Toolbox" app in the module scope list (apps list).

### Expected behaviour/预期行为

The "3C All-in-One Toolbox" app must be on the scope apps list, so user can enable it with a checkbox. Well, not sure if it should be available on its own module scope, but it surely must be available on the other modules scopes.

### Actual behaviour/实际行为

There is no "3C All-in-One Toolbox" app on the apps scope list (no matter which module you choose).

### Xposed Module List/Xposed 模块列表

```shell
1. CustoMIUIzer14
2. XPrivacyLua
3. 3C All-in-One Toolbox
4. LuckyPatcher
```

### Magisk Module List/Magisk 模块列表

```shell
1. 3C Magisk Helper
2. Energized Protection
3. Magisk built-in BusyBox
4. Play Integrity Fix
5. Shamiko
6. Systemless Hosts
7. Zygisk-LSPosed
```

### LSPosed version/LSPosed 版本

1.9.2-7024-zygisk

### Android version/Android 版本

12

### Magisk version/Magisk 版本

26.3 (26300)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-10-22T20_15_35.435147.zip](https://github.com/LSPosed/LSPosed/files/13064038/LSPosed_2023-10-22T20_15_35.435147.zip)

I've cleared the logs from manager interface and then made a device reboot and performed "steps to reproduce". Then saved the logs.

BTW, there was some kind of null reference crash upon manager start (probably not related to current issue), but I haven't captured it and I'm afraid the logs of it were cleared.

**Comment by yujincheng08** [comment]
![Uploading Screenshot_2023-10-23-01-37-35-786_com.android.shell.jpg…]()

**Comment by intruder777** [comment]
So why it's not there on my phone? Actually any app which has its own LSPosed module is not on the scope list.

I've even installed the same io.github.lsposed.disableflagsecure app to test. I've checked: the "3C..." app is not on the list:
![image](https://github.com/LSPosed/LSPosed/assets/1699706/21e9bae2-91ce-4f83-b9e3-2c184bba4082)

**Comment by intruder777** [comment]
Reopen the issue please
