### ISSUE TITLE
[FR] scopes page select all

### ISSUE THREAD

**Issue by green1052** [LSPosed/LSPosed#283]
**Detail**:

like this
https://github.com/LSPosed/LSPosed/issues/138#issuecomment-787131744

**Comment by yujincheng08** [comment]
No module actually needs to be applied to all apps so no.

**Comment by Evengard** [comment]
Actually, there are modules which needs to be applied to all. Mostly old ones, but still. One of which I am using is  ButteredToast Revived - the whole purpose is to display the application which issued a toast - and for that it does need to apply to every app to work (actually, even freshly installed).

**Comment by VD171** [comment]
> Actually, there are modules which needs to be applied to all. Mostly old ones, but still. One of which I am using is ButteredToast Revived - the whole purpose is to display the application which issued a toast - and for that it does need to apply to every app to work (actually, even freshly installed).

LSPosed is built to work with scopes.
So, if LSPosed allows you to apply the scope for all apps, it will lose its purpose. 
I want to apply some modules for all scopes too, so I suggestted a command line interface (CLI): https://github.com/LSPosed/LSPosed/issues/405
It makes more sense, especially comparing with the magiskhide.

**Comment by Evengard** [comment]
The CLI interface while allows to somehow overcome the problem doesn't really solve it. Only power users would be able to use it, and it still feels more like a workaround than an actual solution in the end. You still need to somehow track newly installed applications (which is possible with CLI, but would still be not really practical), and still need to maintain your own script... For something seemingly that easy and widely requested. Definitely not really user-friendly for the use case of global modules.

Now I actually think that making an LSPosed module for the LSPosed manager is another way to tackle this problem... xD

**Comment by vvb2060** [comment]
Any module that requires a full selection is an inferior module, and we have not found a use case so far that requires a full selection.
