### ISSUE TITLE
谷歌pixel5更新安卓14后寄生方法失效

### ISSUE THREAD

**Issue by RainHoutas** [LSPosed/LSPosed#2831]
### Steps to reproduce/复现步骤

pixel5更新安卓14后，且lsp本身运行正常，尝试重新刷入后并未解决

### Expected behaviour/预期行为

点击通知栏的通知或是桌面寄生器原本应该能正常进入管理器

### Actual behaviour/实际行为

实际以上两种方法均失效，只有应用能打开

### Xposed Module List/Xposed 模块列表

```shell
lsposed本身运行均正常
```

### Magisk Module List/Magisk 模块列表

```shell
zygisk版的lsp
循环清垃圾文件
gps pro
monet all
pixel 5通讯增强模块
微信支付宝指纹支付
第三方应用下载目录重定向
```

### LSPosed version/LSPosed 版本

1.9.2(7024)

### Android version/Android 版本

Android 14.  UP1A.231005.007

### Magisk version/Magisk 版本

26.3(26300)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-10-27T18_57_03.819502.zip](https://github.com/LSPosed/LSPosed/files/13188124/LSPosed_2023-10-27T18_57_03.819502.zip)

**Comment by yujincheng08** [comment]
无法复现。日志上只有一个不对劲的地方，先尝试一下 `su -c setenforce 0` 能不能打开，如果可以，再发送日志；如果不清，清空 `com.android.shell` 的数据再尝试。
