### ISSUE TITLE
最新版本，不能hook 一些 app的子进程 比如微信小程序

### ISSUE THREAD

**Issue by pony5551** [LSPosed/LSPosed#2836]
### Steps to reproduce/复现步骤

-

### Expected behaviour/预期行为

-

### Actual behaviour/实际行为

-

### Xposed Module List/Xposed 模块列表

```shell
-
```

### Magisk Module List/Magisk 模块列表

```shell
-
```

### LSPosed version/LSPosed 版本

-

### Android version/Android 版本

android 13

### Magisk version/Magisk 版本

26

### Riru version/Riru 版本

-

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

目前最新版任何机器上都存在这个问题

**Comment by Vstory** [comment]
最新版是什么版
