### ISSUE TITLE
Using Android Studio to connect to the real machine debugging module, observing the logcat, it was found that the package name of the checked APP cannot be obtained in the handleLoadPackage, but some system package names are output.

### ISSUE THREAD

**Issue by af913337456** [LSPosed/LSPosed#2838]
### Steps to reproduce/复现步骤

使用 Android Studio 连接真机调试模块，观察 logcat，发现在 handleLoadPackage 里面无法获取勾选了的 APP 的包名，却输出一些系统的包名。步骤以及机器信息如下：

1. root 真机，OnePlus，安卓 13，ColorOS 13.1；
2. 安装 面具 与 1.9.2 的 lsp；
3. 编写 demo；
4. 运行并观察 logcat

### Expected behaviour/预期行为

能在 logcat 观察到被勾选 app 的包名

### Actual behaviour/实际行为

不能在 logcat 观察到被勾选 app 的包名，却看到了一些系统的。比如：

oplus.R

android.app.Application

### Xposed Module List/Xposed 模块列表

```shell
自编写的 demo 模块，入口代码只有下面的：


public class Main implements IXposedHookLoadPackage {
    
    @Override
    public void handleLoadPackage(XC_LoadPackage.LoadPackageParam lpparam) throws Throwable {
        String packageName = lpparam.packageName;
        XposedBridge.log("----->"+packageName); // 这里无法输出勾选了的 app 的包名。只有系统的
        if (!packageName.equals("com.moetor.qmxy")) {
            return;
        }
        XposedBridge.log("Example module loaded for package: " + packageName); // 无法走到这里
    }
}
```

### Magisk Module List/Magisk 模块列表

```shell
LSPosed 1.9.2
```

### LSPosed version/LSPosed 版本

1.9.2

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.1

### Riru version/Riru 版本

25.4.4

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-11-06T10_57_43.234687.zip](https://github.com/LSPosed/LSPosed/files/13262156/LSPosed_2023-11-06T10_57_43.234687.zip)
[magisk_log_2023-11-06T11.13.18.log](https://github.com/LSPosed/LSPosed/files/13262157/magisk_log_2023-11-06T11.13.18.log)

**Comment by yujincheng08** [comment]
正常

**Comment by af913337456** [comment]
第一份日志是 LSPosed 的。里面能看到系统的包名输出，和我勾选的输出。

第二份是面具的。

但是 logcat 看不到我勾选的输出

**Comment by af913337456** [comment]
> 正常

你好，可以说下我怎样才能在 logcat 看到我勾选的 app 日志输出吗？
