### ISSUE TITLE
小米14pro安卓14鸿鹏OS1.0开发版23.11.13中面具的zygisk模块导致32位应用无法打开。

### ISSUE THREAD

**Issue by a447948814** [LSPosed/LSPosed#2843]
### Steps to reproduce/复现步骤

开启面具zygisk后，32位应用无法打开。根据酷安大家的讨论反馈，是zygisk-lsp v1.9.2（7024）模块导致，貌似原因是zygisk干扰了小米tango转译器的工作，据网友反馈是：根据源码发现zygisk把system/bin/app_process32164的目录放到了zygisk下面，而tango的识别目录是在system/bin/app_process32。
![image](https://github.com/LSPosed/LSPosed/assets/61766946/3eea4778-1475-4fef-bf66-89b40b254a56)

### Expected behaviour/预期行为

可以打开32位应用

### Actual behaviour/实际行为

32位应用卡在启动界面

### Xposed Module List/Xposed 模块列表

```shell
无
```

### Magisk Module List/Magisk 模块列表

```shell
zygisk
shamiko
```

### LSPosed version/LSPosed 版本

1.9.2-7024

### Android version/Android 版本

14

### Magisk version/Magisk 版本

26.4

### Riru version/Riru 版本

无

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

无

**Comment by yujincheng08** [comment]
跟我们没关系

**Comment by a447948814** [comment]
> 跟我们没关系

好的，是面具的问题吗？目前的解决办法是，关闭面具设置里的zyg开关，然后刷ksu的zyg next代替面具的zyg就是好用的。
