### ISSUE TITLE
Lsposed is not installed

### ISSUE THREAD

**Issue by brandonsneiders** [LSPosed/LSPosed#2856]
### Steps to reproduce/复现步骤

Activate zygisk
Install zygisk_lsposed
Reboot

### Expected behaviour/预期行为

Lsposed installed

### Actual behaviour/实际行为

When restarting the manager is not installed nor is lsposed installed

### Xposed Module List/Xposed 模块列表

```shell
N/A
```

### Magisk Module List/Magisk 模块列表

```shell
BusyBox
Call recorder
Google photos unlimited pixel
Magisk bootloop protector
Mm for recovery mode
No storage restrict 
Unity fix
 Wifi bonding
 Xtreme sensitivity
Zygisk_lsposed
```

### LSPosed version/LSPosed 版本

  1.9.2-7041 debug

### Android version/Android 版本

13

### Magisk version/Magisk 版本

26.4

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[liveboot.log](https://github.com/LSPosed/LSPosed/files/13449528/liveboot.log)

**Comment by brandonsneiders** [comment]
This is the log from /data/adb/lspd
[log.zip](https://github.com/LSPosed/LSPosed/files/13449593/log.zip)

**Comment by brandonsneiders** [comment]
How I solve the problem plz

**Comment by yujincheng08** [comment]
buy a phone with larger ram?

**Comment by brandonsneiders** [comment]
> buy a phone with larger ram?
my phone has 3 GB of ram, it is not enough

**Comment by brandonsneiders** [comment]
Or is there a way to modify something to solve that?

**Comment by brandonsneiders** [comment]
If I release startup processes, will it work?

**Comment by brandonsneiders** [comment]
any solution? please

**Comment by vinphan** [comment]
I have the same issue

**Comment by yujincheng08** [comment]
looks like there's nothing to do on our side. try to use lesser xposed modules.
