### ISSUE TITLE
LSposed crash

### ISSUE THREAD

**Issue by vslmc** [LSPosed/LSPosed#2866]
### Steps to reproduce/复现步骤

Magisk Debug aa6c7c15 (26401) (D)
LSposed Debug v1.9.2-7043 zygisk
Xiaomi.eu FUXI OS1.0.23.11.27.DEV

The new HyperOS ROM from xiaomi.eu has some PlayIntegrity fixes that are incompatible with LSposed.
Using stable version of Magisk and LSposed will disable zygisk, using debug builds will crash LSposed. 
Root and su is working as normal

### Expected behaviour/预期行为

Should work like always 

### Actual behaviour/实际行为

Not working

### Xposed Module List/Xposed 模块列表

```shell
Nothing, only LSposed and magisk
```

### Magisk Module List/Magisk 模块列表

```shell
Nothing, only LSposed and magisk
```

### LSPosed version/LSPosed 版本

LSposed Debug v1.9.2-7043 zygisk

### Android version/Android 版本

14 

### Magisk version/Magisk 版本

Magisk Debug aa6c7c15 (26401) (D)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[log.zip](https://github.com/LSPosed/LSPosed/files/13536876/log.zip)

**Comment by Howard20181** [comment]
#2817

**Comment by xiaooloong** [comment]
same issue on xiaomi.eu_multi_ISHTAR_OS1.0.23.11.27.DEV_os1-14.zip
