### ISSUE TITLE
Snapchat randomly crash sometimes

### ISSUE THREAD

**Issue by sn-o-w** [LSPosed/LSPosed#2868]
### Steps to reproduce/复现步骤

To be honest, I'm not sure how to reproduce it. It looks like it happens randomly, always while I'm using Snapchat.

### Expected behaviour/预期行为

Snapchat app to not crash.

### Actual behaviour/实际行为

Snapchat app sometimes randomly crashes.

### Xposed Module List/Xposed 模块列表

```shell
- Disable FLAG_SECURE
- Lucky Patcher
- Pixelify GPhotos
- SnapEnhance
```

### Magisk Module List/Magisk 模块列表

```shell
- SELinux Permissive (DISABLED FOR A VERY LONG TIME)
- TrichromeLibrary Squoosh
- Universal GMS Doze
- YouTube ReVanced
- Zygisk - LSPosed
```

### LSPosed version/LSPosed 版本

1.9.2 (7042)

### Android version/Android 版本

10

### Magisk version/Magisk 版本

26401

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-12-03T05_22_50.964.zip](https://github.com/LSPosed/LSPosed/files/13539215/LSPosed_2023-12-03T05_22_50.964.zip)

**Comment by yujincheng08** [comment]
Cannot see any useful log. Cannot help.

**Comment by yujincheng08** [comment]
i dont think its caused by lsposed.
