### ISSUE TITLE
LSPosed makes Android TV boot process incredibly long (up to 25 minutes!)

### ISSUE THREAD

**Issue by Anderhar** [LSPosed/LSPosed#2870]
### Steps to reproduce/复现步骤

Just activate any LSPosed version on [Walmart onn 4K Box](https://wiki.oddsolutions.us/devices/dopinder/) with a freshly re-installed LineageOS 20 with no modifications except Magisk.

### Expected behaviour/预期行为

With LSPosed disabled, system boots up in about 1 minute.

### Actual behaviour/实际行为

With LSPosed enabled, system boots up in 10-25 minutes.

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
LSPosed only.
```

### LSPosed version/LSPosed 版本

v1.9.2-7042-zygisk-debug (and any other)

### Android version/Android 版本

Android 13 (LineageOS 20)

### Magisk version/Magisk 版本

v26.4

### Riru version/Riru 版本

Zygisk or Riru v26.1.7 (both tested)

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[log.zip](https://github.com/LSPosed/LSPosed/files/13574169/log.zip)
[system-logcats.zip](https://github.com/LSPosed/LSPosed/files/13574204/system-logcats.zip)
(Logs manually exported from /data/adb/lspd due to Android TV GUI limitations.)

**Comment by yujincheng08** [comment]
this is bacause the device does not have enough memory, and the system keep trying gc. it cannot be fixed from our side.
