### ISSUE TITLE
LSPosed makes Android TV boot process incredibly long, despite enough RAM

### ISSUE THREAD

**Issue by Anderhar** [LSPosed/LSPosed#2874]
### Steps to reproduce/复现步骤

Just activate any LSPosed version on [Walmart onn 4K Box](https://wiki.oddsolutions.us/devices/dopinder/) with a freshly re-installed LineageOS 20 with no modifications except Magisk.

**NOTE:** The previous [issue](https://github.com/LSPosed/LSPosed/issues/2870) was closed based on a premature conclusion of a RAM shortage without verification from my side, that showed that ~1/3 of RAM always stays free during the boot process. Don't rush this time, please.

### Expected behaviour/预期行为

With LSPosed disabled, system boots up in about 1 minute.

### Actual behaviour/实际行为

With LSPosed enabled, system boots up in 10-25 minutes.

### Xposed Module List/Xposed 模块列表

```shell
None
```

### Magisk Module List/Magisk 模块列表

```shell
LSPosed only.
```

### LSPosed version/LSPosed 版本

v1.9.2-7042-zygisk-debug (and any other)

### Android version/Android 版本

Android 13 (LineageOS 20)

### Magisk version/Magisk 版本

v26.4

### Riru version/Riru 版本

Zygisk or Riru v26.1.7 (both tested)

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[log.zip](https://github.com/LSPosed/LSPosed/files/13602514/log.zip)
[system-logcats.zip](https://github.com/LSPosed/LSPosed/files/13602515/system-logcats.zip)
(Logs manually exported from /data/adb/lspd due to Android TV GUI limitations.)

**Comment by yujincheng08** [comment]
lmkd has triggered many times, and systemui has been paused for tens of minutes for gc and then crashed, and leads to slow boot. this is indeed memory issue. there may be enough memory, but that does not mean the system thinks tmit is enough.
