### ISSUE TITLE
Azerbaijani language for lsposed

### ISSUE THREAD

**Issue by RashadGasimly** [LSPosed/LSPosed#2879]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

no

### Describe the solution you'd like/描述你想要的解决方案

Hello, i want to add and translate azerbaijani language for lsposed. I visited the translation site and it said you have to submit github issue.

**Comment by Howard20181** [comment]
Added https://lsposed.crowdin.com/lsposed/az
Now you can start translating, it will be included before the next release

**Comment by RashadGasimly** [comment]
> Added https://lsposed.crowdin.com/lsposed/az Now you can start translating, it will be included before the next release

thanks!
