### ISSUE TITLE
Can NOT work on HyperOS

### ISSUE THREAD

**Issue by DeparturesNeko** [LSPosed/LSPosed#2880]
### Steps to reproduce/复现步骤

install the zygisk module (not riru version). all modules didn't work which depend on lsposed. i trid stable version and 7045 version, it didn't help.

### Expected behaviour/预期行为

module work as expected

### Actual behaviour/实际行为

it didn't work.

### Xposed Module List/Xposed 模块列表

```shell
nothing
```

### Magisk Module List/Magisk 模块列表

```shell
zygisk
```

### LSPosed version/LSPosed 版本

7045 and stable version

### Android version/Android 版本

14

### Magisk version/Magisk 版本

26.4

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

i cant see the log because my phone works TOO SLOW if i install the module. only once i can see in the magisk is a lot of error like"umount XXXXX invalid argument 22"

**Comment by Howard20181** [comment]
#2869
