### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Shidapu** [LSPosed/LSPosed#2894]
### Steps to reproduce/复现步骤

See log. 

### Expected behaviour/预期行为

See log. 

### Actual behaviour/实际行为

See log. 

### Xposed Module List/Xposed 模块列表

```shell
See log.
```

### Magisk Module List/Magisk 模块列表

```shell
See log.
```

### LSPosed version/LSPosed 版本

7024

### Android version/Android 版本

14

### Magisk version/Magisk 版本

Canary

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-12-24T15_48_26.277813.zip](https://github.com/LSPosed/LSPosed/files/13762137/LSPosed_2023-12-24T15_48_26.277813.zip)

**Comment by canyie** [comment]
See you again

**Comment by Shidapu** [comment]
> See you again

Alright. :) It is Firefds Kit [Tiramisu] that is complaining that my Magisk Installation (sepolicy not granted). But my Magisk installation is perfectly fine, only just happened when upgrading to A14 just recently on Samsung hardware.
