### ISSUE TITLE
能不能忽略或者排除模块更新？

### ISSUE THREAD

**Issue by DreePure** [LSPosed/LSPosed#2895]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

模块仓库的更新，有的不能更新，还总提示，强迫症受不了。整个忽略更新行不行？

### Describe the solution you'd like/描述你想要的解决方案

模块仓库的更新，有的不能更新，还总提示，强迫症受不了。整个忽略更新行不行？

### Additional context/其他信息

模块仓库的更新，有的不能更新，还总提示，强迫症受不了。整个忽略更新行不行？

**Comment by yujincheng08** [comment]
你强迫症跟我没关系呀。

**Comment by canyie** [comment]
强迫症可以使用认知行为疗法、SSRI 类药物等治疗手段进行治疗。

**Comment by AXEVO** [comment]
> 强迫症可以使用认知行为疗法、SSRI 类药物等治疗手段进行治疗。



> 你强迫症跟我没关系呀。

希望重新考虑此建议，米客等模块的新版本不支持安卓14以下的设备，lsp仓库会一直提示要求更新，比较麻烦

**Comment by vvb2060** [comment]
等play商店支持隐藏更新我们就加
