### ISSUE TITLE
Hide Mock Location

### ISSUE THREAD

**Issue by 462819** [LSPosed/LSPosed#2900]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

隱藏虛擬定位
[com.github.thepiemonster.hidemocklocation-209-2.0.9 (3).zip](https://github.com/LSPosed/LSPosed/files/13792954/com.github.thepiemonster.hidemocklocation-209-2.0.9.3.zip)

### Describe the solution you'd like/描述你想要的解决方案

安裝hide mock location
[com.github.thepiemonster.hidemocklocation-209-2.0.9 (1).zip](https://github.com/LSPosed/LSPosed/files/13792973/com.github.thepiemonster.hidemocklocation-209-2.0.9.1.zip)

**Comment by yujincheng08** [comment]
OK
