### ISSUE TITLE
Cannot create shortcut for parasitic manager

### ISSUE THREAD

**Issue by Twolitrepinto** [LSPosed/LSPosed#2901]
### Steps to reproduce/复现步骤

Install Magisk
Install Lsposed module
Reboot

### Expected behaviour/预期行为

Shortcut created
Notification appears

### Actual behaviour/实际行为

No shortcut or notification.
Install manager.apk manually, toggle "Status Notification" in settings causes Lspose to crash.

### Xposed Module List/Xposed 模块列表

```shell
None currently
```

### Magisk Module List/Magisk 模块列表

```shell
Lsposed
```

### LSPosed version/LSPosed 版本

1.92

### Android version/Android 版本

13 (OneUI 5.1)

### Magisk version/Magisk 版本

Alpha 26403 (also tried Canary)

### Riru version/Riru 版本

N/A

### Version requirement/版本要求

- [X] I am using latest debug CI version of LSPosed and enable verbose log/我正在使用最新 CI 调试版本且启用详细日志

### Logs/日志

[LSPosed_2023-12-29T14_10_18.296351.zip](https://github.com/LSPosed/LSPosed/files/13794222/LSPosed_2023-12-29T14_10_18.296351.zip)

**Comment by yujincheng08** [comment]
Not debug log.
And if shortcut is not working, use notification instead. It's possible that some devices cannot create shortcut.
