### ISSUE TITLE
English description of shamiko 

### ISSUE THREAD

**Issue by aayushrautela** [LSPosed/LSPosed#2906]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

No, just a suggestion 

### Describe the solution you'd like/描述你想要的解决方案

Since many people don't understand 
![Screenshot_20240101-160627](https://github.com/LSPosed/LSPosed/assets/32957381/ad931013-f3ba-4125-9606-502f5d384f52)
Chinese, an English description of module would be nice.

**Comment by yujincheng08** [comment]
That's a slogan, not a description. The description is within `[]`.
