### ISSUE TITLE
为什么页面框架的左边会显示我的真实姓名

### ISSUE THREAD

**Issue by andysay76** [LSPosed/LSPosed#2912]
### Is your feature request related to a problem?/你的请求是否与某个问题相关？

在框架页面，左边是已经激活或者下载好的插件，左边则是显示xspace。
我想不明白的是，为什么左边会显示我的真实姓名，我也没在系统上输入过我的真实姓名，这个名字怎么来的？还改不了

### Describe the solution you'd like/描述你想要的解决方案

建议将这个东西改成可以自己修改

**Comment by yujincheng08** [comment]
MIUI 提供的哦
