### ISSUE TITLE
[FR]Strings.xml

### ISSUE THREAD

**Issue by Pandemic-XDA** [LSPosed/LSPosed#302]
**Detail**:
Please upload a new strings.xml of the LSPosed manager because some lines are missing and we translators don't know what to translate and it will be usefull for us..

Example for this and it is missing the string.xml names: 
Module enabled
Dark theme
Always on
Always off
Follow system

Please add those lines so we can translate it.

Thanks ^^

**Comment by Pandemic-XDA** [comment]
Hope the strings.xml will be posted.

**Comment by Pandemic-XDA** [comment]
Why closed ?

**Comment by vvb2060** [comment]
https://github.com/RikkaApps/RikkaX/blob/master/core/core/src/main/res/values/strings.xml
Please provide translation to upstream
