### ISSUE TITLE
[FR] 需要全选范围功能

### ISSUE THREAD

**Issue by dabai2017** [LSPosed/LSPosed#307]
**Detail**:
开发者您好，LSP管理器需要全选作用域范围功能，因为部分模块，比如储存重定向这样的，需要的作用域太多了，一个个点太麻烦了，而且如果我有很多这样的模块，那真是需要点一个世纪才能点完。

**Comment by yujincheng08** [comment]
这类模块也不需要全选啊。
全选之后你还是要一个一个取消不需要作用的，没区别。

**Comment by tehcneko** [comment]
@dabai2017 https://play.google.com/store/apps/details?id=moe.shizuku.redirectstorage
