### ISSUE TITLE
[BUG] Some module not working with LSPosed on Samsung OneUI 3.1 (Android 11)

### ISSUE THREAD

**Issue by Didyme33** [LSPosed/LSPosed#311]
Hello,

On a Samsung Galaxy S10+, some modules like XPrivacyLua are not working with LSPosed 1.2.2, the module doesn't even load. (screenshot).
Other modules like GravityBox or Firefds Kit are working well.
The configuration is : Android 11 (**Samsung One UI 3.1**), Magisk 22, Riru 23.9, LSPosed 1.2.2, XPrivacyLua 1.30.

I did some testing with another phone : Google Pixel 4a, Android 11 stock (from Google). Magisk 22, Riru 23.9, LSPosed 1.2.2, XPrivacyLua 1.30. With this configuration, XPrivacyLua is working great.

I highly suspect a problem due to OneUI 3.1, because this module is **working really great on my Google Pixel 4a** with the same configuration.

![Screenshot_20210309-110328_XPrivacyLua](https://user-images.githubusercontent.com/72032843/110475848-a6d66f00-80e1-11eb-9d7a-89858275fba1.jpg)
[LSPosed_Modules_20210309_140238.log](https://github.com/LSPosed/LSPosed/files/6108721/LSPosed_Modules_20210309_140238.log)
[LSPosed_Verbose_20210309_141626.log](https://github.com/LSPosed/LSPosed/files/6108736/LSPosed_Verbose_20210309_141626.log)

**Comment by yujincheng08** [comment]
`skip injecting into android because sepolicy was not loaded properly`

Magisk's problem.

**Comment by yujincheng08** [comment]
Please check #314. I try to patch the sepolicy if magisk does not load it.

**Comment by yujincheng08** [comment]
Please also try magisk canary. If it does not work, submit an issue to magisk following its template with bootlog (adb log) and magisk log.
