### ISSUE TITLE
[FR] Possible to add RGB/HEX input ?

### ISSUE THREAD

**Issue by xerta555** [LSPosed/LSPosed#313]
Hi

It could be possible to add an input for RGB/HEX color value in the color setting?
![Screenshot_20210309-165003](https://user-images.githubusercontent.com/20888017/110498683-d55f4480-80f7-11eb-9f48-6e98f7cf9923.jpg)

Thanks in advance.

**Comment by tehcneko** [comment]
impossible :(

**Comment by RikkaW** [comment]
1. Android's resources system does not support runtime changes.
2. Allow customization means there will be people who choose ugly looking colors
