### ISSUE TITLE
Touch/long-press action improvements[FR] 

### ISSUE THREAD

**Issue by entr0pia** [LSPosed/LSPosed#339]
**Detail**:
The most users maybe come from legacy Xposed (original version, EdXpoesd, etc). Exchanging touch and ("setting" of current) long-press action would be more friendly for the habits of legacy Xposed, into module apps with "touch" and opening Ex menu with "long-press",

**Comment by yujincheng08** [comment]
For new users to LSPosed, this is good to guide them to the scope selection page. Otherwise, they may not know selecting scope is required.
