### ISSUE TITLE
[FR] Adding credits for translators

### ISSUE THREAD

**Issue by Pandemic-XDA** [LSPosed/LSPosed#369]
I want to request if all the translators for each language can be added under the credits like each user for the language they translated and also in the LSPosed manager and also if a submenu can be added and under that option, the dev, maintainers and the translators/contributors.

Kind regards

**Comment by yujincheng08** [comment]
We already have one.

**Comment by Pandemic-XDA** [comment]
Oh yeah where ? Can't see it nor find it -__-
No credit list !

**Comment by RyanGamingXbox** [comment]
@Pandemic-XDA 
According to #237, it's in the about page.

**Comment by Pandemic-XDA** [comment]
> @Pandemic-XDA 
> According to #237, it's in the about page.

Lol already solved mate.
