### ISSUE TITLE
[FR] Able to change in Setting for meta-data as prefix

### ISSUE THREAD

**Issue by Stillhard** [LSPosed/LSPosed#37]
Some apps, detecting meta-data for android:name contains 'xposed' in AndroidManifest (such as 'xposedmodule' etc).
It'll be nice for LSPosed Manager if it can provide user (and developer oc 😘) to be able to change 'xposed' part as prefix and leave other (ex. from xposedmodule to imcutemodule - 'imcute' as the prefix).
ex.
`if (info.metaData != null && (info.metaData.containsKey("xposedmodule") || info.metaData.containsKey(pref.prefix + "module"))) {`
or
`if (app.metaData != null && (app.metaData.containsKey("xposedmodule") || app.metaData.containsKey(pref.prefix + "module"))) {`

Best regards,
Stillhard

**Comment by yujincheng08** [comment]
Of course, it will be nice but as long as we can read your pref, the detection app can also do so and find out you are a module.

**Comment by yujincheng08** [comment]
Also half a year later, google force all apps to target 30 and they will no longer read other apps' apk file unless they add your module to its package visibility.

**Comment by Stillhard** [comment]
LOL, that's a heck quick for a [FR] to get closed

**Comment by kotori2** [comment]
It's useless because

1. Apks are accessable by every other app
2. Everything in a module will be stored in apks, thus we can't do anything.

We have to wait until Google forced package visibility.
