### ISSUE TITLE
[BUG] Not working Wi-Fi

### ISSUE THREAD

**Issue by denis1532** [LSPosed/LSPosed#378]
Hi!
Redmi Note 9 Pro, xiaomi.eu 12.0.2.0 with enabled r/w.
Magisk 21.4, Riru of the latest version.
After smartphone reboot, it goes 2 ways:
1) Wi-Fi is stuck on "Getting IP-address..." and only manual turn off and then on helps
2) Wi-Fi is simply not loading, only manual Wi-Fi turn off and then on help

**Comment by denis1532** [comment]
Why invalid and stupid, if it happened only after LSPosed installation and disappears after deinstallation?
I'm shure that the problem is definitely in LSPosed, not firmware...

**Comment by yujincheng08** [comment]
seriously?

1. not follow template
2. no log
3. old version of magisk
4. no Riru version
5. no LSPosed version

too stupid.

**Comment by yujincheng08** [comment]
https://github.com/topjohnwu/Magisk/issues/3179
