### ISSUE TITLE
[BUG] "作用域" List is Empty

### ISSUE THREAD

**Issue by EdenJohnson2006** [LSPosed/LSPosed#4]
**什么情况/What happened?**

When turn on a module the "作用域" list is empty and can't select apps

**Xposed模块列表/Xposed Module List**

[QNotified](https://github.com/ferredoxin/QNotified)

**Magisk模块列表/Magisk Module List**

[ACC 2020.07.26](https://github.com/MatteCarra/AccA)

**版本信息/Versions**

Android: LineageOS 17.1 (Android 10)

Magisk:21.4(21400)

Riru:23.4

LSPposed:v0.5.2.0

**相关日志/Related Logs**

**No Log with Apps :( **

**Comment by tehcneko** [comment]
@EdenJohnson2006 ？

**Comment by EdenJohnson2006** [comment]
> @EdenJohnson2006 ？

?

**Comment by tehcneko** [comment]
@EdenJohnson2006 你加了白名单吗

**Comment by EdenJohnson2006** [comment]
> @EdenJohnson2006 你加了白名单吗

没有 这...

**我居然以为这个白名单是不作用的 我是不是~傻逼~**

**Comment by yujincheng08** [comment]
是的。
