### ISSUE TITLE
[INFO] java.lang.SecurityException when running on LSPosed

### ISSUE THREAD

**Issue by etmatrix** [LSPosed/LSPosed#401]
**What happened?**
I have an app(module lsposed) which use rsa library and hook other apps for import/export tokens in/from my app.
When my app run without lsposed (module is disabled in manager), I have not exception and I can manage my tokens, but when I enable lsposed for my module, I got a java.lang.SecurityException while I init the rsa library.
This is a partial of exception, here [exception.log](https://github.com/LSPosed/LSPosed/files/6191105/exception.log) all details.

```
03-23 12:02:09.803 20906 20906 E AndroidRuntime: Caused by: java.lang.SecurityException: getSerial: The user 10184 does not meet the requirements to access device identifiers.
03-23 12:02:09.803 20906 20906 E AndroidRuntime: 	at android.os.Parcel.createException(Parcel.java:2071)
03-23 12:02:09.803 20906 20906 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:2039)
03-23 12:02:09.803 20906 20906 E AndroidRuntime: 	at android.os.Parcel.readException(Parcel.java:1987)
03-23 12:02:09.803 20906 20906 E AndroidRuntime: 	at android.os.IDeviceIdentifiersPolicyService$Stub$Proxy.getSerialForPackage(IDeviceIdentifiersPolicyService.java:159)
03-23 12:02:09.803 20906 20906 E AndroidRuntime: 	at android.os.Build.getSerial(Build.java:168)
03-23 12:02:09.803 20906 20906 E AndroidRuntime: 	at com.rsa.securidlib.android.y.zz.uu(Unknown Source:293)

```
I tried to add all permissions, but I got always exception.

My environment:
LineageOS 17.1 (Android 10) arm64
Lsposed: 1.3.4 (I have the same issue with 1.2.2)
Magisk: 22.0
Riru Core: 25.3.3 (I have the same issue with 23.9)
Magisk modules: Riru Core and Lsposed
Lsposed modules: only my module.

I have the same issue with EdXposed so is not only with lsposed.
The same module with (Android 8.0 (arm64) or Android 8.1 (x86)) and EdXposed 0.5.2.2 works without exception, with and without xposed enabled, so I don't think rsa library detect xposed.
I can test with Android 9.0 (x86) if is useful.

Is it a normal behaviour with android 10 or is an issue? I expect when lsposed/edxposed is enabled the app run without changes.
If is an issue I can install the debug version and catch log for understand better.

**Comment by VD171** [comment]
getSerial is not allowed for user applications after API 29:
https://developer.android.com/reference/android/os/Build#getSerial()

**Comment by etmatrix** [comment]
@VD171 sure but when the app is running without lsposed enabled it's works.

**Comment by yujincheng08** [comment]
Thanks, @VD171. You are right.

@etmatrix  Please check again. Maybe rsa is failed to detect the Android version correctly when LSPosed enabled?

**Comment by yujincheng08** [comment]
@etmatrix and is your app target 29+?

**Comment by etmatrix** [comment]
@yujincheng08 yes target is 29, compile sdk 29, min sdk version 23.
I will try with target 30.

**Comment by yujincheng08** [comment]
NONONO. Try target 28

**Comment by etmatrix** [comment]
I will test both.

**Comment by etmatrix** [comment]
@yujincheng08 I tested all targets from 27 to 30. I got always the same exception.

**Comment by yujincheng08** [comment]
Did you add `READ_PHONE_STATE ` permission when targeting 28?

**Comment by etmatrix** [comment]
@yujincheng08 no but I have done another test with target 28 and permissions:

    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.ACCESS_WIFI_STATE"/>
    <uses-permission android:name="android.permission.READ_PHONE_STATE"/>
    <uses-permission android:name="android.permission.CALL_PHONE"/>

I got always the same exception.

**Comment by yujincheng08** [comment]
> If the calling app's target SDK is API level 28 or lower and the app has the READ_PHONE_STATE permission then Build#UNKNOWN is returned.

**Comment by etmatrix** [comment]
@yujincheng08 Application Info return 28(min 23) and permission READ_PHONE_STATE is set. Is very weird.
I will publish my project on github and will advice you when done.

**Comment by etmatrix** [comment]
@yujincheng08 you should see it. Sorry if my code is not good to see for you. Not all comments are in english.

**Comment by yujincheng08** [comment]
Can't see the code. Where did u post?

**Comment by etmatrix** [comment]
@yujincheng08 did not receive the invitation?

**Comment by yujincheng08** [comment]
ohh i see. I ignore that emal...

**Comment by etmatrix** [comment]
I tried to hook getSerial and return null

```
if(Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q)
{
    Class<?> clsBuild = findClass("android.os.Build", objXLP.classLoader);
    findAndHookMethod(clsBuild, "getSerial", XC_MethodReplacement.returnConstant(null));
}

```
but the init of rsa library fail and there is this weird warning.
```
03-23 18:54:55.257  2834  2990 I ActivityManager: Start proc 31268:et.nessuno.xrsasecureid/u0a184 for pre-top-activity {et.nessuno.xrsasecureid/et.nessuno.xrsasecureid.MainActivity}
03-23 18:54:55.277 31268 31268 E no.xrsasecurei: Not starting debugger since process cannot load the jdwp agent.
03-23 18:54:55.299 31268 31268 I LSPosed : Start to install inline hooks
03-23 18:54:55.299 31268 31268 I LSPosed : Using api level 29
03-23 18:54:55.299 31268 31268 I LSPosed : Start to install Riru hook
03-23 18:54:55.300 31268 31268 I LSPosed : Riru hooks installed
03-23 18:54:55.422 31268 31268 I LSPosed : ART hooks installed
03-23 18:54:55.487 31268 31268 I LSPosed : Loading modules for et.nessuno.xrsasecureid
03-23 18:54:55.489 31268 31268 I LSPosed-Bridge: Loading modules from /data/app/et.nessuno.xrsasecureid-Dh7GB7ZUSa7cAtTWb38_oQ==/base.apk
03-23 18:54:55.491 31268 31268 W no.xrsasecurei: ClassLoaderContext type mismatch. expected=PCL, found=DLC (PCL[] | DLC[];IMC[<unknown>*281804506];IMC[<unknown>*676155116];PCL[])
03-23 18:54:55.494 31268 31268 I no.xrsasecurei: Failed to add image file Rejecting application image due to class loader mismatch: 'Class loader types don't match dalvik.system.PathClassLoader and dalvik.system.DelegateLastClassLoader'
03-23 18:54:55.497 31268 31268 I LSPosed-Bridge:   Loading class et.nessuno.xrsasecureid.XMain
03-23 18:54:55.532 31268 31268 W LSPosed : New modules detected, hook preferences
03-23 18:54:55.563 31268 31268 V XRSASecureID: et.nessuno.xrsasecureid
03-23 18:54:55.596 31268 31268 W no.xrsasecurei: Unsupported class loader
03-23 18:54:55.596 31268 31268 W no.xrsasecurei: Could not establish class loader context
03-23 18:54:55.712 31268 31268 W no.xrsasecurei: ClassLoaderContext parent mismatch.  (PCL[] | PCL[];PCL[/data/app/et.nessuno.xrsasecureid-Dh7GB7ZUSa7cAtTWb38_oQ==/base.apk*82276606:/data/app/et.nessuno.xrsasecureid-Dh7GB7ZUSa7cAtTWb38_oQ==/base.apk!classes2.dex*479112176])

```

**Comment by yujincheng08** [comment]
This is because of hidden API. We disable hidden API restriction on hooked apps and it causes the RSA library to change its behaviour and to use `getSerial`. Actually, it's hard for us to keep hidden API enabled. So it won't be fixed.

**Comment by yujincheng08** [comment]
Oh it's not because hidden api. I disable it but it still works.

**Comment by yujincheng08** [comment]
Remove `xposedsharedprefs` and set `xposedminversion` to 92 works now.

**Comment by etmatrix** [comment]
@yujincheng08 great thank you for your suggestion. My goal was use the new XSharedPreference, but for this module I will use RemotePreference.

**Comment by yujincheng08** [comment]
The problem is:
The sharedpreference set `AppSetting_DEVICE_ID_VERSION` to be 1 for the first initializing (creating database). It stores to the original place when its not hooked.

And if you enable it in LSPosed, and the library found the database is created, it won't write `AppSetting_DEVICE_ID_VERSION` again. But the preference dir is moved to a new place. That makes the `AppSetting_DEVICE_ID_VERSION` becomes 0 and go to the wrong place.

**Comment by yujincheng08** [comment]
So the solution is: DO NOT initialize `AndroidSecurIDLib` if shared perefence is not hooked.

**Comment by etmatrix** [comment]
@yujincheng08 ok, if I initiliaze the app with xsharedpreference enabled, it's works, also if I have a strange behaviour on one shared preference file but this is another issue (every time analyze all apps, but should done only the first time). The app continue to works until I disable the module on LSPosed, when I got the exception. Inverse of initial issue.
When the preference directory is moved shouldn't it already contain the old content? So AppSetting_DEVICE_ID_VERSION should be 1 and keep to 1. I don't understand, but I will study the source LSPosed for understand better.

- App start without LSPosed, initialize database and in sharedpreference AppSetting_DEVICE_ID_VERSION is 1.
- Enable module on LSPosed 
- shared_prefs is moved to another accessible path
- App start should be access to new path with old content, so AppSetting_DEVICE_ID_VERSION is always 1. 

Should be transparent to application the new XSharedPreference.
I will debug to myself for understand.
Thank you for your time and thank you for your work on LSPosed.

**Comment by yujincheng08** [comment]
@etmatrix 
> Should be transparent to application the new XSharedPreference.

PR is welcome :p

**Comment by etmatrix** [comment]
@yujincheng08 I think your idea reported in #402 is good. /data is encrypted and not only /data/data. I don't know how work FBE because my device is old and has only a kernel 3.18, so LineageOS implement an encrypted partition.

RemotePreferences stop to work on android 10 for a security check, so now I must use XSharedPreference, but it's impossible if the 2 directories are not syncronized. So I will mount --bind before initialize RSA Library and I will use XSharedPreferences.
With mound bind syncronization is perfect: there is unique place where the files stay.

LSPosed should keep syncronized 2 directories, but I don't know how.
