### ISSUE TITLE
[TODO] CLI - Command Line Interface

### ISSUE THREAD

**Issue by VD171** [LSPosed/LSPosed#405]
**Detail**:
First, thank you very much for the entire LSPosed team and community.
 
Xposed is a reality in our lives that we absolutely will not live without more.

I love EdXposed.
I like LSPosed. But I'm sure I will love it too.

Undoubtedly, we all preferred that both projects continued being developed together.
The desire, pleasure, commitment and dedication of the LSPosed team is really admirable.

The primary difference between LSPosed and EdXposed is that LSPosed works exclusively through scopes.
Like MagiskHide, LSPosed needs you to enable or disable scopes for each app.

But, we may want to enable the scopes in a massive way.

With MagiskHide, we can use the command line interface (CLI) to enable and disable apps.

With LSPosed, it would be really very helpful to use a CLI (Command Line Interface).
If a CLI (Command Line Interface) were implemented, certainly I would migrate totally to LSPosed.

I wrote a perl script, it makes all the service for me for long years.
It does:
- (Deprecated) Add apps to automatic hibernation (Greenify).
- (Deprecated) Add apps to hide root (Rootcloak2).
- (Deprecated) Add patterns to hide root (Rootcloak2).
- Add apps to hide root (MagiskHide).
- Check all global settings (XPrivacyLua).
- Enable notification for all apps (XPrivacylua).
- Enable previously selected hooks for the previously selected apps (XPrivacyLua).
- Add scopes to the modules, following the same apps enabled in xprivacylua (LSPosed).
- Enable previously selected modules (LSPosed).
- Check if any app was enabled by mistake in any of the previous steps.

This guarantees with 100% precision that everything will always be perfectly configured, following my own filters, helping me to save my time and preventing me to do something mistakenly due to the exhaustive sequence of steps.

The question here is, I need to use the SQLite to apply the changes in the LSPosed database, which is a very unfortunately not recommended practice.

So, it would be of extreme importance the possibility of enabling and disabling the modules and the scopes through a command line interface (CLI), like:

`lsposed enable module.pkg.name`
`lsposed disable module.pkg.name`

`lsposed add module.pkg.name app.pkg.name`
`lsposed rm module.pkg.name app.pkg.name`

**Comment by yujincheng08** [comment]
We all love cli. However, designing a reasonable cli interface is not that easy. So we have to discuss the interface here before implementation.

My thought is:
1. place the cli in `/data/adb/lspd/bin/lsposed`, which is a shell script to launch `app_process` with `lspd.dex` (we need to use binder so java is required).

And the interface is like:
`lsposed scope ls org.lsposed.module`: output the scope of module. One package name with userid per line. (com.lsposed.app/0) Empty module name with list all modules.

`lsposed scope set org.lsposed.module oeg.lsposed.app/0`: *replace* the scope with apps provided. (-i/--ignore-modules after set to ignore invalid apps)

`lsposed scope append org.lsposed.app/0` *append* provided apps to the scope. (not atomic) (also -i)

`lsposed modules disable/enable org.lsposed.module`: enable/disable provided modules.

`lsposed modules ls`: list all modules. (-e/--enable, -d/--disable to show enabled/disable modules)

`lsposed status`: show status of lsposed

`lsposed log`: show modules log. -v to show verbose.log. -f to follow. (don't know if its possible)

`lsposed resources-hook enable/disable`

**Comment by VD171** [comment]
Wow, your idea was much better than you could imagine.
Perfect !
About the "-i" option, does it mean keeping apps like permanent to scope?
Apparently, the LSPosed app is cleaning the not found/invalid apps, but we may want to keep the application for the scope even after the uninstall.
And then, if we reinstall the application, it will automatically be back to the scope. 


And then, if we reinstall the app, it will be automatically again to the scope.

**Comment by yujincheng08** [comment]
acutally, -i means if u provide an invalid app, cli will not throw error but silently ignore it.

**Comment by VD171** [comment]
May I suggest the "-f" option?
And then force adding the invalid app.
Consequently, this require the ignored/uninstalled app would not automatically removed.

**Comment by yujincheng08** [comment]
its impossible. LSPosed needs to query all process names of an app. When uninstalled, LSPosed can no long query process names and will therefore remove it.

**Comment by VD171** [comment]
I got you.
Thanks for explaining.

**Comment by ichason** [comment]
Hi, Before that, is there any good solution?

**Comment by ducdanganhit** [comment]
Is this done?

**Comment by yujincheng08** [comment]
API for requesting scope was implemented. CLI no longer seems needed.
