### ISSUE TITLE
[FR] 

### ISSUE THREAD

**Issue by hw1020** [LSPosed/LSPosed#42]
激活失效作用域，设置的好好的由于某些原因导致激活失败，之前激活设置的作用域等信息就丢失了，希望可以备份作用域配置信息并可以还原。

昨天刷了一个版本，激活成功了正常使用，后面区刷了下新版本magisk，不知道什么原因导致了它激活失败，然后退回edxposed也一样失败，最后把/data/adb文件夹删了重刷magisk及其模块才弄好。

最好是可以定期自动按时间备份到
某个sdcard目录下

**Comment by 7lsu** [comment]
您是看不懂readme🐴
整个readme就一句中文就是给您写的噢

**Comment by yujincheng08** [comment]
close with #46

**Comment by hw1020** [comment]
没看到，只想着反馈建议了，您收到就行了。
________________________________
发件人: 7lsu <notifications@github.com>
发送时间: 2021年2月2日星期二 下午3:52
收件人: LSPosed/LSPosed
抄送: hw1020; State change
主题: Re: [LSPosed/LSPosed] [FR] (#42)


您是看不懂readme🐴
整个readme就一句中文就是给您写的噢
