### ISSUE TITLE
[FR] Activate a module for all apps

### ISSUE THREAD

**Issue by gabrc52** [LSPosed/LSPosed#421]
**Detail**: I'd like to be able to activate a module for all apps at once, rather than having to do it one by one.

In addition, I'd like to know if there's a reason why modules don't hook every app by default unlike the old XPosed. Does it help with stability? Battery life?

**Comment by gabrc52** [comment]
Closed without explanation or answering the question. I understand this choice is intentional, but I want to understand why.

**Comment by canyie** [comment]
#28 #283 #307
