### ISSUE TITLE
 Active but not active

### ISSUE THREAD

**Issue by q1363679989q** [LSPosed/LSPosed#454]
**什么情况/What happened?**

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android:

Magisk:

Riru:

LSPosed:

**相关日志/Related Logs**

![Screenshot_20210404-210912](https://user-images.githubusercontent.com/55631703/113509913-a0c19a00-958a-11eb-890c-65a216a8c304.jpg)
![Screenshot_20210404-210912](https://user-images.githubusercontent.com/55631703/113509919-a5864e00-958a-11eb-8b25-bfbdfbf29e95.jpg)
![Screenshot_20210404-210846](https://user-images.githubusercontent.com/55631703/113509921-a7e8a800-958a-11eb-8be7-5dc9bc4d6efc.jpg)

**Comment by q1363679989q** [comment]
功能是正常的

**Comment by JasonKhew96** [comment]
换包名了，自己看一下是不是 `org.lsposed.manager`

**Comment by q1363679989q** [comment]
不一样



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 4, 2021 21:18 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LSPosed/LSPosed]  Active but not active (#454)




 
换包名了，自己看一下是不是 org.lsposed.manager

**Comment by yujincheng08** [comment]
不一样那就是你用错管理器了

**Comment by q1363679989q** [comment]
用哪个啊，有链接吗以前一直用的这个



---Original---
From: ***@***.***&gt;
Date: Sun, Apr 4, 2021 21:36 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [LSPosed/LSPosed]  Active but not active (#454)




 
不一样那就是你用错管理器了
