### ISSUE TITLE
[BUG] SEPolicy Not loaded correctly

### ISSUE THREAD

**Issue by q1363679989q** [LSPosed/LSPosed#455]
![Screenshot_20210404-215620](https://user-images.githubusercontent.com/55631703/113511134-df5a5300-9590-11eb-9691-ede8cace6b44.jpg)

**什么情况/What happened?**

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android:

Magisk:

Riru:

LSPosed:

**相关日志/Related Logs**

API 版本
93

框架版本
v1.3.4 (5501)

管理器版本
v1.3.4 (5521)

系统版本
10 (API 29)

设备
OnePlus HD1910 

系统架构
arm64-v8a

**Comment by canyie** [comment]
“报告给 magisk 开发者”
