### ISSUE TITLE
[BUG]ColorOS6（Android9）can't be installed LSPosed

### ISSUE THREAD

**Issue by J-J1** [LSPosed/LSPosed#457]
**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android:9

Magisk:22.0

Riru:v25.3.4r399.84f7084

LSPosed:1.3.4

提示失败 然后弹出支持Android版本网页
安装Edxposed 提示版本低于Android O 然后弹出支持网页 
机型OPPO R11s
官方包 关于本机是Android9

**Comment by yujincheng08** [comment]
反馈给 magisk

**Comment by aviraxp** [comment]
你的报错信息里 Unsupported Android version 后面跟的是什么？
