### ISSUE TITLE
[BUG] Binder is null

### ISSUE THREAD

**Issue by WallyCZ** [LSPosed/LSPosed#462]
**什么情况/What happened?**
When running manager app I am getting "Binder is null" exception in logcat from [here](https://github.com/LSPosed/LSPosed/blob/0facfb958a16317dd10d3da2678c8d9c0fbf20af/app/src/main/java/org/lsposed/manager/receivers/LSPosedManagerServiceClient.java#L44)

Magisk seems is running normally but I can't get to work even EdXposed, so it will be probably issue with ROM (or riru?). But for case you know where is the issue I'll try it here at first. LSPosed log bellow.

**Xposed模块列表/Xposed Module List**
none

**Magisk模块列表/Magisk Module List**
riru
riru-lsposed

**版本信息/Versions**

Android: 11

Magisk: 22.0

Riru: 25.3.4.r399

LSPosed: 1.3.4-5541-debug

**相关日志/Related Logs**

> LSPosed Log
--------- beginning of information
Manufacturer: Xiaomi
Brand: Xiaomi
Device: cepheus
Product: cepheus
Model: MI 9
Fingerprint: Xiaomi/cepheus/cepheus:11/RKQ1.200826.002/21.3.10:user/release-keys
ROM description: cepheus-user 11 RKQ1.200826.002 21.3.10 release-keys
Architecture: arm64-v8a
Android build: RQ2A.210305.006
Android version: 11
Android sdk: 30
LSPosed version: v1.3.4 (5541)
Riru version: v25.3.4.r399.84f7084 (399)
Riru api: 25
Magisk: 22.0 (22000)
--------- beginning of kernel
10-03 13:35:23.759     0     0 F pcie    : pcie_init.
--------- beginning of main
--------- beginning of system
04-05 20:54:23.870   822   822 I LSPosedService: starting server...
04-05 20:54:23.920   822   822 I LSPosedService: version v1.3.4 (v1.3.4)
04-05 20:54:23.947   822   822 I LSPosedService: service package is not started, wait 1s.
04-05 20:54:24.948   822   822 I LSPosedService: service package is not started, wait 1s.
04-05 20:54:25.948   822   822 I LSPosedService: service package is not started, wait 1s.
04-05 20:54:26.949   822   822 I LSPosedService: service package is not started, wait 1s.
04-05 20:54:27.949   822   822 I LSPosedService: service package is not started, wait 1s.
04-05 20:54:28.949   822   822 I LSPosedService: service package is not started, wait 1s.
04-05 20:54:29.952   822   822 V LSPosedService: binder org.lsposed.lspd.service.LSPosedService@d5f2a45
04-05 20:54:29.952   822   822 W LSPosedService: no response from bridge, retry in 1s
04-05 20:54:30.179   822  1260 I LSPosedService: service activity is dead. 
04-05 20:54:30.179   822  1260 I LSPosedService: clear ServiceManager
04-05 20:54:30.179   822  1260 W LSPosedService: system server died
04-05 20:54:30.179   822  1260 I LSPosedService: service activity is not started, wait 1s.
04-05 20:54:30.952   822   822 V LSPosedService: binder org.lsposed.lspd.service.LSPosedService@d5f2a45
04-05 20:54:30.953   822   822 E LSPosedService: send binder android.os.DeadObjectException
04-05 20:54:30.953   822   822 E LSPosedService: 	at android.os.BinderProxy.transactNative(Native Method)
04-05 20:54:30.953   822   822 E LSPosedService: 	at android.os.BinderProxy.transact(BinderProxy.java:550)
04-05 20:54:30.953   822   822 E LSPosedService: 	at org.lsposed.lspd.service.BridgeService.sendToBridge(BridgeService.java:163)
04-05 20:54:30.953   822   822 E LSPosedService: 	at org.lsposed.lspd.service.BridgeService.send(BridgeService.java:237)
04-05 20:54:30.953   822   822 E LSPosedService: 	at org.lsposed.lspd.service.ServiceManager.start(ServiceManager.java:74)
04-05 20:54:30.953   822   822 E LSPosedService: 	at org.lsposed.lspd.core.Main.main(Main.java:124)
04-05 20:54:30.953   822   822 E LSPosedService: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-05 20:54:30.953   822   822 E LSPosedService: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
04-05 20:54:30.953   822   822 W LSPosedService: no response from bridge, retry in 1s
04-05 20:54:31.184   822  1260 I LSPosedService: service activity is not started, wait 1s.
04-05 20:54:31.953   822   822 V LSPosedService: binder org.lsposed.lspd.service.LSPosedService@d5f2a45
04-05 20:54:31.954   822   822 E LSPosedService: send binder android.os.DeadObjectException
04-05 20:54:31.954   822   822 E LSPosedService: 	at android.os.BinderProxy.transactNative(Native Method)
04-05 20:54:31.954   822   822 E LSPosedService: 	at android.os.BinderProxy.transact(BinderProxy.java:550)
04-05 20:54:31.954   822   822 E LSPosedService: 	at org.lsposed.lspd.service.BridgeService.sendToBridge(BridgeService.java:163)
04-05 20:54:31.954   822   822 E LSPosedService: 	at org.lsposed.lspd.service.BridgeService.send(BridgeService.java:237)
04-05 20:54:31.954   822   822 E LSPosedService: 	at org.lsposed.lspd.service.ServiceManager.start(ServiceManager.java:74)
04-05 20:54:31.954   822   822 E LSPosedService: 	at org.lsposed.lspd.core.Main.main(Main.java:124)
04-05 20:54:31.954   822   822 E LSPosedService: 	at com.android.internal.os.RuntimeInit.nativeFinishInit(Native Method)
04-05 20:54:31.954   822   822 E LSPosedService: 	at com.android.internal.os.RuntimeInit.main(RuntimeInit.java:399)
04-05 20:54:31.954   822   822 W LSPosedService: no response from bridge, retry in 1s
04-05 20:54:32.184   822  1260 I LSPosedService: service activity is not started, wait 1s.
04-05 20:54:32.954   822   822 W LSPosedService: no response from bridge
04-05 20:54:33.185   822  1260 I LSPosedService: service activity is not started, wait 1s.
04-05 20:54:34.185   822  1260 W LSPosedService: system restarted...
04-05 20:54:34.185   822  1260 V LSPosedService: binder org.lsposed.lspd.service.LSPosedService@d5f2a45
04-05 20:54:34.186   822  1260 W LSPosedService: no response from bridge, retry in 1s
04-05 20:54:35.186   822  1260 V LSPosedService: binder org.lsposed.lspd.service.LSPosedService@d5f2a45
04-05 20:54:35.186   822  1260 W LSPosedService: no response from bridge, retry in 1s
04-05 20:54:36.189   822  1260 V LSPosedService: binder org.lsposed.lspd.service.LSPosedService@d5f2a45
04-05 20:54:36.191   822  1260 W LSPosedService: no response from bridge, retry in 1s
04-05 20:54:37.191   822  1260 W LSPosedService: no response from bridge

**Comment by yujincheng08** [comment]
riru's problem.
