### ISSUE TITLE
[BUG] 

### ISSUE THREAD

**Issue by QkiZMR** [LSPosed/LSPosed#463]
**什么情况/What happened?**
LSposed Manager claims that framework is enabled but module (XPrivacyLua) is failed to load. XPrivacyLua app doesn't detect framework so it doesn't work. Theres a lot of strange errors in LSPosed log, related to system settings SQLite database. 

**Xposed模块列表/Xposed Module List**
XPrivacyLua

**Magisk模块列表/Magisk Module List**
Riru
Riru - Enhanced mode for Storage Isolation
Riru - LSposed
Systemless Hosts
Universal SafetyNet fix
Viper4Android FX Legacy

**版本信息/Versions**

Android: 9

Magisk: 24.4

Riru: 25.3.3

LSPosed: 1.3.4

**相关日志/Related Logs**
[LSPosed_Verbose_20210405_230834.log](https://github.com/LSPosed/LSPosed/files/6260685/LSPosed_Verbose_20210405_230834.log)

**Comment by yujincheng08** [comment]
I cannot see xlua loading for system server. I guess u didn't configure it properly.

**Comment by QkiZMR** [comment]
You mean System Framework? It's needed to be hooked on system server? On EdXposed 0.5.1.4 I disabled hooking system apps (System Framework inclusive) and it works fine. I enabled hooking for System Framework and it doesn't change anything. Same error.

**Comment by yujincheng08** [comment]
gosh... XLUA supports LSPosed scope declarsion. Needed scope will be selected automatically. Did you update xlua?? And definitely it needs system framework. And also, system settings.

https://github.com/M66B/XPrivacyLua/blob/2c5ab2b5693f0eec283bf45dd0741f8906dadc85/app/src/main/res/values/strings.xml#L80-L84

**Comment by QkiZMR** [comment]
Ok, i will try with system settings also. But this is strange because on EdXposed 0.5.1.4 it works fine without hooking any system framework or apps.

**Comment by QkiZMR** [comment]
Thanks for the link. It guides me on how to configure EdXposed 0.5.2.2 with XPLua correctly. But still, I don't know how it works ok on 0.5.1.4.

**Comment by yujincheng08** [comment]
Ridiculous. This is the LSPosed issue. How comes you keep talking about unrelative EdXposed. You should report result from LSPosed. Lock because of off topic.
