### ISSUE TITLE
[INFO] java.lang.UnsatisfiedLinkError after hook loadLibrary

### ISSUE THREAD

**Issue by etmatrix** [LSPosed/LSPosed#471]
**What happened?**
Maybe it's an issue, maybe no, maybe is stupid or invalid. I will try to explain it.
I have a test app which use XposedDetector and class android.util.StatsLog.
The class StatsLog has a static initializer which load the library libstats_jni.so

```
h1:/ # find /system -name libstats_jni.so
/system/apex/com.android.os.statsd/lib64/libstats_jni.so
/system/apex/com.android.os.statsd/lib/libstats_jni.so
```
Without LSPosed all works without issue on LOS 18.1 (Android 11). The same code and my test module with Android 10 Lineage OS 17.1 was working with LSPosed enabled.
This is the code in the hooked method:
```
  @Override
  protected void onPause()
  {
      super.onPause();
      Log.v("xposeddetector", "onPause");
      Log.v("xposeddetector", "Classloader" + ClassLoader.getSystemClassLoader());
      if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
          StatsLog.logEvent(1);
      }
  }
```
I tried to move the code StatsLog.logEvent out the hooked method, but I have the same result: UnsatisfiedLinkError

My test module implement the code which I described in this [issue.](https://github.com/vvb2060/XposedDetector/issues/3#issuecomment-798129453) Hook on loadLibrary and after the loadlibrary I set hook. New hooks works, but something corrupt LSPosed after XPosedDetector clean hooks. Because when the hooked app try to load the library libstats_jni.so can't find it, I attached log.
If I disable XposedDetector, all works, hooks and loadlibrary libstats_jni.so
I understand if you don't want fix and you don't see it, but with Android 10 all this was working.
I don't use native_init only xposed_init.

**Xposed Module List**
Only my test module

**Magisk Module List**
- Riru Core
- LSPosed

**Versions**

Android: Lineage OS 18.1 (Android 11)
Magisk: 22.0
Riru: 25.3.4
LSPosed: 1.3.4-5550-debug 7070fc4

**Related Logs**
Log debug and exception java.

[lsposed.log](https://github.com/LSPosed/LSPosed/files/6289781/lsposed.log)

**Comment by yujincheng08** [comment]
This might be because `librarySearchPath` of the classloader is corrupt.

Check `DexPathList.nativeLibraryDirectories` and `DexPathList.systemNativeLibraryDirectories`.

It might somehow be a bug of LSPosed that we did not make sure the `librarySearchPath` of modules' classloaders and `LspHooker`'s classloaders. However, from your code, I see you directly pass the application's classloader to `System.loadLibrary0`, then it should not be LSPosed's problem. Please check carefully with `librarySearchPath`. And if it's because of corruption of classloader's `librarySearchPath` brought by LSPosed, we will fix it.

**Comment by etmatrix** [comment]
> This might be because `librarySearchPath` of the classloader is corrupt.

I thought about this, but with android 10 was working. I upgraded without wipe data.

This is ClassLoader.getSystemClassLoader printed from test app with XposedDectror

`Classloaderdalvik.system.PathClassLoader[DexPathList[[directory "."],nativeLibraryDirectories=[/system/lib64, /system/system_ext/lib64, /system/product/lib64, /system/vendor/lib64, /system/lib64, /system/system_ext/lib64, /system/product/lib64, /system/vendor/lib64]]]`

This is the classloader from handleLoadPackage

`Classloader dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/~~D1dMJUKfLHLEP46BAgAuww==/io.github.vvb2060.xposeddetector-pqLbgXOHcrxkKkGYEWdnJQ==/base.apk"],nativeLibraryDirectories=[/data/app/~~D1dMJUKfLHLEP46BAgAuww==/io.github.vvb2060.xposeddetector-pqLbgXOHcrxkKkGYEWdnJQ==/lib/arm64, /data/app/~~D1dMJUKfLHLEP46BAgAuww==/io.github.vvb2060.xposeddetector-pqLbgXOHcrxkKkGYEWdnJQ==/base.apk!/lib/arm64-v8a, /system/lib64, /system/system_ext/lib64, /system/product/lib64, /system/vendor/lib64]]]`

The path of libstats_jni is never in the list, but should load with linkerconfig (I don't know very well this android's feature)

The `UnsatisfiedLinkError` is not on my `System.loadLibrary0` but on the next loadLibrary, which don't call my hook.
In my hook I have a log `"Before load library"` it's printed only the first time for xposeddetector library but for `libstats_jni` I don't see it.
In stacktrace my module `et.nessuno.xintentlog` doesn't exist, so I think is never called the second time. Without the second loadlibrary, all works (hooks, bypass etc...) also on android 11.

```
04-10 13:59:56.368 11249 11249 E AndroidRuntime: Process: io.github.vvb2060.xposeddetector, PID: 11249
04-10 13:59:56.368 11249 11249 E AndroidRuntime: java.lang.UnsatisfiedLinkError: dlopen failed: library "libstats_jni.so" not found
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1098)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at java.lang.System.loadLibrary(System.java:1664)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at de.robv.android.xposed.LspHooker.handleHookedMethod(LspHooker.java:62)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at LspHooker_.loadLibrary(Unknown Source:8)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at android.util.StatsLog.<clinit>(StatsLog.java:41)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at android.util.StatsLog.logEvent(StatsLog.java:89)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at io.github.vvb2060.xposeddetector.MainActivity.onPause(MainActivity.java:44)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at de.robv.android.xposed.LspHooker.handleHookedMethod(LspHooker.java:92)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at LspHooker_.onPause(Unknown Source:8)
04-10 13:59:56.368 11249 11249 E AndroidRuntime: 	at android.app.Activity.performPause(Activity.java:8174)
```

**Comment by yujincheng08** [comment]
`libstats_jni.so` is acutally in `/apex/com.android.os.statsd/lib` without `/system` prefix. But actually the linker of Android will translate some `/system/lib`'s to `/apex` (see https://cs.android.com/android/platform/superproject/+/master:bionic/linker/linker_main.cpp;drc=bb1e37358f142428714d829681f8e767d6170db3;l=383). So I think as soon as the lib search path contains `/system/lib`, it will be okay.

However, classloader of `de.robv.android.xposed.LspHooker` does not have any lib search path and it may lead to ur problem. Please check:
https://github.com/LSPosed/LSPosed/blob/7070fc491832dfc9fbe0d26de690d09900bbc943/core/src/main/java/org/lsposed/lspd/yahfa/dexmaker/HookerDexMaker.java#L92

And 

https://github.com/LSPosed/LSPosed/blob/7070fc491832dfc9fbe0d26de690d09900bbc943/core/src/main/cpp/main/src/jni/yahfa.cpp#L161-L162

Maybe try to add the corresponding lib search path to it. I cannot check it now. You can try that out. And if it works, PR is welcome.

**Comment by yujincheng08** [comment]
Hint: 
you can load your try to load that lib with:
1. Under the main application's classloader
1. Under an InMemoryDexClassloader with your own dex loaded (mimic how hooker class is generated)

If it is the case, the second scenario won't work. (Remember, the above two test at once) At that time, try to copy the libsearchpath from the main application's classloader to the InMemoryDexClassloaer and see if it works. If works, you can submit a PR where the correct libsearchpath is appended to that classloader.

**Comment by etmatrix** [comment]
I solved without changes in LSPosed. In hook loadLibrary I set a new hook on loadLibrary and works.
- set hook on loadLibrary, after load is done with reflection I set hook on app
- load library xposed detector, which clear all hooks, this action leave LSPosed in a corrupt state, I don't understand how solve it and I don't know how to explain it
- when there is the second loadlibrary from app, the hook is invoked but is in a strange state, something is missing.

I tried also to unhook before load library but doesn't work.
When I set a new hook on loadlibrary in hook on loadLibrary, LSPosed come back to work.
I know is not elegant solution. I'm working on test app with native hook but is another story.
I will try with a third library, but I believe it's works.

```
      Class<?> s = XposedHelpers.findClass("java.lang.System", classLoader);
      unhook = XposedHelpers.findAndHookMethod(s, "loadLibrary", String.class, new XC_MethodReplacement() {
          @Override
          protected Object replaceHookedMethod(MethodHookParam param) throws Throwable
          {
              unhook.unhook();
              logV("Before load library " + param.args[0].toString());
              logV("Classloader " + classLoader);
              Class<?> run = XposedHelpers.findClass("java.lang.Runtime", classLoader);
              Method m2 = run.getDeclaredMethod("loadLibrary0", ClassLoader.class, String.class);
              m2.setAccessible(true);
              m2.invoke(Runtime.getRuntime(), classLoader, param.args[0].toString());
              logV("Loaded");
      
              hookTest(classLoader);
              return null;
          }
      });

    private void hookTest(ClassLoader classLoader)
    {
        Class<?> b = XposedHelpers.findClass("et.nessuno.xposeddetector.Main", classLoader);
        if(b!=null)
        {
            logV("Try Hook after load");
            XC_MethodHook.Unhook un1 = XposedHelpers.findAndHookMethod(b, "getXposedStat", new XC_MethodReplacement() {
                @Override
                protected Object replaceHookedMethod(MethodHookParam param) throws Throwable
                {
                    return 0;
                }
            });

            XC_MethodHook.Unhook un = XposedHelpers.findAndHookMethod(b, "onPause", new XC_MethodHook() {
                @Override
                protected void beforeHookedMethod(MethodHookParam param) throws Throwable
                {
                    logV("Hook method onPause after load library");
                }
            });
            logV("HookL " + un.toString());
        }
        Class<?> s = XposedHelpers.findClass("java.lang.System", classLoader);
        unhook2 = XposedHelpers.findAndHookMethod(s, "loadLibrary", String.class, new XC_MethodReplacement() {
            @Override
            protected Object replaceHookedMethod(MethodHookParam param) throws Throwable
            {
                unhook2.unhook();
                logV("Before load library2 " + param.args[0].toString());
                logV("Classloader " + classLoader);
                Class<?> run = XposedHelpers.findClass("java.lang.Runtime", classLoader);
                Method m2 = run.getDeclaredMethod("loadLibrary0", ClassLoader.class, String.class);
                m2.setAccessible(true);
                m2.invoke(Runtime.getRuntime(), classLoader, param.args[0].toString());
                logV("Loaded2");
                return null;
            }
        });
    }
```
