### ISSUE TITLE
LOS 18.1 onePlus-One boot-loop, can you help me please?!

### ISSUE THREAD

**Issue by hamedsbt** [LSPosed/LSPosed#480]
I've installed 
01- Lineage-18.1-20210409-microG-bacon.zip
02- magisk Magisk-22.1(22100)
03- Riru-v25.3.4.r399.84f7084(399)
04- Riru_-_LSPosed-v1.3.5(5551)

After reboot, I stuck on boot-loop :(

I have only Riru & LSposed as activated modules.

/proc/kmsg file: (/proc/last_kmsg is not exist)
[kmsg.txt](https://github.com/LSPosed/LSPosed/files/6296854/kmsg.txt)

I'm interest send any other log file that may help. 

Thank you!

**Comment by yujincheng08** [comment]
we need bootlog

**Comment by hamedsbt** [comment]
Can you help me to achieve the bootlog file please?!

**Comment by yujincheng08** [comment]
PC: https://t.me/hzrtools/2
Magisk module: https://t.me/hzrtools/10

**Comment by hamedsbt** [comment]
I installed it successfully, and let once-boot-loop but log does not contain helpful content :(
[boot-1970-05-05-22-13-35.log](https://github.com/LSPosed/LSPosed/files/6297685/boot-1970-05-05-22-13-35.log)

**Comment by yujincheng08** [comment]
use pc to grab log instead.

**Comment by hamedsbt** [comment]
I boot device as normal state and provide root permission to shell so "su.bat" work properly, but the problem is the boot-loop occur before adb accessibility so the logcat.bat wait for device infinity. any other solution?!

**Comment by yujincheng08** [comment]
No :(
It's your business to grab log and I cannot help you anymore.

You can reopen this issue when you get valid bootlog.

**Comment by hamedsbt** [comment]
I found a solution: https://www.didgeridoohan.com/magisk/MagiskHelp#:~:text=If%20your%20Magisk%20log%20is,what%20happens%20(see%20above).

and now I grab the boot.log file: 

[bootlog_LSposed_bootloop.zip](https://github.com/LSPosed/LSPosed/files/6298624/bootlog_LSposed_bootloop.zip)

I hope you find a solution to resolve boot-loop soon because my phone is not usable right now :(
Thank you.

**Comment by yujincheng08** [comment]
The log isn't full. LSPosed is not even loaded on that log.

**Comment by yujincheng08** [comment]
Hmm, interestingly, I noticed something like this:
```
05-06 00:41:30.560     0     0 W init    : wait for '/dev/.magisk_unblock' timed out and took 40004ms
05-06 00:41:30.560     0     0 I init    : Command 'wait /dev/.magisk_unblock 40' action=post-fs-data (/system/etc/init/hw/init.rc:1098) took 40004ms and failed: wait_for_file() failed
05-06 00:41:30.561     0     0 I init    : Service 'oXpcvcBWKwc6' (pid 289) exited with status 0 oneshot service took 40.005001 seconds in background
05-06 00:41:30.561     0     0 I init    : Sending signal 9 to service 'oXpcvcBWKwc6' (pid 289) process group...
```

It seems that Magisk is stuck! Please report to Magisk instead.

**Comment by hamedsbt** [comment]
have this line more info?!
![image](https://user-images.githubusercontent.com/7298328/114438384-ee6a8200-9bdc-11eb-9027-64827fbdd228.png)

**Comment by yujincheng08** [comment]
The problem is:
Magisk try to load `system.prop` from LSPosed and it gets stuck! 
So there's nothing to do with LSPosed. This is magisk's bug.

**Comment by hamedsbt** [comment]
magisk load successfully with riru-core, when I install (or enable LSposed) the phone stuck on boot-loop, should I report on this to magisk?!

**Comment by yujincheng08** [comment]
Report to Magisk. We cannot fix it.

**Comment by yujincheng08** [comment]
FYI, removing `/data/adb/modules/riru_lsposed/sepolicy.rule` might do some magisc. You can have a try.

**Comment by hamedsbt** [comment]
remove ```/data/adb/modules/riru_lsposed/sepolicy.rule``` help to resolve the bootloop but LSpsed app say: **"Partially activated, SEPolicy is not loaded properly"** 
I'm using xprivacy for safe-privacy so does "Partially activated, SEPolicy is not loaded properly" is reliable?!

**Comment by yujincheng08** [comment]
Of course, it won't work. 

Sepolicy is a necessary part of LSPosed. I am just showing you that Magisk has a bug loading sepolicy.

**Comment by yujincheng08** [comment]
Use this Magisk to grab log. I added some log to it.
[app-release.zip](https://github.com/LSPosed/LSPosed/files/6299305/app-release.zip)

**Comment by hamedsbt** [comment]
I don't know what is happening! after install magisk (app-release.zip) and uninstal/reinstall LSposed module, boot-loop resolved but Lsposed app shown blue banner & snackbar with message: LSposed is not installed on activated.

log files:
[bootlog.log](https://github.com/LSPosed/LSPosed/files/6299427/bootlog.log)
[magisk.log](https://github.com/LSPosed/LSPosed/files/6299431/magisk.log)

Thank you.

**Comment by yujincheng08** [comment]
What? it should not work and should encounter bootloop...

BTW, it's not working because `rirud_java: Riru is not loaded.`

**Comment by yujincheng08** [comment]
Do you have telegram account? It's hard to talk in github.

**Comment by hamedsbt** [comment]
yes, but how to send you privately ?!

**Comment by hamedsbt** [comment]
I'll delete this comment
@neelbas

**Comment by yujincheng08** [comment]
Enter lsposed group and say you are the one with magisk bug. I know magisk's dev and they will also help.
