### ISSUE TITLE
[BUG] Boot doesn't complete sometimes

### ISSUE THREAD

**Issue by nipunnarang** [LSPosed/LSPosed#495]
**Device:** OnePlus 5 (cheeseburger)

**ROM:** OxygenOS 9.0.11 (Android Pie)

**Magisk:** Latest Canary Debug (Version f49966d8, Version Code 22103)

**Riru:** Latest Riru (Version 25.4.2.r415.f42e9c3, Version Code 415)

**LSPosed:** Latest CI Debug (Version 1.3.5, Version Code 5562)

**Issue:** After installation and rebooting, sometimes the boot process just doesn't complete. There are times when:
-  After the boot animation is done, the system gets stuck at a black screen (doesn't restart itself, i.e. no bootloop).
- After the boot animation is done, the system gets stuck at "Phone is starting...".
- After the boot animation is done, the system freezes at the lockscreen and I can't enter my pin to unlock.
- _System boots completely fine and LSPosed is loaded (but most of the times it is one of the above three issues)_

**Boot Logs** _(caught using Log Catcher v22):_ [Direct Download Link](https://androidessentials.shadowstep.workers.dev/0:/Miscellaneous/Boot%20Logs.zip)

**Comment by yujincheng08** [comment]
disable magisk hide and grab log again because it prevents tombstoned from generating useful log.

**Comment by nipunnarang** [comment]
> disable magisk hide and grab log again because it prevents tombstoned from generating useful log.

Here you go: [boot-magisk_hide_disabled.log](https://androidessentials.shadowstep.workers.dev/0:/Miscellaneous/boot-magisk_hide_disabled.log)

**Comment by yujincheng08** [comment]
```
04-18 13:26:03.068   711  1369 D LSPosedService: Skipped com.android.systemui/10031
04-18 13:26:03.068  2742  2742 D LSPosed : skipped com.android.systemui
```
lsposed does nothing to systemui but it crashed
disable all the other modules except for riru and lsposed

**Comment by nipunnarang** [comment]
Thanks, the issue seemed to originate from a custom kernel I was using. As per our discussion on Telegram, I switched back to the stock kernel and everything seems to be working fine!
