### ISSUE TITLE
Launch intent for some apps is null, resulting in them not being displayed inside LSPosed Manager

### ISSUE THREAD

**Issue by srccrow** [LSPosed/LSPosed#499]
LSPosed Manager is unable to visualize this specific app: https://play.google.com/store/apps/details?id=it.tenebraeabisso.tenebra2  syntax, nor hooking it of course, ~~I suspect the final number there is the problem.~~

Other similar cases: https://play.google.com/store/apps/details?id=it.tenebraeabisso.tenebra1

**it.tenebraeabisso.tenebra1**

Request reproduction of the not handling exception inside LSPosed manager from your side.

**Tested:** On two systems using both Android 11 and 10

**Comment by srccrow** [comment]
Looks like problem with comparator unable to handle syntax like this: x.ya.y, so basically anything like **com.catdog.cat** where the element is repeated won't be displayed because comparator cannot compare it?

**Comment by srccrow** [comment]
You say invalid, but you don't provide an argumentation nor have you tested what I spent two hours to report here with tests last night.

**Comment by yujincheng08** [comment]
because u dont follow the issue template...

**Comment by srccrow** [comment]
Template can be bypassed, if I show you a method to detect LSPosed.

**Comment by yujincheng08** [comment]
> Your issue will be close if you don't follow this template
:)
