### ISSUE TITLE
[BUG] No longer pass SafetyNet using Magisk Canary fb8000b5 (22104)

### ISSUE THREAD

**Issue by drewcu** [LSPosed/LSPosed#501]
**什么情况/What happened?**

With recent SafetyNet API changes, Magisk had to up update to get the SafetyNet checking to work properly again. But with all these new Google changes and the latest Canary fb8000b5 (22104), SafetyNet fails attestation for basicIntegrity and ctsProfile when LSposed 1.3.5 is installed.

When I disable LSposed in Magisk and reboot, I am again able to pass SafetyNet using the latest Magisk Canary. Thus, LSposed seems like it needs to be changed in some way to get around the SafetyNet detection.

**Magisk模块列表/Magisk Module List**

- Riru v25.4.2
- LSposed v1.3.5
- Debloater v17.3.3
- Joypixels v6.5

**版本信息/Versions**

Android: 9 (latest for my LG V30)

Magisk: fb8000b5 (22104) (latest)

Riru: 25.4.2 (latest)

LSPosed: 1.3.5 (latest)

**相关日志/Related Logs**

Please tell me how to get a log for SafetyNet and I'll do it. This issue is not specific to my device so I doubt my log will tell you anything different than if you use the same Magisk to check SafetyNet with same latest versions of Riru/LSposed.

Thanks!

**Comment by JasonKhew96** [comment]
~~works fine for me (evalType: Basic), and~~ stop asking about safety net, thank you
