### ISSUE TITLE
[FR] Hushsms (send different types of sms)

### ISSUE THREAD

**Issue by theoneandonly-vector** [LSPosed/LSPosed#503]
Somehow Taichi was able to support it.
I have no idea what we need to make it work..

**Comment by tehcneko** [comment]
You need to install original Xposed Installer

**Comment by theoneandonly-vector** [comment]
Does this mean it will never be compatible with LSPosed?

**Comment by yujincheng08** [comment]
https://github.com/Xposed-Modules-Repo/com.silentservices.hushsms
