### ISSUE TITLE
[BUG] Crash when calling std::unordered_set::count

### ISSUE THREAD

**Issue by sekaiacg** [LSPosed/LSPosed#51]
**什么情况/What happened?**
lsp manager crash

**版本信息/Versions**

Android:11

Magisk:21.4

Riru:23.4

LSPosed:v0.5.2.0-5105

**相关日志/Related Logs**
[LSPosed_Verbose_20210203_002121.log](https://github.com/LSPosed/LSPosed/files/5912711/LSPosed_Verbose_20210203_002121.log)

**Comment by yujincheng08** [comment]
需要 debug 版日志

**Comment by sekaiacg** [comment]
@yujincheng08 
[LSPosed_Verbose_20210203_005350.log](https://github.com/LSPosed/LSPosed/files/5912868/LSPosed_Verbose_20210203_005350.log)

**Comment by yujincheng08** [comment]
[LSPosed-v0.5.2.0-233-debug.zip](https://github.com/LSPosed/LSPosed/files/5913011/LSPosed-v0.5.2.0-233-debug.zip)
试试这个

**Comment by kotori2** [comment]
> 无论如何，请使用英文标题

> Your issue will be close if you don't follow this template

请尊重issue template

**Comment by sekaiacg** [comment]
> > 无论如何，请使用英文标题
> 
> > Your issue will be close if you don't follow this template
> 
> 请尊重issue template

好的，下次一定按要求填写

**Comment by sekaiacg** [comment]
> [LSPosed-v0.5.2.0-233-debug.zip](https://github.com/LSPosed/LSPosed/files/5913011/LSPosed-v0.5.2.0-233-debug.zip)
> 试试这个

这个版本没问题了，应该解决了
[LSPosed_Verbose_20210203_020018.log](https://github.com/LSPosed/LSPosed/files/5913331/LSPosed_Verbose_20210203_020018.log)

**Comment by yujincheng08** [comment]
稳
