### ISSUE TITLE
app can't not open

### ISSUE THREAD

**Issue by aabababb** [LSPosed/LSPosed#514]
app can't not open

China Telecom
Everbright Bank

before use edsposed,they are only open slowly.

**版本信息/Versions**

Android:10

Magisk:22.1

Riru:25.4.2

LSPosed:1.3.5

**Comment by yujincheng08** [comment]
![Screenshot_2021-04-26-15-31-52-872_org.lsposed.manager.jpg](https://user-images.githubusercontent.com/5022927/116045346-8ddf4880-a6a4-11eb-8020-dbc9e8c82400.jpg)
