### ISSUE TITLE
[BUG]Google Recorder Crash

### ISSUE THREAD

**Issue by njtony11** [LSPosed/LSPosed#519]
**版本信息/Versions**

Android:11

Magisk:22.1

Riru:25.4.1

LSPosed:1.3.5

**相关日志/Related Logs**

04-27 09:28:09.887 14485 14485 I LSPosed : Using api level 30
04-27 09:28:09.887 14485 14485 I LSPosed : Start to install Riru hook
04-27 09:28:09.887 14485 14485 I LSPosed : Riru hooks installed
04-27 09:28:09.887 14485 14485 I LSPosed : ART hooks installed
04-27 09:28:09.908 14485 14485 I LSPosed : Loading modules for com.google.android.apps.recorder
04-27 09:28:09.909 14485 14485 I LSPosed-Bridge: Loading modules from /data/app/~~hcjuv6HzQbZOKMB3ug7WSw==/eu.faircode.xlua-vNspZ6pSQTrjHf23gYkdcA==/base.apk
04-27 09:28:09.965 14485 14485 I LSPosed-Bridge:   Loading class eu.faircode.xlua.XLua
04-27 09:28:10.033 14485 14485 I LSPosed-Bridge: XLua.Xposed Loaded com.google.android.apps.recorder:10332
--------- beginning of crash
04-27 09:28:10.081 14485 14485 F libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7c4ef219b0 in tid 14485 (d.apps.recorder), pid 14485 (d.apps.recorder)
04-27 09:28:10.133 14516 14516 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-27 09:28:10.133 14516 14516 F DEBUG   : Build fingerprint: 'google/bonito/bonito:11/RQ2A.210405.005/7181113:user/release-keys'
04-27 09:28:10.133 14516 14516 F DEBUG   : Revision: 'MP1.0'
04-27 09:28:10.133 14516 14516 F DEBUG   : ABI: 'arm64'
04-27 09:28:10.135 14516 14516 F DEBUG   : Timestamp: 2021-04-27 09:28:10+0800
04-27 09:28:10.135 14516 14516 F DEBUG   : pid: 14485, tid: 14485, name: d.apps.recorder  >>> com.google.android.apps.recorder <<<
04-27 09:28:10.135 14516 14516 F DEBUG   : uid: 10332
04-27 09:28:10.135 14516 14516 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x7c4ef219b0
04-27 09:28:10.135 14516 14516 F DEBUG   :     x0  0000007fc57c0280  x1  0000007b9ee1a3b0  x2  0000000000000000  x3  0000000000000010
04-27 09:28:10.135 14516 14516 F DEBUG   :     x4  0000000000000000  x5  0000007b3e662ab6  x6  0000000000000000  x7  00000006f60b8915
04-27 09:28:10.135 14516 14516 F DEBUG   :     x8  d50496d3f1115190  x9  d50496d3f1115190  x10 0000000052ab266a  x11 000000009ee1a3e0
04-27 09:28:10.135 14516 14516 F DEBUG   :     x12 000000003b1736d7  x13 0000007b3e87349c  x14 0000007b3e8734fc  x15 0000000000000000
04-27 09:28:10.135 14516 14516 F DEBUG   :     x16 0000007ad7574bc0  x17 0000007dd1593b8c  x18 0000007dd4890000  x19 00000000ffffb2ed
04-27 09:28:10.135 14516 14516 F DEBUG   :     x20 0000000019f0fc2d  x21 0000007c4ef219b0  x22 0000007bfee19b90  x23 0000000000049478
04-27 09:28:10.135 14516 14516 F DEBUG   :     x24 00000000ffffaeee  x25 000000000002fd94  x26 0000000000049478  x27 000000002775266e
04-27 09:28:10.135 14516 14516 F DEBUG   :     x28 00000000b2f35978  x29 000000000002004d
04-27 09:28:10.135 14516 14516 F DEBUG   :     lr  0000007ad755ad80  sp  0000007fc57c0340  pc  0000007ad755ad80  pst 0000000060000000
04-27 09:28:10.136 14516 14516 F DEBUG   : backtrace:
04-27 09:28:10.136 14516 14516 F DEBUG   :       #00 pc 0000000000045d80  /data/app/~~y-5_nQFJbdDuEm2KZBneVA==/com.google.android.apps.recorder-gsD5qaaIJEHIb6GOFBfQhw==/lib/arm64/libEO9TIcft0T.so

只有取消勾选才能正常工作。

**Comment by yujincheng08** [comment]
google 的东西都有反 hook 机制的。比如谷歌相机也不能 hook。没事针对一个录音机和相机干嘛。。。

**Comment by njtony11** [comment]
其实不是针对相机和录音机，主要是如果其他app也采用这样的机制的话，那么都无法hook了

**Comment by yujincheng08** [comment]
是啊。比如中国移动这些 app 你是不能勾的。

但是防检测从来不是框架能做的事，因为检测方法千千万万防不胜防，所以只能靠模块 *针对性* 防止检测。
