### ISSUE TITLE
lsposed manager does not let you choose Google play store in modules for being intercepted

### ISSUE THREAD

**Issue by thomasdmuc** [LSPosed/LSPosed#532]
in lsposed manager built 02.05 you cannot tic Google play store  in any module for being intercepted. example in module HideMyApplist I would like to enable Google play store in order to stop seeing certain apps. using lsposed manager built from 22nd of apri it is perfectly fine. in case Google play store was already selected, it is visible. so something was introduced to break functionality.

**Comment by eebssk1** [comment]
I can not understand you well.If you can not find google play store in hook target list,then make sure you not tick the system app in filter menu.

**Comment by thomasdmuc** [comment]
ask somebody who understandd English...in older version it is working. so I understand what I am doing

**Comment by thomasdmuc** [comment]
6小时前评论
 在内置的内置管理器02.05中，您无法在任何模块中找到Google Play存储区以进行拦截。 我想启用Google Play商店以停止查看某些应用程序。 使用从4月22日开始构建的lsposed管理器，这完全可以。 如果已经选择了Google Play商店，则可以看到该商店。 因此引入了一些破坏功能的方法

**Comment by JasonKhew96** [comment]
@thomasdmuc works fine for me, not a bug
<img src="https://user-images.githubusercontent.com/29531167/116814655-98aa4980-ab8c-11eb-9e1f-2a972e66d15f.jpg" width="384" /><img src="https://user-images.githubusercontent.com/29531167/116814659-9ea02a80-ab8c-11eb-9883-862120a9aa14.jpg" width="384" /><img src="https://user-images.githubusercontent.com/29531167/116814662-a069ee00-ab8c-11eb-9282-f2f8accd6d68.jpg" width="384" />
