### ISSUE TITLE
[FR] Wildcards in module scope

### ISSUE THREAD

**Issue by gjf** [LSPosed/LSPosed#539]
According to [Module Scope](https://github.com/LSPosed/LSPosed/wiki/Module-Scope) the module should define the apps those should be enabled by default for this very module.

But some modules should be applied for all apps by default. How to define it in Module Scope? Are wildcards available?

If not, maybe it should be available in future revisions? Otherwise LSPosed will never handle some modules those EDXposed does.

**Comment by vvb2060** [comment]
#9
