### ISSUE TITLE
[BUG] Bootloop as soon as a module is enabled.

### ISSUE THREAD

**Issue by Rtizer-9** [LSPosed/LSPosed#546]
Phone goes into bootloop if a single module is enabled in LSPosed, it boots fine if no module is enabled with LSPosed shown as active.

**什么情况/What happened?**

 Bootloop

**Xposed模块列表/Xposed Module List**
 XPrivacyLua

**Magisk模块列表/Magisk Module List**
Riru, Riru-LSPosed, Log Catcher & Magisk Manager for Recovery Mode

**版本信息/Versions**

Android:11

Magisk:22104 (canary)

Riru:25.4.4

LSPosed:1.3.5(5601) Debug

**相关日志/Related Logs**

[boot.log](https://github.com/LSPosed/LSPosed/files/6441788/boot.log)

**Comment by yujincheng08** [comment]
From your log, I think it's caused by xlua. Try to report to xlua instead.

I seems that xlua hooks `ApplicationPackageManager.queryIntentActivities` and returns a `null` and crashes your system.

**Comment by Rtizer-9** [comment]
Confirmed. Everything works fine with latest releases after several reboots if xprivacylua is not enabled.
