### ISSUE TITLE
[BUG] IndexOutOfBoundsException

### ISSUE THREAD

**Issue by HiColinn** [LSPosed/LSPosed#550]
**什么情况/What happened?**
The LSPosed Manager will crash when I sellect the "system app"

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android:

Magisk:

Riru:

LSPosed:

**相关日志/Related Logs**
Build version: v1.3.5 (5551) 
Current date: 2021-05-08 15:45:23 
Device: Xiaomi MI 8 
 
SDK: 29 
 
Stack trace:  
java.lang.IndexOutOfBoundsException: Inconsistency detected. Invalid view holder adapter positione{9d96af2 position=131 id=2101830649, oldPos=-1, pLpos:-1 no parent} rikka.widget.borderview.BorderRecyclerView{cbe6b79 VFED..... ........ 0,0-1080,1832 #7f090174 app:id/0_resource_name_obfuscated}, adapter:tl@a68d0be, layout:org.lsposed.manager.util.LinearLayoutManagerFix@f2ef51f, context:org.lsposed.manager.ui.activity.AppListActivity@b387796
 at androidx.recyclerview.widget.RecyclerView$s.k(:33)
 at androidx.recyclerview.widget.m.c(:2)
 at androidx.recyclerview.widget.m.b(:3)
 at androidx.recyclerview.widget.m.run(:6)
 at android.os.Handler.handleCallback(Handler.java:883)
 at android.os.Handler.dispatchMessage(Handler.java:100)
 at android.os.Looper.loop(Looper.java:224)
 at android.app.ActivityThread.main(ActivityThread.java:7562)
 at java.lang.reflect.Method.invoke(Native

![微信图片_20210508155535](https://user-images.githubusercontent.com/65964332/117531610-db00da00-b015-11eb-89fe-a3904762b9ee.jpg)

**Comment by yujincheng08** [comment]
> > Fixed by [b3ee9ad](https://github.com/LSPosed/LSPosed/commit/b3ee9ad61a0df847e807219d7e751ad12f4ae313)
> 
> How to get the latest version app?

Download from CI https://github.com/LSPosed/LSPosed/actions/workflows/manager.yml

**Comment by HiColinn** [comment]
> > > Fixed by [b3ee9ad](https://github.com/LSPosed/LSPosed/commit/b3ee9ad61a0df847e807219d7e751ad12f4ae313)
> > 
> > 
> > How to get the latest version app?
> 
> Download from CI https://github.com/LSPosed/LSPosed/actions/workflows/manager.yml

谢谢!Thanks!
