### ISSUE TITLE
[BUG] I don't know if it's a BUG,I need open the xp module app every time before I use the be hooked app.

### ISSUE THREAD

**Issue by HiColinn** [LSPosed/LSPosed#552]
**什么情况/What happened?**
  I am a new user ,I found a "bug" maybe .For example, I use "应用变量" (a xposed module app) to hook wifi name for some app(like QQ),when i open first time open the QQ after reboot the phone,the wifi name is be booked.bug if  i reopen the QQ,the wifi name will change to the real name.I need restart the "应用变量" before i open QQ,the wifi name then be hooked.
  I don't know if this is a BUG?

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android:
XiaoMi 8 (Android11)
Magisk:
22.0
Riru:
25.4.4.r426.05efc94
LSPosed:
1.3.5
**相关日志/Related Logs**
none

**Comment by yujincheng08** [comment]
Because this module cannot load its configuration before the first unlock.
