### ISSUE TITLE
[TODO] LSPosed Native APIs (JNI hook etc)

### ISSUE THREAD

**Issue by yujincheng08** [LSPosed/LSPosed#6]
- Add a new API for modules to hook JNI (my thought is a function that receives `long handle`, `long hook_fun`, `String soName`)

**Comment by kotori2** [comment]
Maybe a set of new APIs like Riru but mainly targeting inline hooks.

**Comment by yujincheng08** [comment]
`android::OpenNativeLibrary` should be a good hook point for implementation.
Only this function returns, call modules for further reaction.

But, apps can do their own `dlopen` in JNI code, so we might have to consider this (hook `__loader_dlopen` for P+)

**Comment by kotori2** [comment]
We don't have to hook loader_dlopen. If we only needs to dlsym we could
only hook notmal dlopen in libc.

LoveSy <notifications@github.com> 于 2021年1月31日周日 00:14写道：

**Comment by yujincheng08** [comment]
I heard from @canyie that `dlopen` is not hook-able in Android P+

**Comment by canyie** [comment]
Hook `dlopen` will cause some problems in Android P+, see https://bbs.pediy.com/thread-257022.htm
> apps can do their own dlopen in JNI code

I think we should let module handle it by itself.

**Comment by kotori2** [comment]
My design here. Gonna implement it if everyone agrees. 
https://github.com/LSPosed/LSPosed/blob/cd417e532b7bbb7c5061b8d81bd0e011d6d522a8/core/src/main/cpp/main/src/native_api.cpp#L8-L17

**Comment by yujincheng08** [comment]
Good for an initialization. However, I have some questions:
1. What if the so name conflicts with the target app's so name?
2. Is it necessary to hook `__loader_dlopen`? I mean, `android::OpenNativeLibrary` is a better point. It has more info like classloader to avoid the above conflict and can give a JNIEnv for initialization (don't know if it is necessary).
3. Can some callback at least be made? Once the target app loads a so, the module can at least be called for it. (can also be implemented by `OpenNativeLibrary`)

**Comment by kotori2** [comment]
> What if the so name conflicts with the target app's so name?

Why are developers giving them such idiot name...
> Is it necessary to hook __loader_dlopen? I mean, android::OpenNativeLibrary is a better point. It has more info like classloader to avoid the above conflict and can give a JNIEnv for initialization (don't know if it is necessary).

It could be a little bit too late if someone want to hook something in `.init_array`
> Can some callback at least be made?

Oh true I forgot this.

**Comment by yujincheng08** [comment]
> Why are developers giving them such an idiot name...
But it could happen...

> if someone wants to hook something in .init_array
IDK, is there `.init_array` between `__loader_dlopen` and ``android::OpenNativeLibrary`?

**Comment by canyie** [comment]
I don't think we have to hook `dlopen` or `__loader_dlopen`, and dobby cannot hook __loader_dlopen on Android 10. 
jmpews/Dobby#106

**Comment by yujincheng08** [comment]
True. `android::OpenNativeLibrary` is enough imo.

**Comment by kotori2** [comment]
Mostly completed @ 8c4cf3842618052d950234237bbc932a2dc5cca9

**Comment by kotori2** [comment]
closed via #108
