### ISSUE TITLE
[BUG] Cannot install v1.4.0 on Magisk v23

### ISSUE THREAD

**Issue by rypz79** [LSPosed/LSPosed#637]
**什么情况/What happened?**
![Screenshot_20210519-235906](https://user-images.githubusercontent.com/28814757/118884248-e2ba5b80-b8fe-11eb-8514-1fbe236e3d2e.png)

**Xposed模块列表/Xposed Module List**
- GravityBox [R] 11.0.2
- Lucky Patcher 9.5.8
- NFG Multi Crack 1.41

**Magisk模块列表/Magisk Module List**
- riru-core
- AML
- busybox-ndk
- Fdroid-Classic-Priv
- safetynet-fix 
- ViPER4AndroidFX
- magisk-frida

**版本信息/Versions**

Android:11

Magisk:23

Riru:25.4.4

LSPosed:1.3.5

**相关日志/Related Logs**
[magisk_install_log_2021-05-19T23_30_59Z.log](https://github.com/LSPosed/LSPosed/files/6511526/magisk_install_log_2021-05-19T23_30_59Z.log)
[magisk_log_2021-05-19T23_31_24Z.log](https://github.com/LSPosed/LSPosed/files/6511529/magisk_log_2021-05-19T23_31_24Z.log)
[LSPosed_Modules_20210520_000050.log](https://github.com/LSPosed/LSPosed/files/6511549/LSPosed_Modules_20210520_000050.log)

**Comment by yujincheng08** [comment]
could u send `/data/adb/magisk/util_functions.sh`?

**Comment by rypz79** [comment]
> could u send `/data/adb/magisk/util_functions.sh`?
[util_functions.sh.txt](https://github.com/LSPosed/LSPosed/files/6511937/util_functions.sh.txt)

**Comment by yujincheng08** [comment]
You should update it to the one from Magisk apk
