### ISSUE TITLE
[BUG] partially activated - emulator

### ISSUE THREAD

**Issue by fusionneur** [LSPosed/LSPosed#648]
Android Q x86 on emulator (android studio latest canary)

LSPOSED shows as Partially activated (warning: sepolicy is not loaded properly, modules that hook system framework will not work)

Riru: v25.4.4.r426.05efc94 (426)

Magisk: 23

API version
93

Framework version
v1.4.0 (5666)

Manager version
v1.4.0 (5666)

System version
10 (API 29)

Device
Unknown Android Android SDK built for x86 

System ABI
x86

**Comment by aviraxp** [comment]
It is a Magisk issue. Please ensure you are using Magisk v23.

**Comment by canyie** [comment]
Report to Magisk's developer please

**Comment by yujincheng08** [comment]
you might have cleaned /cache partition

**Comment by yujincheng08** [comment]
my bad. you are using emulator, which is expected because magiskinit is not used in Android Q emulator. Try at least Android R, where magiskinit works.

**Comment by fusionneur** [comment]
> my bad. you are using emulator, which is expected because magiskinit doesnt work in Android Q emulator. Try at least Android R, where magiskinit works. Or if u hv to use Android Q, try sepolicy live patch.

where do i get the sepolicy live patch? thank you!

**Comment by yujincheng08** [comment]
> > my bad. you are using emulator, which is expected because magiskinit doesnt work in Android Q emulator. Try at least Android R, where magiskinit works. Or if u hv to use Android Q, try sepolicy live patch.
> 
> where do i get the sepolicy live patch? thank you!

Add to `post-fs-data.sh`:
```
magiskpolicy --live allow system_server system_server process execmem
```
