### ISSUE TITLE
[BUG] APP cannot open after the update from 5551 to 5711

### ISSUE THREAD

**Issue by Gokou-Ruri** [LSPosed/LSPosed#678]
**什么情况/What happened?**
从 1.3.5.5551 直接升到 1.4.2.5711 后，QQ、bilibili无法运行。
QQ版本为 Play 8.2.11 以及国内 8.7.8，具体情况为点击图标后无任何界面弹出。
bilibili版本为 Play 3.0.2，具体情况为点击后有 Splash 但立刻就会闪退。
退回 1.3.5.5551 以后，以上两款APP均可恢复正常运行，再次更新到 1.4.2.5711 后问题依旧。

**Xposed模块列表/Xposed Module List**
1ceboxTurner
哔哩漫游
对话框取消
核心破解
假装分享Xposed
禁用 FLAG_SECURE
米窗
上帝模式
微聚
微X模块
文本自定义
验证码提取器(Xposed)
应用变量
知了
指纹支付
Fuck Coolapk
lataclysm
release
Thanox Pro
WIFI 模拟器
Xposed Edge Pro

**Magisk模块列表/Magisk Module List**
AudioHQ - Advanced Audio Controller
Busybox for Android NDK
Move Certificates
QTI memory optimization
Riru
Riru - Clipboard Whitelist
Riru - Enhanced mode for Storage Isolation
Riru - IFW Enhance
Riru - InternalBrowserRedirect
Riru - Location Report Enabler
Riru - LSPosed
Riru - Sui

**版本信息/Versions**
API 版本
93

框架版本
v1.3.5 (5551)

管理器版本
v1.3.5 (5551)

系统版本
11 (API 30)

设备
Xiaomi Redmi K20 Pro 

系统架构
arm64-v8a

**相关日志/Related Logs**
[May 25, 2021 14:52:52.log.tar.gz](https://github.com/LSPosed/LSPosed/files/6538541/May.25.2021.14.52.52.log.tar.gz)

**Comment by yujincheng08** [comment]
更新 ibr

**Comment by Gokou-Ruri** [comment]
> 更新 ibr

谢谢，请问是指 Riru - InternalBrowserRedirect 吗？我目前是11.7，应该是最新版了。

**Comment by tehcneko** [comment]
卸载 ibr
