### ISSUE TITLE
[BUG] latest module 1.4.2 delay (Tasker) others apps startup too much after device boot

### ISSUE THREAD

**Issue by ale82to** [LSPosed/LSPosed#680]
first of all thanks to the developer to the great lsposed. 
today I ve updated to version 1.4.2 and I immediately noticed a super annoying bug:
Tasker takes about 2 minutes before starting at every boot (event :device boot),i downgraded to version 1.4.0 and everything went normal as soon as phone boot Tasker start executing my tasks.
I m on lineage OS 18.1 mi 10 Lite 5g.
can someone confirm the issue?

**Comment by yujincheng08** [comment]
we need log.
