### ISSUE TITLE
[BUG] lsposed causes big delay to autostart of others apps on boot 

### ISSUE THREAD

**Issue by ale82to** [LSPosed/LSPosed#684]
as title say all, lsposed causes big delay to autostart of others apps (like Tasker) on boot, event boot received (about 2 minutes). 
the bug is always reproducible, downgrading to lsposed 1.4.0 solves the issue so must be a bug. 
as required I'm attaching the verbose log 
LSPosed Log
--------- beginning of information
Manufacturer: Xiaomi
Brand: Xiaomi
Device: monet
Product: monet
Model: Mi 10 Lite 5G
Fingerprint: Xiaomi/dipper/dipper:8.1.0/OPM1.171019.011/V9.5.5.0.OEAMIFA:user/relè,] ase-keys
ROM description: dipper-user 8.1.0 OPM1.171019.011 V9.5.5.0.OEAMIFA release-keys
Architecture: arm64-v8a
Android build: RQ1A.210205.004
Android version: 11
Android sdk: 30
LSPosed version: v1.4.2 (5711)
Riru version: v25.4.4.r426.05efc94 (426)
Riru api: 25
Magisk: 23.0 (23000)
--------- beginning of main
--------- beginning of system
12-24 06:43:23.176   732   732 I LSPosedService: starting server...
12-24 06:43:23.176   732   732 I LSPosedService: version v1.4.2 (v1.4.2)
12-24 06:43:23.179   732   732 I LSPosedService: service package is not started, wait 1s.
05-26 19:22:49.586   760   760 I LSPosed : onModuleLoaded: welcome to LSPosed!
05-26 19:22:49.586   760   760 I LSPosed : onModuleLoaded: version v1.4.2 (5711)
05-26 19:22:49.587   760   760 I LSPosed : Loaded /dev/eoSM1b/.magisk/modules/riru_lsposed/framework/lspd.dex with size 254660
05-26 19:22:49.693   761   761 I LSPosed : onModuleLoaded: welcome to LSPosed!
05-26 19:22:49.693   761   761 I LSPosed : onModuleLoaded: version v1.4.2 (5711)
05-26 19:22:49.694   761   761 I LSPosed : Loaded /dev/eoSM1b/.magisk/modules/riru_lsposed/framework/lspd.dex with size 254660
05-26 19:22:50.173   732   732 I LSPosedService: service package is not started, wait 1s.
05-26 19:22:51.115  1188  1188 I LSPosed : Start to install inline hooks
05-26 19:22:51.115  1188  1188 I LSPosed : Start to install Riru hook
05-26 19:22:51.115  1188  1188 I LSPosed : Riru hooks installed
05-26 19:22:51.116  1188  1188 I LSPosed : ART hooks installed
05-26 19:22:51.152  1188  1188 I LSPosed : Loading modules for system_server
05-26 19:22:51.154  1188  1188 I LSPosed-Bridge: Loading module com.jozein.xedgepro from /data/app/~~DZhJOM-TkmBDS_x7lObA8A==/com.jozein.xedgepro--Vd7ateL4weAzRiALgWVdQ==/base.apk
05-26 19:22:51.174   732   732 I LSPosedService: service package is not started, wait 1s.
05-26 19:22:51.176  1188  1188 I LSPosed-Bridge:   Loading class com.jozein.xedgepro.xposed.HookMain
05-26 19:22:51.572  1188  1188 I LSPosed-Bridge: [XEdgePro] Xposed-edge-pro-v6.0.6. 
05-26 19:22:51.572  1188  1188 I LSPosed-Bridge:     Xiaomi-Mi 10 Lite 5G, monet, Android 11, SDK 30, ROM: RQ1A.210205.004(RQ1A.210205.004), SELinux enforced.
05-26 19:22:52.179   732   732 I LSPosedService: service package is not started, wait 1s.
05-26 19:22:52.406  1188  1188 I LSPosed-Bridge: [XEdgePro] System hooked.
05-26 19:22:53.180   732   732 I LSPosedService: service package is not started, wait 1s.
05-26 19:22:54.181   732   732 I LSPosedService: service package is not started, wait 1s.
05-26 19:22:55.182   732   732 I LSPosedService: service package is not started, wait 1s.
05-26 19:22:56.185  1188  1241 I LSPosedService: binder received
05-26 19:22:56.185   732   732 I LSPosedService: sent service to bridge
05-26 19:23:01.594  2412  2412 I LSPosed : Start to install inline hooks
05-26 19:23:01.594  2412  2412 I LSPosed : Start to install Riru hook
05-26 19:23:01.594  2412  2412 I LSPosed : Riru hooks installed
05-26 19:23:01.595  2412  2412 I LSPosed : ART hooks installed
05-26 19:23:01.621  2412  2412 I LSPosed : Loading modules for com.android.systemui
05-26 19:23:01.622  2412  2412 I LSPosed-Bridge: Loading module com.ceco.r.gravitybox from /data/app/~~eS6QqjpnZMnLWZwroqZnzA==/com.ceco.r.gravitybox-XUIa6BqVYY5UAgJqqckweA==/base.apk
05-26 19:23:01.793  2412  2412 I LSPosed-Bridge:   Loading class com.ceco.r.gravitybox.GravityBox
05-26 19:23:02.149  2656  2656 I LSPosed : Start to install inline hooks
05-26 19:23:02.150  2656  2656 I LSPosed : Start to install Riru hook
05-26 19:23:02.150  2656  2656 I LSPosed : Riru hooks installed
05-26 19:23:02.155  2656  2656 I LSPosed : ART hooks installed
05-26 19:23:02.207  2656  2656 I LSPosed : Loading modules for com.android.systemui
05-26 19:23:02.207  2656  2656 I LSPosed-Bridge: Loading module com.ceco.r.gravitybox from /data/app/~~eS6QqjpnZMnLWZwroqZnzA==/com.ceco.r.gravitybox-XUIa6BqVYY5UAgJqqckweA==/base.apk
05-26 19:23:02.370  2656  2656 I LSPosed-Bridge:   Loading class com.ceco.r.gravitybox.GravityBox
05-26 19:23:02.437  1188  1747 I LSPosed-Bridge: [XEdgePro] System booted.
05-26 19:23:04.004  1188  1747 I LSPosed-Bridge: [XEdgePro] Boot completed
05-26 19:13:27.327  1188  1747 I LSPosed-Bridge: [XEdgePro] Perform boot completed.
05-26 19:13:27.387  3798  3798 I LSPosed : Start to install inline hooks
05-26 19:13:27.387  3798  3798 I LSPosed : Start to install Riru hook
05-26 19:13:27.387  3798  3798 I LSPosed : Riru hooks installed
05-26 19:13:27.387  3798  3798 I LSPosed : ART hooks installed
05-26 19:13:27.406  3798  3798 I LSPosed : Loading modules for com.jozein.xedgepro
05-26 19:13:27.406  3798  3798 I LSPosed-Bridge: Loading module com.jozein.xedgepro from /data/app/~~DZhJOM-TkmBDS_x7lObA8A==/com.jozein.xedgepro--Vd7ateL4weAzRiALgWVdQ==/base.apk
05-26 19:13:27.419  3798  3798 I LSPosed-Bridge:   Loading class com.jozein.xedgepro.xposed.HookMain
05-26 19:13:33.235  3847  3847 I LSPosed : Start to install inline hooks
05-26 19:13:33.235  3847  3847 I LSPosed : Start to install Riru hook
05-26 19:13:33.235  3847  3847 I LSPosed : Riru hooks installed
05-26 19:13:33.235  3847  3847 I LSPosed : ART hooks installed
05-26 19:13:33.250  3847  3847 I LSPosed : Loading modules for org.lsposed.manager
05-26 19:13:33.298  3847  3847 I LSPosed : Found LSPosed Manager, hooking it
05-26 19:13:33.299  3847  3847 I LSPosed : Hooked LSPosed Manager
05-26 19:13:55.737  6287  6287 I LSPosed : Start to install inline hooks
05-26 19:13:55.737  6287  6287 I LSPosed : Start to install Riru hook
05-26 19:13:55.737  6287  6287 I LSPosed : Riru hooks installed
05-26 19:13:55.737  6287  6287 I LSPosed : ART hooks installed
05-26 19:13:55.752  6287  6287 I LSPosed : Loading modules for com.android.systemui
05-26 19:13:55.752  6287  6287 I LSPosed-Bridge: Loading module com.ceco.r.gravitybox from /data/app/~~eS6QqjpnZMnLWZwroqZnzA==/com.ceco.r.gravitybox-XUIa6BqVYY5UAgJqqckweA==/base.apk
05-26 19:13:55.807  6287  6287 I LSPosed-Bridge:   Loading class com.ceco.r.gravitybox.GravityBox
05-26 19:14:08.811  7018  7018 I LSPosed : Start to install inline hooks
05-26 19:14:08.811  7018  7018 I LSPosed : Start to install Riru hook
05-26 19:14:08.811  7018  7018 I LSPosed : Riru hooks installed
05-26 19:14:08.811  7018  7018 I LSPosed : ART hooks installed
05-26 19:14:08.826  7018  7018 I LSPosed : Loading modules for org.lsposed.manager
05-26 19:14:08.872  7018  7018 I LSPosed : Found LSPosed Manager, hooking it
05-26 19:14:08.873  7018  7018 I LSPosed : Hooked LSPosed Manager

**Comment by yujincheng08** [comment]
You have to grab the boot log with debug build of LSPosed. Otherwise, this log does not prove your situation.

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed/actions

**Comment by ale82to** [comment]
thank you very much for explaining until latest release I ve never had a single problem, so I didn't bother to read Readme.md,today I will provide debug log

**Comment by yujincheng08** [comment]
Anyway, try this ver:
[LSPosed-v1.4.2-5721-release.zip](https://github.com/LSPosed/LSPosed/files/6548832/LSPosed-v1.4.2-5721-release.zip)

**Comment by ale82to** [comment]
thank you very much!! that build solved the issue!
