### ISSUE TITLE
[BUG] LSPosed not detected/working since v1.4.0, downgrade to 1.3.5 is working 

### ISSUE THREAD

**Issue by clavelm** [LSPosed/LSPosed#691]
**什么情况/What happened?**
Since v1.4.0, LSPosed is not detected by companion app (updated to the current LSPosed magisk module installed). Module can't be loaded.
I tried with v1.4.0, 1.4.1, and 1.4.2. Each time setting the companion app to the correct version.
Downgrading to 1.3.5 (with the companion app 1.3.4 embedded in the 1.3.5 release zip), LSPosed is detected and working. 

**Xposed模块列表/Xposed Module List**
App Locale 2 2.0.7

**Magisk模块列表/Magisk Module List**
Riru 25.4.4.r426.05efc94
Riru - Enhanced mode for Storage Isolation 24.1.2
Riru - Clipboard Whitelist v10
Riru - LSPosed (various versions, only one/tests)
App Systemizer (Terminal Emulator) 17.3.1
ARCore/Playground Patcher 2.1
Busybox for Android NDK 1.33.1
Debloater (Terminal Emulator) 17.3.3

**版本信息/Versions**

Android:
Oxygen OS 11.2.5.5.LE15BA (Android 11)

Magisk:
f822ca5b (23001)

Riru:
25.4.4.r426.05efc94

LSPosed:
1.4.0, 1.4.1, 1.4.2

**相关日志/Related Logs**
1.3.5
LSPosed Log
--------- beginning of information
Manufacturer: OnePlus
Brand: OnePlus
Device: OnePlus9Pro
Product: OnePlus9Pro
Model: LE2123
Fingerprint: OnePlus/OnePlus9Pro_EEA/OnePlus9Pro:11/RKQ1.201105.002/2105011307:user/release-keys
ROM description: OnePlus9Pro-user 11   release-keys
Architecture: arm64-v8a
Android build: RKQ1.201105.002
Android version: 11
Android sdk: 30
LSPosed version: v1.3.5 (5551)
Riru version: v25.4.4.r426.05efc94 (426)
Riru api: 25
Magisk: f822ca5b (23001)

1.4.0
Updating from storage from 1.3.5.
Companion app is still 1.3.4.
LSPosed is displayed as not installed or not active so no LSPosed logs.
Same with companion app updated to 1.4.0

1.4.1
Updating from 1.4.0 from storage. 
Here is the Magisk update log:
- Copying zip to temp directory
- Installing LSPosed-v1.4.1-5698-release.zip
- Current boot slot: _a
- Device is system-as-root
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
***********************
 Riru - LSPosed 
 by LSPosed Developers 
***********************
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
*******************
 Powered by Magisk 
*******************
- LSPosed version v1.4.1 (5698)
- Extracting verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
   creating: META-INF/com/google/android/
  inflating: META-INF/com/google/android/update-binary.sha256
  inflating: META-INF/com/google/android/update-binary
  inflating: META-INF/com/google/android/updater-script.sha256
  inflating: META-INF/com/google/android/updater-script
- Verified META-INF/com/google/android/update-binary
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: customize.sh.sha256
- Verified customize.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: verify.sh.sha256
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: util_functions.sh
- Verified verify.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: util_functions.sh.sha256
- Verified util_functions.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: riru.sh
- Android SDK version: 30
- Magisk version: 23001
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: riru.sh.sha256
- Verified riru.sh
- Load /dev/zmtY/.magisk/modules/riru-core/util_functions.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop
- Riru: v25.4.4.r426.05efc94 (API 25)
- Installing from Magisk app
- Device platform: arm64
- Extracting module files
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: module.prop.sha256
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: system.prop
- Verified module.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: system.prop.sha256
- Verified system.prop
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: sepolicy.rule
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: sepolicy.rule.sha256
- Verified sepolicy.rule
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: post-fs-data.sh.sha256
- Verified post-fs-data.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: service.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: service.sh.sha256
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: uninstall.sh
- Verified service.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: uninstall.sh.sha256
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: framework/lspd.dex
- Verified uninstall.sh
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: framework/lspd.dex.sha256
- Verified framework/lspd.dex
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: manager.apk
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: manager.apk.sha256
- Verified manager.apk
- Extracting arm libraries
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: liblspd.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: liblspd.so.sha256
- Verified lib/armeabi-v7a/liblspd.so
- Extracting arm64 libraries
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: liblspd.so
Archive:  /data/user/0/com.topjohnwu.magisk/cache/flash/install.zip
  inflating: liblspd.so.sha256
- Verified lib/arm64-v8a/liblspd.so
- Creating configuration directories
  - Use previous path lspd_5Fw5hCLJ4INDSLk3
- Welcome to LSPosed!
- Installing custom sepolicy rules
rmdir: '/data/adb/modules_update/riru_lsposed': Directory not empty
- Done
![Screenshot_20210529-084822](https://user-images.githubusercontent.com/717388/120061014-5f65dc00-c05b-11eb-9328-0e9a45526e7e.jpg)
Manager/Companion apk is checked but not installed. 

1.4.2
Updating to 1.4.2, same thing, manager not updated, and LSPosed not detected.

**Comment by clavelm** [comment]
Downgrading to 1.3.5 from 1.4.2, the manager version 1.4.2 is replaced by 1.3.4 embedded in 1.3.5.

**Comment by yujincheng08** [comment]
Magisk installation log is useless. We need the verbose log.
Edit or create `/data/adb/lspd/config/verbose_log` with content `1`, and reboot. The log will be generated to `/data/adb/lspd/log/all.log`.

**Comment by clavelm** [comment]
[all.log](https://github.com/LSPosed/LSPosed/files/6564177/all.log)
Here after updating module from 1.3.5 to 1.4.2.

**Comment by yujincheng08** [comment]
Seems that this log is not enough for ur situatioin. Try using this tool https://t.me/hzrtools/10

**Comment by clavelm** [comment]
[boot-2021-05-29-09-32-38.log](https://github.com/LSPosed/LSPosed/files/6564202/boot-2021-05-29-09-32-38.log)
The notice about being on a debug kernel is interesting (but not related to the pending problem). Could it be explained by having rooted the phone with magisk?

**Comment by yujincheng08** [comment]
Cloud you plz install the debug build and try to grab the log again?
https://github.com/LSPosed/LSPosed/runs/2649314579

**Comment by clavelm** [comment]
[bootlog-2021-05-29-09-57-49.tar.gz](https://github.com/LSPosed/LSPosed/files/6564234/bootlog-2021-05-29-09-57-49.tar.gz)
[all.log.tar.gz](https://github.com/LSPosed/LSPosed/files/6564236/all.log.tar.gz)
I didn't see that Log Catcher generates a tar.gz of the logs in Download. I grab the new all.log also and compressed it.

**Comment by yujincheng08** [comment]
I may have fount the problem. Try this ver: 
[LSPosed-v1.4.2-5728-release.zip](https://github.com/LSPosed/LSPosed/files/6564241/LSPosed-v1.4.2-5728-release.zip)

**Comment by clavelm** [comment]
> I may have fount the problem. Try this ver:
> [LSPosed-v1.4.2-5728-release.zip](https://github.com/LSPosed/LSPosed/files/6564241/LSPosed-v1.4.2-5728-release.zip)

Sorry, it's not fixed. Manager was still 1.3.4 after update so I've updated it with the apk from the zip, but LSPosed is still undetected.
Here are the new logs, but as it's a release version, they may not be useful.
[bootlog-2021-05-29-10-05-30.tar.gz](https://github.com/LSPosed/LSPosed/files/6564259/bootlog-2021-05-29-10-05-30.tar.gz)
[all.log.tar.gz](https://github.com/LSPosed/LSPosed/files/6564263/all.log.tar.gz)

**Comment by yujincheng08** [comment]
How about disabling all magisk modules except for lsposed and riru?

**Comment by clavelm** [comment]
> How about disabling all magisk modules except for lsposed and riru?
Done and reboot, same thing
I'm sorry, I'm going to be busy so I will not be able to answer quickly / at all.

**Comment by yujincheng08** [comment]
Maybe you can try to withdraw the root permission of `com.lsdroid.cerberus`. I suspect it killed our process.

**Comment by clavelm** [comment]
> Maybe you can try to withdraw the root permission of `com.lsdroid.cerberus`. I suspect it killed our process.

Yes, that did it after reboot. I'm going to re-enable the other modules but keep cerberus without root.

**Comment by yujincheng08** [comment]
oh. So it's not our bug.

**Comment by clavelm** [comment]
Thanks for the fast work, I'm going to see with Cerberus.
Could you give me technical elements to give to them, please?

**Comment by yujincheng08** [comment]
LSPosed will launch a service process as soon as Magisk loaded it. This process is an orphan process with SELinux context the same as Magisk. And this process got killed by Cerberus. Previously we will try to relaunch our process but we stop doing so from 1.4.0.
Actually, I don't know how it works so I don't know why Cerberus kill it according to what strategy. Maybe it's trying to kill orphan processes but I think it should not kill processes whose SELinux context are the same as Magisk.

**Comment by yujincheng08** [comment]
Hmm, seems that Cerberus should be compatible with our latest but unreleased 1.4.3. You could download it from https://t.me/LSPosedArchives and have a try. We will release 1.4.3 soon.

**Comment by clavelm** [comment]
> Hmm, seems that Cerberus should be compatible with our latest but unreleased 1.4.3. You could download it from https://t.me/LSPosedArchives and have a try. We will release 1.4.3 soon.

Yes, that version is not killed by cerberus. Thanks.
