### ISSUE TITLE
[BUG] QQ cannot be found in the scope

### ISSUE THREAD

**Issue by Squaregentleman** [LSPosed/LSPosed#694]
**什么情况/What happened?**

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android:11

Magisk:23

Riru:25.4.4

LSPosed:1.4.3

**相关日志/Related Logs**
无

![Screenshot_2021-05-30-10-47-57-922_org lsposed manager](https://user-images.githubusercontent.com/22393739/120090464-5e1ec880-c0c8-11eb-8be3-9c087db1a824.jpg)
![Screenshot_2021-05-30-10-48-02-397_com miui home](https://user-images.githubusercontent.com/22393739/120090468-62e37c80-c0c8-11eb-80fd-bf4c734f0770.jpg)

**Comment by hshx123** [comment]
+1

**Comment by hshx123** [comment]
换了个play版，就好了
