### ISSUE TITLE
[BUG] After using LSPosed, there is no file under /data/dalvik-cache/arm64.

### ISSUE THREAD

**Issue by JaeTee211** [LSPosed/LSPosed#70]
Android:10 on MIUI

Magisk:20.4

Riru:23.4

LSPosed:v0.5.3.0-5109-r

When LSPosed is installed, after flashing kernel to my device, it slows down the reboot time. And there is no file under /data/dalvik-cache/arm64. Seems LSPosed inhibits the compilation of Dalvik-cache after it hooked any of the arm64 apps.

**Comment by yujincheng08** [comment]
It only disabled inline
https://github.com/LSPosed/LSPosed/blob/fc1bf22eda9d0a2ef7cdb3a10bb14f58d607773e/core/template_override/system.prop#L3
