### ISSUE TITLE
[BUG] Some apps doesn't show up when trying to hook

### ISSUE THREAD

**Issue by Cyberavater** [LSPosed/LSPosed#701]
Reproduce steps:
Select any module and try to hook this app, https://play.google.com/store/apps/details?id=com.quok.blobRunner

Note: I've enabled all filters and it's still not showing up. LSP, Riru Magisk everything is the latest.

**Comment by yujincheng08** [comment]
![image](https://user-images.githubusercontent.com/5022927/120105339-19a83100-c18b-11eb-8667-0d2485724902.png)

**Comment by aviraxp** [comment]
@Cyberavater You should disable the filter

**Comment by Cyberavater** [comment]
> @Cyberavater You should disable the filter

Thanks, I thought selected means included.
