### ISSUE TITLE
Filter ticks cause no change in the app list

### ISSUE THREAD

**Issue by Shiberal** [LSPosed/LSPosed#728]
Video of the problem:  https://mirror.shiberal.tk/files/screen-20210603-151958.mp4
Also they seems inverted at the first launch: all selected no apps.

**Comment by Shiberal** [comment]
Already fixed in some version?

**Comment by yujincheng08** [comment]
u didnt follow the template

**Comment by Shiberal** [comment]
Thanks for the stupid tag, Where can I find the template so I can redo the issue correctly?

**Comment by yujincheng08** [comment]
https://github.com/LSPosed/LSPosed/issues/new/choose
