### ISSUE TITLE
[BUG] APP: the ticks to select the apps doesn't work properly

### ISSUE THREAD

**Issue by Shiberal** [LSPosed/LSPosed#729]
**什么情况/What happened?**
The filter tick selectors seems to not work properly, when tick and untick the app list seems to update get but it doesn't change.
I also put a video in the previous issue tagged stupid if the description wasn't enough.

**Xposed模块列表/Xposed Module List**
A12 extensions

**Magisk模块列表/Magisk Module List**
Riru, RiruLSposed, PUI for A12, A12 extensions

**版本信息/Versions**

Android: 12

Magisk: 23.0

Riru: 25.4.4

LSPosed: 1.4.4

**相关日志/Related Logs**
I have no logs cause it seems to not generate errors.

**Comment by yujincheng08** [comment]
That video does not prove anything because u didn't list all the apps before and after the change of filters..

**Comment by Shiberal** [comment]
> That video does not prove anything because u didn't list all the apps before and after the change of filters.

Do I have to do it again? If you need it, I'll do it

**Comment by yujincheng08** [comment]
But anyway, the list does change.

before filter system app:
![image](https://user-images.githubusercontent.com/5022927/120657485-1d9fc000-c4b7-11eb-8126-1eae063150c5.png)
after filter system app:
![image](https://user-images.githubusercontent.com/5022927/120657514-255f6480-c4b7-11eb-94d1-d7be6e45ffcc.png)
