### ISSUE TITLE
[FR] Advanced Reboot Menu

### ISSUE THREAD

**Issue by entr0pia** [LSPosed/LSPosed#738]
**Detail**:
|Advanced Reboot|
|---|
|Reboot|
|Restart Zygote|
|Restart SystemUI|
|Reboot to Recovery|
|etc.|

**Comment by tehcneko** [comment]
magisk 有

**Comment by entr0pia** [comment]
> magisk 有

但它还缺少软重启, 重启SystemUI

**Comment by yujincheng08** [comment]
magisk 有软重启。重启 systemui 你直接强制停止它不就行。
