### ISSUE TITLE
[BUG] Unable to read /data folder causing status remain uninstalled

### ISSUE THREAD

**Issue by Darkatse** [LSPosed/LSPosed#74]
**What happened?**  

In some ROMs that have been upgraded to Android 11 (such as the latest version of MIUI), the reading of the data folder by the application is disabled according to Google's instructions, so the status detection in Lsposed keeps showing as not installed, and it is not possible to enable any module or read logs

**版本信息/Versions**

Android:11

Magisk:21.4

Riru:23.4

LSPosed:0.5.3.0

**Related Logs**
/data/user_de/0/io.github.lsposed.manager/log/error.log: open failed: ENOENT (No such file or directory)

/data/user_de/0/io.github.lsposed.manager/log/all.log: open failed: ENOENT (No such file or directory)

**Comment by yujincheng08** [comment]
LSPosed does not storage conf there. I works on Android R.

**Comment by Darkatse** [comment]
When I try to ignore the check to enable the module, lsposed prompts "Failed to save scope list". This error occurs after upgrading to MIUI 21.2.1 beta, while before that everything was fine. One important update in this version is to disable access to the data folder, so I think this may be the reason.

I'm just suggesting a possible cause, please close this issue if it is not caused by this.

**Comment by yujincheng08** [comment]
this is because lsposed magisk module is not working, and then manager cannot know the true config path. You should check why lsposed magisk module does not work (cannot tell the true config path).

**Comment by aviraxp** [comment]
Can you install debug version and catch a full log when booting with another tool, like log catcher?

**Comment by Darkatse** [comment]
I installed the canary build version of lsposed manager and the status detection worked properly, the previous version was the latest version in telegram channel.

It seems that my previous thinking was wrong, I will close this issue
