### ISSUE TITLE
[FR] classify modules plz

### ISSUE THREAD

**Issue by Hickoo** [LSPosed/LSPosed#756]
Hello, I hope to add the grouping function to the module list,  it is difficult to classify them when you installed too many modules

**Comment by yujincheng08** [comment]
How

**Comment by Hickoo** [comment]
> How

Add a category or tag just above the module list

**Comment by yujincheng08** [comment]
what tag?

**Comment by yujincheng08** [comment]
I mean, what principle could be used to categorize modules?
