### ISSUE TITLE
[FR] Allow module to be enabled for all apps

### ISSUE THREAD

**Issue by xKippi** [LSPosed/LSPosed#760]
I have some (legacy) XPosed modules which I want to be enabled for all apps on the system. It would be very nice to have a option to enable the module for every app.

Currently, I have to select every app, which is very time consuming. Also, when a new app is installed I have to manually activate the module for the app.

**Comment by yujincheng08** [comment]
But you just have to do it once.

**Comment by DecentM** [comment]
Not if you install multiple modules. Also if you install a new app, you have to do this for every module.
Not only is this feature important, but there needs to be a way to auto apply modules to newly installed apps. I think XPrivacy does this well, it's whole selection logic could just be lifted, as the flow is more of less the same from a user's perspective

**Comment by ardugitter** [comment]
This is an open task apparently:

https://github.com/LSPosed/LSPosed/issues/9
