### ISSUE TITLE
[FR] Using Xiaomi's own app double-opening function, how to make the module effective?

### ISSUE THREAD

**Issue by etjson** [LSPosed/LSPosed#793]
**Detail**:
As the question is, according to the tutorial of the net, even the LSP manager should be double-opened to work, but it will show that LSP is not installed.

**Comment by etjson** [comment]
@aviraxp What's the situation? You didn't even reply to me and closed it?

**Comment by aviraxp** [comment]
https://github.com/LSPosed/LSPosed/releases/tag/v1.4.0
