### ISSUE TITLE
Where does the name on the module list come from and why does it have my name?

### ISSUE THREAD

**Issue by zhengyi0533** [LSPosed/LSPosed#801]
![IMG_20210703_161827](https://user-images.githubusercontent.com/71653166/124348971-75992600-dc1f-11eb-9c7c-82eb671d436f.jpg)
Where does the name on the module list come from and why does it have my name? Thanks! I can't find it from my phone.

**Comment by vvb2060** [comment]
https://github.com/LSPosed/LSPosed/releases/tag/v1.4.3

**Comment by zhengyi0533** [comment]
My phone doesn't have multi-user settings. I just found my name by browsing /data/system/users/0.xml. This seems to be the file produced by lsposed. Can you tell me where this information comes from? I remember I didn't put my name in my phone. Thank you very much！
