### ISSUE TITLE
When using Xposed Edge Pro can not be determined to enable the Xposed framework

### ISSUE THREAD

**Issue by wanghaifengmayun** [LSPosed/LSPosed#815]
**什么情况/What happened?**

**Xposed模块列表/Xposed Module List**

**Magisk模块列表/Magisk Module List**

**版本信息/Versions**

Android:

Magisk:

Riru:

LSPosed:

**相关日志/Related Logs**

**Comment by wanghaifengmayun** [comment]
？？？？？？？？

**Comment by wanghaifengmayun** [comment]
I really can't use edge when starting the LSP, why do you close the tag for me?

**Comment by canyie** [comment]
u did not provide any info, no one can solve your problem
