### ISSUE TITLE
[BUG] LSPosed not detected/working since v1.4.6, downgrade to 1.4.5 is working

### ISSUE THREAD

**Issue by herivanov** [LSPosed/LSPosed#816]
什么情况/What happened?
Since v1.4.6, LSPosed is not detected by companion app (updated to the current LSPosed magisk module installed). Module can't be loaded.
I tried with v1.4.6 and 1.4.7.
Downgrading to 1.4.5 (with the companion app 1.4.5 embedded in the 1.4.5 release zip), LSPosed is detected and working.

Magisk模块列表/Magisk Module List
Busybox for android ndk
Exsdcard access enabler
Fake encryption
Liboemcrypto disabler
Magisk hide props config
Patches for android (Lucky patcher module) 
Riru 25.4.4.r426.05efc94
Riru LSPosed 1.4.7 (5803)
Systemless hosts
Systemless_TZData
WifiBonding (qcom)

版本信息/Versions
Android: 9
Magisk: f822ca5b (23001) (21)
Riru: 25.4.4.r426.05efc94
LSPosed: 1.4.7 (5803)

相关日志/Related Logs
[all.log](https://github.com/LSPosed/LSPosed/files/6831567/all.log)
[bootlog-2021-07-16-17-18-49.tar.gz](https://github.com/LSPosed/LSPosed/files/6831569/bootlog-2021-07-16-17-18-49.tar.gz)

**Comment by herivanov** [comment]
Thank you Dear! Very fast and efficient! Everything works! Thank you from the bottom of my heart! All the best and prosperity!

**Comment by etmatrix** [comment]
very strange the previous patch 21f9aedce6e495ac798c78b0113d30a461270537 was working for me on android 11, maybe dlopen is not working on android 9.

**Comment by yujincheng08** [comment]
> very strange the previous patch [21f9aed](https://github.com/LSPosed/LSPosed/commit/21f9aedce6e495ac798c78b0113d30a461270537) was working for me on android 11, maybe dlopen is not working on android 9.

This is because some weird Android P ROMs strip linker's symbols.

**Comment by etmatrix** [comment]
So on these "weird Android P ROMs" native hooks can't be working.
It might be useful to show a notice in the manager when this happens. I will try to submit a PR for this.

**Comment by yujincheng08** [comment]
no need.
