### ISSUE TITLE
Make  LSPosed remembers hooked apps by intsalled modules [FR] 

### ISSUE THREAD

**Issue by Marvinoo** [LSPosed/LSPosed#821]
**Detail**:

![Screenshot_20210718-165153913](https://user-images.githubusercontent.com/45720537/126072800-232fd8bb-4d27-406b-a656-94bc7eab07de.jpg)

  Hello can you please make  LSPosed remembers hooked apps, _for example_ : WhatsApp by installed modules, _for example:_  App Settings Reborn
  
  Because when I uninstall _WhatsApp_ and reinstall it, LSPosed will forget that _WhatsApp_ was hooked for _App Settings Reborn_ and I'd have to go into the list of hooked apps by the module and re-check it again? 
  
  I'm sorry I know this sounds stupid because my English is not too good to describe this issue..

**Comment by vvb2060** [comment]
Expected behavior

**Comment by Marvinoo** [comment]
If you want you can make LSPosed stores the hooked apps in an inner database so they won't be forgotten after uninstall.

**Comment by yujincheng08** [comment]
But this is not good since the database cannot clean up itself for uninstalled apps and will slow down the database.

**Comment by andronoob** [comment]
After several uninstall/reinstall upgrading/downgrading attempts of the hook target app, I encountered crash-on-launch of the hook target app. However I cannot reproduce it for the second time.

Anyway, I think LSPosed should take care of app uninstall seriously.
