### ISSUE TITLE
[FR] Add Scope Type of All User App or All Installed App

### ISSUE THREAD

**Issue by runapp** [LSPosed/LSPosed#826]
I found the current scope pattern hard to run with some permission-management type modules, such as XPrivacyLua and Thanox. How do you think of it?

**Comment by etmatrix** [comment]
This FR is already requested with #723 and #760 and maybe some others, I think the reply will be always the same: "wontfix"
Is better to search before open new issue.

**Comment by vvb2060** [comment]
permission-management type modules should hook ams and pms, no need to hook all applications.
