### ISSUE TITLE
[BUG] So ugly the icon it is

### ISSUE THREAD

**Issue by xspeed1989** [LSPosed/LSPosed#890]

**Comment by yujincheng08** [comment]
Any suggestion?

**Comment by etmatrix** [comment]
There was issue #115 with a suggestion.

**Comment by yujincheng08** [comment]
> There was issue #115 with a suggestion.

It's not vector graph.

**Comment by xspeed1989** [comment]
> Any suggestion?

Honestly，I don't have any suggestion,Because I'm not an artist

**Comment by yujincheng08** [comment]
> Honestly，I don't have any suggestions. Because I'm not an artist

Neither are we. So there's nothing we can do to make the icon more elegant.

**Comment by xspeed1989** [comment]
Maybe you can ask for a better-looking icon in readme
@yujincheng08

**Comment by yujincheng08** [comment]
> Maybe you can ask for a better-looking icon in readme
> @yujincheng08

#612

BTW what icon u think is ugly? We recently updated our icon.

**Comment by xspeed1989** [comment]
No offense, I hope someone will submit a better-looking icon to you

**Comment by yujincheng08** [comment]
> BgColor & Font
> No offense, I hope someone will submit a better-looking icon to you

I mean we have recently create a new icon
![image](https://user-images.githubusercontent.com/5022927/129150912-53233236-b218-4c46-b532-146cf769a8e6.png)
Are you talking about this one?

**Comment by xspeed1989** [comment]
> > BgColor & Font
> > No offense, I hope someone will submit a better-looking icon to you
> 
> I mean we have recently create a new icon
> ![image](https://user-images.githubusercontent.com/5022927/129150912-53233236-b218-4c46-b532-146cf769a8e6.png)
> Are you talking about this one?

No,  I talk about an icon that contains LSP

**Comment by xspeed1989** [comment]
backgound & font


> Then wait for the next release...

Do you like the Pink color?

**Comment by xspeed1989** [comment]
> It's not from me.

Ok, I know.
But do you like this icon？

**Comment by yujincheng08** [comment]
Do I have any choice?

**Comment by xspeed1989** [comment]
> Do I have any choice?

Maybe, not
It looks better than the old one

Do you ask for an icon in tg group?

**Comment by yujincheng08** [comment]
Yup

**Comment by xspeed1989** [comment]
> Yup

I will try to submit an icon if my friend can make one

**Comment by yujincheng08** [comment]
Good
