### ISSUE TITLE
[TODO] API for modules to get/add activated module scope

### ISSUE THREAD

**Issue by yujincheng08** [LSPosed/LSPosed#9]
- Modules can get/add their own activated module scope and can react differently
- `XRemotePreferences`, the modern replacement of `XSharedPreferences`

go to libxposed/XposedService#1 to discuss about it

**Comment by captain-miao** [comment]
Can dynamically add/remove scope with API?

Module can activate any app with advertisement.

**Comment by yujincheng08** [comment]
Under development. Plz see binder branch and https://github.com/Xposed-Modules-Repo/XposedService

**Comment by VD171** [comment]
If "API" means "CLI", I am agree with that.
I really would love a command line way to enable/disable scopes AND modules.
Certainly, this would make me migrate totally from EdXposed to LSPosed.

**Comment by XspeedPL** [comment]
If the API will also support adding packages, I have a few questions. 
- How is it supposed to mesh with the metadata scope info? Supporting both seems pointless, in my opinion code-based scope info is better, as developers will be able to provide different package lists for the scope based on local device configuration (SDK level, Android flavor, availability of components or hardware capabilities). 
- Will the call be async to show some kind of UI (allow user to deny the operation)? In general, having a dialog screen like vanilla Android permission one would be ideal, however that would restrict where and when the call can be placed (like after boot completed event). Another idea would be to queue all requested "add" calls and process them later at the convenience of LSP, like most superuser managers.
- Where in the module code the call will be allowed? Even without the UI mentioned in the previous point, I imagine some restrictions would still apply. Putting the "add" call inside the module class constructor or even zygote init sounds like a bad day waiting to happen.

Other than that, it would be a good idea to allow not only the modules to access the scope information, but the user land activities as well. Simplest example would be to inform the user that the module won't function properly without adding another package to the scope.

**Comment by yujincheng08** [comment]
We are actually working on module API, which provides a way for modules to get information about the framework. You can try to use it after we finished it.

BTW, `lsp_xxx` is not reliable because it only used to store preferences. Once `XRemotePreference` which is a preference via IPC  is finished, this folder would be deprecated.

**Comment by yashikada** [comment]
@mywalkb thank you for your suggestion
the code developed by @etmatrix require root, this is not good for me, the code developed by @sshock is an external tool, I'd like to implement on xposed module, this API was an interesting feature, but I began to think which will not be implemented.

**Comment by ucxl** [comment]
没有搞明白作者提供的api 怎么添加删除模块的作用域，最主要是没法获取IBinder，lsp管理器是有核心框架hook赋值ibinder，如果可以用模块自己设置功能的同时自动添加作用域就好了，比如模拟定位模块，不同应用作用域不同，没法加入推荐应用，暂时只能用sqlite3写数据库，然后重启 lspd，太暴力了不好，lsp管理器会提示部分框架未hook

**Comment by noahfriedman** [comment]
I really don't understand why this is being made so complicated. what a bunch of users have repeatedly asked for is a select all/deselect all UI element so they can apply behavior to all/most applications. They don't want ab API, they don't want to have to understand scopes, they just want something simple. Why is that too much to ask?

**Comment by VD171** [comment]
We know what we are doing. THERES IS NO SENSE FOR A "SELECT ALL". A "select all" option is a waste of time. WE NEED CLI. Certainly, the CLI solves everything. If you are "selecting all", you are doing something MISTAKE.

**Comment by mywalkb** [comment]
> the CLI solves everything.

I don't think cli resolve everything. Every module should be control his scope dinamically and not statically, without root privilege.
cli require root.

**Comment by mywalkb** [comment]
@noahfriedman if you don't like LSPosed, you can fork and make your project with feature select all and automatic select new applications.
This project is free, respect the decisions of developers.

**Comment by XspeedPL** [comment]
CLI won't necessarily require root, it can be made to interact with a running service, though hiding it becomes a problem
