### ISSUE TITLE
The problem of stuck on the lock screen. . [BUG] 

### ISSUE THREAD

**Issue by book-devil** [LSPosed/LSPosed#90]
Equipment-Redmi K30S
magisk: 21.4
manager:8.0.7
Module-Version:
WIFI Bonding-1.14
Audio modification Library-v4.0
Axet;s call recorder-v1.0.1
dolby atmos rv4 ryuki mod-v2.5
Exsdcard access enabler-v3.5
log Catcher-v3.5
magiskhide props config-v5.4.0-v116
riru-v6
riru-enhanced mode storage lsolation-v23.5
riru-ifw enhance-v5
riru-location reprot enabler-v10.2
riru-sui-v11.4 r78 290cd8a
systemless hots-v1.0
I try to get the LOG log. But lsposed indicated that it could not get the logs. 
Matlog software displays circles. There is no content in the log. .
The display is bright and there is a small lock on the top. . 
Cannot perform any operations. . . 
It is not stuck in the Mi

**Comment by yujincheng08** [comment]
- first of all, you didn't follow the issue template
- second, you have installed log catcher. why can't you get log?
- third, this is most likely a module's issue, you should try to disable modules that apply to systemui
- fourth, no log, no fix.

closing

**Comment by book-devil** [comment]
I try to crawl the logs. . Wait a minute. .
