### ISSUE TITLE
Issue With latest riru lsposed 1.5.0

### ISSUE THREAD

**Issue by amitcoolcampus** [LSPosed/LSPosed#900]
Module 3c all in one toolbox is not working with the latest version.

**Comment by yujincheng08** [comment]
？

**Comment by amitcoolcampus** [comment]
Android 10, Samsung note 9, I hid a process of an banking app. That was isolated service which was unhidden by the module riru-enhanced. After flashing the latest lsposed module banking app does not open. I downgraded to 1.4.7 version and it starts working.

**Comment by Seasickil-CN** [comment]
The activation interface display needs to be updated. After updating 5880, the manager display version is inconsistent. How to solve it？

**Comment by yujincheng08** [comment]
> The activation interface display needs to be updated. After updating 5880, the manager display version is inconsistent. How to solve it？

you should have read footnote 1 from https://github.com/LSPosed/LSPosed/releases/tag/v1.5.0

**Comment by Seasickil-CN** [comment]
The problem has been solved. Thank the author
