### ISSUE TITLE
[BUG] Android 12extensions can not be work

### ISSUE THREAD

**Issue by kissunyeason** [LSPosed/LSPosed#901]
Android:12

Magisk:23.0

Riru:26.0.5r484

LSPosed:1.5.0
 The module whose working domain is system cannot be checked

![Screenshot_20210815-062126](https://user-images.githubusercontent.com/17369666/129461756-f1f34be8-934a-449d-874f-9e0159862dfb.png)

**Comment by yujincheng08** [comment]
no log.

**Comment by yujincheng08** [comment]
duplicate of #898
