### ISSUE TITLE
[BUG] Edge Sense Plus module doesn't work as in EdXposed

### ISSUE THREAD

**Issue by bengalih** [LSPosed/LSPosed#914]
**什么情况/What happened?**

ESP module on LSPosed doesn't support the long squeeze option.
This module works fine on EdXposed (i.e. Long Squeeze works)

**Xposed模块列表/Xposed Module List**
Edge Sense Plus

**Magisk模块列表/Magisk Module List**
Cross Compiled Bins
MagiskHide Props Config
Riru (26.05)
LSPosed (1.5.0)
Systemless Hosts
Universal SafetyNet Fix 1.2

**版本信息/Versions**

Android: 11 (August) RQ3A.210805.001.A1

Magisk: f822ca5b(23001)

Riru: 26.05

LSPosed:1.50

**相关日志/Related Logs**

This shows in logcat in EdXposed when triggering long press.  No similar even is shown with LSPosed:

```
08-15 15:31:53.705  2673  2673 D Xposed  : hold long enough, execute edge sense plus
08-15 15:31:53.707  2673  2673 D Xposed  : start edgesenseplus mService
08-15 15:31:54.032  1795  1795 D NotificationService: 0|eu.duong.edgesenseplus|1337|null|10407: granting content://settings/system/notification_sound
08-15 15:31:54.041  2673  2673 D InterruptionStateProvider: No bubble up: not allowed to bubble: 0|eu.duong.edgesenseplus|1337|null|10407
08-15 15:31:54.041  2673  2673 D InterruptionStateProvider: No heads up: unimportant notification: 0|eu.duong.edgesenseplus|1337|null|10407
08-15 15:31:54.034  1795  1795 D NotificationService: 0|eu.duong.edgesenseplus|1337|null|10407: granting content://settings/system/notification_sound
```

**Comment by aviraxp** [comment]
@bengalih We need detail log.
