### ISSUE TITLE
[FR] Provide LSPosed manager with the Magisk module

### ISSUE THREAD

**Issue by soumyamahunt** [LSPosed/LSPosed#92]
Right now after updating LSPosed Magisk mod we have to manually download and install the manager. Instead manager could be provided with the Magisk mod itself so that updating the mod updates manager too.

**Comment by NULL0B** [comment]
Isn't this a contradiction with play store upload?

**Comment by NULL0B** [comment]
> Isn't this a contradiction with play store upload?

What about open a magisk issue for install apk as modules or something? And bundle all in apk.

**Comment by soumyamahunt** [comment]
> Isn't this a contradiction with play store upload?

What do you mean by contradiction to play store upload?? LSPosed manager is not in play store and probably won't be allowed for violating lot of policies.

> > Isn't this a contradiction with play store upload?
> 
> What about open a magisk issue for install apk as modules or something? And bundle all in apk. @tehcneko

Magisk already supports bundling apks as mods. Viper4Android uses this, YouTube Vanced used to use this too. So it isn't a Magisk issue.

**Comment by NULL0B** [comment]
> > Isn't this a contradiction with play store upload?
> 
> What do you mean by contradiction to play store upload?? LSPosed manager is not in play store and probably won't be allowed for violating lot of policies.
> 
> > > Isn't this a contradiction with play store upload?
> > 
> > 
> > What about open a magisk issue for install apk as modules or something? And bundle all in apk. @tehcneko
> 
> Magisk already supports bundling apks as mods. Viper4Android uses this, YouTube Vanced used to use this too. So it isn't a Magisk issue.
This commit:
https://github.com/LSPosed/LSPosed/commit/0224d5bd9a3f318922059e2c1eac79a5725b44f4

I didn't know that magisk support flashing apks isn't?
I mean flash the apk as the magisk creator wants to do with Magisk in twrp. the zip is the same apk.

**Comment by yujincheng08** [comment]
Done. Please wait for the next stable release.
