### ISSUE TITLE
[FR] Provide wiki for selecting scope for older xposed mods

### ISSUE THREAD

**Issue by soumyamahunt** [LSPosed/LSPosed#93]
Some xposed mods have not seen any development lately, also some mods have been abandoned but still work with xposed. Since the new scope api probably will never be supported by these mods, may be a wiki could be provided for these mods so that users can select the scope themselves. Wiki can be either in github or could work as xda thread too.

**Comment by NULL0B** [comment]
maybe a db in repo with associated scope of each app. mantained by community

**Comment by kotori2** [comment]
Wiki is not a great option because it (seems?) unable to send PR. 
Maybe a repo like [this](https://github.com/RikkaApps/StorageRedirect-assets/tree/master/app_rule/apps) will work.

**Comment by yujincheng08** [comment]
Please refer to the new Xposed Modules Repo. With a file named `SCOPE` you can define the scope manually. (For example: https://github.com/Xposed-Modules-Repo/com.ceco.q.gravitybox/blob/main/SCOPE)
Welcome any [submission](https://github.com/Xposed-Modules-Repo/submission) to the new repo!
