### ISSUE TITLE
Android 7.0 installation card boot page, how to remove

### ISSUE THREAD

**Issue by insoxin** [LSPosed/LSPosed#933]
I saw it in the CoolSec review, just a single installation package, I do not know the restrictions on Android 8.1 ~ 12 Beta 4

Now I'm stuck on the boot page, how can I save myself ,, there is TWRP Recovery3.1 try to delete data/app/in this software reboot or not

我是在酷安评论看到的,就单一个安装包,不知道限制Android 8.1 ~ 12 Beta 4

现在卡开机页面了,怎么自救 ,,有TWRP Recovery3.1  尝试删除data/app/内这个软件重启还是不行

**Comment by yujincheng08** [comment]
只支持 Android 8.1 及以上

**Comment by insoxin** [comment]
> 只支持 Android 8.1 及以上

现在知道了啊,之前不知道,直接评论区安装的,现在卡机了,大佬有办法自求吗

**Comment by canyie** [comment]
创建 /data/adb/modules/riru_lsposed/disable

**Comment by insoxin** [comment]
@canyie 感谢大佬解决啦,

我把方法贴这里给后来人

```
http://dl-xda.xposed.info/framework/uninstaller/

这里下载卸载包

rec刷进去就行了
```

**Comment by yujincheng08** [comment]
？能不能不要误导人

**Comment by canyie** [comment]
？？？？wtf

**Comment by vvb2060** [comment]
你安装的是原版 Xposed，当然能刷原版XP的卸载包删除。
LSPosed 不能从 TWRP 刷入，不能安装在 Android7 设备，从头到尾和我们没有关系。
