### ISSUE TITLE
[BUG] LSPosed : Fail to get binder for system server

### ISSUE THREAD

**Issue by Nagisakurumi** [LSPosed/LSPosed#942]
riru loaded ,then  LSPosed : Fail to get binder for system server

**Comment by canyie** [comment]
invalid, we need your device info, system info, lsposed version and bootlog

**Comment by Nagisakurumi** [comment]
Riru v26.1.0 (26)
Android 9 (api 28, preview_api 0)
oppo device

**Comment by Nagisakurumi** [comment]
How  to install lsposed no magisk? device is root ok. and riru is installed

**Comment by Nagisakurumi** [comment]
How to compile it on windows?

**Comment by yujincheng08** [comment]
Locked because of off topic.

**Comment by canyie** [comment]
installing without magisk is not supported, please try it yourself. if you are sure LSPosed is installed correctly but still getting this error, please open a new issue with your bootlog.
