### ISSUE TITLE
[BUG]  Re! LSPosed : Fail to get binder for system server,  Help!!

### ISSUE THREAD

**Issue by Nagisakurumi** [LSPosed/LSPosed#948]
I try to learn it.
I hava an error in func "nativeForkSystemServerPost - Context::OnNativeForkSystemServerPost - Service::RequestBinderForSystemServer " . 
In service.cpp.
Code row 202.
binder = JNI_CallStaticObjectMethod(env, service_manager_class_,
                                                get_service_method_, bridgeServiceName); 
The binder is NULL

Riru 26
Android 9 api 28

why?

**Comment by canyie** [comment]
bootlog please

**Comment by Nagisakurumi** [comment]
8-19 09:54:03.655   804   812 I [BIP]   :  [BIP AGENT] 1c  0  0  0     4B:pkt_data_len
08-19 09:54:03.655   804   812 I [BIP]   :  [BIP AGENT]  7  0  4  0   2B2B:(src_mod, dest_mod)
08-19 09:54:03.655   804   812 I [BIP]   :  [BIP AGENT]  0  0  e  0   2B2B:(sap_id, msg_id)
08-19 09:54:03.655   804   812 I [BIP]   :  [BIP AGENT]  1  0  c  0 1B1B2B:(ref_count, lp_reserved, msg_len)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT]  1  0  0  0   1B1B:(sim_id, bip_channel_id)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT]  0  0  0  0     4B:bip_info pointer
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT] can write data now, FD = (5), write length = (40)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT] write full data!! total data size is (40), current write size is (40)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT] the dequeue info. : ap_seq = (3), push_time = (2280440480), pop_time = (2280441788), num_push = (5), num_pop = (4)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT] write new data, ap_seq is (4), buffer index is (4), total data size is (44)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT]  1  0  0  0     4B:pkt_type
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT]  4  0  0  0     4B:pkt_num
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT] 2c  0  0  0     4B:pkt_data_len
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT]  8  0  4  0   2B2B:(src_mod, dest_mod)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT]  0  0 19  0   2B2B:(sap_id, msg_id)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT]  1  0 1c  0 1B1B2B:(ref_count, lp_reserved, msg_len)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT]  1  0  0  0   1B1B:(sim_id, bip_channel_id)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT]  0  0  0  0     4B:bip_info pointer
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT] can write data now, FD = (5), write length = (56)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT] write full data!! total data size is (56), current write size is (56)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT] the dequeue info. : ap_seq = (4), push_time = (2280440801), pop_time = (2280442016), num_push = (5), num_pop = (5)
08-19 09:54:03.656   804   812 I [BIP]   :  [BIP AGENT] end write() now, need_to_write = (0)
08-19 09:54:03.692   424   424 W ccci_fsd(1): O: X://LD40_001, flag 0x700, ret 1
08-19 09:54:03.699   424   424 W ccci_fsd(1): O: Y://LD40_001, flag 0x700, ret 1
08-19 09:54:03.701   424   424 W ccci_fsd(1): O: X://LD40_001, flag 0x700, ret 1
08-19 09:54:03.703   424   424 W ccci_fsd(1): O: Y://LD40_001, flag 0x700, ret 1
08-19 09:54:03.704   424   424 W ccci_fsd(1): O: X://LD40_001, flag 0x700, ret 1
08-19 09:54:03.705   424   424 W ccci_fsd(1): O: Y://LD40_001, flag 0x700, ret 1
08-19 09:54:03.707   424   424 W ccci_fsd(1): O: X://LD40_001, flag 0x700, ret 1
08-19 09:54:03.708   424   424 W ccci_fsd(1): O: Y://LD40_001, flag 0x700, ret 1
08-19 09:54:03.709   424   424 W ccci_fsd(1): O: X://LD40_001, flag 0x700, ret 1
08-19 09:54:03.710   424   424 W ccci_fsd(1): O: Y://LD40_001, flag 0x700, ret 1
08-19 09:54:03.711   424   424 W ccci_fsd(1): O: X://LD40_001, flag 0x700, ret 1
08-19 09:54:03.712   424   424 W ccci_fsd(1): O: Y://LD40_001, flag 0x700, ret 1
08-19 09:54:03.713   424   424 W ccci_fsd(1): O: X://LD40_001, flag 0x700, ret 1
08-19 09:54:03.714   424   424 W ccci_fsd(1): O: Y://LD40_001, flag 0x700, ret 1
08-19 09:54:03.716   424   424 W ccci_fsd(1): O: X://LD40_001, flag 0x700, ret 1
08-19 09:54:03.716   424   424 W ccci_fsd(1): O: Y://LD40_001, flag 0x700, ret 1
08-19 09:54:03.718   424   424 W ccci_fsd(1): O: X://LD40_001, flag 0x700, ret 1
08-19 09:54:03.720   424   424 W ccci_fsd(1): O: Y://LD40_001, flag 0x700, ret 1
08-19 09:54:03.727   424   424 W ccci_fsd(1): O: X://LD40_001, flag 0x700, ret 1
08-19 09:54:03.728   424   424 W ccci_fsd(1): O: Y://LD40_001, flag 0x700, ret 1
08-19 09:54:03.817   482   561 I ServiceManager: Waiting for service package_native...
08-19 09:54:03.876   389   788 E VT HIDL : [IVT] [VT THREAD] [VT_Bind] des = volte_imsvt1 Fail to connect . retry count: 1
08-19 09:54:03.876   389   788 E VT HIDL : [IVT] [VT THREAD] [VT_Bind] des = volte_imsvt1 Success fd: 9
08-19 09:54:03.876   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_Bind] des = volte_imsvt1 initialize communication
08-19 09:54:03.876   389   788 D VT HIDL : [IVT] getInstance
08-19 09:54:03.876   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] read from IMCB
08-19 09:54:03.893   859   859 I LSPosed : Fail to get binder for system server, try again in 1s
08-19 09:54:04.039   420   803 I BufferQueueProducer: [BootAnimation#0](this:0x78bdbbd800,id:1,api:1,p:721,c:420) queueBuffer: fps=14.99 dur=1000.79 max=68.35 min=65.02
08-19 09:54:04.060   420   420 I BufferQueueProducer: [FramebufferSurface](this:0x78bda1e800,id:0,api:1,p:420,c:420) queueBuffer: fps=14.90 dur=1006.72 max=72.37 min=53.82
08-19 09:54:04.239   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wostatusget=0](13)
08-19 09:54:04.239   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wostatusget:0,0](15)
08-19 09:54:04.239   876   876 I [epdg_wo]: [WOA] Daemon & Adpt are ready.
08-19 09:54:04.239   876   876 I [epdg_wo]: [SKT] external server socket[wod_action]-fd:-1 init successfully
08-19 09:54:04.239   876   876 I [epdg_wo]: [SKT] external server socket[wod_sim]-fd:-1 init successfully
08-19 09:54:04.240   876   876 I [epdg_wo]: [SKT] external server socket[wod_ipsec]-fd:6 init successfully
08-19 09:54:04.240   876   876 I [epdg_wo]: [DMN] WI-FI OFFLOAD DAEMON started
08-19 09:54:04.240   876   876 I [epdg_wo]: [CFG] Reset settings[0] to default
08-19 09:54:04.240   876   876 I [epdg_wo]: [CFG] Reset settings[1] to default
08-19 09:54:04.240   876   990 I [epdg_wo]: [DNS] Handle DNS Cmd Loop: dns_handler 594
08-19 09:54:04.240   876   876 D [epdg_wo]: [DSC] epdg discoverer state: [NOT_INIT] -> [IS_READY]
08-19 09:54:04.240   876   876 D [epdg_wo]: [DSC] epdg discoverer state: [NOT_INIT] -> [IS_READY]
08-19 09:54:04.241   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wostatusget:1,1](15)
08-19 09:54:04.241   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wostatusget=0](13)
08-19 09:54:04.241   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wostatusget:0,1](15)
08-19 09:54:04.246   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wosbp=0,0,"",""](15)
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] Reset settings[0] to default
08-19 09:54:04.246   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wosbp:0,0](9)
08-19 09:54:04.246   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [woemset=0,"",""](15)
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] cfg0: epdg_fqdn=[***],ikev2if=[wlan0],select_info=[***],epdg_identifier=[***],retry_vector=[],
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] cfg0: ike_algo=[],
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] cfg0: esp_algo=[],
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] cfg0: ike_rekey_timer=[81000],esp_rekey_timer=[81000],rekey_margin=[32400],dpd_timer=[120],keep_timer=[20],esp_setup_time=[15],pdn_setup_time=[295],cert_used=[1],urlcert=[0],ocsp=[0],nocert=[1],skip_check_cert=[0],noid=[1],force_tsi_64=[1],force_tsi_full=[1],use_cfg_vip=[0],reauth_addr=[0],dpd_no_reply=[0],pre_post_ping=[0],log_level=[1],wdrv_keep_alive=[1],fragment=[0],mobike=[0],oos=[7],retrans_to=[2],retrans_tries=[4],retrans_base=[1],mtu=[1280],mss4_off=[68],mss6_off=[88],cust_pcscf_4=[20],cust_pcscf_6=[21],cust_imei_cp=[0],port=[10500],port_natt=[14500],cpa_nm=[0],cpa_dns4=[1],cpa_dns6=[1],no_ic=[0],no_eap=[0],ike_dscp=[0],IDi=[0],IDr=[0],leftauth=[0],eap=[0],fastreauth=[0],dns_timer=[0],dns_type=[3],dns_max_count=[254],dns_cache=[1],redirect=[0],max_redirects=[5],redirect_loop_detect=[300],detach_soft_timer=[3],detach_hard_timer=[300],
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] cfg0: fdpd_retrans_to=[1],fdpd_retrans_tries=[2],fdpd_retrans_base=[1],certreq_critical=[0],pcscf_restore=[0],liveness_check=[0],device_identity=[0],abort_mode=[0],ho_ip_disc=[0],emerg_epdg=[0],try_epdg_policy=[0],imei_format=[0],leave_standby_dpd=[0],send_del_ike_auth_ntfy_err=[0],
08-19 09:54:04.246   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [woemset:0,"",-1](15)
08-19 09:54:04.246   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wosbp=1,0,"",""](15)
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] Reset settings[1] to default
08-19 09:54:04.246   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wosbp:1,0](9)
08-19 09:54:04.246   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [woemset=1,"",""](15)
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] cfg1: epdg_fqdn=[***],ikev2if=[wlan0],select_info=[***],epdg_identifier=[***],retry_vector=[],
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] cfg1: ike_algo=[],
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] cfg1: esp_algo=[],
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] cfg1: ike_rekey_timer=[81000],esp_rekey_timer=[81000],rekey_margin=[32400],dpd_timer=[120],keep_timer=[20],esp_setup_time=[15],pdn_setup_time=[295],cert_used=[1],urlcert=[0],ocsp=[0],nocert=[1],skip_check_cert=[0],noid=[1],force_tsi_64=[1],force_tsi_full=[1],use_cfg_vip=[0],reauth_addr=[0],dpd_no_reply=[0],pre_post_ping=[0],log_level=[1],wdrv_keep_alive=[1],fragment=[0],mobike=[0],oos=[7],retrans_to=[2],retrans_tries=[4],retrans_base=[1],mtu=[1280],mss4_off=[68],mss6_off=[88],cust_pcscf_4=[20],cust_pcscf_6=[21],cust_imei_cp=[0],port=[10500],port_natt=[14500],cpa_nm=[0],cpa_dns4=[1],cpa_dns6=[1],no_ic=[0],no_eap=[0],ike_dscp=[0],IDi=[0],IDr=[0],leftauth=[0],eap=[0],fastreauth=[0],dns_timer=[0],dns_type=[3],dns_max_count=[254],dns_cache=[1],redirect=[0],max_redirects=[5],redirect_loop_detect=[300],detach_soft_timer=[3],detach_hard_timer=[300],
08-19 09:54:04.246   876   876 I [epdg_wo]: [CFG] cfg1: fdpd_retrans_to=[1],fdpd_retrans_tries=[2],fdpd_retrans_base=[1],certreq_critical=[0],pcscf_restore=[0],liveness_check=[0],device_identity=[0],abort_mode=[0],ho_ip_disc=[0],emerg_epdg=[0],try_epdg_policy=[0],imei_format=[0],leave_standby_dpd=[0],send_del_ike_auth_ntfy_err=[0],
08-19 09:54:04.246   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [woemset:1,"",-1](15)
08-19 09:54:04.247   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wosim=0,"","","",""](19)
08-19 09:54:04.247   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wosim:0,0](9)
08-19 09:54:04.247   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wosim=1,"","","",""](19)
08-19 09:54:04.247   876   876 I [epdg_wo]: [WOA] wo_msg_sensitive_print: [wosim:1,0](9)
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] read from IMCB done
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] write to VTS (status = 0)
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] write to VTS (efGroup = -1648180880)
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] write to VTS (type)
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] write to VTS (len)
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] write to VTS (buffer)
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] read from IMCB
08-19 09:54:04.255   472   785 I VT      : [SRV] [VT THREAD] [VT_HIDL_Thread] msg_type : 101505
08-19 09:54:04.255   472   785 I VT      : [SRV] [VT THREAD] [VT_HIDL_Thread] recv_length : 4
08-19 09:54:04.255   472   785 I VT      : [SRV] [VT THREAD] [VT_HIDL_Thread] outBuffer
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] read from IMCB done
08-19 09:54:04.255   472   785 I VT      : [VT] [DISPATCHER] VTMsgDispatcher dispatchMessage
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] write to VTS (status = 0)
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] write to VTS (efGroup = -1648180880)
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] write to VTS (type)
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] write to VTS (len)
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] write to VTS (buffer)
08-19 09:54:04.255   472   785 I VT      : [SRV] [VT THREAD] [VT_HIDL_Thread] msg_type : 101505
08-19 09:54:04.255   389   788 I VT HIDL : [IVT] [VT THREAD] [VT_IMCB_Thread] read from IMCB
08-19 09:54:04.255   472   783 I VT      : [VT] [PRI HDLR] VTPriMsgHdlr onMessageReceived
08-19 09:54:04.255   472   785 I VT      : [SRV] [VT THREAD] [VT_HIDL_Thread] recv_length : 4
08-19 09:54:04.255   472   783 I VT      : [VT] [PRI HDLR] VTPriMsgHdlr dispatch normal message
08-19 09:54:04.255   472   785 I VT      : [SRV] [VT THREAD] [VT_HIDL_Thread] outBuffer
08-19 09:54:04.255   472   785 I VT      : [VT] [DISPATCHER] VTMsgDispatcher dispatchMessage
08-19 09:54:04.255   472   783 I VT      : [VT] [PRI HDLR] VTPriMsgHdlr onMessageReceived
08-19 09:54:04.255   472   784 I VT      : [VT] [HDLR] VTMsgHdlr onMessageReceived
08-19 09:54:04.255   472   783 I VT      : [VT] [PRI HDLR] VTPriMsgHdlr dispatch normal message
08-19 09:54:04.255   472   784 I VT      : [VT] [HDLR] VTMsgHdlr handle normal message
08-19 09:54:04.255   472   784 W VT      : [SRV] [OPERATION][ID=0] vt_callback (MSG_ID_WRAP_IMSVT_IMCB_GET_CAP_IND)
08-19 09:54:04.255   472   784 W VT      : [SRV] [OPERATION][ID=0] vt_callback (MSG_ID_WRAP_IMSVT_IMCB_GET_CAP_IND) opid = 8
08-19 09:54:04.255   472   784 I VT      : [SRV] [MA NOTIFY] Get camera capability (id = 0) (arg1 = 0, arg2 = 0, arg3 = 0)
08-19 09:54:04.255   472   784 I VT      : [SRV] [MA NOTIFY]                   (obj1 = , obj2 = )
08-19 09:54:04.255   472   784 I VT      : [VTS] gVTSClient == NULL
08-19 09:54:04.532   418   418 I wmt_launcher: (persist.vendor.connsys.fwlog.status) is not supported
08-19 09:54:04.653   420   420 I SurfaceFlinger: [Built-in Screen (type:0)] fps:15.087334,dur:1060.49,max:72.72,min:53.04
08-19 09:54:04.668   492   492 W MTK_FG  : fd < 0, init first!
08-19 09:54:04.668   492   492 E MTK_FG  : open fd failed
08-19 09:54:04.668   492   492 E MTK_FG  : init failed, return!
08-19 09:54:04.668   492   492 D NVRAM   : length of g_NVRAM_BACKUP_DEVICE=44
08-19 09:54:04.668   492   492 D NVRAM   : nvram_layout_callback will run!!!
08-19 09:54:04.668   492   492 D NVRAM   : nvram_platform_log_block: 2
08-19 09:54:04.668   492   492 D NVRAM   : nvram_platform_resv_block: 2
08-19 09:54:04.668   492   492 D NVRAM   : nvram_platform_DM_block: 1
08-19 09:54:04.668   492   492 D NVRAM   : nvram_platform_layout_version: 0
08-19 09:54:04.668   492   492 D NVRAM   : nvram_platform_header_offset: 0
08-19 09:54:04.669   492   492 D NVRAM   : g_i4CFG_File_Count: 51
08-19 09:54:04.669   492   492 D NVRAM   : NVM_Init Max Lid: 79
08-19 09:54:04.669   492   492 D NVRAM   : [NVRAM]: info nvram_gpt_flag =1
08-19 09:54:04.669   492   492 D NVRAM   : [NVRAM]: info NVRAM Init Completed!
08-19 09:54:04.669   492   492 D NVRAM   : NVM_GetFileDesc: Open /mnt/vendor/nvdata/APCFG/APRDCL/FG,LID:76
08-19 09:54:04.669   492   492 D NVRAM   : NVM_CmpFileVerNo 76
08-19 09:54:04.669   492   492 D NVRAM   : Load File Version: 000, NvRam File Version: 000
08-19 09:54:04.669   492   492 D NVRAM   : NVM_ProtectDataFile : 76 ++
08-19 09:54:04.669   492   492 D NVRAM   : iCustomBeginLID = 51
08-19 09:54:04.669   492   492 D NVRAM   : NVM_CheckFileSize:stat_size:26,size in table:24
08-19 09:54:04.671   492   492 D NVRAM   : NVM_CheckFile: File is correct!
08-19 09:54:04.671   492   492 D NVRAM   : NVM_ProtectUserData:Check Success
08-19 09:54:04.671   492   492 D NVRAM   : NVM_GetFileDesc ProtectDataFile Check Success!!
08-19 09:54:04.671   492   492 W MTK_FG  : fd < 0, init first!
08-19 09:54:04.671   492   492 E MTK_FG  : open fd failed
08-19 09:54:04.671   492   492 E MTK_FG  : init failed, return!
08-19 09:54:04.671   492   492 W MTK_FG  : fd < 0, init first!
08-19 09:54:04.671   492   492 E MTK_FG  : open fd failed
08-19 09:54:04.671   492   492 E MTK_FG  : init failed, return!
08-19 09:54:04.672   492   492 D NVRAM   : NVM_CloseFileDesc: Open by Readonly, no need to check when close
08-19 09:54:04.672   492   492 W MTK_FG  : fd < 0, init first!
08-19 09:54:04.672   492   492 E MTK_FG  : open fd failed
08-19 09:54:04.672   492   492 E MTK_FG  : init failed, return!
08-19 09:54:04.672   492   492 W MTK_FG  : fd < 0, init first!
08-19 09:54:04.672   492   492 E MTK_FG  : open fd failed
08-19 09:54:04.672   492   492 E MTK_FG  : init failed, return!
08-19 09:54:04.672   492   492 W MTK_FG  : fd < 0, init first!
08-19 09:54:04.672   492   492 E MTK_FG  : open fd failed
08-19 09:54:04.672   492   492 E MTK_FG  : init failed, return!
08-19 09:54:04.672   492   492 W MTK_FG  : fd < 0, init first!
08-19 09:54:04.672   492   492 E MTK_FG  : open fd failed
08-19 09:54:04.672   492   492 E MTK_FG  : init failed, return!
08-19 09:54:04.672   492   492 W MTK_FG  : fd < 0, init first!
08-19 09:54:04.672   492   492 E MTK_FG  : open fd failed
08-19 09:54:04.672   492   492 E MTK_FG  : init failed, return!
08-19 09:54:04.672   492   492 W MTK_FG  : fd < 0, init first!
08-19 09:54:04.672   492   492 E MTK_FG  : open fd failed
08-19 09:54:04.672   492   492 E MTK_FG  : init failed, return!
08-19 09:54:04.672   492   492 W MTK_FG  : fd < 0, init first!
08-19 09:54:04.672   492   492 E MTK_FG  : open fd failed
08-19 09:54:04.672   492   492 E MTK_FG  : init failed, return!
08-19 09:54:04.818   482   561 I ServiceManager: Waiting for service package_native...
08-19 09:54:04.893   859   859 W LSPosed : Fail to get binder for system server
08-19 09:54:04.906   859   859 I Zygote  : Process: zygote socket RESERVED/zygote_secondary opened, supported ABIS: armeabi-v7a,armeabi
08-19 09:54:04.919   482   561 W ServiceManager: Service package_native didn't start. Returning NULL
08-19 09:54:04.919   482   561 E storaged: getService package_native failed
08-19 09:54:04.920   482   561 I storaged: storaged: Start
08-19 09:54:04.920   482   561 E storaged: getDiskStats failed with result NOT_SUPPORTED and size 0
08-19 09:54:04.944   859   859 I system_server: The ClassLoaderContext is a special shared library.
08-19 09:54:05.000   859   859 I SystemServer: InitBeforeStartServices
08-19 09:54:05.000   859   859 I SystemServer: Entered the Android system server!
08-19 09:54:04.956   859   859 I chatty  : uid=1000 system_server identical 3 lines
08-19 09:54:04.989   859   859 I system_server: The ClassLoaderContext is a special shared library.
08-19 09:54:05.042   420   803 I BufferQueueProducer: [BootAnimation#0](this:0x78bdbbd800,id:1,api:1,p:721,c:420) queueBuffer: fps=14.96 dur=1002.72 max=69.78 min=65.56
08-19 09:54:05.105   859   859 E UsbAlsaJackDetectorJNI: Can't register UsbAlsaJackDetector native methods
08-19 09:54:05.121   420   420 I BufferQueueProducer: [FramebufferSurface](this:0x78bda1e800,id:0,api:1,p:420,c:420) queueBuffer: fps=15.08 dur=1061.24 max=72.73 min=53.09
08-19 09:54:05.122   859   859 I SystemServer: StartServices
08-19 09:54:05.123   859   859 I SystemServer: Reading configuration...
08-19 09:54:05.123   859   859 I SystemServer: ReadingSystemConfig
08-19 09:54:05.123   859   859 I SystemServer: StartInstaller
08-19 09:54:05.123   859   859 I SystemServiceManager: Starting com.android.server.pm.Installer
08-19 09:54:05.123   859   999 D SystemServerInitThreadPool: Started executing ReadingSystemConfig
08-19 09:54:05.126   473   515 D installd: Found quota mount /dev/block/platform/bootdevice/by-name/userdata at /data
08-19 09:54:05.127   859   859 I SystemServer: DeviceIdentifiersPolicyService
08-19 09:54:05.127   859   859 I SystemServiceManager: Starting com.android.server.os.DeviceIdentifiersPolicyService
08-19 09:54:05.127   859   859 I SystemServer: StartActivityManager
08-19 09:54:05.128   859   859 I SystemServiceManager: Starting com.android.server.am.ActivityManagerService$Lifecycle
08-19 09:54:05.133   859   999 I SystemConfig: Non-xml file /system/etc/permissions/pms_sysapp_removable_system_list.txt in /system/etc/permissions directory, ignoring
08-19 09:54:05.145   859   999 I SystemConfig: Non-xml file /vendor/etc/permissions/pms_sysapp_removable_vendor_list.txt in /vendor/etc/permissions directory, ignoring
08-19 09:54:05.148   859   999 D SystemServerInitThreadPool: Finished executing ReadingSystemConfig
08-19 09:54:05.158   859   859 I PowerWrap: Loaded power HAL service
08-19 09:54:05.158   859   859 I PowerWrap: Link to death notification successful
08-19 09:54:05.158   859   859 I PowerWrap: PowerHal_Wrap_querySysInfo
08-19 09:54:05.159   859   859 E PowerHalWrapper: pextpeak_period: 6000
08-19 09:54:05.159   859   859 I PowerWrap: PowerHal_Wrap_querySysInfo
08-19 09:54:05.159   859   859 I chatty  : uid=1000 system_server identical 1 line
08-19 09:54:05.159   859   859 I PowerWrap: PowerHal_Wrap_querySysInfo
08-19 09:54:05.162   859   859 I system_server: The ClassLoaderContext is a special shared library.
08-19 09:54:05.169   859   859 I system_server: type=1400 audit(0.0:363): avc: denied { read } for name="buffer_total_size_kb" dev="tracefs" ino=2069 scontext=u:r:system_server:s0 tcontext=u:object_r:debugfs_tracing_debug:s0 tclass=file permissive=1
08-19 09:54:05.172   859   859 I android.os.Debug: android_os_Debug_getIONDISP match 4:      ion_mm_heap   1    73728   1 ffffffc03b5c6e80 ffffffc03b983700.
08-19 09:54:05.172   859   859 I android.os.Debug:  : 1 73728 1 73728
08-19 09:54:05.172   859   859 I android.os.Debug: android_os_Debug_getIONDISP match 4:      ion_mm_heap   1  5242880   1 ffffffc03b5f3080 ffffffc03b983800.
08-19 09:54:05.172   859   859 I android.os.Debug:  : 1 5242880 1 5316608
08-19 09:54:05.172   859   859 I android.os.Debug: android_os_Debug_getIONDISP match 4:      ion_mm_heap   1    73728   1 ffffffc03b5f3280 ffffffc03b983900.
08-19 09:54:05.172   859   859 I android.os.Debug:  : 1 73728 1 5390336
08-19 09:54:05.172   859   859 I android.os.Debug: android_os_Debug_getIONDISP match 4:      ion_mm_heap   1  5242880   1 ffffffc03b5f3480 ffffffc03b983a00.
08-19 09:54:05.172   859   859 I android.os.Debug:  : 1 5242880 1 10633216
08-19 09:54:05.169   859   859 I system_server: type=1400 audit(0.0:364): avc: denied { open } for path="/sys/kernel/debug/tracing/buffer_total_size_kb" dev="tracefs" ino=2069 scontext=u:r:system_server:s0 tcontext=u:object_r:debugfs_tracing_debug:s0 tclass=file permissive=1
08-19 09:54:05.172   859   859 I android.os.Debug: android_os_Debug_getIONDISP match 4:      ion_mm_heap   1  6291456   1 ffffffc03b5f3680 ffffffc03b983b00.
08-19 09:54:05.172   859   859 I android.os.Debug:  : 1 6291456 1 16924672
08-19 09:54:05.172   859   859 I android.os.Debug: android_os_Debug_getIONDISP match 4:      ion_mm_heap   1  4710400   3 ffffffc02db18080 ffffffc032097900.
08-19 09:54:05.172   859   859 I android.os.Debug:  : 1 4710400 3 21635072
08-19 09:54:05.172   859   859 I android.os.Debug: android_os_Debug_getIONDISP match 4:      ion_mm_heap 175  3457024   1 ffffffc03cd0ad00 ffffffc03cf56400.
08-19 09:54:05.172   859   859 I android.os.Debug:  : 175 3457024 1 25092096
08-19 09:54:05.173   859   859 I android.os.Debug: android_os_Debug_getIONDISP match 4:      ion_mm_heap 175  3457024   1 ffffffc03cd0aa80 ffffffc03cf56200.
08-19 09:54:05.173   859   859 I android.os.Debug:  : 175 3457024 1 28549120
08-19 09:54:05.173   859   859 I android.os.Debug: android_os_Debug_getIONDISP match 4:      ion_mm_heap 175  3457024   1 ffffffc03cd0a800 ffffffc03cf56000.
08-19 09:54:05.173   859   859 I android.os.Debug:  : 175 3457024 1 32006144
08-19 09:54:05.174   859   859 I ActivityManager: Memory class: 384
08-19 09:54:05.180   859   859 D BatteryStatsImpl: Reading daily items from /data/system/batterystats-daily.xml
08-19 09:54:05.184   859  1006 E BluetoothAdapter: Bluetooth binder is null
08-19 09:54:05.185   859  1006 E BatteryExternalStatsWorker: no controller energy info supplied for telephony
08-19 09:54:05.185   859  1006 I KernelUidCpuFreqTimeReader: mPerClusterTimesAvailable=false
08-19 09:54:05.188   859  1006 W KernelCpuProcReader: File not exist: /proc/uid_cpupower/time_in_state
08-19 09:54:05.188   859  1006 W KernelCpuProcReader: File not exist: /proc/uid_cpupower/concurrent_active_time
08-19 09:54:05.189   859  1006 W KernelCpuProcReader: File not exist: /proc/uid_cpupower/concurrent_policy_time
08-19 09:54:05.190   859  1006 W KernelMemoryBandwidthStats: No kernel memory bandwidth stats available
08-19 09:54:05.191   859  1006 I PowerManagerService-JNI: Loaded power HAL 1.0 service
08-19 09:54:05.192   859  1006 I PowerManagerService-JNI: Loaded power HAL 1.1 service
08-19 09:54:05.239   859   859 W AppOps  : Unknown attribute in 'op' tag: n
08-19 09:54:05.246   859   859 I chatty  : uid=1000 system_server identical 159 lines
08-19 09:54:05.246   859   859 W AppOps  : Unknown attribute in 'op' tag: n
08-19 09:54:05.251   859   859 I IntentFirewall: Read new rules (A:0 B:0 S:0)
08-19 09:54:05.254   859   859 I AES     : load Exception Log jni
08-19 09:54:05.256   859   859 W libprocessgroup: Failed to remove /acct/uid_0/pid_321: Device or resource busy
08-19 09:54:05.256   859

**Comment by Nagisakurumi** [comment]
Is this a bootlog?
I got it on device power on.

I was driving just now。

**Comment by yujincheng08** [comment]
Jesus. you shall upload file...

**Comment by Nagisakurumi** [comment]
sorry, I re upload...
[test.txt](https://github.com/LSPosed/LSPosed/files/7014081/test.txt)

**Comment by vvb2060** [comment]
no magisk key word

**Comment by Nagisakurumi** [comment]
yes, I modify riru and lsposed，I want to learn them.
Now, Riru is running, so I want to modify lsposed.

**Comment by yujincheng08** [comment]
then i think its none of our business since its not a legacy usage.

**Comment by vvb2060** [comment]
So, you should solve it yourself.
